"""
This type stub file was generated by pyright.
"""

from .misc_tools import *
from . import name_mangling
from .proxy_property import ProxyProperty
from .overridable_property import OverridableProperty

'''This module defines miscellaneous tools.'''
