"""
This type stub file was generated by pyright.
"""

from fontParts.base import BaseAnchor
from fontParts.fontshell.base import RBaseObject

class RAnchor(RBaseObject, BaseAnchor):
    wrapClass = ...


