"""
This type stub file was generated by pyright.
"""

from fontParts.base import BaseComponent
from fontParts.fontshell.base import RBaseObject

class RComponent(RBaseObject, BaseComponent):
    wrapClass = ...


