from fontTools.misc.visitor import Visitor as Visitor

class TTVisitor(Visitor):
    def visitAttr(self, obj, attr, value, *args, **kwargs): ...
    def visit(self, obj, *args, **kwargs) -> None: ...

def visit(visitor, font, *args, **kwargs): ...
