import types
from _typeshed import Incomplete
from email.generator import BytesGenerator

__all__ = ['build', 'build_from_document', 'fix_method_name', 'key2param']

V1_DISCOVERY_URI = DISCOVERY_URI

class APICoreVersionError(ValueError):
    def __init__(self) -> None: ...

class _BytesGenerator(BytesGenerator): ...

def fix_method_name(name): ...
def key2param(key): ...
def build(serviceName, version, http=None, discoveryServiceUrl=None, developerKey=None, model=None, requestBuilder=..., credentials=None, cache_discovery: bool = True, cache=None, client_options=None, adc_cert_path=None, adc_key_path=None, num_retries: int = 1, static_discovery=None, always_use_jwt_access: bool = False): ...
def build_from_document(service, base=None, future=None, http=None, developerKey=None, model=None, requestBuilder=..., credentials=None, client_options=None, adc_cert_path=None, adc_key_path=None, always_use_jwt_access: bool = False): ...

class ResourceMethodParameters:
    argmap: Incomplete
    required_params: Incomplete
    repeated_params: Incomplete
    pattern_params: Incomplete
    query_params: Incomplete
    path_params: Incomplete
    param_types: Incomplete
    enum_params: Incomplete
    def __init__(self, method_desc) -> None: ...
    def set_parameters(self, method_desc) -> None: ...

class Resource:
    def __init__(self, http, baseUrl, model, requestBuilder, developerKey, resourceDesc, rootDesc, schema, universe_domain=...) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    def close(self) -> None: ...
