"""
This type stub file was generated by pyright.
"""

import cython
from typing import Sequence, Tuple, Union
from numbers import Integral, Real

COMPILED = ...
_Point = Tuple[Real, Real]
_Delta = Tuple[Real, Real]
_PointSegment = Sequence[_Point]
_DeltaSegment = Sequence[_Delta]
_DeltaOrNone = Union[_Delta, None]
_DeltaOrNoneSegment = Sequence[_DeltaOrNone]
_Endpoints = Sequence[Integral]
MAX_LOOKBACK = ...
@cython.cfunc
@cython.locals(j=cython.int, n=cython.int, x1=cython.double, x2=cython.double, d1=cython.double, d2=cython.double, scale=cython.double, x=cython.double, d=cython.double)
def iup_segment(coords: _PointSegment, rc1: _Point, rd1: _Delta, rc2: _Point, rd2: _Delta): # -> zip[Any]:
    """Given two reference coordinates `rc1` & `rc2` and their respective
    delta vectors `rd1` & `rd2`, returns interpolated deltas for the set of
    coordinates `coords`."""
    ...

def iup_contour(deltas: _DeltaOrNoneSegment, coords: _PointSegment) -> _DeltaSegment:
    """For the contour given in `coords`, interpolate any missing
    delta values in delta vector `deltas`.

    Returns fully filled-out delta vector."""
    ...

def iup_delta(deltas: _DeltaOrNoneSegment, coords: _PointSegment, ends: _Endpoints) -> _DeltaSegment:
    """For the outline given in `coords`, with contour endpoints given
    in sorted increasing order in `ends`, interpolate any missing
    delta values in delta vector `deltas`.

    Returns fully filled-out delta vector."""
    ...

@cython.cfunc
@cython.inline
@cython.locals(i=cython.int, j=cython.int, x=cython.double, y=cython.double, p=cython.double, q=cython.double)
@cython.returns(int)
def can_iup_in_between(deltas: _DeltaSegment, coords: _PointSegment, i: Integral, j: Integral, tolerance: Real): # -> bool:
    """Return true if the deltas for points at `i` and `j` (`i < j`) can be
    successfully used to interpolate deltas for points in between them within
    provided error tolerance."""
    ...

def iup_contour_optimize(deltas: _DeltaSegment, coords: _PointSegment, tolerance: Real = ...) -> _DeltaOrNoneSegment:
    """For contour with coordinates `coords`, optimize a set of delta
    values `deltas` within error `tolerance`.

    Returns delta vector that has most number of None items instead of
    the input delta.
    """
    ...

def iup_delta_optimize(deltas: _DeltaSegment, coords: _PointSegment, ends: _Endpoints, tolerance: Real = ...) -> _DeltaOrNoneSegment:
    """For the outline given in `coords`, with contour endpoints given
    in sorted increasing order in `ends`, optimize a set of delta
    values `deltas` within error `tolerance`.

    Returns delta vector that has most number of None items instead of
    the input delta.
    """
    ...

