"""
This type stub file was generated by pyright.
"""

NO_VARIATION_INDEX = ...
class OnlineMultiVarStoreBuilder:
    def __init__(self, axisTags) -> None:
        ...
    
    def setModel(self, model): # -> None:
        ...
    
    def setSupports(self, supports): # -> None:
        ...
    
    def finish(self):
        ...
    
    def storeMasters(self, master_values, *, round=...): # -> tuple[Any, Any | int]:
        ...
    
    def storeDeltas(self, deltas, *, round=...): # -> int:
        ...
    


def MultiVarData_addItem(self, deltas, *, round=...): # -> None:
    ...

def SparseVarRegion_get_support(self, fvar_axes): # -> dict[Any, tuple[Any, Any, Any]]:
    ...

def MultiVarStore___bool__(self): # -> bool:
    ...

class MultiVarStoreInstancer:
    def __init__(self, multivarstore, fvar_axes, location=...) -> None:
        ...
    
    def setLocation(self, location): # -> None:
        ...
    
    @staticmethod
    def interpolateFromDeltasAndScalars(deltas, scalars): # -> Vector:
        ...
    
    def __getitem__(self, varidx): # -> Vector:
        ...
    
    def interpolateFromDeltas(self, varDataIndex, deltas): # -> Vector:
        ...
    


def MultiVarStore_subset_varidxes(self, varIdxes):
    ...

def MultiVarStore_prune_regions(self):
    ...

def MultiVarStore_get_supports(self, major, fvarAxes): # -> list[Any]:
    ...

def VARC_collect_varidxes(self, varidxes): # -> None:
    ...

def VARC_remap_varidxes(self, varidxes_map): # -> None:
    ...

