from _typeshed import Incomplete
from fontTools.designspaceLib import DesignSpaceDocument as DesignSpaceDocument
from fontTools.varLib.models import supportScalar as supportScalar, VariationModel as VariationModel
from mpl_toolkits.mplot3d import axes3d as axes3d

log: Incomplete

def stops(support, count: int = 10): ...
def _plotLocationsDots(locations, axes, subplot, **kwargs) -> None: ...
def plotLocations(locations, fig, names=None, **kwargs) -> None: ...
def _plotLocations2D(model, axis, fig, cols, rows, names, **kwargs) -> None: ...
def _plotLocations3D(model, axes, fig, rows, cols, names, **kwargs) -> None: ...
def plotDocument(doc, fig, **kwargs) -> None: ...
def _plotModelFromMasters2D(model, masterValues, fig, **kwargs) -> None: ...
def _plotModelFromMasters3D(model, masterValues, fig, **kwargs) -> None: ...
def plotModelFromMasters(model, masterValues, fig, **kwargs) -> None:
    """Plot a variation model and set of master values corresponding
    to the locations to the model into a pyplot figure.  Variation
    model must have axisOrder of size 1 or 2.
    """
def main(args=None) -> None: ...
