from _typeshed import Incomplete
from fontTools.misc.intTools import bit_count as bit_count
from fontTools.misc.roundTools import noRound as noRound, otRound as otRound
from fontTools.varLib.builder import buildVarData as buildVarData, buildVarRegion as buildVarRegion, buildVarRegionList as buildVarRegionList, buildVarStore as buildVarStore
from fontTools.varLib.models import supportScalar as supportScalar

NO_VARIATION_INDEX: Incomplete

def _getLocationKey(loc): ...

class OnlineVarStoreBuilder:
    _axisTags: Incomplete
    _regionMap: Incomplete
    _regionList: Incomplete
    _store: Incomplete
    _data: Incomplete
    _model: Incomplete
    _supports: Incomplete
    _varDataIndices: Incomplete
    _varDataCaches: Incomplete
    _cache: Incomplete
    def __init__(self, axisTags) -> None: ...
    def setModel(self, model) -> None: ...
    def setSupports(self, supports) -> None: ...
    def finish(self, optimize: bool = True): ...
    _outer: Incomplete
    def _add_VarData(self, num_items: int = 1) -> None: ...
    def storeMasters(self, master_values, *, round=...): ...
    def storeMastersMany(self, master_values_list, *, round=...): ...
    def storeDeltas(self, deltas, *, round=...): ...
    def storeDeltasMany(self, deltas_list, *, round=...): ...

def VarData_addItem(self, deltas, *, round=...) -> None: ...
def VarRegion_get_support(self, fvar_axes): ...
def VarStore___bool__(self): ...

class VarStoreInstancer:
    fvar_axes: Incomplete
    _varData: Incomplete
    _regions: Incomplete
    def __init__(self, varstore, fvar_axes, location={}) -> None: ...
    location: Incomplete
    def setLocation(self, location) -> None: ...
    _scalars: Incomplete
    def _clearCaches(self) -> None: ...
    def _getScalar(self, regionIdx): ...
    @staticmethod
    def interpolateFromDeltasAndScalars(deltas, scalars): ...
    def __getitem__(self, varidx): ...
    def interpolateFromDeltas(self, varDataIndex, deltas): ...

def VarStore_subset_varidxes(self, varIdxes, optimize: bool = True, retainFirstMap: bool = False, advIdxes=..., *, VarData: str = 'VarData'): ...
def VarStore_prune_regions(self, *, VarData: str = 'VarData', VarRegionList: str = 'VarRegionList') -> None:
    """Remove unused VarRegions."""
def _visit(self, func) -> None:
    """Recurse down from self, if type of an object is ot.Device,
    call func() on it.  Works on otData-style classes."""
def _Device_recordVarIdx(self, s) -> None:
    """Add VarIdx in this Device table (if any) to the set s."""
def Object_collect_device_varidxes(self, varidxes) -> None: ...
def _Device_mapVarIdx(self, mapping, done) -> None:
    """Map VarIdx in this Device table (if any) through mapping."""
def Object_remap_device_varidxes(self, varidxes_map) -> None: ...

class _Encoding:
    chars: Incomplete
    width: Incomplete
    columns: Incomplete
    overhead: Incomplete
    items: Incomplete
    def __init__(self, chars) -> None: ...
    def append(self, row) -> None: ...
    def extend(self, lst) -> None: ...
    def width_sort_key(self): ...
    @staticmethod
    def _characteristic_overhead(columns):
        """Returns overhead in bytes of encoding this characteristic
        as a VarData."""
    @staticmethod
    def _columns(chars): ...
    def gain_from_merging(self, other_encoding): ...

class _EncodingDict(dict):
    def __missing__(self, chars): ...
    def add_row(self, row) -> None: ...
    @staticmethod
    def _row_characteristics(row):
        """Returns encoding characteristics for a row."""

def VarStore_optimize(self, use_NO_VARIATION_INDEX: bool = True, quantization: int = 1):
    """Optimize storage. Returns mapping from old VarIdxes to new ones."""
def main(args=None) -> None:
    """Optimize a font's GDEF variation store"""
