from _typeshed import Incomplete

def _prefer_non_zero(*args): ...
def _ntos(n): ...
def _strip_xml_ns(tag): ...
def _transform(raw_value): ...

class PathBuilder:
    paths: Incomplete
    transforms: Incomplete
    def __init__(self) -> None: ...
    def _start_path(self, initial_path: str = '') -> None: ...
    def _end_path(self) -> None: ...
    def _add(self, path_snippet) -> None: ...
    def _move(self, c, x, y) -> None: ...
    def M(self, x, y) -> None: ...
    def m(self, x, y) -> None: ...
    def _arc(self, c, rx, ry, x, y, large_arc) -> None: ...
    def A(self, rx, ry, x, y, large_arc: int = 0) -> None: ...
    def a(self, rx, ry, x, y, large_arc: int = 0) -> None: ...
    def _vhline(self, c, x) -> None: ...
    def H(self, x) -> None: ...
    def h(self, x) -> None: ...
    def V(self, y) -> None: ...
    def v(self, y) -> None: ...
    def _line(self, c, x, y) -> None: ...
    def L(self, x, y) -> None: ...
    def l(self, x, y) -> None: ...
    def _parse_line(self, line) -> None: ...
    def _parse_rect(self, rect) -> None: ...
    def _parse_path(self, path) -> None: ...
    def _parse_polygon(self, poly) -> None: ...
    def _parse_polyline(self, poly) -> None: ...
    def _parse_circle(self, circle) -> None: ...
    def _parse_ellipse(self, ellipse) -> None: ...
    def add_path_from_element(self, el): ...
