"""
This type stub file was generated by pyright.
"""

"""GDEF Unparser: Extract fontFeatures information from GDEF table."""
class GDEFUnparser:
    """Extract GDEF information into a fontFeatures object.

    Args:
        table: a GDEF table (e.g. ``font["GDEF"]``)
        ff: a fontFeatures object.
    """
    def __init__(self, table, fontfeatures) -> None:
        ...
    
    def unparse(self): # -> None:
        """Extracts glyph class definitions and stores them in the fontFeatures
        object.

        In theory other information can be retrieved, but currently there is no
        place to store it in the fontFeatures object.
        """
        ...
    
    def unparseGlyphClassDefinitions(self): # -> None:
        """Fills the fontFeatures ``glyphclasses`` dictionary from the
        ``GlyphClassDef`` subtable."""
        ...
    


