"""
This type stub file was generated by pyright.
"""

"""ttLib.ValueRecord: Converting ValueRecord rules to TrueType."""
def toOTValueRecord(self, ff, pairPosContext=...): # -> ValueRecord:
    """Converts the ValueRecord to an ``OTLValueRecord`` object. If the
    value record contains any variable scalars, they are saved to the
    GDEF variation store."""
    ...

