"""
This type stub file was generated by pyright.
"""

from future import utils

"""
This is Victor Stinner's pure-Python implementation of PEP 383: the "surrogateescape" error
handler of Python 3.

Source: misc/python/surrogateescape.py in https://bitbucket.org/haypo/misc
"""
FS_ERRORS = ...
def u(text):
    ...

def b(data):
    ...

if utils.PY3:
    _unichr = ...
    bytes_chr = ...
else:
    _unichr = ...
    bytes_chr = ...
def surrogateescape_handler(exc): # -> tuple[str, int]:
    """
    Pure Python implementation of the PEP 383: the "surrogateescape" error
    handler of Python 3. Undecodable bytes will be replaced by a Unicode
    character U+DCxx on decoding, and these are translated into the
    original bytes on encoding.
    """
    ...

class NotASurrogateError(Exception):
    ...


def replace_surrogate_encode(mystring): # -> str:
    """
    Returns a (unicode) string, not the more logical bytes, because the codecs
    register_error functionality expects this.
    """
    ...

def replace_surrogate_decode(mybytes): # -> str:
    """
    Returns a (unicode) string
    """
    ...

def encodefilename(fn): # -> bytes:
    ...

def decodefilename(fn):
    ...

FS_ENCODING = ...
fn = ...
encoded = ...
FS_ENCODING = ...
def register_surrogateescape(): # -> None:
    """
    Registers the surrogateescape error handler on Python 2 (only)
    """
    ...

if __name__ == '__main__':
    ...
