from _typeshed import Incomplete
from collections.abc import Callable
from einops import reduce as reduce, repeat as repeat
from torch.nn import Module
from typing import TypeAlias

def exists(v): ...
def default(v, d): ...
def get_expand_reduce_stream_functions(num_streams, disable: bool = False): ...
def get_init_and_expand_reduce_stream_functions(num_streams, disable=None): ...

class RMSNorm(Module):
    scale: Incomplete
    gamma: Incomplete
    def __init__(self, dim) -> None: ...
    def forward(self, x): ...

class ProjActScale(Module):
    proj: Incomplete
    act: Incomplete
    scale: Incomplete
    maybe_squeeze: Incomplete
    def __init__(self, dim, dim_out, activation: Module = ..., scale_init: float = 0.01, squeeze_output: bool = False) -> None: ...
    def forward(self, x): ...

class Residual(Module):
    branch: Incomplete
    def __init__(self, *args, branch: Module | None = None, **kwargs) -> None: ...
    def width_connection(self, residuals, *args, **kwargs): ...
    def depth_connection(self, branch_output, residuals): ...
    def decorate_branch(self, branch: Callable): ...
    def forward(self, residuals, *branch_args, **branch_kwargs): ...
type InputPathType = int | str

class HyperConnections(Module):
    branch: Incomplete
    num_residual_streams: Incomplete
    norm: Incomplete
    dynamic_alpha_and_branch_input: Incomplete
    static_alpha: Incomplete
    dynamic_beta: Incomplete
    static_beta: Incomplete
    additional_norms: Incomplete
    additional_to_dynamic_input: Incomplete
    additional_static_input: Incomplete
    additional_input_paths: Incomplete
    dropout: Incomplete
    channel_first: Incomplete
    def __init__(self, num_residual_streams, *, dim, additional_input_paths: list[InputPathType | tuple[InputPathType, int]] | None = None, branch: Module | None = None, layer_index=None, tanh: bool = True, channel_first: bool = False, dropout: float = 0.0) -> None:
    def width_connection(self, residuals, *branch_args, **branch_kwargs): ...
    def depth_connection(self, branch_output, residuals, *, beta): ...
    def decorate_branch(self, branch: Callable): ...
    def forward(self, residuals, *branch_args, **branch_kwargs): ...
