from _typeshed import Incomplete
from einops import reduce as reduce, repeat as repeat
from hyper_connections.hyper_connections import Residual as Residual, RMSNorm as RMSNorm
from torch.nn import Module
from typing import Callable

def exists(v): ...
def default(v, d): ...
def identity(t): ...
def get_expand_reduce_stream_functions(num_streams, disable: bool = False): ...
def get_init_and_expand_reduce_stream_functions(num_streams, disable=None): ...

class RMSNorm(Module):
    scale: Incomplete
    gamma: Incomplete
    def __init__(self, dim) -> None: ...
    def forward(self, x): ...

class HyperConnections(Module):
    branch: Incomplete
    act: Incomplete
    norm: Incomplete
    num_residual_streams: Incomplete
    static_beta: Incomplete
    static_alpha: Incomplete
    dynamic_alpha_fn: Incomplete
    dynamic_beta_fn: Incomplete
    dynamic_alpha_scale: Incomplete
    dynamic_beta_scale: Incomplete
    dropout: Incomplete
    def __init__(self, num_residual_streams, *, dim, branch: Module | None = None, layer_index=None, tanh: bool = True, channel_first: bool = True, dropout: float = 0.0) -> None:
    def width_connection(self, residuals): ...
    def depth_connection(self, branch_output, residuals, *, beta): ...
    def decorate_branch(self, branch: Callable): ...
    def forward(self, residuals, *branch_args, **branch_kwargs): ...
