from _typeshed import Incomplete
from collections.abc import Callable
from einops import reduce as reduce, repeat as repeat
from hyper_connections.hyper_connections import Residual as Residual, RMSNorm as RMSNorm, StreamEmbed as StreamEmbed
from torch.nn import Module

def exists(v): ...
def default(v, d): ...
def divisible_by(num, den): ...
def identity(t): ...
def get_expand_reduce_stream_functions(cls, num_streams, disable: bool = False): ...
def get_init_and_expand_reduce_stream_functions(cls, num_streams, disable=None): ...

class HyperConnections(Module):
    branches: Incomplete
    act: Incomplete
    norm: Incomplete
    num_residual_streams: Incomplete
    num_branch_inputs: Incomplete
    static_beta: Incomplete
    static_alpha: Incomplete
    dynamic_alpha_fn: Incomplete
    dynamic_alpha_scale: Incomplete
    dynamic_beta_fn: Incomplete
    dynamic_beta_scale: Incomplete
    dropout: Incomplete
    channel_first: Incomplete
    def __init__(self, num_residual_streams, *, dim, branch: Module | tuple[Module, ...] | list[Module] | None = None, layer_index=None, tanh: bool = True, channel_first: bool = False, dropout: float = 0.0, num_branch_inputs: int = 1) -> None:
    def width_connection(self, residuals): ...
    def depth_connection(self, branch_output, residuals, *, beta): ...
    def decorate_branch(self, branch: Callable | tuple[Callable, ...] | list[Callable]): ...
    def forward(self, residuals, *branch_args, **branch_kwargs): ...
