from _typeshed import Incomplete
from collections.abc import Callable
from torch.nn import Module, Sequential as Sequential

def exists(v): ...
def divisible_by(num, den): ...
def default(v, d): ...
def identity(t): ...
def add(x, y): ...
def l1norm(t, dim): ...
def sinkhorn_knopps(log_alpha, iters: int = 20): ...
def log_domain_sinkhorn_knopps(log_alpha, iters: int = 20): ...
def get_expand_reduce_stream_functions(num_streams, add_stream_embed: bool = False, dim=None, disable: bool = False): ...
def get_init_and_expand_reduce_stream_functions(num_streams, num_fracs: int = 1, dim=None, add_stream_embed: bool = False, disable=None, sinkhorn_iters: int = 20, **kwargs): ...

class RMSNorm(Module):
    scale: Incomplete
    gamma: Incomplete
    def __init__(self, dim) -> None: ...
    def forward(self, x): ...

class Residual(Module):
    branch: Incomplete
    residual_transform: Incomplete
    def __init__(self, *args, branch: Module | None = None, residual_transform: Module | None = None, **kwargs) -> None: ...
    def width_connection(self, residuals): ...
    def depth_connection(self, branch_output, residuals): ...
    def decorate_branch(self, branch: Callable): ...
    def forward(self, residuals, *branch_args, **branch_kwargs): ...

class ManifoldConstrainedHyperConnections(Module):
    branch: Incomplete
    num_fracs: Incomplete
    has_fracs: Incomplete
    split_fracs: Incomplete
    merge_fracs: Incomplete
    norm: Incomplete
    num_residual_streams: Incomplete
    num_input_views: Incomplete
    has_dynamic_alpha_proposals: Incomplete
    num_dynamic_alpha_proposals: Incomplete
    static_alpha: Incomplete
    dynamic_alpha_fn: Incomplete
    pre_branch_scale: Incomplete
    residual_scale: Incomplete
    add_branch_out_to_residual: Incomplete
    static_beta: Incomplete
    dynamic_beta_fn: Incomplete
    h_post_scale: Incomplete
    residual_mix_constraint_fn: Incomplete
    dropout: Incomplete
    channel_first: Incomplete
    residual_transform: Incomplete
    depth_residual_fn: Incomplete
    forward_method_names: Incomplete
    def __init__(self, num_residual_streams, *, dim, branch: Module | None = None, layer_index=None, channel_first: bool = False, dropout: float = 0.0, residual_transform: Module | None = None, add_branch_out_to_residual: bool = True, num_input_views: int = 1, depth_residual_fn=..., num_fracs: int = 1, sinkhorn_iters: int = 20, log_domain_sinkhorn: bool = False, residual_mix_constraint_fn: Callable | None = None, forward_method_names: tuple[str, ...] = (), num_dynamic_alpha_proposals: int = 1) -> None:
    def width_connection(self, residuals): ...
    def depth_connection(self, branch_output, residuals, *, beta): ...
    def decorate_branch(self, branch: Callable): ...
    def forward(self, residuals, *branch_args, **branch_kwargs): ...
mHC = ManifoldConstrainedHyperConnections

class StreamEmbed(Module):
    channel_first: Incomplete
    num_streams: Incomplete
    expand_to_streams: Incomplete
    stream_embed: Incomplete
    def __init__(self, num_streams, dim, channel_first: bool = False, expand_to_streams: bool = False) -> None: ...
    def forward(self, residuals): ...

class AttentionPoolReduceStream(Module):
    num_streams: Incomplete
    channel_first: Incomplete
    to_attn_logits: Incomplete
    def __init__(self, num_streams, dim, channel_first: bool = False) -> None: ...
    def forward(self, residuals): ...
