from torch.autograd import Function
import triton
import triton.language as tl

@triton.jit
def sinkhorn_kernel_forward_log(input_ptr, output_ptr, M, N, stride_b, stride_m, stride_n, iters: tl.constexpr, BLOCK_SIZE: tl.constexpr): ...
@triton.jit
def sinkhorn_kernel_backward_log(grad_output_ptr, output_ptr, grad_input_ptr, M, N, stride_b, stride_m, stride_n, iters: tl.constexpr, BLOCK_SIZE: tl.constexpr): ...

class TritonSinkhornFunction(Function):
    @staticmethod
    def forward(ctx, log_alpha, iters: int = 20): ...
    @staticmethod
    def backward(ctx, grad_output): ...

def triton_sinkhorn(log_alpha, iters: int = 20): ...
def is_triton_available(): ...
