from _typeshed import Incomplete

class FeatureLibError(Exception):
    location: Incomplete
    def __init__(self, message, location=None) -> None: ...
    def __str__(self) -> str: ...

class IncludedFeaNotFound(FeatureLibError):
    def __str__(self) -> str: ...
