from . import DefaultTable as DefaultTable
from _typeshed import Incomplete
from fontTools.misc import sstruct as sstruct
from fontTools.misc.textTools import bytesjoin as bytesjoin, safeEval as safeEval, Tag as Tag
from fontTools.ttLib import TTFont, TTLibError as TTLibError

FVAR_HEADER_FORMAT: str
FVAR_AXIS_FORMAT: str
FVAR_INSTANCE_FORMAT: str

class table__f_v_a_r(DefaultTable.DefaultTable):
    """FonT Variations table

    The ``fvar`` table contains records of the variation axes and of the
    named instances in a variable font.

    See also https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6fvar.html
    """

    dependencies: Incomplete
    axes: Incomplete
    instances: Incomplete
    def __init__(self, tag=None) -> None: ...
    def compile(self, ttFont: TTFont): ...
    def decompile(self, data, ttFont: TTFont) -> None: ...
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...
    def getAxes(self): ...

class Axis:
    axisTag: Incomplete
    axisNameID: int
    flags: int
    minValue: float
    defaultValue: float
    maxValue: float
    def __init__(self) -> None: ...
    def compile(self): ...
    def decompile(self, data) -> None: ...
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    def fromXML(self, name, _attrs, content, ttFont: TTFont): ...

class NamedInstance:
    subfamilyNameID: int
    postscriptNameID: int
    flags: int
    coordinates: Incomplete
    def __init__(self) -> None: ...
    def compile(self, axisTags, includePostScriptName): ...
    def decompile(self, data, axisTags) -> None: ...
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont: TTFont): ...
