"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

GASP_SYMMETRIC_GRIDFIT = ...
GASP_SYMMETRIC_SMOOTHING = ...
GASP_DOGRAY = ...
GASP_GRIDFIT = ...
class table__g_a_s_p(DefaultTable.DefaultTable):
    """Grid-fitting and Scan-conversion Procedure table

    The ``gasp`` table defines the preferred rasterization settings for
    the font when rendered on monochrome and greyscale output devices.

    See also https://learn.microsoft.com/en-us/typography/opentype/spec/gasp
    """
    def decompile(self, data, ttFont): # -> None:
        ...
    
    def compile(self, ttFont): # -> bytes:
        ...
    
    def toXML(self, writer, ttFont): # -> None:
        ...
    
    def fromXML(self, name, attrs, content, ttFont): # -> None:
        ...
    


