"""
This type stub file was generated by pyright.
"""

from . import DefaultTable

log = ...
class table__h_m_t_x(DefaultTable.DefaultTable):
    """Horizontal Metrics table

    The ``hmtx`` table contains per-glyph metrics for the glyphs in a
    ``glyf``, ``CFF ``, or ``CFF2`` table, as needed for horizontal text
    layout.

    See also https://learn.microsoft.com/en-us/typography/opentype/spec/hmtx
    """
    headerTag = ...
    advanceName = ...
    sideBearingName = ...
    numberOfMetricsName = ...
    longMetricFormat = ...
    def decompile(self, data, ttFont): # -> None:
        ...
    
    def compile(self, ttFont): # -> bytes:
        ...
    
    def toXML(self, writer, ttFont): # -> None:
        ...
    
    def fromXML(self, name, attrs, content, ttFont): # -> None:
        ...
    
    def __delitem__(self, glyphName): # -> None:
        ...
    
    def __getitem__(self, glyphName):
        ...
    
    def __setitem__(self, glyphName, advance_sb_pair): # -> None:
        ...
    


