from . import DefaultTable as DefaultTable
from _typeshed import Incomplete
from fontTools.misc.textTools import readHex as readHex, safeEval as safeEval
from fontTools.ttLib import getSearchRange as getSearchRange, TTFont

log: Incomplete

class table__k_e_r_n(DefaultTable.DefaultTable):
    """Kerning table

    The ``kern`` table contains values that contextually adjust the inter-glyph
    spacing for the glyphs in a ``glyf`` table.

    Note that similar contextual spacing adjustments can also be stored
    in the "kern" feature of a ``GPOS`` table.

    See also https://learn.microsoft.com/en-us/typography/opentype/spec/kern
    """

    def getkern(self, format): ...
    version: Incomplete
    kernTables: Incomplete
    def decompile(self, data, ttFont: TTFont) -> None: ...
    def compile(self, ttFont: TTFont): ...
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...

class KernTable_format_0:
    version: int
    format: int
    apple: Incomplete
    def __init__(self, apple: bool = False) -> None: ...
    coverage: Incomplete
    tupleIndex: Incomplete
    kernTable: Incomplete
    def decompile(self, data, ttFont: TTFont) -> None: ...
    def compile(self, ttFont: TTFont): ...
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...
    def __getitem__(self, pair): ...
    def __setitem__(self, pair, value) -> None: ...
    def __delitem__(self, pair) -> None: ...

class KernTable_format_unkown:
    format: Incomplete
    def __init__(self, format) -> None: ...
    data: Incomplete
    def decompile(self, data, ttFont: TTFont) -> None: ...
    def compile(self, ttFont: TTFont): ...
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...

kern_classes: Incomplete
