from . import DefaultTable as DefaultTable
from _typeshed import Incomplete
from collections.abc import MutableMapping
from fontTools.misc import sstruct as sstruct
from fontTools.misc.textTools import bytesjoin as bytesjoin, safeEval as safeEval
from fontTools.ttLib import TTFont, TTLibError as TTLibError

TRAK_HEADER_FORMAT: str
TRAK_HEADER_FORMAT_SIZE: Incomplete
TRACK_DATA_FORMAT: str
TRACK_DATA_FORMAT_SIZE: Incomplete
TRACK_TABLE_ENTRY_FORMAT: str
TRACK_TABLE_ENTRY_FORMAT_SIZE: Incomplete
SIZE_VALUE_FORMAT: str
SIZE_VALUE_FORMAT_SIZE: Incomplete
PER_SIZE_VALUE_FORMAT: str
PER_SIZE_VALUE_FORMAT_SIZE: Incomplete

class table__t_r_a_k(DefaultTable.DefaultTable):
    """The AAT ``trak`` table can store per-size adjustments to each glyph's
    sidebearings to make when tracking is enabled, which applications can
    use to provide more visually balanced line spacing.

    See also https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6trak.html
    """

    dependencies: Incomplete
    reserved: int
    def compile(self, ttFont: TTFont): ...
    def decompile(self, data, ttFont: TTFont) -> None: ...
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    version: Incomplete
    format: Incomplete
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...

class TrackData(MutableMapping):
    _map: Incomplete
    def __init__(self, initialdata={}) -> None: ...
    def compile(self, offset): ...
    def decompile(self, data, offset) -> None: ...
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...
    def sizes(self): ...
    def __getitem__(self, track): ...
    def __delitem__(self, track) -> None: ...
    def __setitem__(self, track, entry) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def keys(self): ...
    tracks = keys

class TrackTableEntry(MutableMapping):
    nameIndex: Incomplete
    _map: Incomplete
    def __init__(self, values={}, nameIndex=None) -> None: ...
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    track: Incomplete
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...
    def __getitem__(self, size): ...
    def __delitem__(self, size) -> None: ...
    def __setitem__(self, size, value) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def keys(self): ...
    sizes = keys
    def __eq__(self, other): ...
    def __ne__(self, other): ...
