from . import DefaultTable as DefaultTable
from _typeshed import Incomplete
from fontTools.misc.textTools import bytesjoin as bytesjoin, safeEval as safeEval
from typing import NamedTuple

class table_C_P_A_L_(DefaultTable.DefaultTable):
    """Color Palette table

    The ``CPAL`` table contains a set of one or more color palettes. The color
    records in each palette can be referenced by the ``COLR`` table to specify
    the colors used in a color glyph.

    See also https://learn.microsoft.com/en-us/typography/opentype/spec/cpal
    """
    NO_NAME_ID: int
    DEFAULT_PALETTE_TYPE: int
    palettes: Incomplete
    paletteTypes: Incomplete
    paletteLabels: Incomplete
    paletteEntryLabels: Incomplete
    def __init__(self, tag=None) -> None: ...
    def decompile(self, data, ttFont) -> None: ...
    def _decompileUInt16Array(self, data, offset, numElements, default: int = 0): ...
    def _decompileUInt32Array(self, data, offset, numElements, default: int = 0): ...
    def compile(self, ttFont): ...
    def _compilePalette(self, palette): ...
    def _compileColorRecords(self): ...
    def _compilePaletteTypes(self): ...
    def _compilePaletteLabels(self): ...
    def _compilePaletteEntryLabels(self): ...
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...

class Color(NamedTuple('Color', [('blue', Incomplete), ('green', Incomplete), ('red', Incomplete), ('alpha', Incomplete)])):
    def hex(self): ...
    def __repr__(self) -> str: ...
    def toXML(self, writer, ttFont, index=None) -> None: ...
    @classmethod
    def fromHex(cls, value): ...
    @classmethod
    def fromRGBA(cls, red, green, blue, alpha): ...
