from . import DefaultTable as DefaultTable
from _typeshed import Incomplete
from fontTools.misc.textTools import tostr as tostr

class table_D__e_b_g(DefaultTable.DefaultTable):
    data: Incomplete
    def __init__(self, tag=None) -> None: ...
    def decompile(self, data, ttFont) -> None: ...
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont): ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
