from . import DefaultTable as DefaultTable
from _typeshed import Incomplete
from fontTools.misc.textTools import tostr as tostr
from fontTools.ttLib import TTFont

class table_D__e_b_g(DefaultTable.DefaultTable):
    data: Incomplete
    def __init__(self, tag=None) -> None: ...
    def decompile(self, data, ttFont: TTFont) -> None: ...
    def compile(self, ttFont: TTFont): ...
    def toXML(self, writer, ttFont: TTFont): ...
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...
