from _typeshed import Incomplete
from fontTools.misc.textTools import Tag as Tag
from fontTools.ttLib import getClassTag as getClassTag, TTFont

class DefaultTable:
    dependencies: Incomplete
    tableTag: Incomplete
    def __init__(self, tag=None) -> None: ...
    data: Incomplete
    def decompile(self, data, ttFont: TTFont) -> None: ...
    def compile(self, ttFont: TTFont): ...
    def toXML(self, writer, ttFont: TTFont, **kwargs) -> None: ...
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
