from fontTools.ttLib import TTFont
from . import DefaultTable as DefaultTable
from .BitmapGlyphMetrics import (
	BigGlyphMetrics as BigGlyphMetrics, bigGlyphMetricsFormat as bigGlyphMetricsFormat,
	SmallGlyphMetrics as SmallGlyphMetrics, smallGlyphMetricsFormat as smallGlyphMetricsFormat)
from _typeshed import Incomplete
from fontTools.misc import sstruct as sstruct
from fontTools.misc.textTools import (
	bytechr as bytechr, byteord as byteord, bytesjoin as bytesjoin, deHexStr as deHexStr, hexStr as hexStr,
	readHex as readHex, safeEval as safeEval, strjoin as strjoin)

log: Incomplete
ebdtTableVersionFormat: str
ebdtComponentFormat: str

class table_E_B_D_T_(DefaultTable.DefaultTable):
    """Embedded Bitmap Data table

    The ``EBDT`` table contains monochrome or grayscale bitmap data for
    glyphs. It must be used in concert with the ``EBLC`` table.

    See also https://learn.microsoft.com/en-us/typography/opentype/spec/ebdt
    """
    locatorName: str
    def getImageFormatClass(self, imageFormat): ...
    strikeData: Incomplete
    def decompile(self, data, ttFont: TTFont) -> None: ...
    def compile(self, ttFont: TTFont): ...
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    version: Incomplete
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...

class EbdtComponent:
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    name: Incomplete
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...

class BitmapGlyph:
    fileExtension: str
    xmlDataFunctions: Incomplete
    data: Incomplete
    ttFont: TTFont
    def __init__(self, data, ttFont: TTFont) -> None: ...
    def __getattr__(self, attr): ...
    def ensureDecompiled(self, recurse: bool = False) -> None: ...
    def getFormat(self): ...
    def toXML(self, strikeIndex, glyphName, writer, ttFont: TTFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...
    def writeMetrics(self, writer, ttFont: TTFont) -> None: ...
    def readMetrics(self, name, attrs, content, ttFont: TTFont) -> None: ...
    def writeData(self, strikeIndex, glyphName, writer, ttFont: TTFont) -> None: ...
    def readData(self, name, attrs, content, ttFont: TTFont) -> None: ...

BitmapPlusBigMetricsMixin: Incomplete
BitmapPlusSmallMetricsMixin: Incomplete

class BitAlignedBitmapMixin:
    def getRow(self, row, bitDepth: int = 1, metrics=None, reverseBytes: bool = False): ...
    imageData: Incomplete
    def setRows(self, dataRows, bitDepth: int = 1, metrics=None, reverseBytes: bool = False) -> None: ...

class ByteAlignedBitmapMixin:
    def getRow(self, row, bitDepth: int = 1, metrics=None, reverseBytes: bool = False): ...
    imageData: Incomplete
    def setRows(self, dataRows, bitDepth: int = 1, metrics=None, reverseBytes: bool = False) -> None: ...

class ebdt_bitmap_format_1(ByteAlignedBitmapMixin, BitmapPlusSmallMetricsMixin, BitmapGlyph):
    metrics: Incomplete
    imageData: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont: TTFont): ...

class ebdt_bitmap_format_2(BitAlignedBitmapMixin, BitmapPlusSmallMetricsMixin, BitmapGlyph):
    metrics: Incomplete
    imageData: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont: TTFont): ...

class ebdt_bitmap_format_5(BitAlignedBitmapMixin, BitmapGlyph):
    imageData: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont: TTFont): ...

class ebdt_bitmap_format_6(ByteAlignedBitmapMixin, BitmapPlusBigMetricsMixin, BitmapGlyph):
    metrics: Incomplete
    imageData: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont: TTFont): ...

class ebdt_bitmap_format_7(BitAlignedBitmapMixin, BitmapPlusBigMetricsMixin, BitmapGlyph):
    metrics: Incomplete
    imageData: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont: TTFont): ...

class ComponentBitmapGlyph(BitmapGlyph):
    def toXML(self, strikeIndex, glyphName, writer, ttFont: TTFont) -> None: ...
    componentArray: Incomplete
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...

class ebdt_bitmap_format_8(BitmapPlusSmallMetricsMixin, ComponentBitmapGlyph):
    metrics: Incomplete
    componentArray: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont: TTFont): ...

class ebdt_bitmap_format_9(BitmapPlusBigMetricsMixin, ComponentBitmapGlyph):
    metrics: Incomplete
    componentArray: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont: TTFont): ...

ebdt_bitmap_classes: Incomplete
