from . import DefaultTable as DefaultTable
from .BitmapGlyphMetrics import BigGlyphMetrics as BigGlyphMetrics, SmallGlyphMetrics as SmallGlyphMetrics, bigGlyphMetricsFormat as bigGlyphMetricsFormat, smallGlyphMetricsFormat as smallGlyphMetricsFormat
from _typeshed import Incomplete
from fontTools.misc import sstruct as sstruct
from fontTools.misc.textTools import bytechr as bytechr, byteord as byteord, bytesjoin as bytesjoin, deHexStr as deHexStr, hexStr as hexStr, readHex as readHex, safeEval as safeEval, strjoin as strjoin

log: Incomplete
ebdtTableVersionFormat: str
ebdtComponentFormat: str

class table_E_B_D_T_(DefaultTable.DefaultTable):
    """Embedded Bitmap Data table

    The ``EBDT`` table contains monochrome or grayscale bitmap data for
    glyphs. It must be used in concert with the ``EBLC`` table.

    See also https://learn.microsoft.com/en-us/typography/opentype/spec/ebdt
    """
    locatorName: str
    def getImageFormatClass(self, imageFormat): ...
    strikeData: Incomplete
    def decompile(self, data, ttFont) -> None: ...
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont) -> None: ...
    version: Incomplete
    def fromXML(self, name, attrs, content, ttFont) -> None: ...

class EbdtComponent:
    def toXML(self, writer, ttFont) -> None: ...
    name: Incomplete
    def fromXML(self, name, attrs, content, ttFont) -> None: ...

def _data2binary(data, numBits): ...
def _binary2data(binary): ...
def _memoize(f): ...
@_memoize
def _reverseBytes(data):
    """
    >>> bin(ord(_reverseBytes(0b00100111)))
    '0b11100100'
    >>> _reverseBytes(b'\\x00\\xf0')
    b'\\x00\\x0f'
    """
def _writeRawImageData(strikeIndex, glyphName, bitmapObject, writer, ttFont) -> None: ...
def _readRawImageData(bitmapObject, name, attrs, content, ttFont) -> None: ...
def _writeRowImageData(strikeIndex, glyphName, bitmapObject, writer, ttFont) -> None: ...
def _readRowImageData(bitmapObject, name, attrs, content, ttFont) -> None: ...
def _writeBitwiseImageData(strikeIndex, glyphName, bitmapObject, writer, ttFont) -> None: ...
def _readBitwiseImageData(bitmapObject, name, attrs, content, ttFont) -> None: ...
def _writeExtFileImageData(strikeIndex, glyphName, bitmapObject, writer, ttFont) -> None: ...
def _readExtFileImageData(bitmapObject, name, attrs, content, ttFont) -> None: ...

_bitmapGlyphSubclassPrefix: str

class BitmapGlyph:
    fileExtension: str
    xmlDataFunctions: Incomplete
    data: Incomplete
    ttFont: Incomplete
    def __init__(self, data, ttFont) -> None: ...
    def __getattr__(self, attr): ...
    def ensureDecompiled(self, recurse: bool = False) -> None: ...
    def getFormat(self): ...
    def toXML(self, strikeIndex, glyphName, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
    def writeMetrics(self, writer, ttFont) -> None: ...
    def readMetrics(self, name, attrs, content, ttFont) -> None: ...
    def writeData(self, strikeIndex, glyphName, writer, ttFont) -> None: ...
    def readData(self, name, attrs, content, ttFont) -> None: ...

def _createBitmapPlusMetricsMixin(metricsClass): ...

BitmapPlusBigMetricsMixin: Incomplete
BitmapPlusSmallMetricsMixin: Incomplete

class BitAlignedBitmapMixin:
    def _getBitRange(self, row, bitDepth, metrics): ...
    def getRow(self, row, bitDepth: int = 1, metrics=None, reverseBytes: bool = False): ...
    imageData: Incomplete
    def setRows(self, dataRows, bitDepth: int = 1, metrics=None, reverseBytes: bool = False) -> None: ...

class ByteAlignedBitmapMixin:
    def _getByteRange(self, row, bitDepth, metrics): ...
    def getRow(self, row, bitDepth: int = 1, metrics=None, reverseBytes: bool = False): ...
    imageData: Incomplete
    def setRows(self, dataRows, bitDepth: int = 1, metrics=None, reverseBytes: bool = False) -> None: ...

class ebdt_bitmap_format_1(ByteAlignedBitmapMixin, BitmapPlusSmallMetricsMixin, BitmapGlyph):
    metrics: Incomplete
    imageData: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont): ...

class ebdt_bitmap_format_2(BitAlignedBitmapMixin, BitmapPlusSmallMetricsMixin, BitmapGlyph):
    metrics: Incomplete
    imageData: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont): ...

class ebdt_bitmap_format_5(BitAlignedBitmapMixin, BitmapGlyph):
    imageData: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont): ...

class ebdt_bitmap_format_6(ByteAlignedBitmapMixin, BitmapPlusBigMetricsMixin, BitmapGlyph):
    metrics: Incomplete
    imageData: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont): ...

class ebdt_bitmap_format_7(BitAlignedBitmapMixin, BitmapPlusBigMetricsMixin, BitmapGlyph):
    metrics: Incomplete
    imageData: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont): ...

class ComponentBitmapGlyph(BitmapGlyph):
    def toXML(self, strikeIndex, glyphName, writer, ttFont) -> None: ...
    componentArray: Incomplete
    def fromXML(self, name, attrs, content, ttFont) -> None: ...

class ebdt_bitmap_format_8(BitmapPlusSmallMetricsMixin, ComponentBitmapGlyph):
    metrics: Incomplete
    componentArray: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont): ...

class ebdt_bitmap_format_9(BitmapPlusBigMetricsMixin, ComponentBitmapGlyph):
    metrics: Incomplete
    componentArray: Incomplete
    def decompile(self) -> None: ...
    def compile(self, ttFont): ...

ebdt_bitmap_classes: Incomplete
