from . import DefaultTable as DefaultTable
from .BitmapGlyphMetrics import BigGlyphMetrics as BigGlyphMetrics, SmallGlyphMetrics as SmallGlyphMetrics, bigGlyphMetricsFormat as bigGlyphMetricsFormat, smallGlyphMetricsFormat as smallGlyphMetricsFormat
from _typeshed import Incomplete
from fontTools.misc import sstruct as sstruct
from fontTools.misc.textTools import bytesjoin as bytesjoin, safeEval as safeEval

log: Incomplete
eblcHeaderFormat: str
bitmapSizeTableFormatPart1: str
sbitLineMetricsFormat: str
bitmapSizeTableFormatPart2: str
indexSubTableArrayFormat: str
indexSubTableArraySize: Incomplete
indexSubHeaderFormat: str
indexSubHeaderSize: Incomplete
codeOffsetPairFormat: str
codeOffsetPairSize: Incomplete

class table_E_B_L_C_(DefaultTable.DefaultTable):
    """Embedded Bitmap Location table

    The ``EBLC`` table contains the locations of monochrome or grayscale
    bitmaps for glyphs. It must be used in concert with the ``EBDT`` table.

    See also https://learn.microsoft.com/en-us/typography/opentype/spec/eblc
    """
    dependencies: Incomplete
    def getIndexFormatClass(self, indexFormat): ...
    strikes: Incomplete
    def decompile(self, data, ttFont) -> None: ...
    numSizes: Incomplete
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont) -> None: ...
    version: Incomplete
    def fromXML(self, name, attrs, content, ttFont) -> None: ...

class Strike:
    bitmapSizeTable: Incomplete
    indexSubTables: Incomplete
    def __init__(self) -> None: ...
    def toXML(self, strikeIndex, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont, locator) -> None: ...

class BitmapSizeTable:
    def _getXMLMetricNames(self): ...
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...

class SbitLineMetrics:
    def toXML(self, name, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...

_indexSubTableSubclassPrefix: str

class EblcIndexSubTable:
    data: Incomplete
    ttFont: Incomplete
    def __init__(self, data, ttFont) -> None: ...
    def __getattr__(self, attr): ...
    def ensureDecompiled(self, recurse: bool = False) -> None: ...
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont) -> None: ...
    imageFormat: Incomplete
    firstGlyphIndex: Incomplete
    lastGlyphIndex: Incomplete
    names: Incomplete
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
    def writeMetrics(self, writer, ttFont) -> None: ...
    def readMetrics(self, name, attrs, content, ttFont) -> None: ...
    def padBitmapData(self, data): ...
    def removeSkipGlyphs(self): ...

def _createOffsetArrayIndexSubTableMixin(formatStringForDataType): ...

class FixedSizeIndexSubTableMixin:
    def writeMetrics(self, writer, ttFont) -> None: ...
    imageSize: Incomplete
    metrics: Incomplete
    def readMetrics(self, name, attrs, content, ttFont) -> None: ...
    def padBitmapData(self, data): ...

class eblc_index_sub_table_1(Incomplete, EblcIndexSubTable): ...

class eblc_index_sub_table_2(FixedSizeIndexSubTableMixin, EblcIndexSubTable):
    metrics: Incomplete
    locations: Incomplete
    names: Incomplete
    def decompile(self) -> None: ...
    imageDataOffset: Incomplete
    def compile(self, ttFont): ...

class eblc_index_sub_table_3(Incomplete, EblcIndexSubTable): ...

class eblc_index_sub_table_4(EblcIndexSubTable):
    locations: Incomplete
    names: Incomplete
    def decompile(self) -> None: ...
    imageDataOffset: Incomplete
    def compile(self, ttFont): ...

class eblc_index_sub_table_5(FixedSizeIndexSubTableMixin, EblcIndexSubTable):
    origDataLen: int
    locations: Incomplete
    names: Incomplete
    def decompile(self) -> None: ...
    imageDataOffset: Incomplete
    def compile(self, ttFont): ...

eblc_sub_table_classes: Incomplete
