from . import DefaultTable as DefaultTable
from _typeshed import Incomplete
from fontTools.misc import sstruct as sstruct
from fontTools.misc.textTools import safeEval as safeEval
from fontTools.ttLib import TTFont

Gloc_header: str

class table_G__l_o_c(DefaultTable.DefaultTable):
    """Graphite Index to Glyph Atttributes table

    See also https://graphite.sil.org/graphite_techAbout#graphite-font-tables
    """

    dependencies: Incomplete
    attribIds: Incomplete
    numAttribs: int
    def __init__(self, tag=None) -> None: ...
    locations: Incomplete
    def decompile(self, data, ttFont: TTFont) -> None: ...
    def compile(self, ttFont: TTFont): ...
    def set(self, locations) -> None: ...
    def toXML(self, writer, ttFont: TTFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont: TTFont) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
