from _typeshed import Incomplete
from collections.abc import Generator

def decompress(data): ...
def compress(scheme, data): ...
def _entries(attrs, sameval) -> Generator[Incomplete]: ...
def entries(attributes, sameval: bool = False): ...
def bininfo(num, size: int = 1): ...
def num2tag(n): ...
def tag2num(n): ...
