from .otBase import BaseTable as BaseTable, CountReference as CountReference, FormatSwitchingBaseTable as FormatSwitchingBaseTable, ValueRecord as ValueRecord, getFormatSwitchingBaseTableClass as getFormatSwitchingBaseTableClass
from _typeshed import Incomplete
from enum import IntEnum, IntFlag
from fontTools.feaLib.lookupDebugInfo import LOOKUP_DEBUG_INFO_KEY as LOOKUP_DEBUG_INFO_KEY, LookupDebugInfo as LookupDebugInfo
from fontTools.misc.arrayTools import quantizeRect as quantizeRect
from fontTools.misc.roundTools import otRound as otRound
from fontTools.misc.textTools import bytesjoin as bytesjoin, pad as pad, safeEval as safeEval
from fontTools.misc.transform import DecomposedTransform as DecomposedTransform, Identity as Identity, Transform as Transform
from fontTools.misc.vector import Vector as Vector
from fontTools.pens.boundsPen import ControlBoundsPen as ControlBoundsPen
from fontTools.pens.transformPen import TransformPen as TransformPen
from fontTools.ttLib import OPTIMIZE_FONT_SPEED as OPTIMIZE_FONT_SPEED
from fontTools.ttLib.tables.TupleVariation import TupleVariation as TupleVariation
from fontTools.ttLib.tables.otTraverse import dfs_base_table as dfs_base_table
from fontTools.ttLib.ttGlyphSet import _TTGlyphSet as _TTGlyphSet
from typing import Iterator, NamedTuple

log: Incomplete

class VarComponentFlags(IntFlag):
    RESET_UNSPECIFIED_AXES = ...
    HAVE_AXES = ...
    AXIS_VALUES_HAVE_VARIATION = ...
    TRANSFORM_HAS_VARIATION = ...
    HAVE_TRANSLATE_X = ...
    HAVE_TRANSLATE_Y = ...
    HAVE_ROTATION = ...
    HAVE_CONDITION = ...
    HAVE_SCALE_X = ...
    HAVE_SCALE_Y = ...
    HAVE_TCENTER_X = ...
    HAVE_TCENTER_Y = ...
    GID_IS_24BIT = ...
    HAVE_SKEW_X = ...
    HAVE_SKEW_Y = ...
    RESERVED_MASK = ...

class VarTransformMappingValues(NamedTuple):
    flag: Incomplete
    fractionalBits: Incomplete
    scale: Incomplete
    defaultValue: Incomplete

VAR_TRANSFORM_MAPPING: Incomplete
_packer: Incomplete
_unpacker: Incomplete

def _read_uint32var(data, i):
    """Read a variable-length number from data starting at index i.

    Return the number and the next index.
    """
def _write_uint32var(v):
    """Write a variable-length number.

    Return the data.
    """

class VarComponent:
    def __init__(self) -> None: ...
    flags: int
    glyphName: Incomplete
    conditionIndex: Incomplete
    axisIndicesIndex: Incomplete
    axisValues: Incomplete
    axisValuesVarIndex: Incomplete
    transformVarIndex: Incomplete
    transform: Incomplete
    def populateDefaults(self, propagator=None) -> None: ...
    def decompile(self, data, font, localState): ...
    def compile(self, font): ...
    def toXML(self, writer, ttFont, attrs) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
    def applyTransformDeltas(self, deltas): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

class VarCompositeGlyph:
    components: Incomplete
    def __init__(self, components=None) -> None: ...
    def decompile(self, data, font, localState) -> None: ...
    def compile(self, font): ...
    def toXML(self, xmlWriter, font, attrs, name) -> None: ...
    def fromXML(self, name, attrs, content, font) -> None: ...

class AATStateTable:
    GlyphClasses: Incomplete
    States: Incomplete
    PerGlyphLookups: Incomplete
    def __init__(self) -> None: ...

class AATState:
    Transitions: Incomplete
    def __init__(self) -> None: ...

class AATAction:
    _FLAGS: Incomplete
    @staticmethod
    def compileActions(font, states): ...
    def _writeFlagsToXML(self, xmlWriter) -> None: ...
    def _setFlag(self, flag) -> None: ...

class RearrangementMorphAction(AATAction):
    staticSize: int
    actionHeaderSize: int
    _FLAGS: Incomplete
    _VERBS: Incomplete
    NewState: int
    Verb: int
    MarkFirst: bool
    DontAdvance: bool
    MarkLast: bool
    ReservedFlags: int
    def __init__(self) -> None: ...
    def compile(self, writer, font, actionIndex) -> None: ...
    def decompile(self, reader, font, actionReader) -> None: ...
    def toXML(self, xmlWriter, font, attrs, name) -> None: ...
    def fromXML(self, name, attrs, content, font) -> None: ...

class ContextualMorphAction(AATAction):
    staticSize: int
    actionHeaderSize: int
    _FLAGS: Incomplete
    NewState: int
    ReservedFlags: int
    def __init__(self) -> None: ...
    def compile(self, writer, font, actionIndex) -> None: ...
    SetMark: Incomplete
    DontAdvance: Incomplete
    MarkIndex: Incomplete
    CurrentIndex: Incomplete
    def decompile(self, reader, font, actionReader) -> None: ...
    def toXML(self, xmlWriter, font, attrs, name) -> None: ...
    def fromXML(self, name, attrs, content, font) -> None: ...

class LigAction:
    Store: bool
    GlyphIndexDelta: int
    def __init__(self) -> None: ...

class LigatureMorphAction(AATAction):
    staticSize: int
    actionHeaderSize: int
    _FLAGS: Incomplete
    NewState: int
    ReservedFlags: int
    Actions: Incomplete
    def __init__(self) -> None: ...
    def compile(self, writer, font, actionIndex) -> None: ...
    SetComponent: Incomplete
    DontAdvance: Incomplete
    def decompile(self, reader, font, actionReader) -> None: ...
    @staticmethod
    def compileActions(font, states): ...
    def compileLigActions(self): ...
    def _decompileLigActions(self, actionReader, actionIndex): ...
    def fromXML(self, name, attrs, content, font) -> None: ...
    def toXML(self, xmlWriter, font, attrs, name) -> None: ...

class InsertionMorphAction(AATAction):
    staticSize: int
    actionHeaderSize: int
    _FLAGS: Incomplete
    NewState: int
    ReservedFlags: int
    def __init__(self) -> None: ...
    def compile(self, writer, font, actionIndex) -> None: ...
    SetMark: Incomplete
    DontAdvance: Incomplete
    CurrentIsKashidaLike: Incomplete
    MarkedIsKashidaLike: Incomplete
    CurrentInsertBefore: Incomplete
    MarkedInsertBefore: Incomplete
    CurrentInsertionAction: Incomplete
    MarkedInsertionAction: Incomplete
    def decompile(self, reader, font, actionReader) -> None: ...
    def _decompileInsertionAction(self, actionReader, font, index, count): ...
    def toXML(self, xmlWriter, font, attrs, name) -> None: ...
    def fromXML(self, name, attrs, content, font) -> None: ...
    @staticmethod
    def compileActions(font, states): ...

class FeatureParams(BaseTable):
    def compile(self, writer, font) -> None: ...
    def toXML(self, xmlWriter, font, attrs=None, name=None) -> None: ...

class FeatureParamsSize(FeatureParams): ...
class FeatureParamsStylisticSet(FeatureParams): ...
class FeatureParamsCharacterVariants(FeatureParams): ...

class Coverage(FormatSwitchingBaseTable):
    glyphs: Incomplete
    def populateDefaults(self, propagator=None) -> None: ...
    def postRead(self, rawTable, font): ...
    Format: Incomplete
    def preWrite(self, font): ...
    def toXML2(self, xmlWriter, font) -> None: ...
    def fromXML(self, name, attrs, content, font) -> None: ...

NO_VARIATION_INDEX: int

class DeltaSetIndexMap(Incomplete):
    mapping: Incomplete
    def populateDefaults(self, propagator=None) -> None: ...
    def postRead(self, rawTable, font) -> None: ...
    @staticmethod
    def getEntryFormat(mapping): ...
    Format: Incomplete
    def preWrite(self, font): ...
    def toXML2(self, xmlWriter, font) -> None: ...
    def fromXML(self, name, attrs, content, font) -> None: ...
    def __getitem__(self, i): ...

class VarIdxMap(BaseTable):
    mapping: Incomplete
    def populateDefaults(self, propagator=None) -> None: ...
    def postRead(self, rawTable, font) -> None: ...
    def preWrite(self, font): ...
    def toXML2(self, xmlWriter, font) -> None: ...
    def fromXML(self, name, attrs, content, font) -> None: ...
    def __getitem__(self, glyphName): ...

class VarRegionList(BaseTable):
    RegionAxisCount: Incomplete
    def preWrite(self, font): ...

class SingleSubst(FormatSwitchingBaseTable):
    mapping: Incomplete
    def populateDefaults(self, propagator=None) -> None: ...
    def postRead(self, rawTable, font) -> None: ...
    Format: Incomplete
    def preWrite(self, font): ...
    def toXML2(self, xmlWriter, font) -> None: ...
    def fromXML(self, name, attrs, content, font) -> None: ...

class MultipleSubst(FormatSwitchingBaseTable):
    mapping: Incomplete
    def populateDefaults(self, propagator=None) -> None: ...
    def postRead(self, rawTable, font) -> None: ...
    Format: int
    def preWrite(self, font): ...
    def toXML2(self, xmlWriter, font) -> None: ...
    old_coverage_: Incomplete
    def fromXML(self, name, attrs, content, font) -> None: ...
    @staticmethod
    def makeSequence_(g): ...

class ClassDef(FormatSwitchingBaseTable):
    classDefs: Incomplete
    def populateDefaults(self, propagator=None) -> None: ...
    def postRead(self, rawTable, font) -> None: ...
    def _getClassRanges(self, font): ...
    Format: Incomplete
    def preWrite(self, font): ...
    def toXML2(self, xmlWriter, font) -> None: ...
    def fromXML(self, name, attrs, content, font) -> None: ...

class AlternateSubst(FormatSwitchingBaseTable):
    alternates: Incomplete
    def populateDefaults(self, propagator=None) -> None: ...
    def postRead(self, rawTable, font) -> None: ...
    Format: int
    sortCoverageLast: int
    def preWrite(self, font): ...
    def toXML2(self, xmlWriter, font) -> None: ...
    def fromXML(self, name, attrs, content, font) -> None: ...

class LigatureSubst(FormatSwitchingBaseTable):
    ligatures: Incomplete
    def populateDefaults(self, propagator=None) -> None: ...
    def postRead(self, rawTable, font) -> None: ...
    @staticmethod
    def _getLigatureSortKey(components): ...
    Format: int
    sortCoverageLast: int
    def preWrite(self, font): ...
    def toXML2(self, xmlWriter, font) -> None: ...
    def fromXML(self, name, attrs, content, font) -> None: ...

class COLR(BaseTable):
    def decompile(self, reader, font): ...
    LayerRecordCount: Incomplete
    def preWrite(self, font): ...
    ClipList: Incomplete
    def computeClipBoxes(self, glyphSet: _TTGlyphSet, quantization: int = 1): ...

class LookupList(BaseTable):
    @property
    def table(self): ...
    def toXML2(self, xmlWriter, font): ...

class BaseGlyphRecordArray(BaseTable):
    BaseGlyphRecord: Incomplete
    def preWrite(self, font): ...

class BaseGlyphList(BaseTable):
    BaseGlyphPaintRecord: Incomplete
    def preWrite(self, font): ...

class ClipBoxFormat(IntEnum):
    Static = 1
    Variable = 2
    def is_variable(self): ...
    def as_variable(self): ...

class ClipBox(Incomplete):
    formatEnum = ClipBoxFormat
    def as_tuple(self): ...
    def __repr__(self) -> str: ...

class ClipList(Incomplete):
    clips: Incomplete
    def populateDefaults(self, propagator=None) -> None: ...
    def postRead(self, rawTable, font) -> None: ...
    def groups(self): ...
    def preWrite(self, font): ...
    def toXML(self, xmlWriter, font, attrs=None, name=None): ...
    def fromXML(self, name, attrs, content, font) -> None: ...

class ExtendMode(IntEnum):
    PAD = 0
    REPEAT = 1
    REFLECT = 2

class CompositeMode(IntEnum):
    CLEAR = 0
    SRC = 1
    DEST = 2
    SRC_OVER = 3
    DEST_OVER = 4
    SRC_IN = 5
    DEST_IN = 6
    SRC_OUT = 7
    DEST_OUT = 8
    SRC_ATOP = 9
    DEST_ATOP = 10
    XOR = 11
    PLUS = 12
    SCREEN = 13
    OVERLAY = 14
    DARKEN = 15
    LIGHTEN = 16
    COLOR_DODGE = 17
    COLOR_BURN = 18
    HARD_LIGHT = 19
    SOFT_LIGHT = 20
    DIFFERENCE = 21
    EXCLUSION = 22
    MULTIPLY = 23
    HSL_HUE = 24
    HSL_SATURATION = 25
    HSL_COLOR = 26
    HSL_LUMINOSITY = 27

class PaintFormat(IntEnum):
    PaintColrLayers = 1
    PaintSolid = 2
    PaintVarSolid = 3
    PaintLinearGradient = 4
    PaintVarLinearGradient = 5
    PaintRadialGradient = 6
    PaintVarRadialGradient = 7
    PaintSweepGradient = 8
    PaintVarSweepGradient = 9
    PaintGlyph = 10
    PaintColrGlyph = 11
    PaintTransform = 12
    PaintVarTransform = 13
    PaintTranslate = 14
    PaintVarTranslate = 15
    PaintScale = 16
    PaintVarScale = 17
    PaintScaleAroundCenter = 18
    PaintVarScaleAroundCenter = 19
    PaintScaleUniform = 20
    PaintVarScaleUniform = 21
    PaintScaleUniformAroundCenter = 22
    PaintVarScaleUniformAroundCenter = 23
    PaintRotate = 24
    PaintVarRotate = 25
    PaintRotateAroundCenter = 26
    PaintVarRotateAroundCenter = 27
    PaintSkew = 28
    PaintVarSkew = 29
    PaintSkewAroundCenter = 30
    PaintVarSkewAroundCenter = 31
    PaintComposite = 32
    def is_variable(self): ...
    def as_variable(self): ...

class Paint(Incomplete):
    formatEnum = PaintFormat
    def getFormatName(self): ...
    def toXML(self, xmlWriter, font, attrs=None, name=None) -> None: ...
    def iterPaintSubTables(self, colr: COLR) -> Iterator[BaseTable.SubTableEntry]: ...
    def getChildren(self, colr) -> list['Paint']: ...
    def traverse(self, colr: COLR, callback):
        """Depth-first traversal of graph rooted at self, callback on each node."""
    def getTransform(self) -> Transform: ...
    def computeClipBox(self, colr: COLR, glyphSet: _TTGlyphSet, quantization: int = 1) -> ClipBox | None: ...

_equivalents: Incomplete

def fixLookupOverFlows(ttf, overflowRecord):
    """Either the offset from the LookupList to a lookup overflowed, or
    an offset from a lookup to a subtable overflowed.

    The table layout is::

      GPSO/GUSB
              Script List
              Feature List
              LookUpList
                      Lookup[0] and contents
                              SubTable offset list
                                      SubTable[0] and contents
                                      ...
                                      SubTable[n] and contents
                      ...
                      Lookup[n] and contents
                              SubTable offset list
                                      SubTable[0] and contents
                                      ...
                                      SubTable[n] and contents

    If the offset to a lookup overflowed (SubTableIndex is None)
            we must promote the *previous* lookup to an Extension type.

    If the offset from a lookup to subtable overflowed, then we must promote it
            to an Extension Lookup type.
    """
def splitMultipleSubst(oldSubTable, newSubTable, overflowRecord): ...
def splitAlternateSubst(oldSubTable, newSubTable, overflowRecord): ...
def splitLigatureSubst(oldSubTable, newSubTable, overflowRecord): ...
def splitPairPos(oldSubTable, newSubTable, overflowRecord): ...
def splitMarkBasePos(oldSubTable, newSubTable, overflowRecord): ...

splitTable: Incomplete

def fixSubTableOverFlows(ttf, overflowRecord):
    """
    An offset has overflowed within a sub-table. We need to divide this subtable into smaller parts.
    """
def _buildClasses() -> None: ...
def _getGlyphsFromCoverageTable(coverage): ...
