"""
This type stub file was generated by pyright.
"""

from . import DefaultTable
from collections.abc import Sequence
from dataclasses import dataclass

"""Compiles/decompiles SVG table.

https://docs.microsoft.com/en-us/typography/opentype/spec/svg

The XML format is:

.. code-block:: xml

	<SVG>
		<svgDoc endGlyphID="1" startGlyphID="1">
			<![CDATA[ <complete SVG doc> ]]
		</svgDoc>
	...
		<svgDoc endGlyphID="n" startGlyphID="m">
			<![CDATA[ <complete SVG doc> ]]
		</svgDoc>
	</SVG>
"""
log = ...
SVG_format_0 = ...
SVG_format_0Size = ...
doc_index_entry_format_0 = ...
doc_index_entry_format_0Size = ...
class table_S_V_G_(DefaultTable.DefaultTable):
    """Scalable Vector Graphics table

    The ``SVG`` table contains representations for glyphs in the SVG
    image format.

    See also https://learn.microsoft.com/en-us/typography/opentype/spec/stat
    """
    def decompile(self, data, ttFont): # -> None:
        ...
    
    def compile(self, ttFont): # -> bytes:
        ...
    
    def toXML(self, writer, ttFont): # -> None:
        ...
    
    def fromXML(self, name, attrs, content, ttFont): # -> None:
        ...
    


class DocumentIndexEntry:
    def __init__(self) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


@dataclass
class SVGDocument(Sequence):
    data: str
    startGlyphID: int
    endGlyphID: int
    compressed: bool = ...
    def __getitem__(self, index): # -> Any:
        ...
    
    def __len__(self): # -> Literal[3]:
        ...
    


