import _cython_3_0_11
from pandas.compat._optional import import_optional_dependency as import_optional_dependency

__pyx_capi__: dict
__test__: dict
_p_tz_cache_key: _cython_3_0_11.cython_function_or_method
dst_cache: dict
get_timezone: _cython_3_0_11.cython_function_or_method
infer_tzinfo: _cython_3_0_11.cython_function_or_method
is_fixed_offset: _cython_3_0_11.cython_function_or_method
is_utc: _cython_3_0_11.cython_function_or_method
maybe_get_tz: _cython_3_0_11.cython_function_or_method
tz_compare: _cython_3_0_11.cython_function_or_method
tz_standardize: _cython_3_0_11.cython_function_or_method
