import _cython_3_0_11
from pandas._libs.tslibs.dtypes import Resolution as Resolution

__test__: dict
dt64arr_to_periodarr: _cython_3_0_11.cython_function_or_method
get_resolution: _cython_3_0_11.cython_function_or_method
ints_to_pydatetime: _cython_3_0_11.cython_function_or_method
is_date_array_normalized: _cython_3_0_11.cython_function_or_method
normalize_i8_timestamps: _cython_3_0_11.cython_function_or_method
tz_convert_from_utc: _cython_3_0_11.cython_function_or_method
