from _typeshed import Incomplete
from fontTools.pens.basePen import BasePen

__all__ = ['AreaPen']

class AreaPen(BasePen):
    value: int
    def __init__(self, glyphset=None) -> None: ...
    _p0: Incomplete
    def _moveTo(self, p0) -> None: ...
    def _lineTo(self, p1) -> None: ...
    def _qCurveToOne(self, p1, p2) -> None: ...
    def _curveToOne(self, p1, p2, p3) -> None: ...
    def _closePath(self) -> None: ...
    def _endPath(self) -> None: ...
