from _typeshed import Incomplete
from fontTools.pens.basePen import BasePen

__all__ = ['PerimeterPen']

class PerimeterPen(BasePen):
    value: int
    tolerance: Incomplete
    _addCubic: Incomplete
    _addQuadratic: Incomplete
    def __init__(self, glyphset=None, tolerance: float = 0.005) -> None: ...
    __startPoint: Incomplete
    def _moveTo(self, p0) -> None: ...
    def _closePath(self) -> None: ...
    def _lineTo(self, p1) -> None: ...
    def _addQuadraticExact(self, c0, c1, c2) -> None: ...
    def _addQuadraticQuadrature(self, c0, c1, c2) -> None: ...
    def _qCurveToOne(self, p1, p2) -> None: ...
    def _addCubicRecursive(self, c0, c1, c2, c3) -> None: ...
    def _addCubicQuadrature(self, c0, c1, c2, c3) -> None: ...
    def _curveToOne(self, p1, p2, p3) -> None: ...
