from _typeshed import Incomplete
from fontTools.pens.basePen import BasePen

__all__ = ['ReportLabPen']

class ReportLabPen(BasePen):
    """A pen for drawing onto a ``reportlab.graphics.shapes.Path`` object."""

    path: Incomplete
    def __init__(self, glyphSet, path=None) -> None: ...
    def _moveTo(self, p) -> None: ...
    def _lineTo(self, p) -> None: ...
    def _curveToOne(self, p1, p2, p3) -> None: ...
    def _closePath(self) -> None: ...
