"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, List
from fontTools.misc.psCharStrings import T2CharString
from fontTools.pens.basePen import BasePen

class T2CharStringPen(BasePen):
    """Pen to draw Type 2 CharStrings.

    The 'roundTolerance' argument controls the rounding of point coordinates.
    It is defined as the maximum absolute difference between the original
    float and the rounded integer value.
    The default tolerance of 0.5 means that all floats are rounded to integer;
    a value of 0 disables rounding; values in between will only round floats
    which are close to their integral part within the tolerated range.
    """
    def __init__(self, width: float | None, glyphSet: Dict[str, Any] | None, roundTolerance: float = ..., CFF2: bool = ...) -> None:
        ...
    
    def getCharString(self, private: Dict | None = ..., globalSubrs: List | None = ..., optimize: bool = ...) -> T2CharString:
        ...
    


