"""
This type stub file was generated by pyright.
"""

def OpenFonts(directory=..., showInterface=..., fileExtensions=...): # -> Generator[Never, Any, None]:
    """
    Open all fonts with the given **fileExtensions** located in
    **directory**. If **directory** is ``None``, a dialog for
    selecting a directory will be opened. **directory** may also
    be a list of directories. If **showInterface** is ``False``,
    the font should be opened without graphical interface. The default
    for **showInterface** is ``True``.

    The fonts are located within the directory using the `glob`
    <https://docs.python.org/library/glob.html>`_ module. The
    patterns are created with ``os.path.join(glob, "*" + fileExtension)``
    for every file extension in ``fileExtensions``. If ``fileExtensions``
    if ``None`` the environment will use its default fileExtensions.

    ::

        from fontParts.world import *

        fonts = OpenFonts()
        fonts = OpenFonts(showInterface=False)
    """
    ...

def OpenFont(path, showInterface=...):
    """
    Open font located at **path**. If **showInterface**
    is ``False``, the font should be opened without
    graphical interface. The default for **showInterface**
    is ``True``.

    ::

        from fontParts.world import *

        font = OpenFont("/path/to/my/font.ufo")
        font = OpenFont("/path/to/my/font.ufo", showInterface=False)
    """
    ...

def NewFont(familyName=..., styleName=..., showInterface=...):
    """
    Create a new font. **familyName** will be assigned
    to ``font.info.familyName`` and **styleName**
    will be assigned to ``font.info.styleName``. These
    are optional and default to ``None``. If **showInterface**
    is ``False``, the font should be created without
    graphical interface. The default for **showInterface**
    is ``True``.

    ::

        from fontParts.world import *

        font = NewFont()
        font = NewFont(familyName="My Family", styleName="My Style")
        font = NewFont(showInterface=False)
    """
    ...

def CurrentFont():
    """
    Get the "current" font.
    """
    ...

def CurrentGlyph():
    """
    Get the "current" glyph from :func:`CurrentFont`.

    ::

        from fontParts.world import *

        glyph = CurrentGlyph()
    """
    ...

def CurrentLayer():
    """
    Get the "current" layer from :func:`CurrentGlyph`.

    ::

        from fontParts.world import *

        layer = CurrentLayer()
    """
    ...

def CurrentContours():
    """
    Get the "currently" selected contours from :func:`CurrentGlyph`.

    ::

        from fontParts.world import *

        contours = CurrentContours()

    This returns an immutable list, even when nothing is selected.
    """
    ...

def CurrentSegments():
    """
    Get the "currently" selected segments from :func:`CurrentContours`.

    ::

        from fontParts.world import *

        segments = CurrentSegments()

    This returns an immutable list, even when nothing is selected.
    """
    ...

def CurrentPoints():
    """
    Get the "currently" selected points from :func:`CurrentContours`.

    ::

        from fontParts.world import *

        points = CurrentPoints()

    This returns an immutable list, even when nothing is selected.
    """
    ...

def CurrentComponents():
    """
    Get the "currently" selected components from :func:`CurrentGlyph`.

    ::

        from fontParts.world import *

        components = CurrentComponents()

    This returns an immutable list, even when nothing is selected.
    """
    ...

def CurrentAnchors():
    """
    Get the "currently" selected anchors from :func:`CurrentGlyph`.

    ::

        from fontParts.world import *

        anchors = CurrentAnchors()

    This returns an immutable list, even when nothing is selected.
    """
    ...

def CurrentGuidelines():
    """
    Get the "currently" selected guidelines from :func:`CurrentGlyph`.
    This will include both font level and glyph level guidelines.

    ::

        from fontParts.world import *

        guidelines = CurrentGuidelines()

    This returns an immutable list, even when nothing is selected.
    """
    ...

def AllFonts(sortOptions=...):
    """
    Get a list of all open fonts. Optionally, provide a
    value for ``sortOptions`` to sort the fonts. See
    :meth:`world.FontList.sortBy` for options.

    ::

        from fontParts.world import *

        fonts = AllFonts()
        for font in fonts:
            # do something

        fonts = AllFonts("magic")
        for font in fonts:
            # do something

        fonts = AllFonts(["familyName", "styleName"])
        for font in fonts:
            # do something
    """
    ...

def RFont(path=..., showInterface=...):
    ...

def RGlyph():
    ...

def FontList(fonts=...):
    """
    Get a list with font specific methods.

    ::

        from fontParts.world import *

        fonts = FontList()

    Refer to :class:`BaseFontList` for full documentation.
    """
    ...

class BaseFontList(list):
    def sortBy(self, sortOptions, reverse=...): # -> None:
        """
        Sort ``fonts`` with the ordering preferences defined
        by ``sortBy``. ``sortBy`` must be one of the following:

        * sort description string
        * :class:`BaseInfo` attribute name
        * sort value function
        * list/tuple containing sort description strings, :class:`BaseInfo`
          attribute names and/or sort value functions
        * ``"magic"``

        Sort Description Strings
        ------------------------

        The sort description strings, and how they modify the sort, are:

        +----------------------+--------------------------------------+
        | ``"familyName"``     | Family names by alphabetical order.  |
        +----------------------+--------------------------------------+
        | ``"styleName"``      | Style names by alphabetical order.   |
        +----------------------+--------------------------------------+
        | ``"isItalic"``       | Italics before romans.               |
        +----------------------+--------------------------------------+
        | ``"isRoman"``        | Romans before italics.               |
        +----------------------+--------------------------------------+
        | ``"widthValue"``     | Width values by numerical order.     |
        +----------------------+--------------------------------------+
        | ``"weightValue"``    | Weight values by numerical order.    |
        +----------------------+--------------------------------------+
        | ``"monospace"``      | Monospaced before proportional.      |
        +----------------------+--------------------------------------+
        | ``"isProportional"`` | Proportional before monospaced.      |
        +----------------------+--------------------------------------+

        ::

            >>> fonts.sortBy(("familyName", "styleName"))


        Font Info Attribute Names
        -------------------------

        Any :class:`BaseFont` attribute name may be included as
        a sort option. For example, to sort by x-height value,
        you'd use the ``"xHeight"`` attribute name.

        ::

            >>> fonts.sortBy("xHeight")


        Sort Value Function
        -------------------

        A sort value function must be a function that accepts
        one argument, ``font``. This function must return
        a sortable value for the given font. For example:

        ::

            >>> def glyphCountSortValue(font):
            >>>   return len(font)
            >>>
            >>> fonts.sortBy(glyphCountSortValue)

        A list of sort description strings and/or sort functions
        may also be provided. This should be in order of most
        to least important. For example, to sort by family name
        and then style name, do this:


        "magic"
        -------

        If "magic" is given for ``sortBy``, the fonts will be
        sorted based on this sort description sequence:

        * ``"familyName"``
        * ``"isProportional"``
        * ``"widthValue"``
        * ``"weightValue"``
        * ``"styleName"``
        * ``"isRoman"``

        ::

            >>> fonts.sortBy("magic")
        """
        ...
    
    def getFontsByFontInfoAttribute(self, *attributeValuePairs): # -> Self:
        """
        Get a list of fonts that match the (attribute, value)
        combinations in ``attributeValuePairs``.

        ::

            >>> subFonts = fonts.getFontsByFontInfoAttribute(("xHeight", 20))
            >>> subFonts = fonts.getFontsByFontInfoAttribute(("xHeight", 20), ("descender", -150))

        This will return an instance of :class:`BaseFontList`.
        """
        ...
    
    def getFontsByFamilyName(self, familyName): # -> Self:
        """
        Get a list of fonts that match ``familyName``.
        This will return an instance of :class:`BaseFontList`.
        """
        ...
    
    def getFontsByStyleName(self, styleName): # -> Self:
        """
        Get a list of fonts that match ``styleName``.
        This will return an instance of :class:`BaseFontList`.
        """
        ...
    
    def getFontsByFamilyNameStyleName(self, familyName, styleName): # -> Self:
        """
        Get a list of fonts that match ``familyName`` and ``styleName``.
        This will return an instance of :class:`BaseFontList`.
        """
        ...
    


class _EnvironmentDispatcher:
    def __init__(self, registryItems) -> None:
        ...
    
    def __setitem__(self, name, func): # -> None:
        ...
    
    def __getitem__(self, name):
        ...
    


dispatcher = ...
