from google.colab import output as output

class Element:
    def __init__(self, tag, attributes=None, properties=None, src=None) -> None: ...
    def get_attribute(self, name): ...
    def set_attribute(self, name, value) -> None: ...
    def get_property(self, name): ...
    def set_property(self, name, value) -> None: ...
    def call(self, method, *args): ...
    def add_event_listener(self, name, callback) -> None: ...
    def remove_event_listener(self, name, callback) -> None: ...
    def append_child(self, child) -> None: ...
    def remove_child(self, child) -> None: ...
    def remove(self) -> None: ...
