import abc
import tornado.web
from _typeshed import Incomplete
from google.colab.html import _background_server

class _Resource(metaclass=abc.ABCMeta):
    headers: Incomplete
    def __init__(self, provider, headers, extension, route) -> None: ...
    @abc.abstractmethod
    def get(self, handler): ...
    @property
    def guid(self): ...
    @property
    def url(self): ...

class _ContentResource(_Resource):
    content: Incomplete
    def __init__(self, content, *args, **kwargs) -> None: ...
    def get(self, handler) -> None: ...

class _FileResource(_Resource):
    filepath: Incomplete
    def __init__(self, filepath, *args, **kwargs) -> None: ...
    def get(self, handler) -> None: ...

class _HandlerResource(_Resource):
    func: Incomplete
    def __init__(self, func, *args, **kwargs) -> None: ...
    def get(self, handler) -> None: ...

class _ResourceHandler(tornado.web.RequestHandler):
    def initialize(self, resources) -> None: ...
    def get(self) -> None: ...

class _Provider(_background_server._BackgroundServer):
    port_options: Incomplete
    def __init__(self) -> None: ...
    def create(self, content=None, filepath=None, handler=None, headers=None, extension=None, route=None): ...

create: Incomplete

def set_port_options(p) -> None: ...
