"""
This type stub file was generated by pyright.
"""

import weakref
import collections

'''
Defines the `WeakKeyIdentityDict` class.

See its documentation for more details.
'''
__all__ = ['WeakKeyIdentityDict']
class IdentityRef(weakref.ref):
    '''A weak reference to an object, hashed by identity and not contents.'''
    def __init__(self, thing, callback=...) -> None:
        ...
    
    def __hash__(self) -> int:
        ...
    


class WeakKeyIdentityDict(collections.abc.MutableMapping):
    """
    A weak key dictionary which cares about the keys' identities.

    This is a fork of `weakref.WeakKeyDictionary`. Like in the original
    `WeakKeyDictionary`, the keys are referenced weakly, so if there are no
    more references to the key, it gets removed from this dict.

    The difference is that `WeakKeyIdentityDict` cares about the keys'
    identities and not their contents, so even unhashable objects like lists
    can be used as keys. The value will be tied to the object's identity and
    not its contents.
    """
    def __init__(self, dict_=...) -> None:
        ...
    
    def __delitem__(self, key): # -> None:
        ...
    
    def __getitem__(self, key):
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def copy(self): # -> WeakKeyIdentityDict:
        """ D.copy() -> a shallow copy of D """
        ...
    
    def get(self, key, default=...): # -> None:
        """ D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None. """
        ...
    
    def __contains__(self, key): # -> bool | Literal[0]:
        ...
    
    has_key = ...
    def items(self): # -> list[Any]:
        """ D.items() -> list of D's (key, value) pairs, as 2-tuples """
        ...
    
    def iteritems(self): # -> Generator[tuple[Any, Any], Any, None]:
        """ D.iteritems() -> an iterator over the (key, value) items of D """
        ...
    
    def iterkeyrefs(self): # -> Iterator[Any]:
        """Return an iterator that yields the weak references to the keys.

        The references are not guaranteed to be 'live' at the time
        they are used, so the result of calling the references needs
        to be checked before being used.  This can be used to avoid
        creating references that will cause the garbage collector to
        keep the keys around longer than needed.

        """
        ...
    
    def iterkeys(self): # -> Generator[Any, Any, None]:
        """ D.iterkeys() -> an iterator over the keys of D """
        ...
    
    def __iter__(self): # -> Iterator[Any]:
        ...
    
    def itervalues(self): # -> Iterator[Any]:
        """ D.itervalues() -> an iterator over the values of D """
        ...
    
    def keyrefs(self): # -> list[Any]:
        """Return a list of weak references to the keys.

        The references are not guaranteed to be 'live' at the time
        they are used, so the result of calling the references needs
        to be checked before being used.  This can be used to avoid
        creating references that will cause the garbage collector to
        keep the keys around longer than needed.

        """
        ...
    
    def keys(self): # -> list[Any]:
        """ D.keys() -> list of D's keys """
        ...
    
    def popitem(self): # -> tuple[Any, Any]:
        """ D.popitem() -> (k, v), remove and return some (key, value) pair
        as a 2-tuple; but raise KeyError if D is empty """
        ...
    
    def pop(self, key, *args):
        """ D.pop(k[,d]) -> v, remove specified key and return the
        corresponding value. If key is not found, d is returned if given,
        otherwise KeyError is raised """
        ...
    
    def setdefault(self, key, default=...): # -> None:
        """D.setdefault(k[,d]) -> D.get(k,d), also set D[k]=d if k not in D"""
        ...
    
    def update(self, dict=..., **kwargs): # -> None:
        """ D.update(E, **F) -> None. Update D from E and F: for k in E: D[k] =
        E[k] (if E has keys else: for (k, v) in E: D[k] = v) then: for k in F:
        D[k] = F[k] """
        ...
    
    def __len__(self): # -> int:
        ...
    


