"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, TYPE_CHECKING, Tuple
from dataclasses import dataclass
from triton.runtime.jit import constexpr_function
from triton.experimental.gluon.language import _core as ttgl
from triton.experimental.gluon.language._core import _unwrap_if_constexpr, base_type, base_value, builtin
from triton.experimental.gluon.language._layouts import SharedLinearLayout
from triton.experimental.gluon.language._semantic import _check, _compute_tmem_reg_layout
from . import tma
from ..hopper import fence_async_shared, mbarrier
from ..ampere import async_copy, mma_v2
from triton._C.libtriton import ir
from triton._C.libtriton.gluon_ir import GluonOpBuilder
from ..._semantic import GluonSemantic

if TYPE_CHECKING:
    ...
__all__ = ["allocate_tensor_memory", "async_copy", "fence_async_shared", "get_tmem_reg_layout", "mbarrier", "mma_v2", "tensor_memory_descriptor", "TensorMemoryLayout", "tma"]
@dataclass(frozen=True, eq=True)
class TensorMemoryLayout:
    """
    Describes the layout for tensor memory in Blackwell architecture.

    Args:
        block (Tuple[int, int]): Number of contiguous elements per row / column in a CTA.
        col_stride (int): Number of 32-bit columns to advance between logically
            adjacent columns. Packed layouts use a stride of 1. Unpacked
            layouts use ``32 / bitwidth``.
        cta_split_num (Optional[Tuple[int, int]]): CTA split factors. Defaults to None.
        two_ctas (bool): Whether the layout is for two-CTA mode. Defaults to False.
    """
    block: Tuple[int, int]
    col_stride: int
    cta_split_num: Optional[Tuple[int, int]] = ...
    two_ctas: bool = ...
    def __post_init__(self): # -> None:
        ...
    
    def mangle(self) -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    


@dataclass(frozen=True, eq=True)
class TensorMemoryScalesLayout:
    """
    Describes the layout for tensor memory scales in Blackwell architecture.

    Args:
        cta_split_num (Optional[Tuple[int, int]]): CTA split factors. Defaults to None.
    """
    cta_split_num: Optional[Tuple[int, int]] = ...
    def __post_init__(self): # -> None:
        ...
    
    def mangle(self) -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    


@constexpr_function
def get_tmem_reg_layout(element_ty, shape, layout, num_warps, instr_variant=..., cga_layout=...):
    """
    Returns a DistributedLinearLayout compatible with TMEM load/store instructions.

    Args:
        element_ty (dtype): Element type stored in tensor memory.
        shape (Sequence[int]): Global tensor shape addressed by the TMEM descriptor.
        layout (TensorMemoryLayout): Tensor memory layout descriptor.
        num_warps (int): Number of warps participating in the operation.
        instr_variant (str): TMEM instruction variant (e.g. ``\"32x32b\"``).
        cga_layout (Sequence[Sequence[int]]): CTA layout bases describing CTA distribution.
    """
    ...

class tensor_memory_descriptor_type(base_type):
    def __init__(self, element_ty, shape, layout, alloc_shape) -> None:
        ...
    
    def to_ir(self, builder: GluonOpBuilder) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __neq__(self, other) -> bool:
        ...
    
    def mangle(self) -> str:
        ...
    


class tensor_memory_descriptor(base_value):
    """
    Represents a tensor memory descriptor handle for Tensor Core Gen5 operations.
    """
    def __init__(self, handle, element_ty, shape, layout, alloc_shape) -> None:
        ...
    
    @property
    def dtype(self):
        ...
    
    @property
    def shape(self):
        ...
    
    @property
    def rank(self): # -> int:
        ...
    
    @property
    def layout(self):
        ...
    
    def __str__(self) -> str:
        ...
    
    @builtin
    def load(self, layout, _semantic: GluonSemantic) -> ttgl.tensor:
        """
        Load a tensor from tensor memory.

        Args:
            layout (DistributedLayout): Destination layout of the tensor.

        Returns:
            tensor: A distributed tensor containing the loaded data.
        """
        ...
    
    @builtin
    def store(self, value, pred=..., _semantic: GluonSemantic = ...) -> None:
        """
        Store a tensor into tensor memory.

        Args:
            value (tensor): The tensor to store.
            pred (bool): Scalar predicate. Operation is skipped if predicate is False. Defaults to True.
        """
        ...
    
    @builtin
    def slice(self, start, length, _semantic: GluonSemantic) -> None:
        """
        Create a slice of the tensor memory descriptor along the last dimension.

        Args:
            start (int): The starting index for subslice.
            length (int): The length of the subslice.

        Returns:
            tensor_memory_descriptor: Descriptor for the subslice.
        """
        ...
    
    @builtin
    def index(self, index, _semantic: GluonSemantic = ...) -> tensor_memory_descriptor:
        """
        Create a subview of tensor memory by indexing the first dimension.

        Args:
            index (tensor): The index tensor for the subview.

        Returns:
            tensor_memory_descriptor: Descriptor for the indexed subview.
        """
        ...
    


@builtin
def allocate_tensor_memory(element_ty, shape, layout, value=..., _semantic=...): # -> tensor_memory_descriptor:
    """
    Allocate tensor memory.

    Args:
        element_ty (dtype): The element data type.
        shape (Sequence[int]): The descriptor shape.
        layout (TensorMemoryLayout): The layout of the tensor memory.
        value (tensor, optional): Initial tensor to copy. Defaults to None.

    Returns:
        tensor_memory_descriptor: Descriptor for the allocated memory.
    """
    ...

@builtin
def tcgen05_copy(src, dst, _semantic=...): # -> None:
    """
    Start an asynchronous copy from shared memory to tensor memory.

    WARNING: The current semantics of the instruction are not well defined and
    the API will change in the future. Use at your own risk.

    Args:
        src (shared_memory_descriptor): Shared memory to copy from.
        dst (tensor_memory_descriptor): Tensor memory to copy to.
    """
    ...

@builtin
def tcgen05_mma(a, b, acc, *, use_acc=..., pred=..., mbarriers=..., mbarrier_preds=..., _semantic=...): # -> None:
    """
    Emit a 5th generation TensorCore MMA instruction.
    acc = a * b + (acc if use_acc else 0)

    Args:
        a (shared_memory_descriptor): Left hand side operand in shared memory.
        b (shared_memory_descriptor or tensor_memory_descriptor): Right hand side operand in shared or tensor memory.
        acc (tensor_memory_descriptor): Accumulator value in tensor memory (mutated).
        use_acc (bool): Whether to use the initial value of the accumulator. Defaults to True.
        pred (bool): Scalar predicate. Operation is skipped if predicate is False. Defaults to True.
        mbarriers (Sequence[shared_memory_descriptor], optional): Barriers to signal when the operation is complete. If None, mma is synchronous. Defaults to None.
        mbarrier_preds (Sequence[bool], optional): Predicates for barriers. Defaults to None.
    """
    ...

@builtin
def tcgen05_mma_scaled(a, b, acc, a_scale, b_scale, a_type, b_type, *, use_acc=..., pred=..., mbarriers=..., mbarrier_preds=..., _semantic=...): # -> None:
    """
    Emit a 5th generation TensorCore MMA scaled instruction.
    acc = (a * a_scale) * (b * b_scale) + (acc if use_acc else 0)

    Args:
        a (shared_memory_descriptor): Left hand side operand in shared memory.
        b (shared_memory_descriptor or tensor_memory_descriptor): Right hand side operand in shared or tensor memory.
        acc (tensor_memory_descriptor): Accumulator value in tensor memory (mutated).
        a_scale (tensor): Scale factor for operand A.
        b_scale (tensor): Scale factor for operand B.
        a_type (str): Type of operand A. One of {"e2m1", "e4m3", "e5m2"}.
        b_type (str): Type of operand B. One of {"e2m1", "e4m3", "e5m2"}.
        use_acc (bool): Whether to use the initial value of the accumulator. Defaults to True.
        pred (bool): Scalar predicate. Operation is skipped if predicate is False. Defaults to True.
        mbarriers (Sequence[mbarrier], optional): Barriers to signal when the operation is complete. If None, mma is synchronous. Defaults to None.
        mbarrier_preds (Sequence[bool], optional): Predicates for barriers. Defaults to None.
    """
    ...

@builtin
def tcgen05_commit(barrier, _semantic=...): # -> None:
    """
    This instruction causes the provided mbarrier to be arrived-on with a count
    of 1 when all async tcgen05 MMA and copy instructions previously issued by
    the thread are complete.

    Args:
        barrier (shared_memory_descriptor): The barrier to track completion of tcgen05 MMA and copy instructions.
    """
    ...

