"""
This type stub file was generated by pyright.
"""

from ufo2ft.filters import BaseFilter

logger = ...
class CubicToQuadraticFilter(BaseFilter):
    _kwargs = ...
    def set_context(self, font, glyphSet): # -> SimpleNamespace:
        ...
    
    def __call__(self, font, glyphSet=...): # -> set[Any] | Any:
        ...
    
    def filter(self, glyph): # -> bool:
        ...
    


