"""
This type stub file was generated by pyright.
"""

from ufo2ft.filters import BaseFilter, BaseIFilter

logger = ...
class PropagateAnchorsFilter(BaseFilter):
    def set_context(self, font, glyphSet): # -> SimpleNamespace:
        ...
    
    def __call__(self, font, glyphSet=...): # -> Any:
        ...
    
    def filter(self, glyph): # -> bool:
        ...
    


class PropagateAnchorsIFilter(BaseIFilter):
    def set_context(self, *args, **kwargs): # -> SimpleNamespace:
        ...
    
    def __call__(self, fonts, glyphSets=..., instantiator=..., **kwargs): # -> set[str]:
        ...
    
    def filter(self, glyphName, glyphs): # -> bool:
        ...
    


