"""
This type stub file was generated by pyright.
"""

from python_toolbox import caching

class _VariationAddingMixin:
    '''Mixin for `PermSpace` to add variations to a perm space.'''
    def get_rapplied(self, sequence):
        '''Get a version of this `PermSpace` that has a range of `sequence`.'''
        ...
    
    def get_partialled(self, n_elements):
        '''Get a partialled version of this `PermSpace`.'''
        ...
    
    @caching.CachedProperty
    def combinationed(self):
        '''Get a combination version of this perm space.'''
        ...
    
    def get_dapplied(self, domain):
        '''Get a version of this `PermSpace` that has a domain of `domain`.'''
        ...
    
    def get_fixed(self, fixed_map):
        '''Get a fixed version of this `PermSpace`.'''
        ...
    
    def get_degreed(self, degrees): # -> Self:
        '''Get a version of this `PermSpace` restricted to certain degrees.'''
        ...
    
    def get_typed(self, perm_type):
        '''
        Get a version of this `PermSpace` where perms are of a custom type.
        '''
        ...
    


