import numpy as np

from pandas.core.dtypes.generic import ABCExtensionArray as ABCExtensionArray
from typing import Any

def arithmetic_op(left: np.ndarray[Any, Any] | ABCExtensionArray, right: Any, op: Any, str_rep: str) -> Any: ...
def comparison_op(
    left: np.ndarray[Any, Any] | ABCExtensionArray, right: Any, op: Any
) -> np.ndarray[Any, Any] | ABCExtensionArray: ...
def na_logical_op(x: np.ndarray[Any, Any], y: Any, op: Any) -> Any: ...
def logical_op(
    left: np.ndarray[Any, Any] | ABCExtensionArray, right: Any, op: Any
) -> np.ndarray[Any, Any] | ABCExtensionArray: ...
def get_array_op(op: Any, str_rep: str | None = ...) -> Any: ...
