import numpy as np

from pandas.core.dtypes.generic import ABCExtensionArray as ABCExtensionArray
from typing import Any

def arithmetic_op(left: np.ndarray | ABCExtensionArray, right: Any, op: Any, str_rep: str): ...
def comparison_op(
    left: np.ndarray | ABCExtensionArray, right: Any, op: Any
) -> np.ndarray | ABCExtensionArray: ...
def na_logical_op(x: np.ndarray, y: Any, op: Any): ...
def logical_op(
    left: np.ndarray | ABCExtensionArray, right: Any, op: Any
) -> np.ndarray | ABCExtensionArray: ...
def get_array_op(op: Any, str_rep: str | None = ...): ...
