from pandas.compat._optional import import_optional_dependency as import_optional_dependency
from typing import Callable

def _arrow_dtype_mapping() -> dict: ...
def arrow_string_types_mapper() -> Callable: ...
