from cffconvert.behavior_1_2_x.bibtex_author import BibtexAuthor as BibtexAuthor
from cffconvert.behavior_1_2_x.bibtex_url import BibtexUrl as BibtexUrl
from cffconvert.behavior_shared.bibtex_object_shared import BibtexObjectShared as Shared

class BibtexObject(Shared):
    supported_cff_versions: list[str]
    author: str
    doi: str | None
    month: str | None
    url: str | None
    year: str | None
    def add_author(self) -> 'BibtexObject': ...
    def add_doi(self) -> 'BibtexObject': ...
    def add_month(self) -> 'BibtexObject': ...
    def add_url(self) -> 'BibtexObject': ...
    def add_year(self) -> 'BibtexObject': ...
