from _typeshed import Incomplete
from cffconvert.behavior_1_2_x.apalike_object import ApalikeObject as ApalikeObject
from cffconvert.behavior_1_2_x.bibtex_object import BibtexObject as BibtexObject
from cffconvert.behavior_1_2_x.codemeta_object import CodemetaObject as CodemetaObject
from cffconvert.behavior_1_2_x.endnote_object import EndnoteObject as EndnoteObject
from cffconvert.behavior_1_2_x.ris_object import RisObject as RisObject
from cffconvert.behavior_1_2_x.schemaorg_object import SchemaorgObject as SchemaorgObject
from cffconvert.behavior_1_2_x.zenodo_object import ZenodoObject as ZenodoObject
from cffconvert.contracts.citation import Contract as Contract
from cffconvert.root import get_package_root as get_package_root

class Citation_1_2_x(Contract):
    supported_cff_versions: Incomplete
    cffstr: Incomplete
    cffversion: Incomplete
    cffobj: Incomplete
    schema: Incomplete
    def __init__(self, cffstr, cffversion) -> None: ...
    def _get_schema(self): ...
    def _parse(self): ...
    def as_apalike(self): ...
    def as_bibtex(self, reference: str = 'YourReferenceHere'): ...
    def as_cff(self): ...
    def as_codemeta(self): ...
    def as_endnote(self): ...
    def as_ris(self): ...
    def as_schemaorg(self): ...
    def as_zenodo(self): ...
    def validate(self) -> None: ...
