from typing import Any
from cffconvert.contracts.citation import Contract as Contract

class Citation_1_2_x(Contract):
	supported_cff_versions: list[str]
	cffstr: str
	cffversion: str
	cffobj: dict[str, Any]
	schema: dict[str, Any]

	def __init__(self, cffstr: str, cffversion: str) -> None: ...

	def _get_schema(self) -> dict[str, Any]: ...

	def _parse(self) -> dict[str, Any]: ...

	def as_apalike(self) -> str: ...

	def as_bibtex(self, reference: str = 'YourReferenceHere') -> str: ...

	def as_cff(self) -> str: ...

	def as_codemeta(self) -> str: ...

	def as_endnote(self) -> str: ...

	def as_ris(self) -> str: ...

	def as_schemaorg(self) -> str: ...

	def as_zenodo(self) -> str: ...

	def validate(self, verbose: bool = True) -> None: ...
