from .matexpr import MatrixExpr as MatrixExpr

class MatPow(MatrixExpr):
    def __new__(cls, base, exp, evaluate: bool = False, **options): ...
    @property
    def base(self): ...
    @property
    def exp(self): ...
    @property
    def shape(self): ...
    def _get_explicit_matrix(self): ...
    def _entry(self, i, j, **kwargs): ...
    def doit(self, **hints): ...
    def _eval_transpose(self): ...
    def _eval_adjoint(self): ...
    def _eval_conjugate(self): ...
    def _eval_derivative(self, x): ...
    def _eval_derivative_matrix_lines(self, x): ...
    def _eval_inverse(self): ...
