"""
This type stub file was generated by pyright.
"""

from defcon.objects.base import BaseObject

class LayoutEngine(BaseObject):
    """
    This object provides a GDEF, GSUB and GPOS OpenType Layout Engine for
    the default layer of the given font. The engine uses the ``compositor``
    module so you must have that installed to use this object.

    **This object posts the following notifications:**

    - LayoutEngine.Changed

    This object monitors the font's feature text and character mapping. When
    those change, the compiled tables will be flagged for recompilation and
    the next time the engine is queried the tables will be recompiled. Any
    data that you have retrieved, such as the list of feature tags, may no
    longer be correct. Thus, the data will need to be retrieved again. To be
    notified when this is necessary, subscribe to the ``LayoutEngine.Changed``
    notification.
    """
    changeNotificationName = ...
    representationFactories = ...
    def __init__(self, font) -> None:
        ...
    
    font = ...
    engine = ...
    def beginSelfNotificationObservation(self): # -> None:
        ...
    
    def endSelfNotificationObservation(self): # -> None:
        ...
    
    def beginSelfLayersObservation(self): # -> None:
        ...
    
    def endSelfLayersObservation(self): # -> None:
        ...
    
    def beginSelfLayerObservation(self): # -> None:
        ...
    
    def endSelfLayerObservation(self): # -> None:
        ...
    
    def beginSelfFeaturesObservation(self): # -> None:
        ...
    
    def endSelfFeaturesObservation(self): # -> None:
        ...
    
    def process(self, stringOrGlyphList, script=..., langSys=..., rightToLeft=..., case=...): # -> list[Any]:
        """
        Process a string (or list of glyph names) with the current
        feature states for the given **script** and **langSys**.

        The writing will be left to right unless **rightToLeft**
        is set to True.

        The case may be changed following the Unicode case conversion
        rules by setting **case** to one of the following:

        +-----------+
        | unchanged |
        +-----------+
        | upper     |
        +-----------+
        | lower     |
        +-----------+
        """
        ...
    
    def getScriptList(self): # -> Any:
        """
        Get a list of defined scripts.
        """
        ...
    
    def getLanguageList(self): # -> Any:
        """
        Get a list of defined languages.
        """
        ...
    
    def getFeatureList(self): # -> Any:
        """
        Get a list of defined features.
        """
        ...
    
    def getFeatureState(self, name): # -> Any:
        """
        Get the state for the feature with **name**.
        """
        ...
    
    def setFeatureState(self, name, state): # -> None:
        """
        Set the state for the feature with **name**.
        """
        ...
    


