"""
This type stub file was generated by pyright.
"""

import unittest

class TestFontList(unittest.TestCase):
    def getFont(self):
        ...
    
    def getFonts_sortBy(self, attr, values):
        ...
    
    def getFont_sortBy_monospaceGlyphs(self):
        ...
    
    def getFont_sortBy_proportionalGlyphs(self):
        ...
    
    def test_sortBy_familyName(self):
        ...
    
    def test_sortBy_styleName(self):
        ...
    
    def test_sortBy_isRoman_styleMapStyleName(self):
        ...
    
    def test_sortBy_isRoman_italicAngle(self):
        ...
    
    def test_sortBy_isItalic_styleMapStyleName(self):
        ...
    
    def test_sortBy_isItalic_italicAngle(self):
        ...
    
    def test_sortBy_widthValue(self):
        ...
    
    def test_sortBy_weightValue(self):
        ...
    
    def test_sortBy_isMonospace_postscriptIsFixedPitch(self):
        ...
    
    def test_sortBy_isMonospace_glyphs(self): # -> None:
        ...
    
    def test_sortBy_isProportional_postscriptIsFixedPitch(self):
        ...
    
    def test_sortBy_isProportional_glyphs(self): # -> None:
        ...
    
    def test_sortBy_fontInfoAttribute_xHeight(self):
        ...
    
    def getFont_withGlyphCount(self, count):
        ...
    
    def test_sortBy_sortValueFunction(self): # -> None:
        ...
    
    def test_getFontsByFamilyName(self): # -> None:
        ...
    
    def test_getFontsByStyleName(self): # -> None:
        ...
    
    def test_getFontsByFamilyNameStyleName(self): # -> None:
        ...
    


class TestFontOpen(unittest.TestCase):
    def setUp(self): # -> None:
        ...
    
    def tearDown(self): # -> None:
        ...
    
    def test_font_open(self): # -> None:
        ...
    


class TestOpenFonts(unittest.TestCase):
    def setUp(self): # -> None:
        ...
    
    def tearDown(self): # -> None:
        ...
    
    def test_font_open(self): # -> None:
        ...
    


class TestFontShell_RFont(unittest.TestCase):
    def test_fontshell_RFont_empty(self): # -> None:
        ...
    


