import _cython_3_2_2
from fontTools.misc.bezierTools import splitCubicAtTC as splitCubicAtTC

COMPILED: bool
__test__: dict
add_implicit_on_curves: _cython_3_2_2.cython_function_or_method
elevate_quadratic: _cython_3_2_2.cython_function_or_method
main: _cython_3_2_2.cython_function_or_method
quadratic_to_curves: _cython_3_2_2.cython_function_or_method
spline_to_curves: _cython_3_2_2.cython_function_or_method
