from .ufo import font_to_quadratic as font_to_quadratic, fonts_to_quadratic as fonts_to_quadratic
from _typeshed import Incomplete

ufo_module: Incomplete
logger: Incomplete

def _cpu_count(): ...
def open_ufo(path): ...
def _font_to_quadratic(input_path, output_path=None, **kwargs) -> None: ...
def _samepath(path1, path2): ...
def _copytree(input_path, output_path) -> None: ...
def _main(args=None) -> None:
    """Convert a UFO font from cubic to quadratic curves"""
