"""
This type stub file was generated by pyright.
"""

from .string_tools import docstring_trim, get_n_identical_edge_characters, rreplace
from . import case_conversions

'''Defines string-related tools.'''
