"""
This type stub file was generated by pyright.
"""

'''Defines functions for converting between different string conventions.'''
def camel_case_to_space_case(s): # -> Literal['']:
    '''
    Convert a string from camelcase to spacecase.

    Example: camelcase_to_underscore('HelloWorld') == 'Hello world'
    '''
    ...

def camel_case_to_lower_case(s): # -> str:
    '''
    Convert a string from camel-case to lower-case.

    Example:

        camel_case_to_lower_case('HelloWorld') == 'hello_world'

    '''
    ...

def lower_case_to_camel_case(s):
    '''
    Convert a string from lower-case to camel-case.

    Example:

        camel_case_to_lower_case('hello_world') == 'HelloWorld'

    '''
    ...

def camel_case_to_upper_case(s): # -> str:
    '''
    Convert a string from camel-case to upper-case.

    Example:

        camel_case_to_lower_case('HelloWorld') == 'HELLO_WORLD'

    '''
    ...

def upper_case_to_camel_case(s):
    '''
    Convert a string from upper-case to camel-case.

    Example:

        camel_case_to_lower_case('HELLO_WORLD') == 'HelloWorld'

    '''
    ...

