from _typeshed import Incomplete
from sympy.tensor.array.expressions import from_indexed_to_array as from_indexed_to_array
from sympy.tensor.array.expressions.conv_array_to_indexed import _conv_to_from_decorator as _conv_to_from_decorator

convert_indexed_to_array: Incomplete
