
__copyright__ = ...
__doc__ = ...
from typing import Any, Literal

re_entry = ...
re_name = ...
class glyph:
	def __init__(self, name) -> None:
		...

	def parse(self, intext) -> bool:
		...

	def check(self) -> list[Any]:
		...

	def aliases(self, addglyphs=...) -> list[Any]:
		...

	def uniname(self) -> str | Any | None:
		...



class dictionary:
	def __init__(self, intext=...) -> None:
		...

	def parse(self, intext, priority=...) -> bool:
		...

	def glyph(self, n) -> None:
		...

	def remove(self, n) -> int | None:
		...

	def add(self, g, priority=...) -> Literal[True]:
		...
