from fontTools.ttLib import TTFont
from _typeshed import Incomplete
from afdko import fdkutils as fdkutils

__usage__: str
__version__: str
__help__: str
gDesignSpaceTolerance: int
kFixedPitchExceptionList: Incomplete
kLigFeatureList: Incomplete
kKnownBaseTags: Incomplete
kKnownScriptTags: Incomplete
kKnownLanguageTags: Incomplete
gAGDDict: Incomplete

class CompareFamilyFont:
    ttFont: TTFont
    path: Incomplete
    def __init__(self, ttFont: TTFont, path) -> None: ...

def readGlyphInfo(cmpfFont): ...
def readCFFTable(cmpfFont) -> None: ...
def sort_font(fontlist):
    """
\tReturns a new list that is first sorted by the font's compatibleFamilyName3
\t(Windows compatible name), and secondly by the font's macStyle (style name).
\t"""
def sort_by_numGlyphs_and_PostScriptName1(fontlist):
    """
\tReturns a new list that is first sorted by the font's numGlyphs,
\tand secondly by the font's PostScriptName1.
\t"""
def sort_angle(fontlist): ...
def sort_version(fontlist): ...
def sort_weight(fontlist): ...
def sort_width(fontlist): ...
def sort_underline(fontlist): ...
def readNameTable(cmpfFont) -> None: ...
def readOS2Table(cmpfFont) -> None: ...
def readpostTable(cmpfFont) -> None: ...
def readheadTable(cmpfFont) -> None: ...
def readhheaTable(cmpfFont) -> None: ...
def handle_datafork_file(path): ...
def handle_resource_file(path): ...
def guessfiletype(path): ...
def get_fontinfo(pathname, font_type): ...
def build_fontlist_from_dir(directory): ...
def doSingleTest1() -> None: ...
def doSingleTest2() -> None: ...
def doSingleTest3() -> None: ...
def doSingleTest4() -> None: ...
def doSingleTest5() -> None: ...
def doSingleTest6() -> None: ...
def doSingleTest7() -> None: ...
def doSingleTest8() -> None: ...
def doSingleTest9() -> None: ...
def doSingleTest10() -> None: ...
def doSingleTest11() -> None: ...
def doSingleTest12() -> None: ...
def doSingleTest13() -> None: ...
def doSingleTest14() -> None: ...
def doSingleTest15() -> None: ...
def doSingleTest16() -> None: ...
def MakeWidthTable(glyphnames, glyphwidths): ...
def doSingleTest17() -> None: ...

hintPat: Incomplete

def checkHintEntry(entry, missingHintsGlyphs, glyphBox, fontPSName): ...
def doSingleTest18() -> None: ...
def doSingleTest19() -> None: ...
def doSingleTest20() -> None: ...
def doSingleTest21() -> None: ...

oldLigatureNames: Incomplete
NAMES_OF_ACCENTS: Incomplete
uniLigPattern: Incomplete

def getLigatureName(font, name): ...
def getLigatureNames(font): ...
def isAccent(glyphName): ...
def doSingleTest22() -> None: ...
def getAcentEntries(font): ...
def doSingleTest23() -> None: ...
def doSingleTest24() -> None: ...
def doSingleTest25() -> None: ...
def doSingleTest26() -> None: ...
def doSingleTest27() -> None: ...
def doSingleTest28() -> None: ...
def doSingleTest29() -> None: ...
def doSingleTest30() -> None: ...
def doSingleTest31() -> None: ...
def doSingleTest32() -> None: ...
def doSingleTest33() -> None: ...
def doSingleTest34() -> None: ...
def doSingleFaceTests(singleTestList, familyTestList) -> None: ...
def doFamilyTest1() -> None: ...
def doFamilyTest2() -> None: ...
def doFamilyTest3() -> None: ...
def doFamilyTest4(): ...
def doFamilyTest5() -> None: ...
def doFamilyTest6() -> None: ...
def doFamilyTest7() -> None: ...
def doFamilyTest8() -> None: ...
def doFamilyTest9() -> None: ...
def doFamilyTest10(): ...
def doFamilyTest11(): ...
def doFamilyTest12():
    """
\tFor each font, step through the script/language/feature tree, and collect a fontDict[script][language][feature] == lookupSetIndex,
\twhere lookupSetIndex is a number that uniquely identifies a set of lookups belonging to a feature. This mapping is kept
\tin lookupDefDict[lookupSetIndex] = <real lookup index list>
\t"""
def doFamilyTest13() -> None: ...
def doFamilyTest14() -> None: ...
def doFamilyTest15() -> None: ...
def doFamilyTest16() -> None: ...
def doFamilyTest17() -> None: ...
def doFamilyTest18() -> None: ...
def doFamilyTest19() -> None: ...
def doFamilyTest20() -> None: ...
def doFamilyTest21() -> None: ...
def doFamilyTests(singleTestList, familyTestList) -> None: ...
def build_preferredFamilyList(fontlist) -> None: ...
def print_menu_name_report() -> None: ...
def print_font_metric_report() -> None: ...
def print_panose_report() -> None: ...
def print_std_charset_report(charSetName) -> None: ...
def read_options(): ...
def main() -> None: ...
