from _typeshed import Incomplete
from fontTools.ttLib import TTFont
from fontTools.ttLib.tables._g_l_y_f import Glyph, table__g_l_y_f
from fontTools.ttLib.ttGlyphSet import _TTGlyphSet

MAX_ERR: float
POST_FORMAT: float
REVERSE_DIRECTION: bool

def glyphs_to_quadratic(glyphs: _TTGlyphSet, max_err: float = 1.0, reverse_direction: bool = True) -> dict[str, Glyph]:
    ...
def update_hmtx(ttFont: TTFont, glyf: table__g_l_y_f) -> None: ...
def otf_to_ttf(ttFont: TTFont, post_format: float = 2.0, **kwargs: float | bool) -> None: ...
def _(fonts, **kwargs) -> None: ...
def run(path, options) -> None: ...
def main(args=None) -> None: ...
