from _typeshed import Incomplete
from afdko import fdkutils as fdkutils
from afdko.pdflib import otfpdf as otfpdf, ttfpdf as ttfpdf
from afdko.pdflib.fontpdf import FontPDFParams as FontPDFParams, kDrawPointTag as kDrawPointTag, kDrawTag as kDrawTag, kShowMetaTag as kShowMetaTag, makeFontSetPDF as makeFontSetPDF, makePDF as makePDF, params_doc as params_doc

curSystem: Incomplete
__usage__: str
__help__: Incomplete

def logMsg(*args) -> None: ...

class FDKEnvironmentError(Exception): ...
class OptionParseError(Exception): ...
class FontError(Exception): ...

def CheckEnvironment(): ...
def fixGlyphNames(glyphName): ...
def parseGlyphListArg(glyphString): ...
def expandRanges(tag): ...
def parsePtSizeListArg(ptSizeString): ...
def parseLayoutFile(filePath): ...
def setDefaultDigiplotRightSideOptions(rightGlyphParams) -> None: ...
def getOptions(params): ...
def getGlyphID(glyphTag, fontGlyphList): ...
def getGlyphNames(glyphTag, fontGlyphList, fontFileName): ...
def filterGlyphList(params, fontGlyphList, fontFileName): ...
def openFile(path, txPath): ...
def proofMakePDF(pathList, params, txPath) -> None: ...
def charplot() -> None: ...
def digiplot() -> None: ...
def fontplot() -> None: ...
def fontplot2() -> None: ...
def fontsetplot() -> None: ...
def hintplot() -> None: ...
def waterfallplot() -> None: ...
def main() -> None: ...
