"""
This type stub file was generated by pyright.
"""

"""
Takes in a TrueType font and de-componentizes (decomposes) any composite
glyphs into simple glyphs.

** NOTE: this process leaves the resulting decomposed glyphs with no
instructions ("hints"). **
"""
__version__ = ...
def get_options(args): # -> Namespace:
    ...

def process_font(input_path, output_path=..., verbose=...): # -> int:
    """
    De-componentize a single font at input_path, saving to output_path (or
    input_path if None)
    """
    ...

def main(args=...): # -> Literal[0]:
    ...

if __name__ == "__main__":
    ...
