from _typeshed import Incomplete
from afdko.fdkutils import get_temp_file_path as get_temp_file_path
from fontTools.ttLib import TTFont

__help__: str
__version__: str
log: Incomplete
curSystem: Incomplete
TX_TOOL: str
INDENT: str
ChainINDENT: Incomplete
MAX_LINE_LENGTH: int
gtextWrapper: Incomplete
NULL_VALUE_RECORD: str

def getValueRecord(a, b, c, d): ...
def getAnchorString(anchorTable): ...

class ClassRecord:
    lookupIndex: Incomplete
    subtableIndex: Incomplete
    classIndex: Incomplete
    side: Incomplete
    anchor: Incomplete
    def __init__(self, lookupIndex, subtableIndex, classIndex, side: str = '', anchor=None) -> None: ...

def addClassDef(otlConv, classDefs, coverage, side=None, anchor=None) -> None: ...
def AddMarkClassDef(otlConv, markCoverage, markArray, tag) -> None: ...
def classPairGPOS(subtable, otlConv=None) -> None: ...
def markClassPOS(subtable, otlConv=None) -> None: ...
def markLigClassPOS(subtable, otlConv=None) -> None: ...
def markMarkClassPOS(subtable, otlConv=None) -> None: ...
def classContext(subtable, otlConv) -> None: ...
def classChainContext(subtable, otlConv) -> None: ...
def classExt(subtable, otlConv) -> None: ...

class ContextRecord:
    inputList: Incomplete
    sequenceIndex: Incomplete
    glyphsUsed: int
    result: str
    def __init__(self, inputList, sequenceIndex) -> None: ...

def checkGlyphInSequence(glyphName, contextSequence, i): ...
def ruleSinglePos(subtable, otlConv, context=None): ...
def rulePairPos(subtable, otlConv, context=None): ...
def ruleCursivePos(subtable, otlConv, context=None): ...
def ruleMarkBasePos(subtable, otlConv, context=None): ...
def ruleMarkLigPos(subtable, otlConv, context=None): ...
def ruleMarkMarkPos(subtable, otlConv, context=None): ...
def ruleContextPOS(subtable, otlConv, context=None): ...
def ruleChainContextPOS(subtable, otlConv, context=None): ...
def ruleExt(subtable, otlConv, context=None): ...
def ruleSingleSub(subtable, otlConv, context=None): ...
def ruleMultipleSub(subtable, otlConv, context=None): ...
def ruleAltSub(subtable, otlConv, context=None): ...
def ruleLigatureSub(subtable, otlConv, context=None): ...
def ruleContextSUB(subtable, otlConv, context=None): ...
def wrap_statement(token_str):
    """
    Wraps a long string of space-separated tokens
    or a list of tokens.
    """
def ruleChainContextSUB(subtable, otlConv, context=None): ...
def ruleReverseChainSub(subtable, otlConv, context=None): ...
def getValRec(valueFormat, valueRec): ...

gLookupFlagMap: Incomplete
gLookupFlagKeys: Incomplete

def getLookupFlagTag(lookupFlag): ...

DFLT_LANGSYS_KEYS: Incomplete

class OTLConverter:
    leftSideTag: str
    rightSideTag: str
    backtrackTag: str
    InputTag: str
    lookAheadTag: str
    markTag: str
    mark1Tag: str
    mark2Tag: str
    writer: Incomplete
    table: Incomplete
    classesByNameList: Incomplete
    classesByLookup: Incomplete
    classesByClassName: Incomplete
    lookupIndex: int
    seenLookup: Incomplete
    glyphDict: Incomplete
    markClassesByDefList: Incomplete
    markClassesByLookup: Incomplete
    markClassesByClassName: Incomplete
    curLookupIndex: int
    curSubTableIndex: int
    curLookupName: str
    showExtension: Incomplete
    ExtensionIndex: int
    classHandlers: Incomplete
    ruleHandlers: Incomplete
    def __init__(self, writer, ttFont: TTFont, table_tag) -> None: ...
    def otlFeatureFormat(self) -> None: ...
    @staticmethod
    def addLangSysEntry(pfeatList, scriptTag, langTag, langSys, featDictByLangSys, featDictByIndex) -> None: ...
    def buildLangSys(self): ...
    def writeLangSys(self, lsList) -> None: ...
    def buildClasses(self) -> None: ...
    def writeClasses(self) -> None: ...
    def writeMarkClasses(self) -> None: ...
    def doFeatures(self, featDictByLangSys) -> None: ...
    def writeDfltLangSysFeat(self, langSysKey, featIndexList): ...
    def writeLangSysFeat(self, langSysKey, prevLangSysKey, featIndexList, dfltLookupIndexDict) -> None: ...
    def writeLookup(self, lookup) -> None: ...

def dumpOTLAsFeatureFile(writer, ttFont: TTFont, table_tag) -> None: ...

class TTXNTTFont(TTFont):
    filePath: Incomplete
    supressHints: Incomplete
    showExtensionFlag: Incomplete
    def __init__(self, file=None, res_name_or_index=None, sfntVersion: str = '\x00\x01\x00\x00', flavor=None, checkChecksums: bool = False, verbose=None, recalcBBoxes: bool = True, ignoreDecompileErrors: bool = False, recalcTimestamp: bool = True, fontNumber: int = -1, lazy=None, quiet=None, supressHints: bool = False, showExtensionFlag: bool = False) -> None: ...

def shellcmd(cmdList): ...
def dumpFont(writer, fontPath, supressHints: bool = False) -> None: ...
def ttnDump(input_file, output, options, showExtensionFlag, supressHints: bool = False, supressVersions: bool = False, supressTTFDiffs: bool = False): ...
def main(args=None): ...
