from typing import ClassVar, Literal

pa_version_under10p1: bool

class ArrowStringArrayMixin:
    _pa_array: ClassVar[None] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def _str_pad(self, width: int, side: Literal['left', 'right', 'both'] = ..., fillchar: str = ...): ...
    def _str_get(self, i: int): ...
    def _str_slice_replace(self, start: int | None, stop: int | None, repl: str | None): ...
    def _str_capitalize(self): ...
    def _str_title(self): ...
    def _str_swapcase(self): ...
    def _str_removesuffix(self, suffix: str): ...
