from _typeshed import Incomplete
from typing import Literal

class ArrowStringArrayMixin:
    _pa_array: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def _str_pad(self, width: int, side: Literal['left', 'right', 'both'] = 'left', fillchar: str = ' '): ...
    def _str_get(self, i: int): ...
    def _str_slice_replace(self, start: int | None = None, stop: int | None = None, repl: str | None = None): ...
    def _str_capitalize(self): ...
    def _str_title(self): ...
    def _str_swapcase(self): ...
    def _str_removesuffix(self, suffix: str): ...
