from typing import (
    Any,
    overload,
)

import numpy as np
from typing_extensions import Self

from pandas._typing import (
    ArrayLike,
    Scalar,
    ScalarIndexer,
    SequenceIndexer,
    TakeIndexer,
    npt,
)

from pandas.core.dtypes.dtypes import ExtensionDtype as ExtensionDtype

class ExtensionArray:
    @overload
    def __getitem__(self, item: ScalarIndexer) -> Any: ...
    @overload
    def __getitem__(self, item: SequenceIndexer) -> Self: ...
    def __setitem__(self, key: int | slice | np.ndarray[Any, Any], value: Any) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...
    def __contains__(self, item: object) -> bool | np.bool_: ...
    def to_numpy(
        self,
        dtype: npt.DTypeLike | None = None,
        copy: bool = False,
        na_value: Scalar = ...,
    ) -> np.ndarray[Any, Any]: ...
    @property
    def dtype(self) -> ExtensionDtype: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    def astype(self, dtype: Any, copy: bool = True) -> Any: ...
    def isna(self) -> ArrayLike: ...
    def argsort(
        self, *, ascending: bool = True, kind: str = 'quicksort', **kwargs: Any
    ) -> np.ndarray[Any, Any]: ...
    def fillna(self, value: Any=None, method: Any=None, limit: Any=None) -> Any: ...
    def dropna(self) -> Any: ...
    def shift(self, periods: int = 1, fill_value: object = None) -> Self: ...
    def unique(self) -> Any: ...
    def searchsorted(self, value: Any, side: str = 'left', sorter: Any=None) -> Any: ...
    def factorize(self, use_na_sentinel: bool = True) -> tuple[np.ndarray, Self]: ...
    def repeat(self, repeats: Any, axis: Any=None) -> Any: ...
    def take(
        self,
        indexer: TakeIndexer,
        *,
        allow_fill: bool = False,
        fill_value: Any=None,
    ) -> Self: ...
    def copy(self) -> Self: ...
    def view(self, dtype: Any=None) -> Self | np.ndarray[Any, Any]: ...
    def ravel(self, order: Any='C') -> Self: ...
    def tolist(self) -> list[Any]: ...
    def _reduce(
        self, name: str, *, skipna: bool = True, keepdims: bool = False, **kwargs: Any
    ) -> object: ...
    def _accumulate(self, name: str, *, skipna: bool = True, **kwargs: Any) -> Self: ...

class ExtensionOpsMixin:
    @classmethod
    def _add_arithmetic_ops(cls) -> None: ...
    @classmethod
    def _add_comparison_ops(cls) -> None: ...
    @classmethod
    def _add_logical_ops(cls) -> None: ...

class ExtensionScalarOpsMixin(ExtensionOpsMixin): ...
