from collections.abc import Sequence
from typing import (
    Any,
    TypeAlias,
    overload,
)

from pandas.core.arrays.base import (
    ExtensionArray,
    ExtensionOpsMixin,
)
from typing_extensions import Self

from pandas._libs import (
    NaT as NaT,
    NaTType as NaTType,
)
from pandas._typing import (
    DatetimeLikeScalar,
    NpDtype,
    PositionalIndexerTuple,
    ScalarIndexer,
    SequenceIndexer,
    TimeAmbiguous,
    TimeNonexistent,
    TimeUnit,
    np_1darray,
)

DTScalarOrNaT: TypeAlias = DatetimeLikeScalar | NaTType

class DatelikeOps:
    def strftime(self, date_format: Any) -> Any: ...

class TimelikeOps:
    @property
    def unit(self) -> TimeUnit: ...
    def as_unit(self, unit: TimeUnit) -> Self: ...
    def round(
        self,
        freq: Any,
        ambiguous: TimeAmbiguous = "raise",
        nonexistent: TimeNonexistent = "raise",
    ) -> Any: ...
    def floor(
        self,
        freq: Any,
        ambiguous: TimeAmbiguous = "raise",
        nonexistent: TimeNonexistent = "raise",
    ) -> Any: ...
    def ceil(
        self,
        freq: Any,
        ambiguous: TimeAmbiguous = "raise",
        nonexistent: TimeNonexistent = "raise",
    ) -> Any: ...

class DatetimeLikeArrayMixin(ExtensionOpsMixin, ExtensionArray):
    @property
    def ndim(self) -> int: ...
    @property
    def shape(self) -> Any: ...
    def reshape(self, *args: Any, **kwargs: Any) -> Any: ...
    def ravel(self, *args: Any, **kwargs: Any) -> Any: ...
    def __iter__(self) -> Any: ...
    @property
    def nbytes(self) -> Any: ...
    def __array__(
        self, dtype: NpDtype | None = None, copy: bool | None = None
    ) -> np_1darray: ...
    @property
    def size(self) -> int: ...
    @overload
    def __getitem__(self, key: ScalarIndexer) -> DTScalarOrNaT: ...
    @overload
    def __getitem__(  # ty: ignore[invalid-method-override]
        self,
        item: SequenceIndexer | PositionalIndexerTuple,
    ) -> Self: ...
    def __setitem__(  # type: ignore[override] # pyright: ignore[reportIncompatibleMethodOverride]
        self, key: int | Sequence[int] | Sequence[bool] | slice, value: Any
    ) -> None: ...
    def view(self, dtype: Any=...) -> Any: ...
    def unique(self) -> Any: ...
    def copy(self) -> Any: ...
    def shift(self, periods: int = 1, fill_value: Any=..., axis: int = ...) -> Any: ...
    def repeat(self, repeats: Any, *args: Any, **kwargs: Any) -> Any: ...
    def value_counts(self, dropna: bool = True) -> Any: ...
    def map(self, mapper: Any) -> Any: ...
    def isna(self) -> Any: ...
    @property
    def freq(self) -> Any: ...
    @freq.setter
    def freq(self, value: Any) -> None: ...
    @property
    def freqstr(self) -> Any: ...
    @property
    def inferred_freq(self) -> Any: ...
    @property
    def resolution(self) -> Any: ...
    __pow__ = ...
    __rpow__ = ...
    __rmul__ = ...
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __iadd__(self, other: Any) -> Any: ...
    def __isub__(self, other: Any) -> Any: ...
    def min(self, *, axis: Any=..., skipna: bool = ..., **kwargs: Any) -> Any: ...
    def max(self, *, axis: Any=..., skipna: bool = ..., **kwargs: Any) -> Any: ...
    def mean(self, *, skipna: bool = ...) -> Any: ...
