from datetime import tzinfo as _tzinfo
from pandas._typing import TimeAmbiguous, TimeNonexistent, TimeZones
from pandas.core.arrays.datetimelike import DatelikeOps, DatetimeLikeArrayMixin, TimelikeOps
from pandas.core.dtypes.dtypes import DatetimeTZDtype as DatetimeTZDtype
from typing import Any
import numpy as np

class DatetimeArray(DatetimeLikeArrayMixin, TimelikeOps, DatelikeOps):
    __array_priority__: int = ...
    def __init__(self, values: Any, dtype: Any=None, freq: Any=..., copy: bool = False) -> None: ...
    # ignore in dtype() is from the pandas source
    @property
    def dtype(self) -> np.dtype | DatetimeTZDtype: ...  # type: ignore[override] # pyright: ignore[reportIncompatibleMethodOverride]
    @property
    def tz(self) -> Any: ...
    @tz.setter
    def tz(self, value: Any) -> None: ...
    @property
    def tzinfo(self) -> _tzinfo | None: ...
    @property
    def is_normalized(self) -> Any: ...
    def __array__(self, dtype: Any=None) -> np.ndarray[Any, Any]: ...
    def __iter__(self) -> Any: ...
    def astype(self, dtype: Any, copy: bool = True) -> Any: ...
    def tz_convert(self, tz: TimeZones) -> Any: ...
    def tz_localize(
        self,
        tz: TimeZones,
        ambiguous: TimeAmbiguous = "raise",
        nonexistent: TimeNonexistent = "raise",
    ) -> Any: ...
    def to_pydatetime(self) -> Any: ...
    def normalize(self) -> Any: ...
    def to_period(self, freq: Any=None) -> Any: ...
    def to_perioddelta(self, freq: Any) -> Any: ...
    def month_name(self, locale: Any=None) -> Any: ...
    def day_name(self, locale: Any=None) -> Any: ...
    @property
    def time(self) -> Any: ...
    @property
    def timetz(self) -> Any: ...
    @property
    def date(self) -> Any: ...
    year = ...
    month = ...
    day = ...
    hour = ...
    minute = ...
    second = ...
    microsecond = ...
    nanosecond = ...
    dayofweek = ...
    weekday = ...
    dayofyear = ...
    quarter = ...
    days_in_month = ...
    daysinmonth = ...
    is_month_start = ...
    is_month_end = ...
    is_quarter_start = ...
    is_quarter_end = ...
    is_year_start = ...
    is_year_end = ...
    is_leap_year = ...
    def to_julian_date(self) -> Any: ...

def objects_to_datetime64ns(
    data: Any,
    dayfirst: Any,
    yearfirst: Any,
    utc: bool = ...,
    errors: str = ...,
    require_iso8601: bool = ...,
    allow_object: bool = ...,
) -> Any: ...
