from typing import (
    Any,
    overload,
)

import numpy as np
from pandas.core.arrays import (
    ExtensionArray as ExtensionArray,
    ExtensionOpsMixin,
)
from typing_extensions import Self

from pandas._typing import (
    Scalar,
    ScalarIndexer,
    SequenceIndexer,
    npt,
)

class BaseMaskedArray(ExtensionArray, ExtensionOpsMixin):
    @overload
    def __getitem__(self, item: ScalarIndexer) -> Any: ...
    @overload
    def __getitem__(self, item: SequenceIndexer) -> Self: ...
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __invert__(self) -> Any: ...
    def to_numpy(
        self,
        dtype: npt.DTypeLike | None = None,
        copy: bool = False,
        na_value: Scalar = ...,
    ) -> np.ndarray[Any, Any]: ...
    __array_priority__: int = ...
    def __array__(self, dtype: Any=None) -> np.ndarray[Any, Any]: ...
    def __arrow_array__(self, type: Any=None) -> Any: ...
    def isna(self) -> Any: ...
    @property
    def nbytes(self) -> int: ...
    def copy(self) -> Any: ...
    def value_counts(self, dropna: bool = True) -> Any: ...
