from typing import Literal

from pandas.core.arrays import PandasArray

from pandas._libs.missing import NAType

from pandas.core.dtypes.base import ExtensionDtype
from typing import Any

class StringDtype(ExtensionDtype):
    def __init__(self, storage: Literal["python", "pyarrow"] | None = None) -> None: ...
    @property
    def na_value(self) -> NAType: ...

class StringArray(PandasArray):
    def __init__(self, values: Any, copy: bool = False) -> None: ...
    def __arrow_array__(self, type: Any=None): ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def fillna(self, value: Any=None, method: Any=None, limit: Any=None): ...
    def astype(self, dtype: Any, copy: bool = True): ...
    def value_counts(self, dropna: bool = True): ...
