from collections.abc import Sequence
from datetime import timedelta

from pandas.core.arrays.datetimelike import (
    DatetimeLikeArrayMixin,
    TimelikeOps,
)
from typing import Any

class TimedeltaArray(DatetimeLikeArrayMixin, TimelikeOps):
    __array_priority__: int = ...
    @property
    def dtype(self) -> Any: ...
    def __init__(self, values: Any, dtype: Any=..., freq: Any=..., copy: bool = ...) -> None: ...
    def sum(
        self,
        *,
        axis: Any=...,
        dtype: Any=...,
        out: Any=...,
        keepdims: bool = ...,
        initial: Any=...,
        skipna: bool = ...,
        min_count: int = ...,
    ) -> Any: ...
    def std(
        self,
        *,
        axis: Any=...,
        dtype: Any=...,
        out: Any=...,
        ddof: int = ...,
        keepdims: bool = ...,
        skipna: bool = ...,
    ) -> Any: ...
    def median(
        self,
        *,
        axis: Any=...,
        out: Any=...,
        overwrite_input: bool = ...,
        keepdims: bool = ...,
        skipna: bool = ...,
    ) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    __rmul__ = ...
    def __truediv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> Any: ...
    def __floordiv__(self, other: Any) -> Any: ...
    def __rfloordiv__(self, other: Any) -> Any: ...
    def __mod__(self, other: Any) -> Any: ...
    def __rmod__(self, other: Any) -> Any: ...
    def __divmod__(self, other: Any) -> Any: ...
    def __rdivmod__(self, other: Any) -> Any: ...
    def __neg__(self) -> Any: ...
    def __pos__(self) -> Any: ...
    def __abs__(self) -> Any: ...
    def total_seconds(self) -> int: ...
    def to_pytimedelta(self) -> Sequence[timedelta]: ...
    days: int = ...
    seconds: int = ...
    microseconds: int = ...
    nanoseconds: int = ...
    @property
    def components(self) -> int: ...
