from collections.abc import Sequence
from datetime import timedelta

from pandas.core.arrays.datetimelike import (
    DatetimeLikeArrayMixin,
    TimelikeOps,
)
from typing import Any

class TimedeltaArray(DatetimeLikeArrayMixin, TimelikeOps):
    __array_priority__: int = ...
    @property
    def dtype(self) -> Any: ...
    def __init__(self, values: Any, dtype: Any=None, freq: Any=..., copy: bool = False) -> None: ...
    def astype(self, dtype: Any, copy: bool = True) -> Any: ...
    def sum(
        self,
        *,
        axis: Any=None,
        dtype: Any=None,
        out: Any=None,
        keepdims: bool = False,
        initial: Any=None,
        skipna: bool = True,
        min_count: int = 0,
    ) -> Any: ...
    def std(
        self,
        *,
        axis: Any=None,
        dtype: Any=None,
        out: Any=None,
        ddof: int = 1,
        keepdims: bool = False,
        skipna: bool = True,
    ) -> Any: ...
    def median(
        self,
        *,
        axis: Any=None,
        out: Any=...,
        overwrite_input: bool = ...,
        keepdims: bool = ...,
        skipna: bool = True,
    ) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    __rmul__ = ...
    def __truediv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> Any: ...
    def __floordiv__(self, other: Any) -> Any: ...
    def __rfloordiv__(self, other: Any) -> Any: ...
    def __mod__(self, other: Any) -> Any: ...
    def __rmod__(self, other: Any) -> Any: ...
    def __divmod__(self, other: Any) -> Any: ...
    def __rdivmod__(self, other: Any) -> Any: ...
    def __neg__(self) -> Any: ...
    def __pos__(self) -> Any: ...
    def __abs__(self) -> Any: ...
    def total_seconds(self) -> int: ...
    def to_pytimedelta(self) -> Sequence[timedelta]: ...
    days: int = ...
    seconds: int = ...
    microseconds: int = ...
    nanoseconds: int = ...
    @property
    def components(self) -> int: ...
