"""
This type stub file was generated by pyright.
"""

"""CFF2 to CFF converter."""
__all__ = ["convertCFF2ToCFF", "main"]
log = ...
def convertCFF2ToCFF(font, *, updatePostTable=...): # -> None:
    ...

def main(args=...): # -> None:
    """Convert CFF2 OTF font to CFF OTF font"""
    ...

if __name__ == "__main__":
    ...
