from _typeshed import Incomplete
from fontTools.misc.psCharStrings import (
	calcSubrBias as calcSubrBias, SimpleT2Decompiler as SimpleT2Decompiler, T2WidthExtractor as T2WidthExtractor)

def _uniq_sort(l): ...

class StopHintCountEvent(Exception): ...

class _DesubroutinizingT2Decompiler(SimpleT2Decompiler):
    stop_hintcount_ops: Incomplete
    def __init__(self, localSubrs, globalSubrs, private=None) -> None: ...
    need_hintcount: bool
    def execute(self, charString) -> None: ...
    def op_callsubr(self, index) -> None: ...
    def op_callgsubr(self, index) -> None: ...
    def stop_hint_count(self, *args) -> None: ...
    def op_hintmask(self, index) -> None: ...
    def processSubr(self, index, subr) -> None: ...

def desubroutinizeCharString(cs) -> None:
    """Desubroutinize a charstring in-place."""
def desubroutinize(cff) -> None: ...

class _MarkingT2Decompiler(SimpleT2Decompiler):
    def __init__(self, localSubrs, globalSubrs, private) -> None: ...
    def op_callsubr(self, index) -> None: ...
    def op_callgsubr(self, index) -> None: ...

class _DehintingT2Decompiler(T2WidthExtractor):
    class Hints:
        has_hint: bool
        last_hint: int
        last_checked: int
        status: int
        has_hintmask: bool
        deletions: Incomplete
        def __init__(self) -> None: ...
    _css: Incomplete
    private: Incomplete
    def __init__(self, css, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, private=None) -> None: ...
    def execute(self, charString) -> None: ...
    def op_callsubr(self, index) -> None: ...
    def op_callgsubr(self, index) -> None: ...
    def op_hstem(self, index) -> None: ...
    def op_vstem(self, index) -> None: ...
    def op_hstemhm(self, index) -> None: ...
    def op_vstemhm(self, index) -> None: ...
    def op_hintmask(self, index): ...
    def op_cntrmask(self, index): ...
    def processHintmask(self, index) -> None: ...
    def processHint(self, index) -> None: ...
    def processSubr(self, index, subr) -> None: ...

def _cs_subset_subroutines(charstring, subrs, gsubrs) -> None: ...
def _cs_drop_hints(charstring) -> None: ...
def remove_hints(cff, *, removeUnusedSubrs: bool = True): ...
def _pd_delete_empty_subrs(private_dict) -> None: ...
def remove_unused_subroutines(cff) -> None: ...
