from _typeshed import Incomplete
from collections.abc import Iterable
from enum import IntEnum
from fontTools.pens.basePen import AbstractPen
from fontTools.pens.pointPen import AbstractPointPen
from ufoLib2.typing import PathLike
import os

__all__ = ['ARROW', 'BOTTOMGHOST', 'CAP', 'CIRCLE', 'CORNER', 'CURVE', 'GSCURVE', 'GSLINE', 'GSMOVE', 'GSOFFCURVE', 'GSSHARP', 'GSSMOOTH', 'LINE', 'LTR', 'LTRTTB', 'MINUS', 'MOVE', 'OFFCURVE', 'PLUS', 'QCURVE', 'RTL', 'RTLTTB', 'STEM', 'TAG', 'TEXT', 'TOPGHOST', 'TRIPLE', 'TTALIGN', 'TTANCHOR', 'TTDELTA', 'TTDIAGONAL', 'TTDONTROUND', 'TTINTERPOLATE', 'TTROUND', 'TTROUNDDOWN', 'TTROUNDUP', 'TTSTEM', 'WEIGHT_CODES', 'WIDTH_CODES', 'GSAlignmentZone', 'GSAnchor', 'GSAnnotation', 'GSBackgroundImage', 'GSBottomCenter', 'GSBottomLeft', 'GSBottomRight', 'GSCenterCenter', 'GSCenterLeft', 'GSCenterRight', 'GSClass', 'GSComponent', 'GSCustomParameter', 'GSFeature', 'GSFeaturePrefix', 'GSFont', 'GSFontMaster', 'GSGlyph', 'GSGuide', 'GSHint', 'GSInstance', 'GSLayer', 'GSNode', 'GSPath', 'GSSmartComponentAxis', 'GSTopCenter', 'GSTopLeft', 'GSTopRight', 'Glyphs']

class InstanceType(IntEnum):
	SINGLE = 0
	VARIABLE = 1

ARROW: int
BOTTOMGHOST: int
CAP: int
CIRCLE: int
CORNER: int
CURVE: str
GSBottomCenter: int
GSBottomLeft: int
GSBottomRight: int
GSCenterCenter: int
GSCenterLeft: int
GSCenterRight: int
GSCURVE: str
GSLINE: str
GSMOVE: str
GSOFFCURVE: str
GSSHARP: int
GSSMOOTH: int
GSTopCenter: int
GSTopLeft: int
GSTopRight: int
LINE: str
LTR: int
LTRTTB: int
MINUS: int
MOVE: str
OFFCURVE: str
PLUS: int
QCURVE: str
RTL: int
RTLTTB: int
STEM: int
TAG: int
TEXT: int
TOPGHOST: int
TRIPLE: int
TTALIGN: int
TTANCHOR: int
TTDELTA: int
TTDIAGONAL: int
TTDONTROUND: int
TTINTERPOLATE: int
TTROUND: int
TTROUNDDOWN: int
TTROUNDUP: int
TTSTEM: int
WEIGHT_CODES: Incomplete
WIDTH_CODES: Incomplete

class OnlyInGlyphsAppError(NotImplementedError):
	def __init__(self) -> None: ...

class GSApplication:
	font: Incomplete
	fonts: Incomplete
	def __init__(self) -> None: ...
	def open(self, path: PathLike) -> Incomplete: ...

Glyphs: Incomplete

class GSBase:
	"""Represent the base class for all GS classes.

	Attributes
	----------
		_defaultsForName (dict): Used to determine which values to serialize and which
			to imply by their absence.
	"""
	def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...

class Proxy:
	def __init__(self, owner: Incomplete) -> None: ...
	def __len__(self) -> int: ...
	def pop(self, i: Incomplete) -> Incomplete: ...
	def __iter__(self) -> Incomplete: ...
	def index(self, value: Incomplete) -> Incomplete: ...
	def __copy__(self) -> Incomplete: ...
	def __deepcopy__(self, memo: Incomplete) -> Incomplete: ...
	def setter(self, values: Incomplete) -> None: ...

class ListDictionaryProxy(Proxy):
	def __init__(self, owner: Incomplete, name: Incomplete, klass: Incomplete) -> None: ...
	def get(self, name: Incomplete, default: Incomplete=None) -> Incomplete: ...
	def append(self, item: Incomplete) -> None: ...
	def extend(self, items: Incomplete) -> None: ...
	def remove(self, item: Incomplete) -> None: ...
	def insert(self, index: Incomplete, item: Incomplete) -> None: ...
	def values(self) -> Incomplete: ...
	def setterMethod(self) -> Incomplete: ...
	def __getitem__(self, key: Incomplete) -> Incomplete: ...
	def __setitem__(self, name: Incomplete, value: Incomplete) -> None: ...
	def __delitem__(self, key: Incomplete) -> None: ...
	def __contains__(self, item: Incomplete) -> bool: ...
	def __iter__(self) -> Incomplete: ...
	def __len__(self) -> int: ...
	def __setter__(self, items: Incomplete) -> None: ...

class LayersIterator:
	def __init__(self, owner: Incomplete) -> None: ...
	def __iter__(self) -> Incomplete: ...
	def next(self) -> Incomplete: ...
	def __next__(self) -> Incomplete: ...
	@staticmethod
	def orderedLayers(glyph: Incomplete) -> Incomplete: ...

class FontFontMasterProxy(Proxy):
	"""The list of masters. You can access it with the index or the master ID.

	Usage:
		Font.masters[index]
		Font.masters[id]
		for master in Font.masters:
		...
	"""
	def __getitem__(self, Key: Incomplete) -> Incomplete: ...
	def __setitem__(self, Key: Incomplete, FontMaster: Incomplete) -> None: ...
	def __delitem__(self, Key: Incomplete) -> None: ...
	def values(self) -> Incomplete: ...
	def append(self, FontMaster: Incomplete) -> None: ...
	def remove(self, FontMaster: Incomplete) -> None: ...
	def insert(self, Index: Incomplete, FontMaster: Incomplete) -> None: ...
	def extend(self, FontMasters: Incomplete) -> None: ...
	def setter(self, values: Incomplete) -> None: ...

class FontGlyphsProxy(Proxy):
	"""The list of glyphs. You can access it with the index or the glyph name.

	Usage:
		Font.glyphs[index]
		Font.glyphs[name]
		for glyph in Font.glyphs:
		...
	"""
	def __getitem__(self, key: Incomplete) -> Incomplete: ...
	def __setitem__(self, key: Incomplete, glyph: Incomplete) -> None: ...
	def __delitem__(self, key: Incomplete) -> None: ...
	def __contains__(self, item: Incomplete) -> bool: ...
	def values(self) -> Incomplete: ...
	def items(self) -> Incomplete: ...
	def append(self, glyph: Incomplete) -> None: ...
	def extend(self, objects: Incomplete) -> None: ...
	def __len__(self) -> int: ...
	def setter(self, values: Incomplete) -> None: ...

class FontClassesProxy(Proxy):
	VALUES_ATTR: str
	def __getitem__(self, key: Incomplete) -> Incomplete: ...
	def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...
	def __delitem__(self, key: Incomplete) -> None: ...
	def __contains__(self, item: Incomplete) -> bool: ...
	def append(self, item: Incomplete) -> None: ...
	def insert(self, key: Incomplete, item: Incomplete) -> None: ...
	def extend(self, items: Incomplete) -> None: ...
	def remove(self, item: Incomplete) -> None: ...
	def values(self) -> Incomplete: ...
	def setter(self, values: Incomplete) -> None: ...

class FontFeaturesProxy(FontClassesProxy):
	VALUES_ATTR: str

class FontFeaturePrefixesProxy(FontClassesProxy):
	VALUES_ATTR: str

class GlyphLayerProxy(Proxy):
	def __getitem__(self, key: Incomplete) -> Incomplete: ...
	def __setitem__(self, key: Incomplete, layer: Incomplete) -> None: ...
	def __delitem__(self, key: Incomplete) -> None: ...
	def __iter__(self) -> Incomplete: ...
	def __len__(self) -> int: ...
	def keys(self) -> Incomplete: ...
	def values(self) -> Incomplete: ...
	def append(self, layer: Incomplete) -> None: ...
	def extend(self, layers: Incomplete) -> None: ...
	def remove(self, layer: Incomplete) -> Incomplete: ...
	def insert(self, index: Incomplete, layer: Incomplete) -> None: ...
	def setter(self, values: Incomplete) -> None: ...
	def plistArray(self) -> Incomplete: ...

class LayerAnchorsProxy(Proxy):
	def __getitem__(self, key: Incomplete) -> Incomplete: ...
	def __setitem__(self, key: Incomplete, anchor: Incomplete) -> None: ...
	def __delitem__(self, key: Incomplete) -> None: ...
	def values(self) -> Incomplete: ...
	def append(self, anchor: Incomplete) -> None: ...
	def extend(self, anchors: Incomplete) -> None: ...
	def remove(self, anchor: Incomplete) -> Incomplete: ...
	def insert(self, index: Incomplete, anchor: Incomplete) -> None: ...
	def __len__(self) -> int: ...
	def setter(self, anchors: Incomplete) -> None: ...  # pyright: ignore[reportIncompatibleMethodOverride] # ty:ignore[invalid-method-override]

class IndexedObjectsProxy(Proxy):
	def __getitem__(self, key: Incomplete) -> Incomplete: ...
	def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...
	def __delitem__(self, key: Incomplete) -> None: ...
	def values(self) -> Incomplete: ...
	def append(self, value: Incomplete) -> None: ...
	def extend(self, values: Incomplete) -> None: ...
	def remove(self, value: Incomplete) -> None: ...
	def insert(self, index: Incomplete, value: Incomplete) -> None: ...
	def __len__(self) -> int: ...
	def setter(self, values: Incomplete) -> None: ...

class LayerShapesProxy(IndexedObjectsProxy):
	def __init__(self, owner: Incomplete) -> None: ...
	def append(self, value: Incomplete) -> None: ...
	def extend(self, values: Incomplete) -> None: ...
	def remove(self, value: Incomplete) -> None: ...
	def insert(self, index: Incomplete, value: Incomplete) -> None: ...
	def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...
	def __delitem__(self, key: Incomplete) -> None: ...
	def setter(self, values: Incomplete) -> Incomplete: ...
	def values(self) -> Incomplete: ...

class LayerHintsProxy(IndexedObjectsProxy):
	def __init__(self, owner: Incomplete) -> None: ...

class LayerAnnotationProxy(IndexedObjectsProxy):
	def __init__(self, owner: Incomplete) -> None: ...

class LayerGuideLinesProxy(IndexedObjectsProxy):
	def __init__(self, owner: Incomplete) -> None: ...

class PathNodesProxy(IndexedObjectsProxy):
	def __init__(self, owner: Incomplete) -> None: ...

class CustomParametersProxy(ListDictionaryProxy):
	def __init__(self, owner: Incomplete) -> None: ...
	def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...  # ty:ignore[invalid-method-override]
	def __contains__(self, item: Incomplete) -> bool: ...
	def __setter__(self, items: Incomplete) -> None: ...
	def __iter__(self) -> Incomplete: ...
	def __len__(self) -> int: ...

class PropertiesProxy(ListDictionaryProxy):
	def __init__(self, owner: Incomplete) -> None: ...

class UserDataProxy(Proxy):
	def __getitem__(self, key: Incomplete) -> Incomplete: ...
	def __setitem__(self, key: Incomplete, value: Incomplete) -> None: ...
	def __delitem__(self, key: Incomplete) -> None: ...
	def __contains__(self, item: Incomplete) -> bool: ...
	def __iter__(self) -> Incomplete: ...
	def values(self) -> Incomplete: ...
	def keys(self) -> Incomplete: ...
	def items(self) -> Incomplete: ...
	def get(self, key: Incomplete) -> Incomplete: ...
	def setter(self, values: Incomplete) -> None: ...

class GSAxis(GSBase):
	name: Incomplete
	axisTag: Incomplete
	axisId: Incomplete
	hidden: Incomplete
	def __init__(self, name: str = '', tag: str = '', hidden: bool = False) -> None: ...
	def __eq__(self, other: Incomplete) -> Incomplete: ...

class GSCustomParameter(GSBase):
	name: Incomplete
	value: Incomplete
	disabled: Incomplete
	def __init__(self, name: str = 'New Value', value: str = 'New Parameter', disabled: bool = False) -> None: ...
	def plistValue(self, format_version: int = 2) -> Incomplete: ...
	def getValue(self) -> Incomplete: ...
	def setValue(self, value: Incomplete) -> None:
		"""Cast some known data in custom parameters."""

class GSMetric(GSBase):
	name: Incomplete
	type: Incomplete
	id: str
	filter: str
	horizontal: bool
	def __init__(self, name: str = '', type: str = '') -> None: ...  # noqa: A002

class GSMetricValue(GSBase):
	position: Incomplete
	overshoot: Incomplete
	name: str
	filter: str
	metric: str
	def __init__(self, position: int = 0, overshoot: int = 0) -> None: ...

class GSAlignmentZone(GSBase):
	position: Incomplete
	size: Incomplete
	def __init__(self, pos: int = 0, size: int = 20) -> None: ...
	def read(self, src: Incomplete) -> Incomplete: ...
	def __lt__(self, other: Incomplete) -> Incomplete: ...
	def __eq__(self, other: Incomplete) -> Incomplete: ...
	def plistValue(self, format_version: int = 2) -> Incomplete: ...

class GSGuide(GSBase):
	alignment: str
	angle: int
	filter: str
	locked: bool
	name: str
	position: Incomplete
	showMeasurement: bool
	lockAngle: bool
	def __init__(self) -> None: ...
	@property
	def parent(self) -> Incomplete: ...

class GSFontMaster(GSBase):
	customParameters: Incomplete
	axes: Incomplete
	metrics: Incomplete
	customName: str
	font: Incomplete
	guides: Incomplete
	iconName: str
	id: Incomplete
	numbers: Incomplete
	stems: Incomplete
	visible: bool
	weight: Incomplete
	width: Incomplete
	def __init__(self) -> None: ...
	@property
	def metricsSource(self) -> Incomplete:
		"""Returns the source master to be used for glyph and kerning metrics.

		If linked metrics parameters are being used, the master is returned here,
		otherwise None.
		"""
	@property
	def name(self) -> Incomplete: ...
	@name.setter
	def name(self, name: Incomplete) -> None:
		"""Function will take the given name and split it into components weight, width, customName, and possibly the full name.

		This is what Glyphs 1113 seems to be doing, approximately.
		"""
	def set_all_name_components(self, name: Incomplete, weight: Incomplete, width: Incomplete, custom_name: Incomplete) -> None:
		"""Function ensures that after being called, the master.name, master.weight, master.width, and master.customName match the given values."""
	userData: Incomplete
	@property
	def alignmentZones(self) -> Incomplete: ...
	@alignmentZones.setter
	def alignmentZones(self, entries: Incomplete) -> None: ...
	@property
	def horizontalStems(self) -> Incomplete: ...
	@horizontalStems.setter
	def horizontalStems(self, value: Incomplete) -> None: ...
	@property
	def verticalStems(self) -> Incomplete: ...
	@verticalStems.setter
	def verticalStems(self, value: Incomplete) -> None: ...
	@property
	def ascender(self) -> Incomplete: ...
	@ascender.setter
	def ascender(self, value: Incomplete) -> None: ...
	@property
	def xHeight(self) -> Incomplete: ...
	@xHeight.setter
	def xHeight(self, value: Incomplete) -> None: ...
	@property
	def capHeight(self) -> Incomplete: ...
	@capHeight.setter
	def capHeight(self, value: Incomplete) -> None: ...
	@property
	def descender(self) -> Incomplete: ...
	@descender.setter
	def descender(self, value: Incomplete) -> None: ...
	@property
	def italicAngle(self) -> Incomplete: ...
	@italicAngle.setter
	def italicAngle(self, value: Incomplete) -> None: ...
	@property
	def weightValue(self) -> Incomplete: ...
	@weightValue.setter
	def weightValue(self, value: Incomplete) -> Incomplete: ...
	@property
	def widthValue(self) -> Incomplete: ...
	@widthValue.setter
	def widthValue(self, value: Incomplete) -> Incomplete: ...
	@property
	def customValue(self) -> Incomplete: ...
	@customValue.setter
	def customValue(self, value: Incomplete) -> Incomplete: ...
	@property
	def customValue1(self) -> Incomplete: ...
	@customValue1.setter
	def customValue1(self, value: Incomplete) -> Incomplete: ...
	@property
	def customValue2(self) -> Incomplete: ...
	@customValue2.setter
	def customValue2(self, value: Incomplete) -> Incomplete: ...
	@property
	def customValue3(self) -> Incomplete: ...
	@customValue3.setter
	def customValue3(self, value: Incomplete) -> Incomplete: ...

class GSNode(GSBase):
	smooth: Incomplete
	type: Incomplete
	def __init__(self, position: Incomplete = (0, 0), type: Incomplete = ..., smooth: bool = False, name: Incomplete = None, nodetype: Incomplete = None) -> None: ...  # noqa: A002
	def clone(self) -> Incomplete:
		"""Clones the node (does not clone attributes)"""
	userData: Incomplete
	@property
	def position(self) -> Incomplete: ...
	@position.setter
	def position(self, value: Incomplete) -> None: ...
	@property
	def parent(self) -> Incomplete: ...
	def plistValue(self, format_version: int = 2) -> Incomplete: ...
	@classmethod
	def read(cls, line: Incomplete) -> Incomplete:
		"""Parse a Glyphs node string into a GSNode.

		The format of a Glyphs node string (`line`) is:

			"X Y (LINE|CURVE|QCURVE|OFFCURVE)"
			"X Y (LINE|CURVE|QCURVE|OFFCURVE) SMOOTH"
			"X Y (LINE|CURVE|QCURVE|OFFCURVE) SMOOTH {dictionary}"
			"X Y (LINE|CURVE|QCURVE|OFFCURVE) {dictionary}"

		X and Y can be integers or floats, positive or negative.

		WARNING: This method is HOT. It is called for every single node and can
		account for a significant portion of the file parsing time.
		"""
	@classmethod
	def read_v3(cls, lst: Incomplete) -> Incomplete: ...
	@property
	def name(self) -> Incomplete: ...
	@name.setter
	def name(self, value: Incomplete) -> None: ...
	@property
	def index(self) -> Incomplete: ...
	@property
	def nextNode(self) -> Incomplete: ...
	@property
	def prevNode(self) -> Incomplete: ...
	def makeNodeFirst(self) -> None: ...
	def toggleConnection(self) -> None: ...
	@property
	def connection(self) -> None: ...
	@property
	def selected(self) -> None: ...

class GSPath(GSBase):
	closed: Incomplete
	attributes: Incomplete
	def __init__(self) -> None: ...
	def clone(self) -> Incomplete:
		"""Clones the path (Does not clone attributes)"""
	@property
	def parent(self) -> Incomplete: ...
	nodes: Incomplete
	@property
	def segments(self) -> Incomplete: ...
	@segments.setter
	def segments(self, value: Incomplete) -> None: ...
	def setSegments(self, segments: Incomplete) -> None: ...
	@property
	def bounds(self) -> Incomplete: ...
	@property
	def direction(self) -> Incomplete: ...
	@property
	def selected(self) -> None: ...
	@property
	def bezierPath(self) -> None: ...
	def reverse(self) -> None: ...
	def addNodesAtExtremes(self) -> None: ...
	def applyTransform(self, transformationMatrix: Incomplete) -> None: ...
	def draw(self, pen: AbstractPen) -> None:
		"""Draws contour with the given pen."""
	def drawPoints(self, pointPen: AbstractPointPen) -> None:
		"""Draws points of contour with the given point pen."""

class segment(list[Incomplete]):
	nodes: Incomplete
	def appendNode(self, node: Incomplete) -> None: ...
	@property
	def nextSegment(self) -> Incomplete: ...
	@property
	def prevSegment(self) -> Incomplete: ...
	def bbox(self) -> Incomplete: ...
	def bezierMinMax(self, x0: Incomplete, y0: Incomplete, x1: Incomplete, y1: Incomplete, x2: Incomplete, y2: Incomplete, x3: Incomplete, y3: Incomplete) -> Incomplete: ...

class GSComponent(GSBase):
	alignment: int
	anchor: str
	locked: bool
	name: Incomplete
	smartComponentValues: Incomplete
	transform: Incomplete
	def __init__(self, glyph: str = '', offset: Incomplete = (0, 0), scale: Incomplete = (1, 1), transform: Incomplete = None) -> None: ...
	def clone(self) -> Incomplete: ...
	@property
	def parent(self) -> Incomplete: ...
	@property
	def position(self) -> Incomplete: ...
	@position.setter
	def position(self, value: Incomplete) -> None: ...
	@property
	def scale(self) -> Incomplete: ...
	@scale.setter
	def scale(self, value: Incomplete) -> None: ...
	@property
	def rotation(self) -> Incomplete: ...
	@rotation.setter
	def rotation(self, value: Incomplete) -> None: ...
	def updateAffineTransform(self) -> None: ...
	@property
	def componentName(self) -> Incomplete: ...
	@componentName.setter
	def componentName(self, value: Incomplete) -> None: ...
	@property
	def component(self) -> Incomplete: ...
	@property
	def layer(self) -> Incomplete: ...
	def applyTransformation(self, x: Incomplete, y: Incomplete) -> Incomplete: ...
	@property
	def bounds(self) -> Incomplete: ...
	def draw(self, pen: AbstractPen) -> None:
		"""Draws component with given pen."""
	def drawPoints(self, pointPen: AbstractPointPen) -> None:
		"""Draws points of component with given point pen."""

class GSSmartComponentAxis(GSBase):
	bottomName: str
	bottomValue: Incomplete
	name: str
	topName: str
	topValue: Incomplete
	def __init__(self) -> None: ...

class GSAnchor(GSBase):
	name: Incomplete
	position: Incomplete
	userData: Incomplete
	def __init__(self, name: Incomplete=None, position: Incomplete=None, userData: Incomplete=None) -> None: ...
	@property
	def parent(self) -> Incomplete: ...

class GSHint(GSBase):
	horizontal: bool
	name: str
	options: int
	place: Incomplete
	scale: Incomplete
	settings: Incomplete
	stem: Incomplete
	type: str
	def __init__(self) -> None: ...
	@property
	def parent(self) -> Incomplete: ...
	@property
	def originNode(self) -> Incomplete: ...
	@originNode.setter
	def originNode(self, node: Incomplete) -> None: ...
	@property
	def origin(self) -> Incomplete: ...
	@origin.setter
	def origin(self, origin: Incomplete) -> None: ...
	@property
	def targetNode(self) -> Incomplete: ...
	@targetNode.setter
	def targetNode(self, node: Incomplete) -> None: ...
	@property
	def target(self) -> Incomplete: ...
	@target.setter
	def target(self, target: Incomplete) -> None: ...
	@property
	def otherNode1(self) -> Incomplete: ...
	@otherNode1.setter
	def otherNode1(self, node: Incomplete) -> None: ...
	@property
	def other1(self) -> Incomplete: ...
	@other1.setter
	def other1(self, other1: Incomplete) -> None: ...
	@property
	def otherNode2(self) -> Incomplete: ...
	@otherNode2.setter
	def otherNode2(self, node: Incomplete) -> None: ...
	@property
	def other2(self) -> Incomplete: ...
	@other2.setter
	def other2(self, other2: Incomplete) -> None: ...

class GSFeature(GSBase):
	automatic: bool
	code: Incomplete
	disabled: bool
	name: Incomplete
	notes: str
	labels: Incomplete
	def __init__(self, name: str = 'xxxx', code: str = '') -> None: ...
	def getCode(self) -> Incomplete: ...
	def setCode(self, code: Incomplete) -> None: ...
	@property
	def parent(self) -> Incomplete: ...

class GSClass(GSFeature): ...
class GSFeaturePrefix(GSClass): ...

class GSAnnotation(GSBase):
	angle: Incomplete
	position: Incomplete
	text: Incomplete
	type: Incomplete
	width: Incomplete
	def __init__(self) -> None: ...
	@property
	def parent(self) -> Incomplete: ...

class GSFontInfoValue(GSBase):
	key: Incomplete
	def __init__(self, key: str = '', value: str = '') -> None: ...
	@property
	def name(self) -> Incomplete: ...
	@name.setter
	def name(self, value: Incomplete) -> None: ...
	@property
	def value(self) -> Incomplete: ...
	@value.setter
	def value(self, value: Incomplete) -> None: ...

class GSInstance(GSBase):
	axes: Incomplete
	customParameters: Incomplete
	active: Incomplete
	custom: Incomplete
	instanceInterpolations: Incomplete
	isBold: bool
	isItalic: bool
	linkStyle: str
	manualInterpolation: bool
	name: str
	properties: Incomplete
	visible: bool
	weight: Incomplete
	width: Incomplete
	type: Incomplete
	def __init__(self) -> None: ...
	@property
	def exports(self) -> Incomplete:
		"""Deprecated alias for `active`, which is in the documentation."""
	@exports.setter
	def exports(self, value: Incomplete) -> None: ...
	@property
	def familyName(self) -> Incomplete: ...
	@familyName.setter
	def familyName(self, value: Incomplete) -> None: ...
	@property
	def preferredFamily(self) -> Incomplete: ...
	@preferredFamily.setter
	def preferredFamily(self, value: Incomplete) -> None: ...
	@property
	def preferredFamilyName(self) -> Incomplete: ...
	@property
	def preferredSubfamilyName(self) -> Incomplete: ...
	@preferredSubfamilyName.setter
	def preferredSubfamilyName(self, value: Incomplete) -> None: ...
	@property
	def windowsFamily(self) -> Incomplete: ...
	@windowsFamily.setter
	def windowsFamily(self, value: Incomplete) -> None: ...
	@property
	def windowsStyle(self) -> Incomplete: ...
	@property
	def windowsLinkedToStyle(self) -> Incomplete: ...
	@property
	def fontName(self) -> Incomplete: ...
	@fontName.setter
	def fontName(self, value: Incomplete) -> None: ...
	@property
	def fullName(self) -> Incomplete: ...
	@fullName.setter
	def fullName(self, value: Incomplete) -> None: ...
	@property
	def weightValue(self) -> Incomplete: ...
	@weightValue.setter
	def weightValue(self, value: Incomplete) -> Incomplete: ...
	@property
	def widthValue(self) -> Incomplete: ...
	@widthValue.setter
	def widthValue(self, value: Incomplete) -> Incomplete: ...
	@property
	def customValue(self) -> Incomplete: ...
	@customValue.setter
	def customValue(self, value: Incomplete) -> Incomplete: ...
	@property
	def customValue1(self) -> Incomplete: ...
	@customValue1.setter
	def customValue1(self, value: Incomplete) -> Incomplete: ...
	@property
	def customValue2(self) -> Incomplete: ...
	@customValue2.setter
	def customValue2(self, value: Incomplete) -> Incomplete: ...
	@property
	def customValue3(self) -> Incomplete: ...
	@customValue3.setter
	def customValue3(self, value: Incomplete) -> Incomplete: ...

class GSBackgroundImage(GSBase):
	crop: Incomplete
	imagePath: Incomplete
	locked: bool
	transform: Incomplete
	def __init__(self, path: Incomplete = None) -> None: ...
	@property
	def path(self) -> Incomplete: ...
	@path.setter
	def path(self, value: Incomplete) -> None: ...
	@property
	def position(self) -> Incomplete: ...
	@position.setter
	def position(self, value: Incomplete) -> None: ...
	@property
	def scale(self) -> Incomplete: ...
	@scale.setter
	def scale(self, value: Incomplete) -> None: ...
	@property
	def rotation(self) -> Incomplete: ...
	@rotation.setter
	def rotation(self, value: Incomplete) -> None: ...
	@property
	def alpha(self) -> Incomplete: ...
	@alpha.setter
	def alpha(self, value: Incomplete) -> None: ...
	def updateAffineTransform(self) -> None: ...

class LayerPathsProxy(LayerShapesProxy): ...
class LayerComponentsProxy(LayerShapesProxy): ...

class GSLayer(GSBase):
	attributes: Incomplete
	partSelection: Incomplete
	associatedMasterId: str
	backgroundImage: Incomplete
	color: Incomplete
	metricLeft: Incomplete
	parent: Incomplete
	metricRight: Incomplete
	vertOrigin: Incomplete
	vertWidth: Incomplete
	visible: bool
	width: Incomplete
	metricWidth: Incomplete
	def __init__(self) -> None: ...
	def __lt__(self, other: Incomplete) -> Incomplete: ...
	@property
	def layerId(self) -> Incomplete: ...
	@layerId.setter
	def layerId(self, value: Incomplete) -> None: ...
	@property
	def master(self) -> Incomplete: ...
	@property
	def name(self) -> Incomplete: ...
	@name.setter
	def name(self, value: Incomplete) -> None: ...
	anchors: Incomplete
	hints: Incomplete
	paths: Incomplete
	components: Incomplete
	shapes: Incomplete
	guides: Incomplete
	annotations: Incomplete
	userData: Incomplete
	@property
	def smartComponentPoleMapping(self) -> Incomplete: ...
	@smartComponentPoleMapping.setter
	def smartComponentPoleMapping(self, value: Incomplete) -> None: ...
	@property
	def bounds(self) -> Incomplete: ...
	@property
	def background(self) -> Incomplete:
		"""Only a getter on purpose. See the tests."""
	@property
	def hasBackground(self) -> Incomplete: ...
	@property
	def foreground(self) -> None:
		"""Forbidden, and also forbidden to set it."""
	def getPen(self) -> AbstractPen:
		"""Returns a pen for others to draw into self."""
	def getPointPen(self) -> AbstractPointPen:
		"""Returns a point pen for others to draw points into self."""
	def draw(self, pen: AbstractPen) -> None:
		"""Draws glyph with the given pen."""
	def drawPoints(self, pointPen: AbstractPointPen) -> None:
		"""Draws points of glyph with the given point pen."""
	@property
	def rightMetricsKey(self) -> Incomplete: ...
	@property
	def leftMetricsKey(self) -> Incomplete: ...
	@property
	def widthMetricsKey(self) -> Incomplete: ...
	@rightMetricsKey.setter
	def rightMetricsKey(self, value: Incomplete) -> None: ...
	@leftMetricsKey.setter
	def leftMetricsKey(self, value: Incomplete) -> None: ...
	@widthMetricsKey.setter
	def widthMetricsKey(self, value: Incomplete) -> None: ...
	BRACKET_LAYER_RE: Incomplete
	COLOR_PALETTE_LAYER_RE: Incomplete

class GSBackgroundLayer(GSLayer):
	@property
	def background(self) -> None: ...
	@property
	def foreground(self) -> Incomplete: ...
	@property
	def width(self) -> Incomplete: ...
	@width.setter
	def width(self, whatever: Incomplete) -> None: ...

class GSGlyph(GSBase):
	bottomKerningGroup: str
	bottomMetricsKey: str
	category: Incomplete
	case: Incomplete
	color: Incomplete
	export: Incomplete
	lastChange: Incomplete
	leftKerningGroup: Incomplete
	leftKerningKey: str
	metricLeft: Incomplete
	name: Incomplete
	note: Incomplete
	parent: Incomplete
	partsSettings: Incomplete
	production: str
	rightKerningGroup: Incomplete
	rightKerningKey: str
	metricRight: Incomplete
	script: Incomplete
	selected: bool
	subCategory: Incomplete
	tags: Incomplete
	topKerningGroup: str
	topMetricsKey: str
	userData: Incomplete
	metricVertWidth: Incomplete
	metricWidth: Incomplete
	def __init__(self, name: Incomplete=None) -> None: ...
	layers: Incomplete
	def removeLayerForKey_(self, key: Incomplete) -> None: ...
	@property
	def string(self) -> Incomplete: ...
	@property
	def glyphname(self) -> Incomplete: ...
	@glyphname.setter
	def glyphname(self, value: Incomplete) -> None: ...
	@property
	def smartComponentAxes(self) -> Incomplete: ...
	@smartComponentAxes.setter
	def smartComponentAxes(self, value: Incomplete) -> None: ...
	@property
	def id(self) -> Incomplete:
		"""An unique identifier for each glyph"""
	@property
	def unicode(self) -> str: ...
	@unicode.setter
	def unicode(self, unicode: str) -> None: ...
	@property
	def unicodes(self) -> Iterable[str]: ...
	@unicodes.setter
	def unicodes(self, unicodes: Iterable[str]) -> None: ...
	@property
	def rightMetricsKey(self) -> Incomplete: ...
	@rightMetricsKey.setter
	def rightMetricsKey(self, value: Incomplete) -> None: ...
	@property
	def leftMetricsKey(self) -> Incomplete: ...
	@leftMetricsKey.setter
	def leftMetricsKey(self, value: Incomplete) -> None: ...
	@property
	def widthMetricsKey(self) -> Incomplete: ...
	@widthMetricsKey.setter
	def widthMetricsKey(self, value: Incomplete) -> None: ...
	@property
	def vertWidthMetricsKey(self) -> Incomplete: ...
	@vertWidthMetricsKey.setter
	def vertWidthMetricsKey(self, value: Incomplete) -> None: ...
	def colorIndex(self) -> Incomplete: ...
	def countOfUnicodes(self) -> Incomplete: ...
	def countOfLayers(self) -> Incomplete: ...
	def hasAnnotations(self) -> Incomplete: ...
	def hasComponents(self) -> Incomplete: ...
	def hasCorners(self) -> Incomplete: ...
	def hasSpecialLayers(self) -> Incomplete: ...
	def isAnyColorGlyph(self) -> Incomplete: ...
	def isFullColorGlyph(self) -> Incomplete: ...
	def isColorPaletteGlyph(self) -> Incomplete: ...
	def isSVGColorGlyph(self) -> Incomplete: ...
	def isAppleColorGlyph(self) -> Incomplete: ...

class GSFont(GSBase):
	appVersion: str
	axes: Incomplete
	classes: Incomplete
	customParameters: Incomplete
	date: Incomplete
	disablesAutomaticAlignment: Incomplete
	disablesNiceNames: Incomplete
	DisplayStrings: str
	EMPTY_KERNING_VALUE: Incomplete
	familyName: str
	featurePrefixes: Incomplete
	features: Incomplete
	filepath: Incomplete
	format_version: int
	glyphs: Iterable[GSGlyph]
	grid: Incomplete
	gridSubDivisions: Incomplete
	keepAlternatesTogether: bool
	keyboardIncrement: Incomplete
	keyboardIncrementBig: int
	keyboardIncrementHuge: int
	masters: Incomplete
	metrics: Incomplete
	numbers: Incomplete
	properties: Incomplete
	stems: Incomplete
	upm: Incomplete
	userData: Incomplete
	versionMajor: int
	versionMinor: Incomplete
	def __init__(self, path: PathLike | None = None) -> None: ...
	def save(self, path: Incomplete = None) -> None: ...
	def getVersionMinor(self) -> Incomplete: ...
	def setVersionMinor(self, value: Incomplete) -> None:
		"""Ensure that the minor version number is between 0 and 999."""
	def masterForId(self, key: Incomplete) -> Incomplete: ...
	@property
	def instances(self) -> Incomplete: ...
	@instances.setter
	def instances(self, value: Incomplete) -> None: ...
	@property
	def kerning(self) -> Incomplete: ...
	@kerning.setter
	def kerning(self, kerning: Incomplete) -> None: ...
	@property
	def kerningLTR(self) -> Incomplete: ...
	@kerningLTR.setter
	def kerningLTR(self, kerning: Incomplete) -> None: ...
	@property
	def kerningRTL(self) -> Incomplete: ...
	@kerningRTL.setter
	def kerningRTL(self, kerning: Incomplete) -> None: ...
	@property
	def kerningVertical(self) -> Incomplete: ...
	@kerningVertical.setter
	def kerningVertical(self, kerning: Incomplete) -> None: ...
	@property
	def selection(self) -> Incomplete: ...
	@property
	def note(self) -> Incomplete: ...
	@note.setter
	def note(self, value: Incomplete) -> None: ...
	@property
	def gridLength(self) -> Incomplete: ...
	def kerningForPair(self, fontMasterId: Incomplete, leftKey: Incomplete, rightKey: Incomplete, direction: Incomplete=...) -> Incomplete: ...
	def setKerningForPair(self, fontMasterId: Incomplete, leftKey: Incomplete, rightKey: Incomplete, value: Incomplete, direction: Incomplete=...) -> None: ...
	def removeKerningForPair(self, fontMasterId: Incomplete, leftKey: Incomplete, rightKey: Incomplete, direction: Incomplete=...) -> None: ...
	@property
	def manufacturer(self) -> Incomplete: ...
	@manufacturer.setter
	def manufacturer(self, value: Incomplete) -> None: ...
	@property
	def manufacturerURL(self) -> Incomplete: ...
	@manufacturerURL.setter
	def manufacturerURL(self, value: Incomplete) -> None: ...
	@property
	def copyright(self) -> Incomplete: ...
	@copyright.setter  # noqa: A003
	def copyright(self, value: Incomplete) -> None: ...
	@property
	def designer(self) -> Incomplete: ...
	@designer.setter
	def designer(self, value: Incomplete) -> None: ...
	@property
	def designerURL(self) -> Incomplete: ...
	@designerURL.setter
	def designerURL(self, value: Incomplete) -> None: ...
	@property
	def settings(self) -> Incomplete: ...
