from _typeshed import Incomplete
from collections.abc import Generator
from enum import IntEnum
from fontTools.pens.basePen import AbstractPen
from fontTools.pens.pointPen import AbstractPointPen
import os

__all__ = ['ARROW', 'BOTTOMGHOST', 'CAP', 'CIRCLE', 'CORNER', 'CURVE', 'GSCURVE', 'GSLINE', 'GSMOVE', 'GSOFFCURVE', 'GSSHARP', 'GSSMOOTH', 'LINE', 'LTR', 'LTRTTB', 'MINUS', 'MOVE', 'OFFCURVE', 'PLUS', 'QCURVE', 'RTL', 'RTLTTB', 'STEM', 'TAG', 'TEXT', 'TOPGHOST', 'TRIPLE', 'TTALIGN', 'TTANCHOR', 'TTDELTA', 'TTDIAGONAL', 'TTDONTROUND', 'TTINTERPOLATE', 'TTROUND', 'TTROUNDDOWN', 'TTROUNDUP', 'TTSTEM', 'WEIGHT_CODES', 'WIDTH_CODES', 'GSAlignmentZone', 'GSAnchor', 'GSAnnotation', 'GSBackgroundImage', 'GSBottomCenter', 'GSBottomLeft', 'GSBottomRight', 'GSCenterCenter', 'GSCenterLeft', 'GSCenterRight', 'GSClass', 'GSComponent', 'GSCustomParameter', 'GSFeature', 'GSFeaturePrefix', 'GSFont', 'GSFontMaster', 'GSGlyph', 'GSGuide', 'GSHint', 'GSInstance', 'GSLayer', 'GSNode', 'GSPath', 'GSSmartComponentAxis', 'GSTopCenter', 'GSTopLeft', 'GSTopRight', 'Glyphs', '__all__']

GSSHARP: int
GSSMOOTH: int
GSMOVE: str
GSLINE: str
GSCURVE: str
GSOFFCURVE: str
MOVE: str
LINE: str
CURVE: str
OFFCURVE: str
QCURVE: str

class InstanceType(IntEnum):
    SINGLE = 0
    VARIABLE = 1

TAG: int
TOPGHOST: int
STEM: int
BOTTOMGHOST: int
TTANCHOR: int
TTSTEM: int
TTALIGN: int
TTINTERPOLATE: int
TTDIAGONAL: int
TTDELTA: int
CORNER: int
CAP: int
TTDONTROUND: int
TTROUND: int
TTROUNDUP: int
TTROUNDDOWN: int
TRIPLE: int
TEXT: int
ARROW: int
CIRCLE: int
PLUS: int
MINUS: int
LTR: int
RTL: int
LTRTTB: int
RTLTTB: int
GSTopLeft: int
GSTopCenter: int
GSTopRight: int
GSCenterLeft: int
GSCenterCenter: int
GSCenterRight: int
GSBottomLeft: int
GSBottomCenter: int
GSBottomRight: int
WEIGHT_CODES: Incomplete
WIDTH_CODES: Incomplete

class OnlyInGlyphsAppError(NotImplementedError):
    def __init__(self) -> None: ...

class GSApplication:
    __slots__: Incomplete
    font: Incomplete
    fonts: Incomplete
    def __init__(self) -> None: ...
    def open(self, path): ...

Glyphs: Incomplete

class GSBase:
    """Represent the base class for all GS classes.

    Attributes
    ----------
        _defaultsForName (dict): Used to determine which values to serialize and which
            to imply by their absence.
    """

    _defaultsForName: Incomplete
    def __setitem__(self, key, value) -> None: ...
    @classmethod
    def _add_parsers(cls, specification) -> None: ...

class Proxy:
    __slots__: str
    _owner: Incomplete
    def __init__(self, owner) -> None: ...
    def __len__(self) -> int: ...
    def pop(self, i): ...
    def __iter__(self): ...
    def index(self, value): ...
    def __copy__(self): ...
    def __deepcopy__(self, memo): ...
    def setter(self, values) -> None: ...

class ListDictionaryProxy(Proxy):
    _name: Incomplete
    _class: Incomplete
    _items: Incomplete
    def __init__(self, owner, name, klass) -> None: ...
    def get(self, name, default=None): ...
    def append(self, item) -> None: ...
    def extend(self, items) -> None: ...
    def remove(self, item) -> None: ...
    def insert(self, index, item) -> None: ...
    def values(self): ...
    def setterMethod(self): ...
    def __getitem__(self, key): ...
    def __setitem__(self, name, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, item) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __setter__(self, items) -> None: ...
    def _get_by_name(self, name): ...

class LayersIterator:
    __slots__: Incomplete
    _layers: Incomplete
    def __init__(self, owner) -> None: ...
    def __iter__(self): ...
    def next(self): ...
    def __next__(self): ...
    @staticmethod
    def orderedLayers(glyph): ...

class FontFontMasterProxy(Proxy):
    """The list of masters. You can access it with the index or the master ID.
    Usage:
        Font.masters[index]
        Font.masters[id]
        for master in Font.masters:
        ...
    """

    def __getitem__(self, Key): ...
    def __setitem__(self, Key, FontMaster) -> None: ...
    def __delitem__(self, Key) -> None: ...
    def values(self): ...
    def append(self, FontMaster) -> None: ...
    def remove(self, FontMaster) -> None: ...
    def insert(self, Index, FontMaster) -> None: ...
    def extend(self, FontMasters) -> None: ...
    def setter(self, values) -> None: ...

class FontGlyphsProxy(Proxy):
    """The list of glyphs. You can access it with the index or the glyph name.
    Usage:
        Font.glyphs[index]
        Font.glyphs[name]
        for glyph in Font.glyphs:
        ...
    """

    def __getitem__(self, key): ...
    def __setitem__(self, key, glyph) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, item) -> bool: ...
    def _get_glyph_by_string(self, key): ...
    def values(self): ...
    def items(self): ...
    def append(self, glyph) -> None: ...
    def extend(self, objects) -> None: ...
    def __len__(self) -> int: ...
    def setter(self, values) -> None: ...

class FontClassesProxy(Proxy):
    VALUES_ATTR: str
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, item) -> bool: ...
    def append(self, item) -> None: ...
    def insert(self, key, item) -> None: ...
    def extend(self, items) -> None: ...
    def remove(self, item) -> None: ...
    def values(self): ...
    def setter(self, values) -> None: ...

class FontFeaturesProxy(FontClassesProxy):
    VALUES_ATTR: str

class FontFeaturePrefixesProxy(FontClassesProxy):
    VALUES_ATTR: str

class GlyphLayerProxy(Proxy):
    def __getitem__(self, key): ...
    def __setitem__(self, key, layer) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def keys(self): ...
    def values(self): ...
    def append(self, layer) -> None: ...
    def extend(self, layers) -> None: ...
    def remove(self, layer): ...
    def insert(self, index, layer) -> None: ...
    def setter(self, values) -> None: ...
    def plistArray(self): ...

class LayerAnchorsProxy(Proxy):
    def __getitem__(self, key): ...
    def __setitem__(self, key, anchor) -> None: ...
    def __delitem__(self, key) -> None: ...
    def values(self): ...
    def append(self, anchor) -> None: ...
    def extend(self, anchors) -> None: ...
    def remove(self, anchor): ...
    def insert(self, index, anchor) -> None: ...
    def __len__(self) -> int: ...
    def setter(self, anchors) -> None: ...

class IndexedObjectsProxy(Proxy):
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def values(self): ...
    def append(self, value) -> None: ...
    def extend(self, values) -> None: ...
    def remove(self, value) -> None: ...
    def insert(self, index, value) -> None: ...
    def __len__(self) -> int: ...
    def setter(self, values) -> None: ...

class LayerShapesProxy(IndexedObjectsProxy):
    _objects_name: str
    _filter: Incomplete
    def __init__(self, owner) -> None: ...
    def append(self, value) -> None: ...
    def extend(self, values) -> None: ...
    def remove(self, value) -> None: ...
    def insert(self, index, value) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def setter(self, values): ...
    def values(self): ...

class LayerHintsProxy(IndexedObjectsProxy):
    _objects_name: str
    def __init__(self, owner) -> None: ...

class LayerAnnotationProxy(IndexedObjectsProxy):
    _objects_name: str
    def __init__(self, owner) -> None: ...

class LayerGuideLinesProxy(IndexedObjectsProxy):
    _objects_name: str
    def __init__(self, owner) -> None: ...

class PathNodesProxy(IndexedObjectsProxy):
    _objects_name: str
    def __init__(self, owner) -> None: ...

class CustomParametersProxy(ListDictionaryProxy):
    def __init__(self, owner) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __contains__(self, item) -> bool: ...
    def __setter__(self, items) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def _get_by_name(self, name, skip_disabled: bool = True): ...
    def _should_add_axes(self): ...

class PropertiesProxy(ListDictionaryProxy):
    def __init__(self, owner) -> None: ...

class UserDataProxy(Proxy):
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, item) -> bool: ...
    def __iter__(self): ...
    def values(self): ...
    def keys(self): ...
    def items(self): ...
    def get(self, key): ...
    def setter(self, values) -> None: ...

class GSAxis(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    name: Incomplete
    axisTag: Incomplete
    axisId: Incomplete
    hidden: Incomplete
    def __init__(self, name: str = '', tag: str = '', hidden: bool = False) -> None: ...
    def __eq__(self, other): ...

class GSCustomParameter(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    _CUSTOM_INT_PARAMS: Incomplete
    _CUSTOM_FLOAT_PARAMS: Incomplete
    _CUSTOM_BOOL_PARAMS: Incomplete
    _CUSTOM_INTLIST_PARAMS: Incomplete
    _CUSTOM_DICT_PARAMS: Incomplete
    name: Incomplete
    value: Incomplete
    disabled: Incomplete
    def __init__(self, name: str = 'New Value', value: str = 'New Parameter', disabled: bool = False) -> None: ...
    def plistValue(self, format_version: int = 2): ...
    def getValue(self): ...
    _value: Incomplete
    def setValue(self, value) -> None:
        """Cast some known data in custom parameters."""

class GSMetric(GSBase):
    name: Incomplete
    type: Incomplete
    id: str
    filter: str
    horizontal: bool
    def __init__(self, name: str = '', type: str = '') -> None: ...
    def _serialize_to_plist(self, writer) -> None: ...

class GSMetricValue(GSBase):
    position: Incomplete
    overshoot: Incomplete
    name: str
    filter: str
    metric: str
    def __init__(self, position: int = 0, overshoot: int = 0) -> None: ...
    def _serialize_to_plist(self, writer) -> None: ...

class GSAlignmentZone(GSBase):
    position: Incomplete
    size: Incomplete
    def __init__(self, pos: int = 0, size: int = 20) -> None: ...
    def read(self, src): ...
    def __lt__(self, other): ...
    def __eq__(self, other): ...
    def plistValue(self, format_version: int = 2): ...

class GSGuide(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    _parent: Incomplete
    _defaultsForName: Incomplete
    alignment: str
    angle: int
    filter: str
    locked: bool
    name: str
    position: Incomplete
    showMeasurement: bool
    lockAngle: bool
    def __init__(self) -> None: ...
    @property
    def parent(self): ...

class GSFontMaster(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    _defaultsForName: Incomplete
    _axis_defaults: Incomplete
    _alignmentZones: Incomplete
    def _parse_alignmentZones_dict(self, parser, text) -> None:
        """
        For glyphs file format 2 this parses the aligmentZone parameter
        directly. For file format 3 alignmentZones will be infered from
        metricValues.
        """
    customParameters: Incomplete
    _name: Incomplete
    _userData: Incomplete
    _horizontalStems: Incomplete
    _verticalStems: Incomplete
    axes: Incomplete
    metrics: Incomplete
    customName: str
    font: Incomplete
    guides: Incomplete
    iconName: str
    id: Incomplete
    numbers: Incomplete
    stems: Incomplete
    visible: bool
    weight: Incomplete
    width: Incomplete
    def __init__(self) -> None: ...
    @property
    def metricsSource(self):
        """Returns the source master to be used for glyph and kerning metrics.

        If linked metrics parameters are being used, the master is returned here,
        otherwise None.
        """
    @property
    def name(self): ...
    @name.setter
    def name(self, name) -> None:
        """This function will take the given name and split it into components
        weight, width, customName, and possibly the full name.
        This is what Glyphs 1113 seems to be doing, approximately.
        """
    def set_all_name_components(self, name, weight, width, custom_name) -> None:
        """This function ensures that after being called, the master.name,
        master.weight, master.width, and master.customName match the given
        values.
        """
    def _joinName(self): ...
    def _splitName(self, value): ...
    userData: Incomplete
    def _get_metric(self, metricname): ...
    def _set_metric(self, metricname, value) -> None: ...
    @property
    def alignmentZones(self): ...
    @alignmentZones.setter
    def alignmentZones(self, entries) -> None: ...
    @property
    def horizontalStems(self): ...
    @horizontalStems.setter
    def horizontalStems(self, value) -> None: ...
    @property
    def verticalStems(self): ...
    @verticalStems.setter
    def verticalStems(self, value) -> None: ...
    @property
    def ascender(self): ...
    @ascender.setter
    def ascender(self, value) -> None: ...
    @property
    def xHeight(self): ...
    @xHeight.setter
    def xHeight(self, value) -> None: ...
    @property
    def capHeight(self): ...
    @capHeight.setter
    def capHeight(self, value) -> None: ...
    @property
    def descender(self): ...
    @descender.setter
    def descender(self, value) -> None: ...
    @property
    def italicAngle(self): ...
    @italicAngle.setter
    def italicAngle(self, value) -> None: ...
    def _get_axis_value(self, index): ...
    def _set_axis_value(self, index, value) -> None: ...
    @property
    def weightValue(self): ...
    @weightValue.setter
    def weightValue(self, value): ...
    @property
    def widthValue(self): ...
    @widthValue.setter
    def widthValue(self, value): ...
    @property
    def customValue(self): ...
    @customValue.setter
    def customValue(self, value): ...
    @property
    def customValue1(self): ...
    @customValue1.setter
    def customValue1(self, value): ...
    @property
    def customValue2(self): ...
    @customValue2.setter
    def customValue2(self, value): ...
    @property
    def customValue3(self): ...
    @customValue3.setter
    def customValue3(self, value): ...

class GSNode(GSBase):
    _PLIST_VALUE_RE: Incomplete
    __slots__: Incomplete
    _position: Incomplete
    _userData: Incomplete
    smooth: Incomplete
    type: Incomplete
    def __init__(self, position=(0, 0), type=..., smooth: bool = False, name=None, nodetype=None) -> None: ...
    def clone(self):
        """Clones the node (does not clone attributes)"""
    userData: Incomplete
    @property
    def position(self): ...
    @position.setter
    def position(self, value) -> None: ...
    @property
    def parent(self): ...
    def plistValue(self, format_version: int = 2): ...
    @classmethod
    def read(cls, line):
        """Parse a Glyphs node string into a GSNode.

        The format of a Glyphs node string (`line`) is:

            "X Y (LINE|CURVE|QCURVE|OFFCURVE)"
            "X Y (LINE|CURVE|QCURVE|OFFCURVE) SMOOTH"
            "X Y (LINE|CURVE|QCURVE|OFFCURVE) SMOOTH {dictionary}"
            "X Y (LINE|CURVE|QCURVE|OFFCURVE) {dictionary}"

        X and Y can be integers or floats, positive or negative.

        WARNING: This method is HOT. It is called for every single node and can
        account for a significant portion of the file parsing time.
        """
    @classmethod
    def read_v3(cls, lst): ...
    @property
    def name(self): ...
    @name.setter
    def name(self, value) -> None: ...
    @property
    def index(self): ...
    @property
    def nextNode(self): ...
    @property
    def prevNode(self): ...
    def makeNodeFirst(self) -> None: ...
    def toggleConnection(self) -> None: ...
    @property
    def connection(self) -> None: ...
    @property
    def selected(self) -> None: ...
    @staticmethod
    def _encode_dict_as_string(value):
        """Takes the PLIST string of a dict, and returns the same string
        encoded such that it can be included in the string representation
        of a GSNode.
        """
    _ESCAPED_CHAR_RE: Incomplete
    @staticmethod
    def _unescape_char(m): ...
    @classmethod
    def _decode_dict_as_string(cls, value):
        """Reverse function of _encode_string_as_dict"""
    def _indices(self):
        """Find the path_index and node_index that identify the given node."""

class GSPath(GSBase):
    _defaultsForName: Incomplete
    _parent: Incomplete
    def _serialize_to_plist(self, writer) -> None: ...
    def _parse_nodes_dict(self, parser, d) -> None: ...
    closed: Incomplete
    _nodes: Incomplete
    attributes: Incomplete
    def __init__(self) -> None: ...
    def clone(self):
        """Clones the path (Does not clone attributes)"""
    @property
    def parent(self): ...
    nodes: Incomplete
    _segments: Incomplete
    _segmentLength: int
    @property
    def segments(self): ...
    @segments.setter
    def segments(self, value) -> None: ...
    def setSegments(self, segments) -> None: ...
    @property
    def bounds(self): ...
    @property
    def direction(self): ...
    @property
    def selected(self) -> None: ...
    @property
    def bezierPath(self) -> None: ...
    def reverse(self) -> None: ...
    def addNodesAtExtremes(self) -> None: ...
    def applyTransform(self, transformationMatrix) -> None: ...
    def draw(self, pen: AbstractPen) -> None:
        """Draws contour with the given pen."""
    def drawPoints(self, pointPen: AbstractPointPen) -> None:
        """Draws points of contour with the given point pen."""

class segment(list):
    nodes: Incomplete
    def appendNode(self, node) -> None: ...
    @property
    def nextSegment(self): ...
    @property
    def prevSegment(self): ...
    def bbox(self): ...
    def bezierMinMax(self, x0, y0, x1, y1, x2, y2, x3, y3): ...

class GSComponent(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    _defaultsForName: Incomplete
    _parent: Incomplete
    alignment: int
    anchor: str
    locked: bool
    name: Incomplete
    smartComponentValues: Incomplete
    transform: Incomplete
    def __init__(self, glyph: str = '', offset=(0, 0), scale=(1, 1), transform=None) -> None: ...
    def clone(self): ...
    @property
    def parent(self): ...
    @property
    def position(self): ...
    @position.setter
    def position(self, value) -> None: ...
    @property
    def scale(self): ...
    _sX: Incomplete
    _sY: Incomplete
    @scale.setter
    def scale(self, value) -> None: ...
    @property
    def rotation(self): ...
    _R: Incomplete
    @rotation.setter
    def rotation(self, value) -> None: ...
    def updateAffineTransform(self) -> None: ...
    @property
    def componentName(self): ...
    @componentName.setter
    def componentName(self, value) -> None: ...
    @property
    def component(self): ...
    @property
    def layer(self): ...
    def applyTransformation(self, x, y): ...
    @property
    def bounds(self): ...
    def draw(self, pen: AbstractPen) -> None:
        """Draws component with given pen."""
    def drawPoints(self, pointPen: AbstractPointPen) -> None:
        """Draws points of component with given point pen."""

class GSSmartComponentAxis(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    _defaultsForName: Incomplete
    bottomName: str
    bottomValue: Incomplete
    name: str
    topName: str
    topValue: Incomplete
    def __init__(self) -> None: ...

class GSAnchor(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    _parent: Incomplete
    _defaultsForName: Incomplete
    name: Incomplete
    position: Incomplete
    _userData: Incomplete
    userData: Incomplete
    def __init__(self, name=None, position=None, userData=None) -> None: ...
    @property
    def parent(self): ...

class GSHint(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    _defaultsForName: Incomplete
    horizontal: bool
    name: str
    options: int
    place: Incomplete
    scale: Incomplete
    settings: Incomplete
    stem: Incomplete
    type: str
    _target: Incomplete
    _targetNode: Incomplete
    def __init__(self) -> None: ...
    def _origin_pos(self): ...
    def _width_pos(self): ...
    @property
    def parent(self): ...
    @property
    def originNode(self): ...
    _originNode: Incomplete
    _origin: Incomplete
    @originNode.setter
    def originNode(self, node) -> None: ...
    @property
    def origin(self): ...
    @origin.setter
    def origin(self, origin) -> None: ...
    @property
    def targetNode(self): ...
    @targetNode.setter
    def targetNode(self, node) -> None: ...
    @property
    def target(self): ...
    @target.setter
    def target(self, target) -> None: ...
    @property
    def otherNode1(self): ...
    _otherNode1: Incomplete
    _other1: Incomplete
    @otherNode1.setter
    def otherNode1(self, node) -> None: ...
    @property
    def other1(self): ...
    @other1.setter
    def other1(self, other1) -> None: ...
    @property
    def otherNode2(self): ...
    _otherNode2: Incomplete
    _other2: Incomplete
    @otherNode2.setter
    def otherNode2(self, node) -> None: ...
    @property
    def other2(self): ...
    @other2.setter
    def other2(self, other2) -> None: ...

class GSFeature(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    automatic: bool
    code: Incomplete
    disabled: bool
    name: Incomplete
    notes: str
    labels: Incomplete
    def __init__(self, name: str = 'xxxx', code: str = '') -> None: ...
    def getCode(self): ...
    _code: Incomplete
    def setCode(self, code) -> None: ...
    @property
    def parent(self): ...

class GSClass(GSFeature):
    def _serialize_to_plist(self, writer) -> None: ...

class GSFeaturePrefix(GSClass): ...

class GSAnnotation(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    _defaultsForName: Incomplete
    _parent: Incomplete
    angle: Incomplete
    position: Incomplete
    text: Incomplete
    type: Incomplete
    width: Incomplete
    def __init__(self) -> None: ...
    @property
    def parent(self): ...

class GSFontInfoValue(GSBase):
    key: Incomplete
    _value: Incomplete
    _localized_values: Incomplete
    def __init__(self, key: str = '', value: str = '') -> None: ...
    def _parse_values_dict(self, parser, values) -> None: ...
    def _serialize_to_plist(self, writer) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, value) -> None: ...
    @property
    def value(self): ...
    @value.setter
    def value(self, value) -> None: ...

class GSInstance(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    _axis_defaults: Incomplete
    _defaultsForName: Incomplete
    axes: Incomplete
    customParameters: Incomplete
    active: Incomplete
    custom: Incomplete
    instanceInterpolations: Incomplete
    isBold: bool
    isItalic: bool
    linkStyle: str
    manualInterpolation: bool
    name: str
    properties: Incomplete
    visible: bool
    weight: Incomplete
    width: Incomplete
    type: Incomplete
    def __init__(self) -> None: ...
    @property
    def exports(self):
        """Deprecated alias for `active`, which is in the documentation."""
    @exports.setter
    def exports(self, value) -> None: ...
    @property
    def familyName(self): ...
    @familyName.setter
    def familyName(self, value) -> None: ...
    @property
    def preferredFamily(self): ...
    @preferredFamily.setter
    def preferredFamily(self, value) -> None: ...
    @property
    def preferredFamilyName(self): ...
    @property
    def preferredSubfamilyName(self): ...
    @preferredSubfamilyName.setter
    def preferredSubfamilyName(self, value) -> None: ...
    @property
    def windowsFamily(self): ...
    @windowsFamily.setter
    def windowsFamily(self, value) -> None: ...
    @property
    def windowsStyle(self): ...
    @property
    def windowsLinkedToStyle(self): ...
    @property
    def fontName(self): ...
    @fontName.setter
    def fontName(self, value) -> None: ...
    @property
    def fullName(self): ...
    @fullName.setter
    def fullName(self, value) -> None: ...
    def _get_axis_value(self, index): ...
    def _set_axis_value(self, index, value) -> None: ...
    @property
    def weightValue(self): ...
    @weightValue.setter
    def weightValue(self, value): ...
    @property
    def widthValue(self): ...
    @widthValue.setter
    def widthValue(self, value): ...
    @property
    def customValue(self): ...
    @customValue.setter
    def customValue(self, value): ...
    @property
    def customValue1(self): ...
    @customValue1.setter
    def customValue1(self, value): ...
    @property
    def customValue2(self): ...
    @customValue2.setter
    def customValue2(self, value): ...
    @property
    def customValue3(self): ...
    @customValue3.setter
    def customValue3(self, value): ...

class GSBackgroundImage(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    _defaultsForName: Incomplete
    _R: float
    _sX: float
    _sY: float
    crop: Incomplete
    imagePath: Incomplete
    locked: bool
    transform: Incomplete
    def __init__(self, path=None) -> None: ...
    @property
    def path(self): ...
    @path.setter
    def path(self, value) -> None: ...
    @property
    def position(self): ...
    @position.setter
    def position(self, value) -> None: ...
    @property
    def scale(self): ...
    @scale.setter
    def scale(self, value) -> None: ...
    @property
    def rotation(self): ...
    @rotation.setter
    def rotation(self, value) -> None: ...
    @property
    def alpha(self): ...
    _alpha: Incomplete
    @alpha.setter
    def alpha(self, value) -> None: ...
    def updateAffineTransform(self) -> None: ...

class LayerPathsProxy(LayerShapesProxy):
    _filter = GSPath

class LayerComponentsProxy(LayerShapesProxy):
    _filter = GSComponent

class GSLayer(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    def _parse_shapes_dict(self, parser, shapes) -> None: ...
    _defaultsForName: Incomplete
    _background: Incomplete
    def _parse_background_dict(self, parser, value) -> None: ...
    _anchors: Incomplete
    _annotations: Incomplete
    _foreground: Incomplete
    _guides: Incomplete
    _hints: Incomplete
    _layerId: str
    _name: str
    _selection: Incomplete
    _shapes: Incomplete
    _userData: Incomplete
    attributes: Incomplete
    partSelection: Incomplete
    associatedMasterId: str
    backgroundImage: Incomplete
    color: Incomplete
    metricLeft: Incomplete
    parent: Incomplete
    metricRight: Incomplete
    vertOrigin: Incomplete
    vertWidth: Incomplete
    visible: bool
    width: Incomplete
    metricWidth: Incomplete
    def __init__(self) -> None: ...
    def __lt__(self, other): ...
    @property
    def layerId(self): ...
    @layerId.setter
    def layerId(self, value) -> None: ...
    @property
    def master(self): ...
    @property
    def _is_master_layer(self): ...
    @property
    def name(self): ...
    @name.setter
    def name(self, value) -> None: ...
    anchors: Incomplete
    hints: Incomplete
    paths: Incomplete
    components: Incomplete
    shapes: Incomplete
    guides: Incomplete
    annotations: Incomplete
    userData: Incomplete
    @property
    def smartComponentPoleMapping(self): ...
    @smartComponentPoleMapping.setter
    def smartComponentPoleMapping(self, value) -> None: ...
    @property
    def bounds(self): ...
    def _find_node_by_indices(self, point):
        """ "Find the GSNode that is refered to by the given indices.

        See GSNode::_indices()
        """
    @property
    def background(self):
        """Only a getter on purpose. See the tests."""
    @property
    def hasBackground(self): ...
    @property
    def foreground(self) -> None:
        """Forbidden, and also forbidden to set it."""
    def getPen(self) -> AbstractPen:
        """Returns a pen for others to draw into self."""
    def getPointPen(self) -> AbstractPointPen:
        """Returns a point pen for others to draw points into self."""
    def draw(self, pen: AbstractPen) -> None:
        """Draws glyph with the given pen."""
    def drawPoints(self, pointPen: AbstractPointPen) -> None:
        """Draws points of glyph with the given point pen."""
    @property
    def rightMetricsKey(self): ...
    @property
    def leftMetricsKey(self): ...
    @property
    def widthMetricsKey(self): ...
    @rightMetricsKey.setter
    def rightMetricsKey(self, value) -> None: ...
    @leftMetricsKey.setter
    def leftMetricsKey(self, value) -> None: ...
    @widthMetricsKey.setter
    def widthMetricsKey(self, value) -> None: ...
    BRACKET_LAYER_RE: Incomplete
    def _is_bracket_layer(self): ...
    def _bracket_axis_rules(self) -> Generator[Incomplete]: ...
    def _bracket_info(self, axes): ...
    def _is_brace_layer(self): ...
    def _brace_coordinates(self): ...
    def _brace_layer_name(self): ...
    COLOR_PALETTE_LAYER_RE: Incomplete
    def _is_color_palette_layer(self): ...
    def _color_palette_index(self): ...

class GSBackgroundLayer(GSLayer):
    @property
    def background(self) -> None: ...
    @property
    def foreground(self): ...
    @property
    def width(self): ...
    @width.setter
    def width(self, whatever) -> None: ...

class GSGlyph(GSBase):
    def _serialize_to_plist(self, writer) -> None: ...
    _defaultsForName: Incomplete
    def _parse_unicode_dict(self, parser, value) -> None: ...
    def _parse_layers_dict(self, parser, value): ...
    _layers: Incomplete
    _unicodes: Incomplete
    bottomKerningGroup: str
    bottomMetricsKey: str
    category: Incomplete
    case: Incomplete
    color: Incomplete
    export: Incomplete
    lastChange: Incomplete
    leftKerningGroup: Incomplete
    leftKerningKey: str
    metricLeft: Incomplete
    name: Incomplete
    note: Incomplete
    parent: Incomplete
    partsSettings: Incomplete
    production: str
    rightKerningGroup: Incomplete
    rightKerningKey: str
    metricRight: Incomplete
    script: Incomplete
    selected: bool
    subCategory: Incomplete
    tags: Incomplete
    topKerningGroup: str
    topMetricsKey: str
    userData: Incomplete
    metricVertWidth: Incomplete
    metricWidth: Incomplete
    def __init__(self, name=None) -> None: ...
    layers: Incomplete
    def _setupLayer(self, layer, key) -> None: ...
    def removeLayerForKey_(self, key) -> None: ...
    @property
    def string(self): ...
    @property
    def glyphname(self): ...
    @glyphname.setter
    def glyphname(self, value) -> None: ...
    @property
    def smartComponentAxes(self): ...
    @smartComponentAxes.setter
    def smartComponentAxes(self, value) -> None: ...
    @property
    def id(self):
        """An unique identifier for each glyph"""
    @property
    def unicode(self): ...
    @unicode.setter
    def unicode(self, unicode) -> None: ...
    @property
    def unicodes(self): ...
    @unicodes.setter
    def unicodes(self, unicodes) -> None: ...
    @property
    def rightMetricsKey(self): ...
    @rightMetricsKey.setter
    def rightMetricsKey(self, value) -> None: ...
    @property
    def leftMetricsKey(self): ...
    @leftMetricsKey.setter
    def leftMetricsKey(self, value) -> None: ...
    @property
    def widthMetricsKey(self): ...
    @widthMetricsKey.setter
    def widthMetricsKey(self, value) -> None: ...
    @property
    def vertWidthMetricsKey(self): ...
    @vertWidthMetricsKey.setter
    def vertWidthMetricsKey(self, value) -> None: ...
    def colorIndex(self): ...
    def countOfUnicodes(self): ...
    def countOfLayers(self): ...
    def hasAnnotations(self): ...
    def hasComponents(self): ...
    def hasCorners(self): ...
    def hasSpecialLayers(self): ...
    def isAnyColorGlyph(self): ...
    def isFullColorGlyph(self): ...
    def isColorPaletteGlyph(self): ...
    def isSVGColorGlyph(self): ...
    def isAppleColorGlyph(self): ...

class GSFont(GSBase):
    _defaultsForName: Incomplete
    def _serialize_to_plist(self, writer) -> None: ...
    _defaultMetrics: Incomplete
    _defaultAxes: Incomplete
    def _parse_glyphs_dict(self, parser, value): ...
    disablesAutomaticAlignment: Incomplete
    disablesNiceNames: Incomplete
    grid: Incomplete
    gridSubDivisions: Incomplete
    keepAlternatesTogether: Incomplete
    keyboardIncrement: Incomplete
    keyboardIncrementBig: Incomplete
    keyboardIncrementHuge: Incomplete
    def _parse_settings_dict(self, parser, settings) -> None: ...
    format_version: Incomplete
    def _parse___formatVersion_dict(self, parser, val) -> None: ...
    DisplayStrings: str
    _glyphs: Incomplete
    _instances: Incomplete
    _masters: Incomplete
    axes: Incomplete
    _userData: Incomplete
    _versionMinor: int
    appVersion: str
    classes: Incomplete
    features: Incomplete
    featurePrefixes: Incomplete
    customParameters: Incomplete
    date: Incomplete
    familyName: str
    filepath: Incomplete
    _kerningLTR: Incomplete
    _kerningRTL: Incomplete
    _kerningVertical: Incomplete
    metrics: Incomplete
    numbers: Incomplete
    properties: Incomplete
    stems: Incomplete
    upm: Incomplete
    versionMajor: int
    _note: str
    def __init__(self, path: str | bytes | os.PathLike[str] | os.PathLike[bytes] | None = None) -> None: ...
    def save(self, path: str | bytes | os.PathLike[str] | os.PathLike[bytes] | None = None) -> None: ...
    def getVersionMinor(self): ...
    def setVersionMinor(self, value) -> None:
        """Ensure that the minor version number is between 0 and 999."""
    versionMinor: Incomplete
    glyphs: Incomplete
    def _setupGlyph(self, glyph) -> None: ...
    masters: Incomplete
    def masterForId(self, key): ...
    @property
    def instances(self): ...
    @instances.setter
    def instances(self, value) -> None: ...
    userData: Incomplete
    @property
    def kerning(self): ...
    @kerning.setter
    def kerning(self, kerning) -> None: ...
    @property
    def kerningLTR(self): ...
    @kerningLTR.setter
    def kerningLTR(self, kerning) -> None: ...
    @property
    def kerningRTL(self): ...
    @kerningRTL.setter
    def kerningRTL(self, kerning) -> None: ...
    @property
    def kerningVertical(self): ...
    @kerningVertical.setter
    def kerningVertical(self, kerning) -> None: ...
    @property
    def selection(self): ...
    @property
    def note(self): ...
    @note.setter
    def note(self, value) -> None: ...
    @property
    def gridLength(self): ...
    EMPTY_KERNING_VALUE: Incomplete
    def kerningForPair(self, fontMasterId, leftKey, rightKey, direction=...): ...
    def setKerningForPair(self, fontMasterId, leftKey, rightKey, value, direction=...) -> None: ...
    def removeKerningForPair(self, fontMasterId, leftKey, rightKey, direction=...) -> None: ...
    @property
    def manufacturer(self): ...
    @manufacturer.setter
    def manufacturer(self, value) -> None: ...
    @property
    def manufacturerURL(self): ...
    @manufacturerURL.setter
    def manufacturerURL(self, value) -> None: ...
    @property
    def copyright(self): ...
    @copyright.setter
    def copyright(self, value) -> None: ...
    @property
    def designer(self): ...
    @designer.setter
    def designer(self, value) -> None: ...
    @property
    def designerURL(self): ...
    @designerURL.setter
    def designerURL(self, value) -> None: ...
    def _get_custom_parameter_from_axes(self): ...
    def _set_axes_from_custom_parameter(self, value) -> None: ...
    @property
    def settings(self): ...
