import collections
import enum
import glyphsLib.types
import os
import re
from _typeshed import Incomplete
from fontTools.pens.basePen import AbstractPen
from fontTools.pens.pointPen import AbstractPointPen
from typing import Callable, ClassVar

__all__ = ['Glyphs', 'GSFont', 'GSFontMaster', 'GSAlignmentZone', 'GSInstance', 'GSCustomParameter', 'GSClass', 'GSFeaturePrefix', 'GSFeature', 'GSGlyph', 'GSLayer', 'GSAnchor', 'GSComponent', 'GSSmartComponentAxis', 'GSPath', 'GSNode', 'GSGuide', 'GSAnnotation', 'GSHint', 'GSBackgroundImage', '__all__', 'MOVE', 'LINE', 'CURVE', 'QCURVE', 'OFFCURVE', 'GSMOVE', 'GSLINE', 'GSCURVE', 'GSOFFCURVE', 'GSSHARP', 'GSSMOOTH', 'TAG', 'TOPGHOST', 'STEM', 'BOTTOMGHOST', 'TTANCHOR', 'TTSTEM', 'TTALIGN', 'TTINTERPOLATE', 'TTDIAGONAL', 'TTDELTA', 'CORNER', 'CAP', 'TTDONTROUND', 'TTROUND', 'TTROUNDUP', 'TTROUNDDOWN', 'TRIPLE', 'TEXT', 'ARROW', 'CIRCLE', 'PLUS', 'MINUS', 'LTR', 'RTL', 'LTRTTB', 'RTLTTB', 'GSTopLeft', 'GSTopCenter', 'GSTopRight', 'GSCenterLeft', 'GSCenterCenter', 'GSCenterRight', 'GSBottomLeft', 'GSBottomCenter', 'GSBottomRight', 'WEIGHT_CODES', 'WIDTH_CODES']

GSSHARP: int
GSSMOOTH: int
GSMOVE: str
GSLINE: str
GSCURVE: str
GSOFFCURVE: str
MOVE: str
LINE: str
CURVE: str
OFFCURVE: str
QCURVE: str

class InstanceType(enum.IntEnum):
    _new_member_: ClassVar[builtin_function_or_method] = ...
    _use_args_: ClassVar[bool] = ...
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _value2member_map_: ClassVar[dict] = ...
    _hashable_values_: ClassVar[list] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value_repr_: ClassVar[wrapper_descriptor] = ...
    SINGLE: ClassVar[InstanceType] = ...
    VARIABLE: ClassVar[InstanceType] = ...
    __format__: ClassVar[method_descriptor] = ...
    @staticmethod
    def _generate_next_value_(name, start, count, last_values):
        """
        Generate the next value when not given.

        name: the name of the member
        start: the initial start value or None
        count: the number of existing members
        last_values: the list of values assigned
        """
    @classmethod
    def __init__(cls, value) -> None: ...
TAG: int
TOPGHOST: int
STEM: int
BOTTOMGHOST: int
TTANCHOR: int
TTSTEM: int
TTALIGN: int
TTINTERPOLATE: int
TTDIAGONAL: int
TTDELTA: int
CORNER: int
CAP: int
TTDONTROUND: int
TTROUND: int
TTROUNDUP: int
TTROUNDDOWN: int
TRIPLE: int
TEXT: int
ARROW: int
CIRCLE: int
PLUS: int
MINUS: int
LTR: int
RTL: int
LTRTTB: int
RTLTTB: int
GSTopLeft: int
GSTopCenter: int
GSTopRight: int
GSCenterLeft: int
GSCenterCenter: int
GSCenterRight: int
GSBottomLeft: int
GSBottomCenter: int
GSBottomRight: int
WEIGHT_CODES: dict
WIDTH_CODES: dict

class OnlyInGlyphsAppError(NotImplementedError):
    def __init__(self) -> None: ...

class GSApplication:
    font: Incomplete
    fonts: Incomplete
    def __init__(self) -> None: ...
    def open(self, path): ...
Glyphs: GSApplication

class GSBase:
    """Represent the base class for all GS classes.

    Attributes:
        _defaultsForName (dict): Used to determine which values to serialize and which
            to imply by their absence.
    """
    _defaultsForName: ClassVar[dict] = ...
    def __setitem__(self, key, value) -> None: ...
    @classmethod
    def _add_parsers(cls, specification): ...

class Proxy:
    _owner: Incomplete
    def __init__(self, owner) -> None: ...
    def __len__(self) -> int: ...
    def pop(self, i): ...
    def __iter__(self): ...
    def index(self, value): ...
    def __copy__(self): ...
    def __deepcopy__(self, memo): ...
    def setter(self, values): ...

class ListDictionaryProxy(Proxy):
    def __init__(self, owner, name, klass) -> None: ...
    def get(self, name, default: Incomplete | None = ...): ...
    def append(self, item): ...
    def extend(self, items): ...
    def remove(self, item): ...
    def insert(self, index, item): ...
    def values(self): ...
    def setterMethod(self): ...
    def __getitem__(self, key): ...
    def __setitem__(self, name, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, item) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __setter__(self, items): ...
    def _get_by_name(self, name): ...

class LayersIterator:
    _layers: Incomplete
    def __init__(self, owner) -> None: ...
    def __iter__(self): ...
    def next(self): ...
    def __next__(self): ...
    @staticmethod
    def orderedLayers(glyph): ...

class FontFontMasterProxy(Proxy):
    """The list of masters. You can access it with the index or the master ID.
    Usage:
        Font.masters[index]
        Font.masters[id]
        for master in Font.masters:
        ...
    """
    def __getitem__(self, Key): ...
    def __setitem__(self, Key, FontMaster) -> None: ...
    def __delitem__(self, Key) -> None: ...
    def values(self): ...
    def append(self, FontMaster): ...
    def remove(self, FontMaster): ...
    def insert(self, Index, FontMaster): ...
    def extend(self, FontMasters): ...
    def setter(self, values): ...

class FontGlyphsProxy(Proxy):
    """The list of glyphs. You can access it with the index or the glyph name.
    Usage:
        Font.glyphs[index]
        Font.glyphs[name]
        for glyph in Font.glyphs:
        ...
    """
    def __getitem__(self, key): ...
    def __setitem__(self, key, glyph) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, item) -> bool: ...
    def _get_glyph_by_string(self, key): ...
    def values(self): ...
    def items(self): ...
    def append(self, glyph): ...
    def extend(self, objects): ...
    def __len__(self) -> int: ...
    def setter(self, values): ...

class FontClassesProxy(Proxy):
    VALUES_ATTR: ClassVar[str] = ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, item) -> bool: ...
    def append(self, item): ...
    def insert(self, key, item): ...
    def extend(self, items): ...
    def remove(self, item): ...
    def values(self): ...
    def setter(self, values): ...

class FontFeaturesProxy(FontClassesProxy):
    VALUES_ATTR: ClassVar[str] = ...

class FontFeaturePrefixesProxy(FontClassesProxy):
    VALUES_ATTR: ClassVar[str] = ...

class GlyphLayerProxy(Proxy):
    def __getitem__(self, key): ...
    def __setitem__(self, key, layer) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def keys(self): ...
    def values(self): ...
    def append(self, layer): ...
    def extend(self, layers): ...
    def remove(self, layer): ...
    def insert(self, index, layer): ...
    def setter(self, values): ...
    def plistArray(self): ...

class LayerAnchorsProxy(Proxy):
    def __getitem__(self, key): ...
    def __setitem__(self, key, anchor) -> None: ...
    def __delitem__(self, key) -> None: ...
    def values(self): ...
    def append(self, anchor): ...
    def extend(self, anchors): ...
    def remove(self, anchor): ...
    def insert(self, index, anchor): ...
    def __len__(self) -> int: ...
    def setter(self, anchors): ...

class IndexedObjectsProxy(Proxy):
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def values(self): ...
    def append(self, value): ...
    def extend(self, values): ...
    def remove(self, value): ...
    def insert(self, index, value): ...
    def __len__(self) -> int: ...
    def setter(self, values): ...

class LayerShapesProxy(IndexedObjectsProxy):
    _objects_name: ClassVar[str] = ...
    _filter: ClassVar[None] = ...
    def __init__(self, owner) -> None: ...
    def append(self, value): ...
    def extend(self, values): ...
    def remove(self, value): ...
    def insert(self, index, value): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def setter(self, values): ...
    def values(self): ...

class LayerHintsProxy(IndexedObjectsProxy):
    _objects_name: ClassVar[str] = ...
    def __init__(self, owner) -> None: ...

class LayerAnnotationProxy(IndexedObjectsProxy):
    _objects_name: ClassVar[str] = ...
    def __init__(self, owner) -> None: ...

class LayerGuideLinesProxy(IndexedObjectsProxy):
    _objects_name: ClassVar[str] = ...
    def __init__(self, owner) -> None: ...

class PathNodesProxy(IndexedObjectsProxy):
    _objects_name: ClassVar[str] = ...
    def __init__(self, owner) -> None: ...

class CustomParametersProxy(ListDictionaryProxy):
    def __init__(self, owner) -> None: ...
    def __setitem__(self, key, value) -> None: ...
    def __contains__(self, item) -> bool: ...
    def __setter__(self, items): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def _get_by_name(self, name, skip_disabled: bool = ...): ...
    def _should_add_axes(self): ...

class PropertiesProxy(ListDictionaryProxy):
    def __init__(self, owner) -> None: ...

class UserDataProxy(Proxy):
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, item) -> bool: ...
    def __iter__(self): ...
    def values(self): ...
    def keys(self): ...
    def items(self): ...
    def get(self, key): ...
    def setter(self, values): ...

class GSAxis(GSBase):
    def _serialize_to_plist(self, writer): ...
    def __init__(self, name: str = ..., tag: str = ..., hidden: bool = ...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def _parse_tag_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_hidden_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[bool] = ...): ...

class GSCustomParameter(GSBase):
    _CUSTOM_INT_PARAMS: ClassVar[frozenset] = ...
    _CUSTOM_FLOAT_PARAMS: ClassVar[frozenset] = ...
    _CUSTOM_BOOL_PARAMS: ClassVar[frozenset] = ...
    _CUSTOM_INTLIST_PARAMS: ClassVar[frozenset] = ...
    _CUSTOM_DICT_PARAMS: ClassVar[frozenset] = ...
    value: Incomplete
    def _serialize_to_plist(self, writer): ...
    def __init__(self, name: str = ..., value: str = ..., disabled: bool = ...) -> None: ...
    def plistValue(self, format_version: int = ...): ...
    def getValue(self): ...
    def setValue(self, value):
        """Cast some known data in custom parameters."""

class GSMetric(GSBase):
    def __init__(self, name: str = ..., type: str = ...) -> None: ...
    def _serialize_to_plist(self, writer): ...

class GSMetricValue(GSBase):
    def __init__(self, position: int = ..., overshoot: int = ...) -> None: ...
    def _serialize_to_plist(self, writer): ...
    def _parse_over_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_pos_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...

class GSAlignmentZone(GSBase):
    def __init__(self, pos: int = ..., size: int = ...) -> None: ...
    def read(self, src): ...
    def __lt__(self, other) -> bool: ...
    def __eq__(self, other) -> bool: ...
    def plistValue(self, format_version: int = ...): ...

class GSGuide(GSBase):
    _parent: ClassVar[None] = ...
    _defaultsForName: ClassVar[dict] = ...
    def _serialize_to_plist(self, writer): ...
    def __init__(self) -> None: ...
    def _parse_position_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Point] = ...): ...
    def _parse_pos_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Point] = ...): ...
    @property
    def parent(self): ...

class GSFontMaster(GSBase):
    _defaultsForName: ClassVar[dict] = ...
    _axis_defaults: ClassVar[tuple] = ...
    name: Incomplete
    customParameters: Incomplete
    userData: Incomplete
    alignmentZones: Incomplete
    horizontalStems: Incomplete
    verticalStems: Incomplete
    ascender: Incomplete
    xHeight: Incomplete
    capHeight: Incomplete
    descender: Incomplete
    italicAngle: Incomplete
    weightValue: Incomplete
    widthValue: Incomplete
    customValue: Incomplete
    customValue1: Incomplete
    customValue2: Incomplete
    customValue3: Incomplete
    def _serialize_to_plist(self, writer): ...
    def _parse_alignmentZones_dict(self, parser, text):
        """
        For glyphs file format 2 this parses the aligmentZone parameter
        directly. For file format 3 alignmentZones will be infered from
        metricValues.
        """
    def __init__(self) -> None: ...
    def set_all_name_components(self, name, weight, width, custom_name):
        """This function ensures that after being called, the master.name,
        master.weight, master.width, and master.customName match the given
        values.
        """
    def _joinName(self): ...
    def _splitName(self, value): ...
    def _get_metric(self, metricname): ...
    def _set_metric(self, metricname, value): ...
    def _get_axis_value(self, index): ...
    def _set_axis_value(self, index, value): ...
    def _parse_customParameters_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSCustomParameter] = ..., transformer: Incomplete | None = ...): ...
    def _parse_guideLines_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSGuide] = ..., transformer: Incomplete | None = ...): ...
    def _parse_guides_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSGuide] = ..., transformer: Incomplete | None = ...): ...
    def _parse_custom_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_axesValues_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_numberValues_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_stemValues_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_metricValues_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSMetricValue] = ..., transformer: Incomplete | None = ...): ...
    def _parse_name_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    @property
    def metricsSource(self):
        """Returns the source master to be used for glyph and kerning metrics.

        If linked metrics parameters are being used, the master is returned here,
        otherwise None.
        Returns the source master to be used for glyph and kerning metrics.

        If linked metrics parameters are being used, the master is returned here,
        otherwise None."""

class GSNode(GSBase):
    _PLIST_VALUE_RE: ClassVar[re.Pattern] = ...
    _ESCAPED_CHAR_RE: ClassVar[re.Pattern] = ...
    userData: Incomplete
    position: Incomplete
    name: Incomplete
    _parent: Incomplete
    _position: Incomplete
    _userData: Incomplete
    smooth: Incomplete
    type: Incomplete
    def __init__(self, position: tuple = ..., type: str = ..., smooth: bool = ..., name: Incomplete | None = ..., nodetype: Incomplete | None = ...) -> None: ...
    def clone(self):
        """Clones the node (does not clone attributes)"""
    def plistValue(self, format_version: int = ...): ...
    @classmethod
    def read(cls, line):
        '''Parse a Glyphs node string into a GSNode.

        The format of a Glyphs node string (`line`) is:

            "X Y (LINE|CURVE|QCURVE|OFFCURVE)"
            "X Y (LINE|CURVE|QCURVE|OFFCURVE) SMOOTH"
            "X Y (LINE|CURVE|QCURVE|OFFCURVE) SMOOTH {dictionary}"
            "X Y (LINE|CURVE|QCURVE|OFFCURVE) {dictionary}"

        X and Y can be integers or floats, positive or negative.

        WARNING: This method is HOT. It is called for every single node and can
        account for a significant portion of the file parsing time.
        '''
    @classmethod
    def read_v3(cls, lst): ...
    def makeNodeFirst(self): ...
    def toggleConnection(self): ...
    @staticmethod
    def _encode_dict_as_string(value):
        """Takes the PLIST string of a dict, and returns the same string
        encoded such that it can be included in the string representation
        of a GSNode."""
    @staticmethod
    def _unescape_char(m): ...
    @classmethod
    def _decode_dict_as_string(cls, value):
        """Reverse function of _encode_string_as_dict"""
    def _indices(self):
        """Find the path_index and node_index that identify the given node."""
    @property
    def parent(self): ...
    @property
    def index(self): ...
    @property
    def nextNode(self): ...
    @property
    def prevNode(self): ...
    @property
    def connection(self): ...
    @property
    def selected(self): ...

class GSPath(GSBase):
    _defaultsForName: ClassVar[dict] = ...
    _parent: ClassVar[None] = ...
    nodes: Incomplete
    segments: Incomplete
    def _serialize_to_plist(self, writer): ...
    def _parse_nodes_dict(self, parser, d): ...
    def __init__(self) -> None: ...
    def clone(self):
        """Clones the path (Does not clone attributes)"""
    def setSegments(self, segments): ...
    def reverse(self): ...
    def addNodesAtExtremes(self): ...
    def applyTransform(self, transformationMatrix): ...
    def draw(self, pen: AbstractPen) -> None:
        """Draws contour with the given pen."""
    def drawPoints(self, pointPen: AbstractPointPen) -> None:
        """Draws points of contour with the given point pen."""
    def _parse_attr_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    @property
    def parent(self): ...
    @property
    def bounds(self): ...
    @property
    def direction(self): ...
    @property
    def selected(self): ...
    @property
    def bezierPath(self): ...

class segment(list):
    def appendNode(self, node): ...
    def bbox(self): ...
    def bezierMinMax(self, x0, y0, x1, y1, x2, y2, x3, y3): ...
    @property
    def nextSegment(self): ...
    @property
    def prevSegment(self): ...

class GSComponent(GSBase):
    _defaultsForName: ClassVar[dict] = ...
    _parent: ClassVar[None] = ...
    position: Incomplete
    scale: Incomplete
    rotation: Incomplete
    componentName: Incomplete
    def _serialize_to_plist(self, writer): ...
    def __init__(self, glyph: str = ..., offset: tuple = ..., scale: tuple = ..., transform: Incomplete | None = ...) -> None: ...
    def clone(self): ...
    def updateAffineTransform(self): ...
    def applyTransformation(self, x, y): ...
    def draw(self, pen: AbstractPen) -> None:
        """Draws component with given pen."""
    def drawPoints(self, pointPen: AbstractPointPen) -> None:
        """Draws points of component with given point pen."""
    def _parse_transform_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Transform] = ...): ...
    def _parse_piece_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[dict] = ..., transformer: Incomplete | None = ...): ...
    def _parse_angle_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[float] = ..., transformer: Incomplete | None = ...): ...
    def _parse_pos_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Point] = ...): ...
    def _parse_ref_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_locked_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[bool] = ...): ...
    @property
    def parent(self): ...
    @property
    def component(self): ...
    @property
    def layer(self): ...
    @property
    def bounds(self): ...

class GSSmartComponentAxis(GSBase):
    _defaultsForName: ClassVar[dict] = ...
    def _serialize_to_plist(self, writer): ...
    def __init__(self) -> None: ...

class GSAnchor(GSBase):
    _parent: ClassVar[None] = ...
    _defaultsForName: ClassVar[dict] = ...
    userData: Incomplete
    def _serialize_to_plist(self, writer): ...
    def __init__(self, name: Incomplete | None = ..., position: Incomplete | None = ..., userData: Incomplete | None = ...) -> None: ...
    def _parse_pos_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Point] = ...): ...
    def _parse_userData_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[dict] = ..., transformer: Incomplete | None = ...): ...
    def _parse_position_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Point] = ...): ...
    @property
    def parent(self): ...

class GSHint(GSBase):
    _defaultsForName: ClassVar[dict] = ...
    originNode: Incomplete
    origin: Incomplete
    targetNode: Incomplete
    target: Incomplete
    otherNode1: Incomplete
    other1: Incomplete
    otherNode2: Incomplete
    other2: Incomplete
    def _serialize_to_plist(self, writer): ...
    def __init__(self) -> None: ...
    def _origin_pos(self): ...
    def _width_pos(self): ...
    def _parse_origin_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.IndexPath] = ...): ...
    def _parse_other1_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.IndexPath] = ...): ...
    def _parse_other2_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.IndexPath] = ...): ...
    def _parse_target_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.IndexPath] = ...): ...
    def _parse_place_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Point] = ...): ...
    def _parse_scale_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Point] = ...): ...
    def _parse_horizontal_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[bool] = ...): ...
    @property
    def parent(self): ...

class GSFeature(GSBase):
    code: Incomplete
    def _serialize_to_plist(self, writer): ...
    def __init__(self, name: str = ..., code: str = ...) -> None: ...
    def getCode(self): ...
    def setCode(self, code): ...
    def _parse_code_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_tag_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_labels_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[dict] = ..., transformer: Incomplete | None = ...): ...
    @property
    def parent(self): ...

class GSClass(GSFeature):
    def _serialize_to_plist(self, writer): ...

class GSFeaturePrefix(GSClass): ...

class GSAnnotation(GSBase):
    _defaultsForName: ClassVar[dict] = ...
    _parent: ClassVar[None] = ...
    def _serialize_to_plist(self, writer): ...
    def __init__(self) -> None: ...
    def _parse_pos_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Point] = ...): ...
    def _parse_position_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Point] = ...): ...
    @property
    def parent(self): ...

class GSFontInfoValue(GSBase):
    name: Incomplete
    value: Incomplete
    def __init__(self, key: str = ..., value: str = ...) -> None: ...
    def _parse_values_dict(self, parser, values): ...
    def _serialize_to_plist(self, writer): ...

class GSInstance(GSBase):
    _axis_defaults: ClassVar[tuple] = ...
    _defaultsForName: ClassVar[dict] = ...
    customParameters: Incomplete
    properties: Incomplete
    exports: Incomplete
    familyName: Incomplete
    preferredFamily: Incomplete
    preferredSubfamilyName: Incomplete
    windowsFamily: Incomplete
    fontName: Incomplete
    fullName: Incomplete
    weightValue: Incomplete
    widthValue: Incomplete
    customValue: Incomplete
    customValue1: Incomplete
    customValue2: Incomplete
    customValue3: Incomplete
    def _serialize_to_plist(self, writer): ...
    def __init__(self) -> None: ...
    def _get_axis_value(self, index): ...
    def _set_axis_value(self, index, value): ...
    def _parse_customParameters_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSCustomParameter] = ..., transformer: Incomplete | None = ...): ...
    def _parse_instanceInterpolations_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[dict] = ..., transformer: Incomplete | None = ...): ...
    def _parse_interpolationCustom_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_interpolationCustom1_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_interpolationCustom2_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_interpolationCustom3_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_interpolationWeight_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_interpolationWidth_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_weightClass_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_widthClass_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_axesValues_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_manualInterpolation_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[bool] = ...): ...
    def _parse_properties_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSFontInfoValue] = ..., transformer: Incomplete | None = ...): ...
    def _parse_type_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Callable = ...): ...
    @property
    def preferredFamilyName(self): ...
    @property
    def windowsStyle(self): ...
    @property
    def windowsLinkedToStyle(self): ...

class GSBackgroundImage(GSBase):
    _defaultsForName: ClassVar[dict] = ...
    path: Incomplete
    position: Incomplete
    scale: Incomplete
    rotation: Incomplete
    alpha: Incomplete
    def _serialize_to_plist(self, writer): ...
    def __init__(self, path: Incomplete | None = ...) -> None: ...
    def updateAffineTransform(self): ...
    def _parse_transform_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Transform] = ...): ...
    def _parse_crop_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Rect] = ...): ...
    def _parse_locked_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[bool] = ...): ...
    def _parse_angle_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_pos_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...

class LayerPathsProxy(LayerShapesProxy):
    class _filter(GSBase):
        _defaultsForName: ClassVar[dict] = ...
        _parent: ClassVar[None] = ...
        nodes: Incomplete
        segments: Incomplete
        def _serialize_to_plist(self, writer): ...
        def _parse_nodes_dict(self, parser, d): ...
        def __init__(self) -> None: ...
        def clone(self):
            """Clones the path (Does not clone attributes)"""
        def setSegments(self, segments): ...
        def reverse(self): ...
        def addNodesAtExtremes(self): ...
        def applyTransform(self, transformationMatrix): ...
        def draw(self, pen: AbstractPen) -> None:
            """Draws contour with the given pen."""
        def drawPoints(self, pointPen: AbstractPointPen) -> None:
            """Draws points of contour with the given point pen."""
        def _parse_attr_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
        @property
        def parent(self): ...
        @property
        def bounds(self): ...
        @property
        def direction(self): ...
        @property
        def selected(self): ...
        @property
        def bezierPath(self): ...

class LayerComponentsProxy(LayerShapesProxy):
    class _filter(GSBase):
        _defaultsForName: ClassVar[dict] = ...
        _parent: ClassVar[None] = ...
        position: Incomplete
        scale: Incomplete
        rotation: Incomplete
        componentName: Incomplete
        def _serialize_to_plist(self, writer): ...
        def __init__(self, glyph: str = ..., offset: tuple = ..., scale: tuple = ..., transform: Incomplete | None = ...) -> None: ...
        def clone(self): ...
        def updateAffineTransform(self): ...
        def applyTransformation(self, x, y): ...
        def draw(self, pen: AbstractPen) -> None:
            """Draws component with given pen."""
        def drawPoints(self, pointPen: AbstractPointPen) -> None:
            """Draws points of component with given point pen."""
        def _parse_transform_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Transform] = ...): ...
        def _parse_piece_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[dict] = ..., transformer: Incomplete | None = ...): ...
        def _parse_angle_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[float] = ..., transformer: Incomplete | None = ...): ...
        def _parse_pos_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[glyphsLib.types.Point] = ...): ...
        def _parse_ref_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
        def _parse_locked_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[bool] = ...): ...
        @property
        def parent(self): ...
        @property
        def component(self): ...
        @property
        def layer(self): ...
        @property
        def bounds(self): ...

class GSLayer(GSBase):
    _defaultsForName: ClassVar[dict] = ...
    BRACKET_LAYER_RE: ClassVar[re.Pattern] = ...
    COLOR_PALETTE_LAYER_RE: ClassVar[re.Pattern] = ...
    layerId: Incomplete
    name: Incomplete
    anchors: Incomplete
    hints: Incomplete
    paths: Incomplete
    components: Incomplete
    shapes: Incomplete
    guides: Incomplete
    annotations: Incomplete
    userData: Incomplete
    smartComponentPoleMapping: Incomplete
    rightMetricsKey: Incomplete
    leftMetricsKey: Incomplete
    widthMetricsKey: Incomplete
    def _serialize_to_plist(self, writer): ...
    def _parse_shapes_dict(self, parser, shapes): ...
    def _parse_background_dict(self, parser, value): ...
    def __init__(self) -> None: ...
    def __lt__(self, other) -> bool: ...
    def _find_node_by_indices(self, point):
        '''"Find the GSNode that is refered to by the given indices.

        See GSNode::_indices()
        '''
    def getPen(self) -> AbstractPen:
        """Returns a pen for others to draw into self."""
    def getPointPen(self) -> AbstractPointPen:
        """Returns a point pen for others to draw points into self."""
    def draw(self, pen: AbstractPen) -> None:
        """Draws glyph with the given pen."""
    def drawPoints(self, pointPen: AbstractPointPen) -> None:
        """Draws points of glyph with the given point pen."""
    def _is_bracket_layer(self): ...
    def _bracket_axis_rules(self): ...
    def _bracket_info(self, axes): ...
    def _is_brace_layer(self): ...
    def _brace_coordinates(self): ...
    def _brace_layer_name(self): ...
    def _is_color_palette_layer(self): ...
    def _color_palette_index(self): ...
    def _parse_annotations_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSAnnotation] = ..., transformer: Incomplete | None = ...): ...
    def _parse_backgroundImage_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSBackgroundImage] = ..., transformer: Incomplete | None = ...): ...
    def _parse_paths_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSPath] = ..., transformer: Incomplete | None = ...): ...
    def _parse_anchors_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSAnchor] = ..., transformer: Incomplete | None = ...): ...
    def _parse_guideLines_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSGuide] = ..., transformer: Incomplete | None = ...): ...
    def _parse_guides_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSGuide] = ..., transformer: Incomplete | None = ...): ...
    def _parse_components_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSComponent] = ..., transformer: Incomplete | None = ...): ...
    def _parse_hints_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSHint] = ..., transformer: Incomplete | None = ...): ...
    def _parse_userData_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[dict] = ..., transformer: Incomplete | None = ...): ...
    def _parse_partSelection_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[dict] = ..., transformer: Incomplete | None = ...): ...
    def _parse_leftMetricsKey_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[str] = ..., transformer: Incomplete | None = ...): ...
    def _parse_rightMetricsKey_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[str] = ..., transformer: Incomplete | None = ...): ...
    def _parse_widthMetricsKey_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[str] = ..., transformer: Incomplete | None = ...): ...
    def _parse_attr_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[dict] = ..., transformer: Incomplete | None = ...): ...
    @property
    def master(self): ...
    @property
    def _is_master_layer(self): ...
    @property
    def bounds(self): ...
    @property
    def background(self):
        """Only a getter on purpose. See the tests.
        Only a getter on purpose. See the tests."""
    @property
    def hasBackground(self): ...
    @property
    def foreground(self):
        """Forbidden, and also forbidden to set it.
        Forbidden, and also forbidden to set it."""

class GSBackgroundLayer(GSLayer):
    width: Incomplete
    @property
    def background(self): ...
    @property
    def foreground(self): ...

class GSGlyph(GSBase):
    _defaultsForName: ClassVar[dict] = ...
    layers: Incomplete
    userData: Incomplete
    glyphname: Incomplete
    smartComponentAxes: Incomplete
    unicode: Incomplete
    unicodes: Incomplete
    rightMetricsKey: Incomplete
    leftMetricsKey: Incomplete
    widthMetricsKey: Incomplete
    vertWidthMetricsKey: Incomplete
    def _serialize_to_plist(self, writer): ...
    def _parse_unicode_dict(self, parser, value): ...
    def _parse_layers_dict(self, parser, value): ...
    def __init__(self, name: Incomplete | None = ...) -> None: ...
    def _setupLayer(self, layer, key): ...
    def removeLayerForKey_(self, key): ...
    def colorIndex(self): ...
    def countOfUnicodes(self): ...
    def countOfLayers(self): ...
    def hasAnnotations(self): ...
    def hasComponents(self): ...
    def hasCorners(self): ...
    def hasSpecialLayers(self): ...
    def isAnyColorGlyph(self): ...
    def isFullColorGlyph(self): ...
    def isColorPaletteGlyph(self): ...
    def isSVGColorGlyph(self): ...
    def isAppleColorGlyph(self): ...
    def _parse_glyphname_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_partsSettings_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSSmartComponentAxis] = ..., transformer: Incomplete | None = ...): ...
    def _parse_export_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[bool] = ...): ...
    def _parse_lastChange_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Callable = ...): ...
    def _parse_kernLeft_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_kernRight_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_leftMetricsKey_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_rightMetricsKey_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_widthMetricsKey_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_vertWidthMetricsKey_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    @property
    def string(self): ...
    @property
    def id(self):
        """An unique identifier for each glyph
        An unique identifier for each glyph"""

class GSFont(GSBase):
    _defaultsForName: ClassVar[dict] = ...
    def _serialize_to_plist(self, writer) -> None: ...
    _defaultMetrics: ClassVar[list] = ...
    _defaultAxes: ClassVar[list] = ...
    EMPTY_KERNING_VALUE: ClassVar[int] = ...
    versionMinor: Incomplete
    glyphs: Incomplete
    masters: Incomplete
    instances: Incomplete
    classes: Incomplete
    features: Incomplete
    featurePrefixes: Incomplete
    customParameters: Incomplete
    properties: Incomplete
    userData: Incomplete
    kerning: Incomplete
    kerningLTR: Incomplete
    kerningRTL: Incomplete
    kerningVertical: Incomplete
    note: Incomplete
    manufacturer: Incomplete
    manufacturerURL: Incomplete
    copyright: Incomplete
    designer: Incomplete
    designerURL: Incomplete
    def _serialize_to_plist(self, writer): ...
    def _parse_glyphs_dict(self, parser, value): ...
    def _parse_settings_dict(self, parser, settings): ...
    def _parse___formatVersion_dict(self, parser, val): ...
    def __init__(self, path: str | bytes | os.PathLike[str] | os.PathLike[bytes] | None = ...) -> None: ...
    def save(self, path: Incomplete | None = ...): ...
    def getVersionMinor(self): ...
    def setVersionMinor(self, value):
        """Ensure that the minor version number is between 0 and 999."""
    def _setupGlyph(self, glyph): ...
    def masterForId(self, key): ...
    def kerningForPair(self, fontMasterId, leftKey, rightKey, direction: int = ...): ...
    def setKerningForPair(self, fontMasterId, leftKey, rightKey, value, direction: int = ...): ...
    def removeKerningForPair(self, fontMasterId, leftKey, rightKey, direction: int = ...): ...
    def _get_custom_parameter_from_axes(self): ...
    def _set_axes_from_custom_parameter(self, value): ...
    def _parse_customParameters_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSCustomParameter] = ..., transformer: Incomplete | None = ...): ...
    def _parse_unitsPerEm_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_gridLength_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_gridSubDivisions_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse___appVersion_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    def _parse_classes_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSClass] = ..., transformer: Incomplete | None = ...): ...
    def _parse_instances_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSInstance] = ..., transformer: Incomplete | None = ...): ...
    def _parse_featurePrefixes_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSFeaturePrefix] = ..., transformer: Incomplete | None = ...): ...
    def _parse_features_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSFeature] = ..., transformer: Incomplete | None = ...): ...
    def _parse_fontMaster_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSFontMaster] = ..., transformer: Incomplete | None = ...): ...
    def _parse_kerning_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[collections.OrderedDict] = ..., transformer: Incomplete | None = ...): ...
    def _parse_kerningLTR_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[collections.OrderedDict] = ..., transformer: Incomplete | None = ...): ...
    def _parse_kerningRTL_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[collections.OrderedDict] = ..., transformer: Incomplete | None = ...): ...
    def _parse_kerningVertical_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[collections.OrderedDict] = ..., transformer: Incomplete | None = ...): ...
    def _parse_date_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Callable = ...): ...
    def _parse_disablesAutomaticAlignment_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: type[bool] = ...): ...
    def _parse_axes_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSAxis] = ..., transformer: Incomplete | None = ...): ...
    def _parse_stems_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSMetric] = ..., transformer: Incomplete | None = ...): ...
    def _parse_metrics_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSMetric] = ..., transformer: Incomplete | None = ...): ...
    def _parse_numbers_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSMetric] = ..., transformer: Incomplete | None = ...): ...
    def _parse_properties_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: type[GSFontInfoValue] = ..., transformer: Incomplete | None = ...): ...
    def _parse_note_dict(self, parser, value, keyname: str = ..., target: str = ..., classname: Incomplete | None = ..., transformer: Incomplete | None = ...): ...
    @property
    def selection(self): ...
    @property
    def gridLength(self): ...
    @property
    def settings(self): ...
