"""
This type stub file was generated by pyright.
"""

def main(args=...): # -> Any | None:
    ...

def glyphs2ufo(options): # -> None:
    """Converts a Glyphs.app source file into UFO masters and a designspace file."""
    ...

def ufo2glyphs(options): # -> Literal[1] | None:
    """Convert one designspace file or one or more UFOs to a Glyphs.app source file."""
    ...

