from glyphsLib.types import Point as Point, Transform as Transform
from typing import Any
import fontTools.pens.pointPen

class LayerPointPen(fontTools.pens.pointPen.AbstractPointPen):
    """A point pen to draw onto GSLayer object.

    See :mod:`fontTools.pens.basePen` and :mod:`fontTools.pens.pointPen` for an
    introduction to pens.
    """

    def __init__(self, layer: GSLayer) -> None: ...
    def beginPath(self, **kwargs: Any) -> None: ...
    def endPath(self) -> None: ...
    def addPoint(self, pt: tuple, segmentType=..., smooth: bool = ..., name=..., userData=..., **kwargs: Any) -> None: ...
    def addComponent(self, baseGlyph: str, transformation, **kwargs: Any) -> None: ...
def _to_glyphs_node_type(node_type): ...
def _to_ufo_node_type(node_type): ...

