from fontTools.pens.pointPen import AbstractPointPen
from glyphsLib.types import Point as Point, Transform as Transform
from typing import Any

Number = int | float

class LayerPointPen(AbstractPointPen):
    """A point pen to draw onto GSLayer object.

    See :mod:`fontTools.pens.basePen` and :mod:`fontTools.pens.pointPen` for an
    introduction to pens.
    """
    _layer: GSLayer
    _path: GSPath | None
    def __init__(self, layer: GSLayer) -> None: ...
    def beginPath(self, **kwargs: Any) -> None: ...
    def endPath(self) -> None: ...
    def addPoint(self, pt: tuple[Number, Number], segmentType: str | None = None, smooth: bool = False, name: str | None = None, userData: dict[str, Any] | None = None, **kwargs: Any) -> None: ...
    def addComponent(self, baseGlyph: str, transformation: Transform | tuple[float, float, float, float, float, float], **kwargs: Any) -> None: ...

def _to_glyphs_node_type(node_type): ...
def _to_ufo_node_type(node_type): ...
