from _typeshed import Incomplete
from glyphsLib.types import floatToString5 as floatToString5

logger: Incomplete

class Writer:
    file: Incomplete
    format_version: Incomplete
    def __init__(self, fp, format_version: int = 2) -> None: ...
    def write(self, rootObject) -> None: ...
    def writeDict(self, dictValue) -> None: ...
    def writeArray(self, arrayValue) -> None: ...
    def writeUserData(self, userDataValue) -> None: ...
    def writeKeyValue(self, key, value) -> None: ...
    def writeObjectKeyValue(self, d, key, condition=None, keyName=None, default=None) -> None: ...
    def writeValue(self, value, forKey=None) -> None: ...
    def writeKey(self, key) -> None: ...
    def escape_string(self, string, forKey): ...

def dump(obj, fp) -> None:
    """Write a GSFont object to a .glyphs file.
    'fp' should be a (writable) file object.
    """
def dumps(obj):
    """Serialize a GSFont object to a .glyphs file format.
    Return a (unicode) str object.
    """

NSPropertyListNameSet: Incomplete
