from _typeshed import Incomplete

class Writer:
    def __init__(self, fp, format_version: int = ...) -> None: ...
    def write(self, rootObject): ...
    def writeDict(self, dictValue): ...
    def writeArray(self, arrayValue): ...
    def writeUserData(self, userDataValue): ...
    def writeKeyValue(self, key, value): ...
    def writeObjectKeyValue(self, d, key, condition: Incomplete | None = ..., keyName: Incomplete | None = ..., default: Incomplete | None = ...): ...
    def writeValue(self, value, forKey: Incomplete | None = ...): ...
    def writeKey(self, key): ...
    def escape_string(self, string, forKey): ...
def dump(obj, fp):
    """Write a GSFont object to a .glyphs file.
    'fp' should be a (writable) file object.
    """
def dumps(obj):
    """Serialize a GSFont object to a .glyphs file format.
    Return a (unicode) str object.
    """

NSPropertyListNameSet: tuple
def _needs_quotes(string): ...

