def check_compatible(*args, **kwargs): ...
def get_pointer(*args, **kwargs): ...
def new_type_manager(*args, **kwargs): ...
def select_overload(*args, **kwargs): ...
def set_compatible(*args, **kwargs): ...
