TYPE_CHECKING: bool
def create_pandas_abc_type(name, attr, comp): ...

class ABCRangeIndex:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCMultiIndex:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCDatetimeIndex:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCTimedeltaIndex:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCPeriodIndex:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCCategoricalIndex:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCIntervalIndex:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCIndex:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCNDFrame:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCSeries:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCDataFrame:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCCategorical:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCDatetimeArray:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCTimedeltaArray:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCPeriodArray:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCExtensionArray:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...

class ABCNumpyExtensionArray:
    @classmethod
    def __instancecheck__(cls, inst) -> bool: ...
    @classmethod
    def __subclasscheck__(cls, inst) -> bool: ...
