from ..backends import backends as backends, DriverBase as DriverBase

class DriverConfig:
    def __init__(self) -> None: ...
    @property
    def default(self) -> DriverBase: ...
    @property
    def active(self) -> DriverBase: ...
    def set_active(self, driver: DriverBase) -> None: ...
    def reset_active(self) -> None: ...

driver: DriverConfig
