import torch.nn as nn
from _typeshed import Incomplete
from typing import Any

def get_norm_layer(use_norm: bool | str | dict[str, Any], out_channels: int) -> nn.Module: ...

class Conv2dReLU(nn.Sequential):
    def __init__(self, in_channels: int, out_channels: int, kernel_size: int, padding: int = 0, stride: int = 1, use_norm: bool | str | dict[str, Any] = 'batchnorm') -> None: ...

class SCSEModule(nn.Module):
    cSE: Incomplete
    sSE: Incomplete
    def __init__(self, in_channels, reduction: int = 16) -> None: ...
    def forward(self, x): ...

class ArgMax(nn.Module):
    dim: Incomplete
    def __init__(self, dim=None) -> None: ...
    def forward(self, x): ...

class Clamp(nn.Module):
    def __init__(self, min: int = 0, max: int = 1) -> None: ...
    def forward(self, x): ...

class Activation(nn.Module):
    activation: Incomplete
    def __init__(self, name, **params) -> None: ...
    def forward(self, x): ...

class Attention(nn.Module):
    attention: Incomplete
    def __init__(self, name, **params) -> None: ...
    def forward(self, x): ...
