"""
This type stub file was generated by pyright.
"""

import python_toolbox.version_info

'''
Python Toolbox is a collection of Python tools.

These tools include caching, context manager tools, data structures, binary
search, import tools, tools for manipulating Python's built-in types, and many
more.

Visit http://pypi.python.org/pypi/python_toolbox/ for more info.
'''
__version__ = ...
__version_info__ = ...
