"""
This type stub file was generated by pyright.
"""

'''Defines various introspection tools, similar to the stdlib's `inspect`.'''
def get_default_args_dict(function): # -> OrderedDict:
    '''
    Get ordered dict from arguments which have a default to their default.

    Example:

        >>> def f(a, b, c=1, d='meow'): pass
        >>> get_default_args_dict(f)
        OrderedDict([('c', 1), ('d', 'meow')])

    '''
    ...

