"""
This type stub file was generated by pyright.
"""

'''Defines various tools related to file-system paths.'''
_is_windows = ...
null_path = ...
path_type = ...
def list_sub_folders(path): # -> tuple[Path, ...]:
    '''List all the immediate sub-folders of the folder at `path`.'''
    ...

def get_path_of_package(package): # -> Path:
    '''Get the path of a Python package, i.e. where its modules would be.'''
    ...

def get_root_path_of_module(module): # -> Path:
    '''
    Get the root path of a module.

    This is the path that should be in `sys.path` for the module to be
    importable. Note that this would give the same answer for
    `my_package.my_sub_package.my_module` as for `my_package`; it only cares
    about the root module.
    '''
    ...

