# ruff: noqa: UP040 PYI001
from collections.abc import Generator
from numpy import float32, float64, int16, int32
from numpy.typing import NDArray
from os import SEEK_SET
from typing import Any, BinaryIO, Literal, overload, Self, TypeAlias, TypeVar
import numpy
import os as _os

__version__: str
FileDescriptorOrPath: TypeAlias = str | int | BinaryIO | _os.PathLike[Any]
AudioData: TypeAlias = NDArray[numpy.float32 | numpy.float64 | numpy.int16 | numpy.int32]
AudioData_2d: TypeAlias = numpy.ndarray[tuple[int, int], numpy.dtype[numpy.float32 | numpy.float64 | numpy.int16 | numpy.int32]]
_2d_float32: TypeAlias = numpy.ndarray[tuple[int, int], numpy.dtype[numpy.float32]]
_2d_float64: TypeAlias = numpy.ndarray[tuple[int, int], numpy.dtype[numpy.float64]]
_2d_int16: TypeAlias = numpy.ndarray[tuple[int, int], numpy.dtype[numpy.int16]]
_2d_int32: TypeAlias = numpy.ndarray[tuple[int, int], numpy.dtype[numpy.int32]]

T_ndarray = TypeVar('T_ndarray', bound=numpy.ndarray)

dtype_str: TypeAlias = Literal['float32', 'float64', 'int16', 'int32']
__libsndfile_version__: str

@overload
def read(file: FileDescriptorOrPath, frames: int = -1, start: int = 0, stop: int | None = None, dtype: dtype_str = 'float64', *, always_2d: Literal[True], fill_value: float | None = None, out: AudioData_2d | None = None, samplerate: int | None = None, channels: int | None = None, format: str | None = None, subtype: str | None = None, endian: str | None = None, closefd: bool = True) -> tuple[AudioData_2d, int]: ...
@overload
def read(file: FileDescriptorOrPath, frames: int = -1, start: int = 0, stop: int | None = None, dtype: dtype_str = 'float64', always_2d: bool = False, fill_value: float | None = None, out: AudioData | None = None, samplerate: int | None = None, channels: int | None = None, format: str | None = None, subtype: str | None = None, endian: str | None = None, closefd: bool = True) -> tuple[AudioData, int]: ...
def read(file: FileDescriptorOrPath, frames: int = -1, start: int = 0, stop: int | None = None, dtype: dtype_str = 'float64', always_2d: bool = False, fill_value: float | None = None, out: AudioData | None = None, samplerate: int | None = None, channels: int | None = None, format: str | None = None, subtype: str | None = None, endian: str | None = None, closefd: bool = True) -> tuple[AudioData | AudioData_2d, int]: ...  # noqa: A002

def write(file: FileDescriptorOrPath, data: AudioData, samplerate: int, subtype: str | None = None, endian: str | None = None, format: str | None = None, closefd: bool = True, compression_level: float | None = None, bitrate_mode: str | None = None) -> None: ...  # noqa: A002

def blocks(file: FileDescriptorOrPath, blocksize: int | None = None, overlap: int = 0, frames: int = -1, start: int = 0, stop: int | None = None, dtype: dtype_str = 'float64', always_2d: bool = False, fill_value: float | None = None, out: AudioData | None = None, samplerate: int | None = None, channels: int | None = None, format: str | None = None, subtype: str | None = None, endian: str | None = None, closefd: bool = True) -> Generator[AudioData]: ...  # noqa: A002

class _SoundFileInfo:
	verbose: bool
	name: str | int | Any
	samplerate: int
	channels: int
	frames: int
	duration: float
	format: str
	subtype: str
	endian: str
	format_info: str
	subtype_info: str
	sections: int
	extra_info: str

def info(file: FileDescriptorOrPath, verbose: bool = False) -> _SoundFileInfo: ...

def available_formats() -> dict[str, str]: ...

def available_subtypes(format: str | None = None) -> dict[str, str]: ...  # noqa: A002

def check_format(format: str, subtype: str | None = None, endian: str | None = None) -> bool: ...  # noqa: A002

def default_subtype(format: str) -> str: ...  # noqa: A002

class SoundFile:

	def __init__(self, file: FileDescriptorOrPath, mode: str | None = 'r', samplerate: int | None = None, channels: int | None = None, subtype: str | None = None, endian: str | None = None, format: str | None = None, closefd: bool = True, compression_level: float | None = None, bitrate_mode: str | None = None) -> None: ...  # noqa: A002

	@property
	def name(self) -> str | int | Any: ...
	@property
	def mode(self) -> str: ...
	@property
	def samplerate(self) -> int: ...
	@property
	def frames(self) -> int: ...
	@property
	def channels(self) -> int: ...
	@property
	def format(self) -> str: ...
	@property
	def subtype(self) -> str: ...
	@property
	def endian(self) -> str: ...
	@property
	def format_info(self) -> str: ...
	@property
	def subtype_info(self) -> str: ...
	@property
	def sections(self) -> int: ...
	@property
	def closed(self) -> bool: ...
	@property
	def compression_level(self) -> float | None: ...
	@property
	def bitrate_mode(self) -> str | None: ...
	@property
	def extra_info(self) -> str: ...

	def __del__(self) -> None: ...
	def __enter__(self) -> Self: ...

	def __exit__(self, *args: object) -> None: ...
	def __setattr__(self, name: str, value: Any) -> None: ...
	def __getattr__(self, name: str) -> Any: ...

	def __len__(self) -> int: ...
	def __bool__(self) -> bool: ...
	def __nonzero__(self) -> bool: ...
	def seekable(self) -> bool: ...

	def seek(self, frames: int, whence: int = SEEK_SET) -> int: ...

	def tell(self) -> int: ...

	@overload
	def read(self, frames: int = -1, dtype: dtype_str = 'float64', always_2d: bool = False, fill_value: float | None = None,
			*, out: T_ndarray) -> T_ndarray: ...
	@overload
	def read(self, frames: int = -1, *, dtype: Literal['float32'], always_2d: Literal[True],
			fill_value: float | None = None, out: None = None) -> _2d_float32: ...
	@overload
	def read(self, frames: int = -1, *, dtype: Literal['float32'], always_2d: bool = False,
			fill_value: float | None = None, out: None = None) -> NDArray[float32]: ...
	@overload
	def read(self, frames: int = -1, dtype: Literal['float64'] = 'float64', *, always_2d: Literal[True],
			fill_value: float | None = None, out: None = None) -> _2d_float64: ...
	@overload
	def read(self, frames: int = -1, dtype: Literal['float64'] = 'float64', always_2d: bool = False,
			fill_value: float | None = None, out: None = None) -> NDArray[float64]: ...
	@overload
	def read(self, frames: int = -1, *, dtype: Literal['int16'], always_2d: Literal[True],
			fill_value: float | None = None, out: None = None) -> _2d_int16: ...
	@overload
	def read(self, frames: int = -1, *, dtype: Literal['int16'], always_2d: bool = False,
			fill_value: float | None = None, out: None = None) -> NDArray[int16]: ...
	@overload
	def read(self, frames: int = -1, *, dtype: Literal['int32'], always_2d: Literal[True],
			fill_value: float | None = None, out: None = None) -> _2d_int32: ...
	@overload
	def read(self, frames: int = -1, *, dtype: Literal['int32'], always_2d: bool = False,
			fill_value: float | None = None, out: None = None) -> NDArray[int32]: ...
	def read(self, frames: int = -1, dtype: dtype_str = 'float64',
			always_2d: bool = False, fill_value: float | None = None,
			out: T_ndarray | None = None) -> AudioData | AudioData_2d | T_ndarray: ...
	# @overload
	# def read(self, frames: int = -1, dtype: dtype_str = 'float64', *, always_2d: Literal[True], fill_value: float | None = None, out: AudioData_2d | None = None) -> AudioData_2d: ...
	# @overload
	# def read(self, frames: int = -1, dtype: dtype_str = 'float64', always_2d: bool = False, fill_value: float | None = None, out: AudioData | None = None) -> AudioData: ...
	# def read(self, frames: int = -1, dtype: dtype_str = 'float64', always_2d: bool = False, fill_value: float | None = None, out: AudioData | None = None) -> AudioData | AudioData_2d: ...

	def buffer_read(self, frames: int = -1, dtype: dtype_str | None = None) -> memoryview: ...

	def buffer_read_into(self, buffer: bytearray | memoryview | Any, dtype: dtype_str) -> int: ...
	def write(self, data: AudioData) -> None: ...
	def buffer_write(self, data: bytes, dtype: dtype_str) -> None: ...
	def blocks(self, blocksize: int | None = None, overlap: int = 0, frames: int = -1, dtype: dtype_str = 'float64', always_2d: bool = False, fill_value: float | None = None, out: AudioData | AudioData_2d | None = None) -> Generator[AudioData] | Generator[AudioData_2d]: ...
	def truncate(self, frames: int | None = None) -> None: ...
	def flush(self) -> None: ...
	def close(self) -> None: ...
	def copy_metadata(self) -> dict[str, str]: ...

class SoundFileError(Exception): ...

class SoundFileRuntimeError(SoundFileError, RuntimeError): ...

class LibsndfileError(SoundFileRuntimeError):
	def __init__(self, code: int, prefix: str = "") -> None: ...
	@property
	def error_string(self) -> str: ...
