from collections.abc import (
    Collection,
    Iterable,
)

from pandas._typing import T
from typing import Any

def flatten(line: Any) -> None: ...
def consensus_name_attr(objs: Any) -> Any: ...
def is_bool_indexer(key: Any) -> bool: ...
def cast_scalar_indexer(val: Any) -> Any: ...
def not_none(*args: Any) -> Any: ...
def any_none(*args: Any) -> Any: ...
def all_none(*args: Any) -> Any: ...
def any_not_none(*args: Any) -> Any: ...
def all_not_none(*args: Any) -> Any: ...
def count_not_none(*args: Any) -> Any: ...
def asarray_tuplesafe(values: Any, dtype: Any=None) -> Any: ...
def index_labels_to_array(labels: Any, dtype: Any=None) -> Any: ...
def maybe_make_list(obj: Any) -> Any: ...
def maybe_iterable_to_list(obj: Iterable[T] | T) -> Collection[T] | T: ...
def is_null_slice(obj: Any) -> Any: ...
def is_true_slices(line: Any) -> Any: ...
def is_full_slice(obj: Any, line: Any) -> Any: ...
def get_callable_name(obj: Any) -> Any: ...
def apply_if_callable(maybe_callable: Any, obj: Any, **kwargs: Any) -> Any: ...
def standardize_mapping(into: Any) -> Any: ...
def random_state(state: Any=None) -> Any: ...
def pipe(obj: Any, func: Any, *args: Any, **kwargs: Any) -> Any: ...
def get_rename_function(mapper: Any) -> Any: ...
