from _typeshed import Incomplete
from typing import ClassVar

TYPE_CHECKING: bool

class Flags:
    _keys: ClassVar[set] = ...
    allows_duplicate_labels: Incomplete
    def __init__(self, obj: NDFrame, *, allows_duplicate_labels: bool) -> None: ...
    def __getitem__(self, key: str): ...
    def __setitem__(self, key: str, value) -> None: ...
    def __eq__(self, other) -> bool: ...
