from typing import Any
def mask_missing(arr: Any, values_to_mask: Any): ...
def clean_fill_method(method: Any, allow_nearest: bool = False): ...
def clean_interp_method(method: Any, **kwargs): ...
def interpolate_2d(
    values: Any, method: str = ..., axis: int = ..., limit: Any=..., fill_value: Any=..., dtype: Any=...
): ...
def get_fill_func(method: Any): ...
def clean_reindex_fill_method(method: Any): ...
