"""
This type stub file was generated by pyright.
"""

from strictyaml.validators import Validator

def schema_from_document(document): # -> Map | FixedSeq | Str:
    ...

def schema_from_data(data, allow_empty): # -> EmptyDict | Map | EmptyList | FixedSeq | Bool | Int | Float | Str:
    ...

class Any(Validator):
    """
    Validates any YAML and returns simple dicts/lists of strings.
    """
    def validate(self, chunk): # -> YAML:
        ...
    
    def to_yaml(self, data, allow_empty=...): # -> str | PreservedScalarString | CommentedMap | CommentedSeq:
        """
        Args:
            allow_empty (bool): True to allow EmptyDict and EmptyList in the
                    schema generated from the data.
        """
        ...
    
    @property
    def key_validator(self): # -> Str:
        ...
    


