"""
This type stub file was generated by pyright.
"""

import sys
from strictyaml.validators import MapValidator, SeqValidator

if sys.version_info[0] == 3:
    unicode = str
class Optional:
    def __init__(self, key, default=..., drop_if_none=...) -> None:
        ...
    
    def __repr__(self): # -> LiteralString:
        ...
    


class MapPattern(MapValidator):
    def __init__(self, key_validator, value_validator, minimum_keys=..., maximum_keys=...) -> None:
        ...
    
    @property
    def key_validator(self): # -> Any:
        ...
    
    def validate(self, chunk): # -> None:
        ...
    
    def to_yaml(self, data): # -> CommentedMap:
        ...
    
    def __repr__(self): # -> str:
        ...
    


class Map(MapValidator):
    def __init__(self, validator, key_validator=...) -> None:
        ...
    
    @property
    def key_validator(self): # -> Str:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def get_validator(self, key):
        ...
    
    def unexpected_key(self, key, yaml_key, value, chunk): # -> None:
        ...
    
    def validate(self, chunk): # -> None:
        ...
    
    def to_yaml(self, data): # -> CommentedMap:
        ...
    


class MapCombined(Map):
    def __init__(self, map_validator, key_validator, value_validator) -> None:
        ...
    
    def get_validator(self, key): # -> None:
        ...
    
    def unexpected_key(self, key, yaml_key, value, chunk): # -> None:
        ...
    


class Seq(SeqValidator):
    def __init__(self, validator) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def validate(self, chunk): # -> None:
        ...
    
    def to_yaml(self, data): # -> CommentedSeq:
        ...
    


class FixedSeq(SeqValidator):
    def __init__(self, validators) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def validate(self, chunk): # -> None:
        ...
    
    def to_yaml(self, data): # -> CommentedSeq:
        ...
    


class UniqueSeq(SeqValidator):
    def __init__(self, validator) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def validate(self, chunk): # -> None:
        ...
    
    def to_yaml(self, data): # -> CommentedSeq:
        ...
    


