from typing import Any
class FrozenList(list):
    def union(self, other: Any) -> FrozenList: ...
    def difference(self, other: Any) -> FrozenList: ...
    def __getitem__(self, n: Any): ...
    def __radd__(self, other: Any): ...
    def __eq__(self, other: Any) -> bool: ...
    def __mul__(self, other: Any): ...
    def __reduce__(self): ...
    def __hash__(self) -> int: ...  # type: ignore[override] # pyright: ignore[reportIncompatibleVariableOverride]
