from typing import Any
class FrozenList(list[Any]):
    def union(self, other: Any) -> FrozenList: ...
    def difference(self, other: Any) -> FrozenList: ...
    def __getitem__(self, n: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> bool: ...
    def __mul__(self, other: Any) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __hash__(self) -> int: ...  # type: ignore[override] # pyright: ignore[reportIncompatibleVariableOverride]
