from collections.abc import (
    Callable,
    Hashable,
    Iterable,
    Sequence,
)
from typing import overload

import numpy as np
import pandas as pd
from pandas.core.indexes.base import Index
from typing_extensions import Self

from pandas._typing import (
    AnyAll,
    Axes,
    DropKeep,
    Dtype,
    DtypeArg,
    HashableT,
    Level,
    MaskType,
    NaPosition,
    SequenceNotStr,
    np_ndarray_anyint,
    np_ndarray_bool,
)

class MultiIndex(Index):
    def __new__(
        cls,
        levels: Sequence[SequenceNotStr[Hashable]] = None,
        codes: Sequence[Sequence[int]] = None,
        sortorder: int | None = None,
        names: SequenceNotStr[Hashable] = None,
        copy: bool = False,
        name: SequenceNotStr[Hashable] = None,
        verify_integrity: bool = True,
    ) -> Self: ...
    @classmethod
    def from_arrays(
        cls,
        arrays: Sequence[Axes],
        sortorder: int | None = None,
        names: SequenceNotStr[Hashable] = ...,
    ) -> Self: ...
    @classmethod
    def from_tuples(
        cls,
        tuples: Iterable[tuple[Hashable, ...]],
        sortorder: int | None = None,
        names: SequenceNotStr[Hashable] = None,
    ) -> Self: ...
    @classmethod
    def from_product(
        cls,
        iterables: Sequence[SequenceNotStr[Hashable] | pd.Series | pd.Index],
        sortorder: int | None = None,
        names: SequenceNotStr[Hashable] = ...,
    ) -> Self: ...
    @classmethod
    def from_frame(
        cls,
        df: pd.DataFrame,
        sortorder: int | None = None,
        names: SequenceNotStr[Hashable] = None,
    ) -> Self: ...
    @property
    def shape(self): ...
    @property  # Should be read-only
    def levels(self) -> list[Index]: ...
    def set_levels(self, levels, *, level=None, verify_integrity: bool = True): ...
    @property
    def codes(self): ...
    def set_codes(self, codes, *, level=None, verify_integrity: bool = True): ...
    def copy(  # pyright: ignore[reportIncompatibleMethodOverride] # pyrefly: ignore
        self, names=None, deep: bool = False
    ) -> Self: ...
    def __array__(self, dtype=None) -> np.ndarray: ...
    def view(self, cls=None): ...
    def __contains__(self, key) -> bool: ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def dtypes(self) -> pd.Series[Dtype]: ...
    def memory_usage(self, deep: bool = False) -> int: ...
    @property
    def nbytes(self) -> int: ...
    def format(
        self,
        name: bool | None = None,
        formatter: Callable | None = None,
        na_rep: str | None = None,
        names: bool = False,
        space: int = 2,
        sparsify: bool | None = None,
        adjoin: bool = True,
    ) -> list: ...
    def __len__(self) -> int: ...
    @property
    def values(self): ...
    @property
    def is_monotonic_increasing(self) -> bool: ...
    @property
    def is_monotonic_decreasing(self) -> bool: ...
    def duplicated(self, keep: DropKeep = 'first'): ...
    def dropna(self, how: AnyAll = 'any') -> Self: ...
    def get_level_values(self, level: str | int) -> Index: ...
    def unique(self, level=None): ...
    def to_frame(  # pyrefly: ignore
        self,
        index: bool = True,
        name: list[HashableT] = ...,
        allow_duplicates: bool = False,
    ) -> pd.DataFrame: ...
    def to_flat_index(self): ...
    def remove_unused_levels(self): ...
    @property
    def nlevels(self) -> int: ...
    @property
    def levshape(self): ...
    def __reduce__(self): ...
    @overload  # type: ignore[override]
    def __getitem__(
        self,
        idx: slice | np_ndarray_anyint | Sequence[int] | Index | MaskType,
    ) -> Self: ...
    @overload
    def __getitem__(  # pyright: ignore[reportIncompatibleMethodOverride]
        self, key: int
    ) -> tuple: ...
    def take(
        self, indices, axis: int = 0, allow_fill: bool = True, fill_value=None, **kwargs
    ): ...
    def append(self, other): ...
    def argsort(self, *args, **kwargs): ...
    def repeat(self, repeats, axis=None): ...
    def where(self, cond, other=None) -> None: ...
    def drop(self, codes, level=None, errors: str = 'raise') -> Self: ...  # type: ignore[override] # pyright: ignore[reportIncompatibleMethodOverride]
    def swaplevel(self, i: int = -2, j: int = -1): ...
    def reorder_levels(self, order): ...
    def sortlevel(
        self,
        level: Level | Sequence[Level] = 0,
        ascending: bool = True,
        sort_remaining: bool = True,
        na_position: NaPosition = 'first',
    ): ...
    def get_indexer(self, target, method=None, limit=None, tolerance=None): ...
    def get_indexer_non_unique(self, target): ...
    def reindex(self, target, method=None, level=None, limit=None, tolerance=None): ...
    def get_slice_bound(
        self, label: Hashable | Sequence[Hashable], side: str
    ) -> int: ...
    def get_loc_level(self, key, level=0, drop_level: bool = True): ...
    def get_locs(self, seq): ...
    def truncate(self, before=None, after=None): ...
    def equals(self, other) -> bool: ...
    def equal_levels(self, other): ...
    def union(self, other, sort=None): ...  # pyrefly: ignore
    def intersection(  # pyright: ignore[reportIncompatibleMethodOverride]
        self, other: list | Self, sort: bool | None = False
    ): ...
    def difference(self, other, sort=None): ...
    def astype(self, dtype: DtypeArg, copy: bool = True) -> Self: ...
    def insert(self, loc, item): ...
    def delete(self, loc): ...
    def isin(self, values, level=None) -> np_ndarray_bool: ...
