from collections.abc import Hashable, Sequence
from typing import Any, final, overload

import numpy as np
from pandas._typing import HashableT, MaskType, np_1darray, np_ndarray_anyint
from pandas.core.indexes.base import Index, _IndexSubclassBase

class RangeIndex(_IndexSubclassBase[int, np.int64]):
    def __new__(
        cls,
        start: int | RangeIndex | range = None,
        stop: int = None,
        step: int = None,
        dtype: Any=None,
        copy: bool = False,
        name: Hashable = None,
    ) -> Any: ...
    @classmethod
    def from_range(cls, data: Any, name: Hashable = None, dtype: Any=None) -> Any: ...
    def __reduce__(self) -> Any: ...
    @property
    def start(self) -> int: ...
    @property
    def stop(self) -> int: ...
    @property
    def step(self) -> int: ...
    @property
    def nbytes(self) -> int: ...
    def memory_usage(self, deep: bool = False) -> int: ...
    @property
    def dtype(self) -> np.dtype: ...
    @property
    def is_unique(self) -> bool: ...
    @property
    def is_monotonic_increasing(self) -> bool: ...
    @property
    def is_monotonic_decreasing(self) -> bool: ...
    @property
    def has_duplicates(self) -> bool: ...
    def __contains__(self, key: int | np.integer) -> bool: ...
    @final
    def get_indexer(self, target: Any, method: Any=None, limit: Any=None, tolerance: Any=None) -> Any: ...
    def tolist(self) -> Any: ...
    def min(self, axis: Any=None, skipna: bool = True, *args: Any, **kwargs: Any) -> Any: ...
    def max(self, axis: Any=None, skipna: bool = True, *args: Any, **kwargs: Any) -> Any: ...
    def argsort(self, *args: Any, **kwargs: Any) -> Any: ...
    def factorize(
        self, sort: bool = False, use_na_sentinel: bool = True
    ) -> tuple[np_1darray[np.intp], RangeIndex]: ...
    def equals(self, other: Any) -> Any: ...
    @final
    def join(
        self,
        other: Any,
        *,
        how: str = 'left',
        level: Any=None,
        return_indexers: bool = False,
        sort: bool = False,
    ) -> Any: ...
    def __len__(self) -> int: ...
    @property
    def size(self) -> int: ...
    def __floordiv__(self, other: Any) -> Any: ...
    def all(self, *args: Any, **kwargs: Any) -> bool: ...
    def any(self, *args: Any, **kwargs: Any) -> bool: ...
    @final
    def union(  # pyrefly: ignore
        self, other: list[HashableT] | Index[Any], sort: bool | None = None
    ) -> Index[Any] | Index[int] | RangeIndex: ...
    @overload  # type: ignore[override]
    def __getitem__(
        self,
        idx: slice | np_ndarray_anyint | Sequence[int] | Index[Any] | MaskType,
    ) -> Index[Any]: ...
    @overload
    def __getitem__(  # pyright: ignore[reportIncompatibleMethodOverride]
        self, idx: int
    ) -> int: ...
