"""
This type stub file was generated by pyright.
"""

'''Defines functions for cheat-hashing various types.'''
def cheat_hash_object(thing): # -> int:
    '''Cheat-hash an `object`.'''
    ...

def cheat_hash_set(my_set): # -> int:
    '''Cheat-hash a `set`.'''
    ...

def cheat_hash_sequence(my_sequence): # -> int:
    '''Cheat-hash a sequence.'''
    ...

def cheat_hash_dict(my_dict): # -> int:
    '''Cheat-hash a `dict`.'''
    ...

