"""
This type stub file was generated by pyright.
"""

'''
Defines the `cheat_hash` function for cheat-hashing mutable objects.

See its documentation for more details.
'''
infinity = ...
dispatch_map = ...
def cheat_hash(thing):
    '''
    Cheat-hash an object. Works on mutable objects.

    This is a replacement for `hash` which generates something like an hash for
    an object, even if it is mutable, unhashable and/or refers to
    mutable/unhashable objects.

    This is intended for situtations where you have mutable objects that you
    never modify, and you want to be able to hash them despite Python not
    letting you.
    '''
    ...

