from collections.abc import Callable
from torch import Tensor
from typing import Any

def exists(v) -> bool:
    ...

def default(v, d):
    ...

def identity(t, *args, **kwargs):
    ...

def first(arr):
    ...

def compact(arr) -> list[Any]:
    ...

def maybe(fn) -> Callable[..., Any] | _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | None]:
    ...

def safe(fn) -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any | None]:
    ...

def masked_mean(t, mask=..., dim=..., eps=...):
    ...

def shape_with_replace(t, replace_dict: dict[int, int] | None = ...) -> Size:
    ...

def slice_at_dim(t, slc, dim=...):
    ...

def slice_left_at_dim(t, length, dim=...):
    ...

def slice_right_at_dim(t: Tensor, length: int, dim:int=...) -> Tensor:
    ...

def pad_ndim(t, ndims: tuple[int, int]):
    ...

def pad_left_ndim(t, ndims: int):
    ...

def pad_right_ndim(t, ndims: int):
    ...

def pad_right_ndim_to(t, ndims: int):
    ...

def pad_left_ndim_to(t, ndims: int):
    ...

def align_dims_left(tensors, *, ndim=...) -> tuple[Any, ...]:
    ...

def safe_stack(tensors, dim=...) -> Tensor | None:
    ...

@safe
def safe_cat(tensors, dim=...) -> Tensor:
    ...

def lens_to_mask(lens, max_len=...):
    ...

@safe
def reduce_masks(masks, op):
    ...

def and_masks(*masks: Tensor | None) -> Tensor:
    ...

def or_masks(masks):
    ...

def pad_at_dim(t, pad: tuple[int, int], *, dim=..., value=...) -> Tensor:
    ...

def pad_left_at_dim(t, pad: int, **kwargs) -> Tensor:
    ...

def pad_right_at_dim(t, pad: int, **kwargs) -> Tensor:
    ...

def pad_left_at_dim_to(t, length: int, dim=..., **kwargs) -> Tensor:
    ...

def pad_right_at_dim_to(t, length: int, dim=..., **kwargs) -> Tensor:
    ...

def pad_sequence(tensors, *, dim=..., value=..., left=..., dim_stack=..., return_stacked=..., return_lens=..., pad_lens=...) -> Tensor | list[Tensor] | tuple[Tensor | list[Tensor], Tensor] | None:
    ...

def pad_sequence_and_cat(tensors, *, dim_cat=..., **kwargs):
    ...

def tree_map_tensor(fn, tree) -> PyTree:
    ...

def tree_flatten_with_inverse(tree) -> tuple[list[Any], Callable[..., PyTree]]:
    ...

def pack_with_inverse(t, pattern) -> tuple[Tensor, Callable[..., Any | list[Any]]]:
    ...

