from _typeshed import Incomplete
from dataclasses import dataclass
from enum import IntEnum
from glyphsLib.builder.constants import HINTS_LIB_KEY as HINTS_LIB_KEY, SHAPE_ORDER_LIB_KEY as SHAPE_ORDER_LIB_KEY
from ufo2ft.filters import BaseFilter

logger: Incomplete

class Alignment(IntEnum):
    OUTSTROKE = 0
    INSTROKE = 1
    MIDDLE = 2
    UNUSED = 3
    UNALIGNED = 4

def otRoundNode(node): ...
def as_tuples(pts): ...
def get_next_segment(path, index): ...
def get_previous_segment(path, index): ...
def closest_point_on_segment(seg, pt): ...
def closest_point_on_line(seg, pt): ...
def closest_point_on_cubic(bez, pt, start: float = 0.0, end: float = 1.0, iterations: int = 5, slices: int = 5): ...
def unbounded_seg_seg_intersection(seg1, seg2): ...
def point_on_seg_at_distance(seg, distance): ...
def split_cubic_at_point(seg, point, inward: bool = True): ...

@dataclass
class CornerComponentApplier:
    corner_name: str
    glyph_name: str
    alignment: Alignment
    glyph: object
    path_index: int
    corner_path: object
    other_paths: list
    target_node: object
    target_node_ix: int = ...
    origin: tuple[int, int] = ...
    effective_start: tuple[int, int] = ...
    effective_end: tuple[int, int] = ...
    scale: tuple[int, int] = ...
    left_x: int = ...
    right_x: int = ...
    outstroke_intersection_point: tuple[int, int] = ...
    def fail(self, msg, hard: bool = True) -> None: ...
    @property
    def instroke(self): ...
    @property
    def outstroke(self): ...
    @property
    def first_seg(self): ...
    @property
    def last_seg(self): ...
    path = ...
    flipped = ...
    def apply(self) -> None: ...
    def determine_start_and_end_vectors(self) -> None: ...
    def scale_paths(self) -> None: ...
    def align_my_path_to_main_path(self): ...
    def recompute_instroke_intersection_point(self): ...
    def recompute_outstroke_intersection_point(self, original_outstroke): ...
    def split_instroke(self, intersection) -> None: ...
    def fixup_outstroke(self, original_outstroke, intersection) -> None: ...
    def stretch_first_seg_to_fit(self, intersection) -> None: ...
    def reverse_corner_path(self) -> None: ...
    def insert_other_paths(self) -> None: ...

class CornerComponentsFilter(BaseFilter):
    def filter(self, glyph): ...

