import fontTools.pens.basePen
import ufo2ft.filters.base

def _pointIsLeftOfLine(line, aPoint): ...

class EraseOpenCornersPen(fontTools.pens.basePen.BasePen):
    def __init__(self, outpen) -> None: ...
    def _moveTo(self, p1): ...
    def _operate(self, *points): ...
    def _qCurveTo(self, *points): ...
    def _curveTo(self, *points): ...
    def _lineTo(self, *points): ...
    def _qCurveToOne(self, *points): ...
    def _curveToOne(self, *points): ...
    def closePath(self): ...
    def endPath(self): ...

class EraseOpenCornersFilter(ufo2ft.filters.base.BaseFilter):
    def filter(self, glyph): ...

