from pandas._typing import AnyArrayLike, ListLike, np_1darray_bool, ScalarIndexer
from typing import overload

@overload
def check_array_indexer(array: AnyArrayLike, indexer: ScalarIndexer) -> int: ...
@overload
def check_array_indexer(array: AnyArrayLike, indexer: slice) -> slice: ...
@overload
def check_array_indexer(array: AnyArrayLike, indexer: ListLike) -> np_1darray_bool: ...
