from fontTools.varLib.models import normalizeValue as normalizeValue

def _denormalize(v, triplet): ...
def map(font, location, *, inputNormalized: bool = False, outputNormalized: bool = False, dropZeroes: bool = False): ...
def main(args=None) -> None:
    """Map variation coordinates through the `avar` table."""
