from _typeshed import Incomplete

class DuplicatedNameError(NameError): ...

class NameScope:
    _useset: Incomplete
    _basenamemap: Incomplete
    def __init__(self) -> None: ...
    def is_used(self, name): ...
    def register(self, name, deduplicate: bool = False): ...
    def deduplicate(self, name): ...
    def get_child(self): ...

class _StrCaching:
    def _clear_string_cache(self) -> None: ...
    def __str__(self) -> str: ...

class _StringReferenceCaching:
    def get_reference(self): ...

class _HasMetadata:
    def set_metadata(self, name, node) -> None:
        """
        Attach unnamed metadata *node* to the metadata slot *name* of this
        value.
        """
    def _stringify_metadata(self, leading_comma: bool = False): ...
