from typing import Protocol, TypeVar

T = TypeVar('T')

class RingElement(Protocol):
    """A ring element.

    Must support ``+``, ``-``, ``*``, ``**`` and ``-``.
    """
    def __add__(self, other: T) -> T: ...
    def __sub__(self, other: T) -> T: ...
    def __mul__(self, other: T) -> T: ...
    def __pow__(self, other: int) -> T: ...
    def __neg__(self) -> T: ...
