from torch.autograd import Function

def exists(v): ...
def default(v, d): ...
def cache_by_id(fn): ...
@cache_by_id
def get_autotuned_kernel(kernel_fn, configs_fn, keys, blk_d, elem_bytes, device_idx: int = 0): ...
def flash_attn_forward(q, k, v, freqs=None, pope_bias=None, mask=None, causal: bool = False, softmax_scale=None, dropout: float = 0.0, drop_seed: int = 0): ...
def flash_attn_backward(do, q, k, v, o, lse, dq, dk, dv, dfreqs=None, dpope_bias=None, freqs=None, pope_bias=None, mask=None, causal: bool = False, softmax_scale=None, dropout: float = 0.0, drop_seed: int = 0): ...

class FlashAttnFunction(Function):
    @staticmethod
    def forward(ctx, q, k, v, freqs=None, pope_bias=None, mask=None, causal: bool = False, softmax_scale=None, dropout: float = 0.0): ...
    @staticmethod
    def backward(ctx, do): ...

def flash_attn(q, k, v, freqs=None, pope_bias=None, mask=None, causal: bool = False, softmax_scale=None, dropout: float = 0.0): ...
