from collections.abc import Callable
from triton.runtime.autotuner import Autotuner
from triton.runtime.jit import JITFunction
import torch
import triton
import triton.language as tl

def softplus(x: tl.tensor) -> tl.tensor: ...
def softplus_grad(x: tl.tensor) -> tl.tensor: ...
def cache_by_id(fn: Callable[..., Autotuner]) -> Callable[..., Autotuner]: ...
@cache_by_id
def get_autotuned_kernel(kernel_fn: JITFunction[torch.Tensor], configs_fn: Callable[[], list[triton.Config]], keys: list[str], blk_d: int, elem_bytes: int, device_idx: int = 0) -> Autotuner: ...
class _PoPESimilarityContext(torch.autograd.function.FunctionCtx): ...
class PoPESimilarityFunction(torch.autograd.Function):
	@staticmethod
	def forward(ctx: _PoPESimilarityContext, q: torch.Tensor, k: torch.Tensor, freqs: torch.Tensor, bias: torch.Tensor, rotate_dim: int, *, allow_tf32: bool) -> torch.Tensor: ...
	@staticmethod
	def backward(ctx: _PoPESimilarityContext, grad_sim: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor | None, torch.Tensor | None, None, None]: ...

def triton_compute_qk_similarity(q: torch.Tensor, k: torch.Tensor, freqs: torch.Tensor, bias: torch.Tensor, rotate_dim: int, *, allow_tf32: bool = True) -> torch.Tensor: ...
