import torch
import triton

def exists(v): ...
def divisible_by(num, den): ...
@triton.jit
def softplus(x): ...
@triton.jit
def softplus_grad(x): ...
def cache_by_id(fn): ...
@cache_by_id
def get_autotuned_kernel(kernel_fn, configs_fn, keys, blk_d, elem_bytes, device_idx: int = 0): ...

class PoPESimilarityFunction(torch.autograd.Function):
    @staticmethod
    def forward(ctx, q, k, freqs, bias, rotate_dim, allow_tf32): ...
    @staticmethod
    def backward(ctx, grad_sim): ...

def triton_compute_qk_similarity(q, k, freqs, bias, rotate_dim, allow_tf32: bool = True): ...
