from .mix_transformer import mix_transformer_encoders as mix_transformer_encoders
from .supported import TIMM_ENCODERS as TIMM_ENCODERS, TIMM_VIT_ENCODERS as TIMM_VIT_ENCODERS, UNSUPPORTED_ENCODERS as UNSUPPORTED_ENCODERS
from .timm import TimmEncoder as TimmEncoder, TimmViTEncoder as TimmViTEncoder

def list_unsupported_encoders(): ...
def list_encoders(): ...
def get_encoder(name, in_channels: int = 3, depth=None, indices=None, weights=None, output_stride: int = 32, scale_factors=None, **kwargs): ...
