from pandas.core.dtypes.generic import ABCDataFrame as ABCDataFrame, ABCSeries as ABCSeries

def flex_binary_moment(arg1, arg2, f, pairwise: bool = False): ...
def zsqrt(x): ...
def prep_binary(arg1, arg2): ...
