import functools
from pandas.compat._optional import import_optional_dependency as import_optional_dependency
from pandas.core.util.numba_ import jit_user_function as jit_user_function

TYPE_CHECKING: bool
generate_numba_apply_func: functools._lru_cache_wrapper
generate_numba_ewm_func: functools._lru_cache_wrapper
generate_numba_table_func: functools._lru_cache_wrapper
generate_manual_numpy_nan_agg_with_axis: functools._lru_cache_wrapper
generate_numba_ewm_table_func: functools._lru_cache_wrapper
