"""
This type stub file was generated by pyright.
"""

"""Helpers to build or extract data from feaLib AST objects."""
self = ...
def getScriptLanguageSystems(feaFile, excludeDflt=...): # -> OrderedDict[Any, Any]:
    """Return dictionary keyed by Unicode script code containing lists of
    (OT_SCRIPT_TAG, [OT_LANGUAGE_TAG, ...]) tuples (excluding "DFLT" by default,
    unless excludeDflt is False).
    """
    ...

def iterFeatureBlocks(feaFile, tag=...): # -> Generator[FeatureBlock, Any, None]:
    ...

def findFeatureTags(feaFile): # -> set[Any]:
    ...

def findCommentPattern(feaFile, pattern): # -> Generator[tuple[Any, *tuple[Any | Comment, ...]] | tuple[Comment], Any, None]:
    """
    Yield a tuple of statements, starting with the parent block, followed by
    nested blocks if present, ending with the comment matching a given pattern.
    There is not parent block if the matched comment is a the root level.
    """
    ...

def findTable(feaLib, tag): # -> TableBlock | None:
    ...

def iterClassDefinitions(feaFile): # -> Generator[GlyphClassDefinition | Any, Any, None]:
    ...

LOOKUP_FLAGS = ...
def makeLookupFlag(flags=..., markAttachment=..., markFilteringSet=...): # -> LookupFlagStatement:
    ...

def makeGlyphClassDefinitions(groups, feaFile=..., stripPrefix=...): # -> dict[Any, Any]:
    """Given a groups dictionary ({str: list[str]}), create feaLib
    GlyphClassDefinition objects for each group.
    Return a dict keyed by the original group name.

    If `stripPrefix` (str) is provided and a group name starts with it,
    the string will be stripped from the beginning of the class name.
    """
    ...

def makeGlyphClassDefinition(className, members): # -> GlyphClassDefinition:
    ...

def makeFeaClassName(name, existingClassNames=...): # -> str:
    """Make a glyph class name which is legal to use in feature text.

    Ensures the name only includes characters in "A-Za-z0-9._", and
    isn't already defined.
    """
    ...

def addLookupReferences(feature, lookups, script=..., languages=..., exclude_dflt=...): # -> None:
    """Add references to named lookups to the feature's statements.
    If `script` (str) and `languages` (sequence of str) are provided,
    only register the lookup for the given script and languages,
    optionally with `exclude_dflt` directive.
    Otherwise add a global reference which will be registered for all
    the scripts and languages in the feature file's `languagesystems`
    statements.
    """
    ...

_GDEFGlyphClasses = ...
def getGDEFGlyphClasses(feaLib): # -> _GDEFGlyphClasses:
    """Return GDEF GlyphClassDef base/mark/ligature/component glyphs, or
    None if no GDEF table is defined in the feature file.
    """
    ...

