from . import _backend_gtk as _backend_gtk
from ._backend_gtk import _BackendGTK as _BackendGTK, _FigureCanvasGTK as _FigureCanvasGTK, _FigureManagerGTK as _FigureManagerGTK, _NavigationToolbar2GTK as _NavigationToolbar2GTK
from _typeshed import Incomplete
from gi.repository import Gtk
from matplotlib import _api as _api, backend_tools as backend_tools, cbook as cbook
from matplotlib.backend_bases import CloseEvent as CloseEvent, KeyEvent as KeyEvent, LocationEvent as LocationEvent, MouseButton as MouseButton, MouseEvent as MouseEvent, ResizeEvent as ResizeEvent, ToolContainerBase as ToolContainerBase

_GOBJECT_GE_3_47: Incomplete

class FigureCanvasGTK4(_FigureCanvasGTK, Gtk.DrawingArea):
    required_interactive_framework: str
    supports_blit: bool
    manager_class: Incomplete
    _idle_draw_id: int
    _rubberband_rect: Incomplete
    def __init__(self, figure: Incomplete | None = None) -> None: ...
    def destroy(self) -> None: ...
    def set_cursor(self, cursor) -> None: ...
    def _mpl_coords(self, xy: Incomplete | None = None):
        """
        Convert the *xy* position of a GTK event, or of the current cursor
        position if *xy* is None, to Matplotlib coordinates.

        GTK use logical pixels, but the figure is scaled to physical pixels for
        rendering.  Transform to physical pixels so that all of the down-stream
        transforms work as expected.

        Also, the origin is different and needs to be corrected.
        """
    def scroll_event(self, controller, dx, dy): ...
    def button_press_event(self, controller, n_press, x, y) -> None: ...
    def button_release_event(self, controller, n_press, x, y) -> None: ...
    def key_press_event(self, controller, keyval, keycode, state): ...
    def key_release_event(self, controller, keyval, keycode, state): ...
    def motion_notify_event(self, controller, x, y) -> None: ...
    def enter_notify_event(self, controller, x, y) -> None: ...
    def leave_notify_event(self, controller) -> None: ...
    def resize_event(self, area, width, height) -> None: ...
    def _mpl_buttons(self, controller): ...
    def _mpl_modifiers(self, controller: Incomplete | None = None): ...
    def _get_key(self, keyval, keycode, state): ...
    def _update_device_pixel_ratio(self, *args, **kwargs) -> None: ...
    def _draw_rubberband(self, rect) -> None: ...
    def _draw_func(self, drawing_area, ctx, width, height) -> None: ...
    def _post_draw(self, widget, ctx) -> None: ...
    def on_draw_event(self, widget, ctx) -> None: ...
    def draw(self) -> None: ...
    def draw_idle(self): ...
    def flush_events(self) -> None: ...

class NavigationToolbar2GTK4(_NavigationToolbar2GTK, Gtk.Box):
    _gtk_ids: Incomplete
    message: Incomplete
    def __init__(self, canvas) -> None: ...
    _save_dialog: Incomplete
    def save_figure(self, *args): ...

class ToolbarGTK4(ToolContainerBase, Gtk.Box):
    _icon_extension: str
    _tool_box: Incomplete
    _groups: Incomplete
    _toolitems: Incomplete
    _message: Incomplete
    def __init__(self, toolmanager) -> None: ...
    def add_toolitem(self, name, group, position, image_file, description, toggle) -> None: ...
    def _find_child_at_position(self, group, position): ...
    def _add_button(self, button, group, position) -> None: ...
    def _call_tool(self, btn, name) -> None: ...
    def toggle_toolitem(self, name, toggled) -> None: ...
    def remove_toolitem(self, name) -> None: ...
    def _add_separator(self) -> None: ...
    def set_message(self, s) -> None: ...

class SaveFigureGTK4(backend_tools.SaveFigureBase):
    def trigger(self, *args, **kwargs) -> None: ...

class HelpGTK4(backend_tools.ToolHelpBase):
    def _normalize_shortcut(self, key):
        """
        Convert Matplotlib key presses to GTK+ accelerator identifiers.

        Related to `FigureCanvasGTK4._get_key`.
        """
    def _is_valid_shortcut(self, key):
        """
        Check for a valid shortcut to be displayed.

        - GTK will never send 'cmd+' (see `FigureCanvasGTK4._get_key`).
        - The shortcut window only shows keyboard shortcuts, not mouse buttons.
        """
    def trigger(self, *args) -> None: ...

class ToolCopyToClipboardGTK4(backend_tools.ToolCopyToClipboardBase):
    def trigger(self, *args, **kwargs) -> None: ...
Toolbar = ToolbarGTK4

class FigureManagerGTK4(_FigureManagerGTK):
    _toolbar2_class = NavigationToolbar2GTK4
    _toolmanager_toolbar_class = ToolbarGTK4

class _BackendGTK4(_BackendGTK):
    FigureCanvas = FigureCanvasGTK4
    FigureManager = FigureManagerGTK4
