from _typeshed import Incomplete
from collections.abc import Hashable, Iterable, Mapping
from pandas import DataFrame as DataFrame, Series as Series
from pandas._typing import Axis as Axis, AxisInt as AxisInt, HashableT as HashableT
from pandas.core.arrays.categorical import factorize_from_iterable as factorize_from_iterable, factorize_from_iterables as factorize_from_iterables
from pandas.core.dtypes.common import is_bool as is_bool, is_iterator as is_iterator
from pandas.core.dtypes.generic import ABCDataFrame as ABCDataFrame, ABCSeries as ABCSeries
from pandas.core.indexes.api import Index as Index, MultiIndex as MultiIndex, all_indexes_same as all_indexes_same, default_index as default_index, ensure_index as ensure_index, get_objs_combined_axis as get_objs_combined_axis, get_unanimous_names as get_unanimous_names
from typing import Literal, overload

@overload
def concat(objs: Iterable[DataFrame] | Mapping[HashableT, DataFrame], *, axis: Literal[0, 'index'] = ..., join: str = ..., ignore_index: bool = ..., keys: Iterable[Hashable] | None = ..., levels=..., names: list[HashableT] | None = ..., verify_integrity: bool = ..., sort: bool = ..., copy: bool | None = ...) -> DataFrame: ...
@overload
def concat(objs: Iterable[Series] | Mapping[HashableT, Series], *, axis: Literal[0, 'index'] = ..., join: str = ..., ignore_index: bool = ..., keys: Iterable[Hashable] | None = ..., levels=..., names: list[HashableT] | None = ..., verify_integrity: bool = ..., sort: bool = ..., copy: bool | None = ...) -> Series: ...
@overload
def concat(objs: Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame], *, axis: Literal[0, 'index'] = ..., join: str = ..., ignore_index: bool = ..., keys: Iterable[Hashable] | None = ..., levels=..., names: list[HashableT] | None = ..., verify_integrity: bool = ..., sort: bool = ..., copy: bool | None = ...) -> DataFrame | Series: ...
@overload
def concat(objs: Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame], *, axis: Literal[1, 'columns'], join: str = ..., ignore_index: bool = ..., keys: Iterable[Hashable] | None = ..., levels=..., names: list[HashableT] | None = ..., verify_integrity: bool = ..., sort: bool = ..., copy: bool | None = ...) -> DataFrame: ...
@overload
def concat(objs: Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame], *, axis: Axis = ..., join: str = ..., ignore_index: bool = ..., keys: Iterable[Hashable] | None = ..., levels=..., names: list[HashableT] | None = ..., verify_integrity: bool = ..., sort: bool = ..., copy: bool | None = ...) -> DataFrame | Series: ...

class _Concatenator:
    """
    Orchestrates a concatenation operation for BlockManagers
    """
    sort: bool
    intersect: bool
    ignore_index: Incomplete
    verify_integrity: Incomplete
    copy: Incomplete
    _is_frame: bool
    _is_series: bool
    objs: Incomplete
    bm_axis: Incomplete
    axis: Incomplete
    keys: Incomplete
    names: Incomplete
    levels: Incomplete
    def __init__(self, objs: Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame], axis: Axis = 0, join: str = 'outer', keys: Iterable[Hashable] | None = None, levels: Incomplete | None = None, names: list[HashableT] | None = None, ignore_index: bool = False, verify_integrity: bool = False, copy: bool = True, sort: bool = False) -> None: ...
    def _get_ndims(self, objs: list[Series | DataFrame]) -> set[int]: ...
    def _clean_keys_and_objs(self, objs: Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame], keys) -> tuple[list[Series | DataFrame], Index | None]: ...
    def _get_sample_object(self, objs: list[Series | DataFrame], ndims: set[int], keys, names, levels) -> tuple[Series | DataFrame, list[Series | DataFrame]]: ...
    def _sanitize_mixed_ndim(self, objs: list[Series | DataFrame], sample: Series | DataFrame, ignore_index: bool, axis: AxisInt) -> list[Series | DataFrame]: ...
    def get_result(self): ...
    def _get_result_dim(self) -> int: ...
    def new_axes(self) -> list[Index]: ...
    def _get_comb_axis(self, i: AxisInt) -> Index: ...
    def _get_concat_axis(self) -> Index:
        """
        Return index to be used along concatenation axis.
        """
    def _maybe_check_integrity(self, concat_index: Index): ...

def _concat_indexes(indexes) -> Index: ...
def _make_concat_multiindex(indexes, keys, levels: Incomplete | None = None, names: Incomplete | None = None) -> MultiIndex: ...
