"""
This type stub file was generated by pyright.
"""

from compreffor.pyCompressor import CandidateSubr
from compreffor import timer

"""
Tool to subroutinize a CFF OpenType font. Backed by a C++ binary.

This file is a bootstrap for the C++ edition of the FontTools compreffor.
It prepares the input data for the extension and reads back in the results,
applying them to the input font.

Usage (command line):
>> ./cxxCompressor.py /path/to/font.otf
# font written to /path/to/font.compressed.otf

Usage (python):
>> font = TTFont("/path/to/font.otf")
>> cxxCompressor.compreff(font)
>> font.save("/path/to/output.otf")
"""
log = ...
__all__ = ["compreff"]
class IdKeyMap:
    """A map that where every key's value is itself. Used
    as a map from simplified key space to actual key space
    in pyCompressor"""
    def __getitem__(self, tok):
        ...
    


class SimpleCandidateSubr(CandidateSubr):
    """A reimplimentation of CandidateSubr to be more
    compatible with results from C++"""
    def __init__(self, length, ref_loc) -> None:
        ...
    
    def usages(self): # -> int:
        ...
    
    frequency = ...
    def cost(self):
        ...
    
    def encoding(self):
        ...
    


@timer("produce data for C++ library")
def write_data(td): # -> bytes:
    """Writes CharStrings from the TopDict td into a string that is easily
    readable."""
    ...

def get_encoding(data_buffer, subrs): # -> tuple[list[Any], int]:
    """Read a charstring's encoding stream out of a string buffer response
    from cffCompressor.cc"""
    ...

def read_data(td, result_string): # -> tuple[list[Any], list[Any]]:
    """Read the output of cffCompressor.cc into Python data
    structures."""
    ...

@timer("extract results")
def interpret_data(td, results): # -> tuple[list[Any], list[Any]]:
    """Interpret the result array from a lib.compreff call to
    produce Python data structures."""
    class MutableSpace:
        ...
    
    

@timer("compress the font")
def compreff(font, nrounds=..., max_subrs=...): # -> None:
    """Main function that compresses `font`, a TTFont object,
    in place.
    """
    ...

