from typing import Any
class TablePlotter:
    cell_width = ...
    cell_height = ...
    font_size = ...
    def __init__(
        self, cell_width: float = 0.37, cell_height: float = 0.25, font_size: float = 7.5
    ) -> None: ...
    def plot(self, left: Any, right: Any, labels: Any=(), vertical: bool = True) -> Any: ...
