from _typeshed import Incomplete
from fontTools.merge.base import add_method as add_method, mergeObjects as mergeObjects

log: Incomplete

def mergeLookupLists(lst): ...
def mergeFeatures(lst): ...
def mergeFeatureLists(lst): ...
def mergeLangSyses(lst): ...
def mergeScripts(lst): ...
def mergeScriptRecords(lst): ...
def merge(self, m, tables): ...
def mapLookups(self, lookupMap) -> None: ...
def __merge_classify_context(self): ...
def layoutPreMerge(font) -> None: ...
def layoutPostMerge(font) -> None: ...
