"""
This type stub file was generated by pyright.
"""

from fontTools import ttLib
from fontTools.ttLib.tables import otTables
from fontTools.merge.base import add_method
from fontTools.merge.util import *

log = ...
def mergeLookupLists(lst): # -> list[Any]:
    ...

def mergeFeatures(lst):
    ...

def mergeFeatureLists(lst): # -> list[Any]:
    ...

def mergeLangSyses(lst):
    ...

def mergeScripts(lst):
    ...

def mergeScriptRecords(lst): # -> list[Any]:
    ...

@add_method(ttLib.getTableClass("GSUB"))
def merge(self, m, tables):
    ...

@add_method(otTables.SingleSubst, otTables.MultipleSubst, otTables.AlternateSubst, otTables.LigatureSubst, otTables.ReverseChainSingleSubst, otTables.SinglePos, otTables.PairPos, otTables.CursivePos, otTables.MarkBasePos, otTables.MarkLigPos, otTables.MarkMarkPos)
def mapLookups(self, lookupMap): # -> None:
    ...

@add_method(otTables.ContextSubst, otTables.ChainContextSubst, otTables.ContextPos, otTables.ChainContextPos)
def mapLookups(self, lookupMap): # -> None:
    ...

@add_method(otTables.ExtensionSubst, otTables.ExtensionPos)
def mapLookups(self, lookupMap): # -> None:
    ...

@add_method(otTables.Lookup)
def mapLookups(self, lookupMap): # -> None:
    ...

@add_method(otTables.LookupList)
def mapLookups(self, lookupMap): # -> None:
    ...

@add_method(otTables.Lookup)
def mapMarkFilteringSets(self, markFilteringSetMap): # -> None:
    ...

@add_method(otTables.LookupList)
def mapMarkFilteringSets(self, markFilteringSetMap): # -> None:
    ...

@add_method(otTables.Feature)
def mapLookups(self, lookupMap): # -> None:
    ...

@add_method(otTables.FeatureList)
def mapLookups(self, lookupMap): # -> None:
    ...

@add_method(otTables.DefaultLangSys, otTables.LangSys)
def mapFeatures(self, featureMap): # -> None:
    ...

@add_method(otTables.Script)
def mapFeatures(self, featureMap): # -> None:
    ...

@add_method(otTables.ScriptList)
def mapFeatures(self, featureMap): # -> None:
    ...

def layoutPreMerge(font): # -> None:
    ...

def layoutPostMerge(font): # -> None:
    ...

