from google.auth import environment_vars as environment_vars, exceptions as exceptions, metrics as metrics, transport as transport
from google.auth._exponential_backoff import ExponentialBackoff as ExponentialBackoff

def is_on_gce(request): ...
def detect_gce_residency_linux(): ...
def ping(request, timeout=..., retry_count: int = 3): ...
def get(request, path, root=None, params=None, recursive: bool = False, retry_count: int = 5, headers=None, return_none_for_not_found_error: bool = False, timeout=...): ...
def get_project_id(request): ...
def get_universe_domain(request): ...
def get_service_account_info(request, service_account: str = 'default'): ...
def get_service_account_token(request, service_account: str = 'default', scopes=None): ...
