from _typeshed import Incomplete
from google.auth import credentials as credentials, exceptions as exceptions, iam as iam, jwt as jwt, metrics as metrics

class Credentials(credentials.Scoped, credentials.CredentialsWithQuotaProject, credentials.CredentialsWithUniverseDomain, credentials.CredentialsWithTrustBoundary):
    def __init__(self, service_account_email: str = 'default', quota_project_id=None, scopes=None, default_scopes=None, universe_domain=None, trust_boundary=None) -> None: ...
    @property
    def service_account_email(self): ...
    @property
    def requires_scopes(self): ...
    @property
    def universe_domain(self): ...
    def get_cred_info(self): ...
    def with_quota_project(self, quota_project_id): ...
    def with_scopes(self, scopes, default_scopes=None): ...
    def with_universe_domain(self, universe_domain): ...
    def with_trust_boundary(self, trust_boundary): ...

class IDTokenCredentials(credentials.CredentialsWithQuotaProject, credentials.Signing, credentials.CredentialsWithTokenUri):
    def __init__(self, request, target_audience, token_uri=None, additional_claims=None, service_account_email=None, signer=None, use_metadata_identity_endpoint: bool = False, quota_project_id=None) -> None: ...
    def with_target_audience(self, target_audience): ...
    def with_quota_project(self, quota_project_id): ...
    def with_token_uri(self, token_uri): ...
    token: Incomplete
    expiry: Incomplete
    def refresh(self, request) -> None: ...
    @property
    def signer(self): ...
    def sign_bytes(self, message): ...
    @property
    def service_account_email(self): ...
    @property
    def signer_email(self): ...
