from typing import Any

"""
This type stub file was generated by pyright.
"""

class CuteBaseTimer:
    """A base class for timers, allowing easy central stopping."""

    __timers = ...
    def __init__(self, parent: Any) -> None:
        ...

    @staticmethod
    def stop_timers_by_frame(frame: Any) -> Any: # -> None:
        """Stop all the timers that are associated with the given frame."""






