from typing import Any

"""
This type stub file was generated by pyright.
"""

from python_toolbox.wx_tools.timing import cute_base_timer
import threading

wxEVT_THREAD_TIMER = ...
EVT_THREAD_TIMER = ...
class ThreadTimer(cute_base_timer.CuteBaseTimer):
    """
    A timer for a wxPython app which runs on a different thread.

    This solved a problem of wxPython timers being late when the program is
    busy.
    """

    n = ...
    _EventHandlerGrokker__event_code = ...
    def __init__(self, parent: Any) -> None:
        """
        Construct the ThreadTimer.

        `parent` is the parent window.
        """

    def start(self, interval: Any) -> Any: # -> None:
        """Start the timer."""

    def stop(self) -> Any: # -> None:
        """Stop the timer."""

    Start = ...
    Stop = ...
    def GetId(self) -> Any:
        """Get the wx ID of this timer."""



class Thread(threading.Thread):
    """Thread used as a timer for wxPython programs."""

    def __init__(self, parent: Any, name: Any) -> None:
        ...

    def run(self) -> Any: # -> None:
        """Run the thread. Internal function."""






