from _typeshed import Incomplete


def GetExpandedName(Source, /) -> str: ...
def Close(handle, /) -> None: ...
def Copy(hSrc, hDest, /): ...
def Init(handle, /) -> None: ...
def OpenFile(fileName: str, action, /) -> tuple[Incomplete, Incomplete]: ...
