"""
This type stub file was generated by pyright.
"""

"""Routines for converting Attachment rules to and from XML."""
@classmethod
def fromXML(klass, el):
    """Creates a rule from a lxml Element object."""
    ...

