"""
This type stub file was generated by pyright.
"""

"""Routines for converting Rule objects to and from XML."""
@classmethod
def fromXML(klass, el): # -> Any:
    """Creates a Rule from a lxml Element object."""
    ...

def toXML(self):
    """Serializes a Rule to a lxml Element object."""
    ...

