from _typeshed import Incomplete
from fontTools.voltLib.error import VoltLibError as VoltLibError
from typing import NamedTuple

class Pos(NamedTuple):
    adv: int
    dx: int
    dy: int
    adv_adjust_by: dict
    dx_adjust_by: dict
    dy_adjust_by: dict
    def __str__(self) -> str: ...

class Element:
    location: Incomplete
    def __init__(self, location=None) -> None: ...
    def build(self, builder) -> None: ...
    def __str__(self) -> str: ...

class Statement(Element): ...
class Expression(Element): ...

class VoltFile(Statement):
    statements: Incomplete
    def __init__(self) -> None: ...
    def build(self, builder) -> None: ...
    def __str__(self) -> str: ...

class GlyphDefinition(Statement):
    name: Incomplete
    id: Incomplete
    unicode: Incomplete
    type: Incomplete
    components: Incomplete
    def __init__(self, name, gid, gunicode, gtype, components, location=None) -> None: ...
    def __str__(self) -> str: ...

class GroupDefinition(Statement):
    name: Incomplete
    enum: Incomplete
    glyphs_: Incomplete
    def __init__(self, name, enum, location=None) -> None: ...
    def glyphSet(self, groups=None): ...
    def __str__(self) -> str: ...

class GlyphName(Expression):
    """A single glyph name, such as cedilla."""
    glyph: Incomplete
    def __init__(self, glyph, location=None) -> None: ...
    def glyphSet(self): ...
    def __str__(self) -> str: ...

class Enum(Expression):
    """An enum"""
    enum: Incomplete
    def __init__(self, enum, location=None) -> None: ...
    def __iter__(self): ...
    def glyphSet(self, groups=None): ...
    def __str__(self) -> str: ...

class GroupName(Expression):
    """A glyph group"""
    group: Incomplete
    parser_: Incomplete
    def __init__(self, group, parser, location=None) -> None: ...
    glyphs_: Incomplete
    def glyphSet(self, groups=None): ...
    def __str__(self) -> str: ...

class Range(Expression):
    """A glyph range"""
    start: Incomplete
    end: Incomplete
    parser: Incomplete
    def __init__(self, start, end, parser, location=None) -> None: ...
    def glyphSet(self): ...
    def __str__(self) -> str: ...

class ScriptDefinition(Statement):
    name: Incomplete
    tag: Incomplete
    langs: Incomplete
    def __init__(self, name, tag, langs, location=None) -> None: ...
    def __str__(self) -> str: ...

class LangSysDefinition(Statement):
    name: Incomplete
    tag: Incomplete
    features: Incomplete
    def __init__(self, name, tag, features, location=None) -> None: ...
    def __str__(self) -> str: ...

class FeatureDefinition(Statement):
    name: Incomplete
    tag: Incomplete
    lookups: Incomplete
    def __init__(self, name, tag, lookups, location=None) -> None: ...
    def __str__(self) -> str: ...

class LookupDefinition(Statement):
    name: Incomplete
    process_base: Incomplete
    process_marks: Incomplete
    mark_glyph_set: Incomplete
    direction: Incomplete
    reversal: Incomplete
    comments: Incomplete
    context: Incomplete
    sub: Incomplete
    pos: Incomplete
    def __init__(self, name, process_base, process_marks, mark_glyph_set, direction, reversal, comments, context, sub, pos, location=None) -> None: ...
    def __str__(self) -> str: ...

class SubstitutionDefinition(Statement):
    mapping: Incomplete
    def __init__(self, mapping, location=None) -> None: ...
    def __str__(self) -> str: ...

class SubstitutionSingleDefinition(SubstitutionDefinition): ...
class SubstitutionMultipleDefinition(SubstitutionDefinition): ...
class SubstitutionLigatureDefinition(SubstitutionDefinition): ...
class SubstitutionAlternateDefinition(SubstitutionDefinition): ...
class SubstitutionReverseChainingSingleDefinition(SubstitutionDefinition): ...

class PositionAttachDefinition(Statement):
    coverage: Incomplete
    coverage_to: Incomplete
    def __init__(self, coverage, coverage_to, location=None) -> None: ...
    def __str__(self) -> str: ...

class PositionAttachCursiveDefinition(Statement):
    coverages_exit: Incomplete
    coverages_enter: Incomplete
    def __init__(self, coverages_exit, coverages_enter, location=None) -> None: ...
    def __str__(self) -> str: ...

class PositionAdjustPairDefinition(Statement):
    coverages_1: Incomplete
    coverages_2: Incomplete
    adjust_pair: Incomplete
    def __init__(self, coverages_1, coverages_2, adjust_pair, location=None) -> None: ...
    def __str__(self) -> str: ...

class PositionAdjustSingleDefinition(Statement):
    adjust_single: Incomplete
    def __init__(self, adjust_single, location=None) -> None: ...
    def __str__(self) -> str: ...

class ContextDefinition(Statement):
    ex_or_in: Incomplete
    left: Incomplete
    right: Incomplete
    def __init__(self, ex_or_in, left=None, right=None, location=None) -> None: ...
    def __str__(self) -> str: ...

class AnchorDefinition(Statement):
    name: Incomplete
    gid: Incomplete
    glyph_name: Incomplete
    component: Incomplete
    locked: Incomplete
    pos: Incomplete
    def __init__(self, name, gid, glyph_name, component, locked, pos, location=None) -> None: ...
    def __str__(self) -> str: ...

class SettingDefinition(Statement):
    name: Incomplete
    value: Incomplete
    def __init__(self, name, value, location=None) -> None: ...
    def __str__(self) -> str: ...
