from _typeshed import Incomplete
from fontTools.feaLib import ast as ast
from fontTools.ttLib import TTFont as TTFont, TTLibError as TTLibError

log: Incomplete
TABLES: Incomplete

def _flatten_group(group): ...
def sort_groups(groups): ...

class Lookup(ast.LookupBlock):
    chained: Incomplete
    def __init__(self, name, use_extension: bool = False, location=None) -> None: ...

class VoltToFea:
    _NOT_LOOKUP_NAME_RE: Incomplete
    _NOT_CLASS_NAME_RE: Incomplete
    _font: Incomplete
    _glyph_map: Incomplete
    _glyph_order: Incomplete
    _gdef: Incomplete
    _glyphclasses: Incomplete
    _features: Incomplete
    _lookups: Incomplete
    _marks: Incomplete
    _ligatures: Incomplete
    _markclasses: Incomplete
    _anchors: Incomplete
    _settings: Incomplete
    _lookup_names: Incomplete
    _class_names: Incomplete
    def __init__(self, file_or_path, font=None) -> None: ...
    def _lookupName(self, name): ...
    def _className(self, name): ...
    def _collectStatements(self, doc, tables, ignore_unsupported_settings: bool = False) -> None: ...
    def _buildFeatureFile(self, tables): ...
    _doc: Incomplete
    def convert(self, tables=None, ignore_unsupported_settings: bool = False): ...
    def _glyphName(self, glyph): ...
    def _groupName(self, group): ...
    def _glyphSet(self, item): ...
    def _coverage(self, coverage, flatten: bool = False): ...
    def _context(self, context): ...
    def _groupDefinition(self, group) -> None: ...
    def _glyphDefinition(self, glyph) -> None: ...
    def _scriptDefinition(self, script) -> None: ...
    def _settingDefinition(self, setting, ignore_unsupported: bool = False) -> None: ...
    def _adjustment(self, adjustment): ...
    def _anchor(self, adjustment): ...
    def _anchorDefinition(self, anchordef) -> None: ...
    def _gposLookup(self, lookup, fealookup) -> None: ...
    def _gposContextLookup(self, lookup, prefix, suffix, ignore, fealookup, chained) -> None: ...
    def _gsubLookup(self, lookup, fealookup) -> None: ...
    def _gsubContextLookup(self, lookup, prefix, suffix, ignore, fealookup, chained) -> None: ...
    def _lookupDefinition(self, lookup) -> None: ...

def main(args=None):
    """Convert MS VOLT to AFDKO feature files."""
