import abc
import types
from ._copy import copy_dir as copy_dir, copy_file as copy_file
from ._errors import DestinationExists as DestinationExists, DirectoryExpected as DirectoryExpected, FileExpected as FileExpected, FilesystemClosed as FilesystemClosed, NoSysPath as NoSysPath, ResourceNotFound as ResourceNotFound
from ._info import Info as Info
from ._path import dirname as dirname
from ._subfs import SubFS as SubFS
from ._walk import BoundWalker as BoundWalker
from abc import ABC, abstractmethod
from typing import Any, Collection, IO, Iterator, Self

class FS(ABC, metaclass=abc.ABCMeta):
    """Abstract base class for custom filesystems."""
    _closed: bool
    @abstractmethod
    def open(self, path: str, mode: str = 'rb', **kwargs) -> IO[Any]: ...
    @abstractmethod
    def exists(self, path: str) -> bool: ...
    @abstractmethod
    def isdir(self, path: str) -> bool: ...
    @abstractmethod
    def isfile(self, path: str) -> bool: ...
    @abstractmethod
    def listdir(self, path: str) -> list[str]: ...
    @abstractmethod
    def makedir(self, path: str, recreate: bool = False) -> SubFS: ...
    @abstractmethod
    def makedirs(self, path: str, recreate: bool = False) -> SubFS: ...
    @abstractmethod
    def getinfo(self, path: str, namespaces: Collection[str] | None = None) -> Info: ...
    @abstractmethod
    def remove(self, path: str) -> None: ...
    @abstractmethod
    def removedir(self, path: str) -> None: ...
    @abstractmethod
    def removetree(self, path: str) -> None: ...
    @abstractmethod
    def movedir(self, src: str, dst: str, create: bool = False) -> None: ...
    def getsyspath(self, path: str) -> str: ...
    def close(self) -> None: ...
    def isclosed(self) -> bool: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: types.TracebackType | None): ...
    def check(self) -> None: ...
    def opendir(self, path: str, *, factory: type[SubFS] | None = None) -> SubFS:
        """Return a sub‑filesystem rooted at `path`."""
    def scandir(self, path: str, namespaces: Collection[str] | None = None) -> Iterator[Info]: ...
    @property
    def walk(self) -> BoundWalker: ...
    def readbytes(self, path: str) -> bytes: ...
    def writebytes(self, path: str, data: bytes): ...
    def create(self, path: str, wipe: bool = False): ...
    def copy(self, src_path: str, dst_path: str, overwrite: bool = False): ...
    def copydir(self, src_path: str, dst_path: str, create: bool = False): ...
