from ._errors import MissingInfoNamespace as MissingInfoNamespace
from _typeshed import Incomplete
from collections.abc import Mapping
from datetime import datetime
from typing import Any

def epoch_to_datetime(t: int | None) -> datetime | None:
    """Convert epoch time to a UTC datetime."""

class Info:
    __slots__: Incomplete
    raw: Incomplete
    namespaces: Incomplete
    def __init__(self, raw_info: Mapping[str, Any]) -> None: ...
    def get(self, namespace: str, key: str, default: Any | None = None) -> Any | None: ...
    @property
    def name(self) -> str: ...
    @property
    def is_dir(self) -> bool: ...
    @property
    def is_file(self) -> bool: ...
    @property
    def accessed(self) -> datetime | None: ...
    @property
    def modified(self) -> datetime | None: ...
    @property
    def size(self) -> int | None: ...
    @property
    def type(self) -> int | None: ...
    @property
    def created(self) -> datetime | None: ...
    @property
    def metadata_changed(self) -> datetime | None: ...
    def __str__(self) -> str: ...
    __repr__ = __str__
