from ._base import FS as FS
from ._errors import CreateFailed as CreateFailed, DirectoryExpected as DirectoryExpected, DirectoryNotEmpty as DirectoryNotEmpty, FileExpected as FileExpected, IllegalDestination as IllegalDestination, ResourceError as ResourceError, ResourceNotFound as ResourceNotFound
from ._info import Info as Info
from ._path import isbase as isbase
from ._subfs import SubFS as SubFS
from _typeshed import Incomplete
from collections.abc import Collection
from os import PathLike
from pathlib import Path
from typing import Any, IO

_WINDOWS_PLATFORM: Incomplete

class OSFS(FS):
    """Filesystem for a directory on the local disk.

    A thin layer on top of `pathlib.Path`.
    """
    _root: Incomplete
    def __init__(self, root: str | PathLike, create: bool = False) -> None: ...
    def _abs(self, rel_path: str) -> Path: ...
    def open(self, path: str, mode: str = 'rb', **kwargs) -> IO[Any]: ...
    def exists(self, path: str) -> bool: ...
    def isdir(self, path: str) -> bool: ...
    def isfile(self, path: str) -> bool: ...
    def listdir(self, path: str) -> list[str]: ...
    def _mkdir(self, path: str, parents: bool = False, exist_ok: bool = False) -> SubFS: ...
    def makedir(self, path: str, recreate: bool = False) -> SubFS: ...
    def makedirs(self, path: str, recreate: bool = False) -> SubFS: ...
    def getinfo(self, path: str, namespaces: Collection[str] | None = None) -> Info: ...
    def remove(self, path: str): ...
    def removedir(self, path: str): ...
    def removetree(self, path: str): ...
    def movedir(self, src_dir: str, dst_dir: str, create: bool = False): ...
    def getsyspath(self, path: str) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
