from _typeshed import Incomplete

_WINDOWS_PLATFORM: Incomplete

def combine(path1: str, path2) -> str: ...
def split(path: str) -> tuple[str, str]: ...
def dirname(path: str) -> str: ...
def basename(path: str) -> str: ...
def forcedir(path: str) -> str: ...
def abspath(path: str) -> str: ...
def isbase(path1: str, path2: str) -> bool: ...
def frombase(path1: str, path2: str) -> str: ...
def relpath(path: str) -> str: ...
def normpath(path: str) -> str: ...
