from ._base import FS as FS
from ._errors import DirectoryExpected as DirectoryExpected, ResourceNotFound as ResourceNotFound
from ._info import Info as Info
from _typeshed import Incomplete
from collections.abc import Collection
from typing import Any, IO

class SubFS(FS):
    """Maps a sub-directory of another filesystem."""
    _parent: Incomplete
    _prefix: Incomplete
    def __init__(self, parent: FS, sub_path: str) -> None: ...
    def delegate_fs(self): ...
    def _full(self, rel: str) -> str: ...
    def open(self, path: str, mode: str = 'rb', **kwargs) -> IO[Any]: ...
    def exists(self, path: str) -> bool: ...
    def isdir(self, path: str) -> bool: ...
    def isfile(self, path: str) -> bool: ...
    def listdir(self, path: str) -> list[str]: ...
    def makedir(self, path: str, recreate: bool = False): ...
    def makedirs(self, path: str, recreate: bool = False): ...
    def getinfo(self, path: str, namespaces: Collection[str] | None = None) -> Info: ...
    def remove(self, path: str): ...
    def removedir(self, path: str): ...
    def removetree(self, path: str): ...
    def movedir(self, src: str, dst: str, create: bool = False): ...
    def getsyspath(self, path: str) -> str: ...
    def readbytes(self, path: str) -> bytes: ...
    def writebytes(self, path: str, data: bytes): ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class ClosingSubFS(SubFS):
    """Like SubFS, but auto-closes the parent filesystem when closed."""
    def close(self) -> None: ...
