from ._base import FS as FS
from ._info import Info as Info
from ._path import combine as combine
from collections.abc import Iterator

class BoundWalker:
    def __init__(self, fs: FS) -> None: ...
    def files(self, path: str = '/') -> Iterator[str]: ...
    def dirs(self, path: str = '/') -> Iterator[str]: ...
