import abc
import os
from ._base import FS as FS
from ._errors import FileExpected as FileExpected, ResourceNotFound as ResourceNotFound, ResourceReadOnly as ResourceReadOnly
from ._info import Info as Info
from ._path import dirname as dirname, forcedir as forcedir, normpath as normpath, relpath as relpath
from ._subfs import SubFS as SubFS
from ._tempfs import TempFS as TempFS
from _typeshed import Incomplete
from collections.abc import Collection
from typing import Any, IO

class ZipFS(FS, metaclass=abc.ABCMeta):
    """Read and write zip files."""
    def __new__(cls, file: str | os.PathLike, write: bool = False, encoding: str = 'utf-8'): ...
    def __init__(self, file: str | os.PathLike, write: bool = False, encoding: str = 'utf-8') -> None: ...

class ReadZipFS(FS):
    """A readable zip file."""
    _file: Incomplete
    encoding: Incomplete
    _zip: Incomplete
    _directory_fs: Incomplete
    def __init__(self, file: str | os.PathLike, encoding: str = 'utf-8') -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def _path_to_zip_name(self, path: str) -> str:
        """Convert a path to a zip file name."""
    @property
    def _directory(self) -> TempFS: ...
    def close(self) -> None: ...
    def getinfo(self, path: str, namespaces: Collection[str] | None = None) -> Info: ...
    def exists(self, path: str) -> bool: ...
    def isdir(self, path: str) -> bool: ...
    def isfile(self, path: str) -> bool: ...
    def listdir(self, path: str) -> str: ...
    def makedir(self, path: str, recreate: bool = False) -> SubFS: ...
    def makedirs(self, path: str, recreate: bool = False) -> SubFS: ...
    def remove(self, path: str): ...
    def removedir(self, path: str): ...
    def removetree(self, path: str): ...
    def movedir(self, src: str, dst: str, create: bool = False): ...
    def readbytes(self, path: str) -> bytes: ...
    def open(self, path: str, mode: str = 'rb', **kwargs) -> IO[Any]: ...

class WriteZipFS(TempFS):
    """A writable zip file."""
    _file: Incomplete
    encoding: Incomplete
    def __init__(self, file: str | os.PathLike, encoding: str = 'utf-8') -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def close(self) -> None: ...
