"""
This type stub file was generated by pyright.
"""

from .parser import ParseError, load, loads
from .writer import dump, dumps
from ._version import version as __version__

__all__ = ["load", "loads", "dump", "dumps", "ParseError"]
