"""
This type stub file was generated by pyright.
"""

class MathInfo:
    def __init__(self, infoObject) -> None:
        ...
    
    def copy(self): # -> MathInfo:
        ...
    
    def __add__(self, otherInfo): # -> MathInfo:
        ...
    
    def __sub__(self, otherInfo): # -> MathInfo:
        ...
    
    def __mul__(self, factor): # -> MathInfo:
        ...
    
    __rmul__ = ...
    def __div__(self, factor): # -> MathInfo:
        ...
    
    __truediv__ = ...
    __rdiv__ = ...
    __rtruediv__ = ...
    def round(self, digits=...): # -> MathInfo:
        ...
    
    def extractInfo(self, otherInfoObject): # -> None:
        """
        >>> from fontMath.test.test_mathInfo import _TestInfoObject, _testData
        >>> from fontMath.mathFunctions import _roundNumber
        >>> info1 = MathInfo(_TestInfoObject())
        >>> info2 = info1 * 2.5
        >>> info3 = _TestInfoObject()
        >>> info2.extractInfo(info3)
        >>> written = {}
        >>> expected = {}
        >>> for attr, value in _testData.items():
        ...     if value is None:
        ...         continue
        ...     written[attr] = getattr(info2, attr)
        ...     if isinstance(value, list):
        ...         expectedValue = [_roundNumber(v * 2.5) for v in value]
        ...     elif isinstance(value, int):
        ...         expectedValue = _roundNumber(value * 2.5)
        ...     else:
        ...         expectedValue = value * 2.5
        ...     expected[attr] = expectedValue
        >>> sorted(expected) == sorted(written)
        True
        """
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    


_infoAttrs = ...
_numberListAttrs = ...
_postscriptWeightNameOptions = ...
if __name__ == "__main__":
    ...
