"""
This type stub file was generated by pyright.
"""

from fontTools.misc.transform import Transform

def matrixToMathTransform(matrix): # -> ShallowTransform:
    """ Take a 6-tuple and return a ShallowTransform object."""
    ...

def mathTransformToMatrix(mathTransform): # -> tuple[Any, ...]:
    """ Take a ShallowTransform object and return a 6-tuple. """
    ...

class ShallowTransform:
    """ A shallow math container for offset, scale and rotation. """
    def __init__(self, offset, scale, rotation) -> None:
        ...
    
    def __repr__(self): # -> LiteralString:
        ...
    
    def __add__(self, other): # -> Self:
        ...
    
    def __sub__(self, other): # -> Self:
        ...
    
    def __mul__(self, factor): # -> Self:
        ...
    
    __rmul__ = ...
    def __truediv__(self, factor): # -> Self:
        """ XXX why not __div__ ?"""
        ...
    
    def asTuple(self): # -> tuple[Any, ...]:
        ...
    


class MathTransform:
    """ A Transform object that can compose and decompose the matrix into offset, scale and rotation."""
    transformClass = Transform
    def __init__(self, *matrixes) -> None:
        ...
    
    matrix = ...
    def __repr__(self): # -> LiteralString:
        ...
    
    def __len__(self): # -> Literal[6]:
        ...
    
    def __getitem__(self, index): # -> Any:
        ...
    
    def __getslice__(self, i, j): # -> Any | tuple[float, ...]:
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def translate(self, x=..., y=...): # -> Self:
        ...
    
    def scale(self, x=..., y=...): # -> Self:
        ...
    
    def rotate(self, angle): # -> Self:
        ...
    
    def rotateDegrees(self, angle): # -> Self:
        ...
    
    def skew(self, x=..., y=...): # -> Self:
        ...
    
    def skewDegrees(self, x=..., y=...): # -> Self:
        ...
    
    def transform(self, other): # -> Self:
        ...
    
    def reverseTransform(self, other): # -> Self:
        ...
    
    def inverse(self): # -> Self:
        ...
    
    def copy(self): # -> Self:
        ...
    
    def scaleSign(self): # -> Literal[-1, 1]:
        ...
    
    def eq(self, a, b):
        ...
    
    def calcFromValues(self, r1, m1, r2, m2):
        ...
    
    def transpose(self): # -> Self:
        ...
    
    def decompose(self): # -> tuple[tuple[Any, Any], tuple[Any | int, Any | int], tuple[int | float, int | float]]:
        ...
    
    def compose(self, translate, scale, angle): # -> Self:
        ...
    
    def interpolate(self, other, value): # -> Self:
        ...
    


class FontMathWarning(Exception):
    ...


if __name__ == "__main__":
    ...
