from typing import Any
def set_use_numexpr(v: bool = True) -> None: ...
def set_numexpr_threads(n: Any=None) -> None: ...
def evaluate(op: Any, a: Any, b: Any, use_numexpr: bool = True) -> Any: ...
def where(cond: Any, a: Any, b: Any, use_numexpr: bool = True) -> Any: ...
def set_test_mode(v: bool = True) -> None: ...
def get_test_result() -> Any: ...
