def set_use_numexpr(v: bool = True) -> None: ...
def set_numexpr_threads(n=None) -> None: ...
def evaluate(op, a, b, use_numexpr: bool = True): ...
def where(cond, a, b, use_numexpr: bool = True): ...
def set_test_mode(v: bool = True) -> None: ...
def get_test_result(): ...
