import numpy as np
from typing import Any

class UndefinedVariableError(NameError):
    def __init__(self, name: Any, is_local: bool = ...) -> None: ...

class Term:
    def __new__(cls, name: Any, env: Any, side: Any=None, encoding: Any=None): ...
    is_local: bool
    env = ...
    side = ...
    encoding = ...
    def __init__(self, name: Any, env: Any, side: Any=None, encoding: Any=None) -> None: ...
    @property
    def local_name(self) -> str: ...
    def __call__(self, *args, **kwargs): ...
    def evaluate(self, *args, **kwargs): ...
    def update(self, value: Any) -> None: ...
    @property
    def is_scalar(self) -> bool: ...
    @property
    def type(self): ...
    return_type = ...
    @property
    def raw(self) -> str: ...
    @property
    def is_datetime(self) -> bool: ...
    @property
    def value(self): ...
    @value.setter
    def value(self, new_value: Any) -> None: ...
    @property
    def name(self): ...
    @property
    def ndim(self) -> int: ...

class Constant(Term):
    @property
    def name(self): ...

class Op:
    op: str
    operands = ...
    encoding = ...
    def __init__(self, op: str, operands: Any, *args, **kwargs) -> None: ...
    def __iter__(self): ...
    @property
    def return_type(self): ...
    @property
    def has_invalid_return_type(self) -> bool: ...
    @property
    def operand_types(self): ...
    @property
    def is_scalar(self) -> bool: ...
    @property
    def is_datetime(self) -> bool: ...

class BinOp(Op):
    lhs = ...
    rhs = ...
    func = ...
    def __init__(self, op: str, lhs: Any, rhs: Any, **kwargs) -> None: ...
    def __call__(self, env: Any): ...
    def evaluate(self, env: Any, engine: str, parser: Any, term_type: Any, eval_in_python: Any): ...
    def convert_values(self): ...

def isnumeric(dtype: Any) -> bool: ...

class Div(BinOp):
    def __init__(self, lhs: Any, rhs: Any, **kwargs) -> None: ...

class UnaryOp(Op):
    operand = ...
    func = ...
    def __init__(self, op: str, operand: Any) -> None: ...
    def __call__(self, env: Any): ...
    @property
    def return_type(self) -> np.dtype: ...

class MathCall(Op):
    func = ...
    def __init__(self, func: Any, args: Any) -> None: ...
    def __call__(self, env: Any): ...

class FuncNode:
    name = ...
    func = ...
    def __init__(self, name: str) -> None: ...
    def __call__(self, *args): ...
