from typing import Any
class Scope:
    level = ...
    scope = ...
    target = ...
    resolvers = ...
    temps = ...
    def __init__(
        self, level: Any, global_dict: Any=..., local_dict: Any=..., resolvers: Any=..., target: Any=...
    ) -> None: ...
    @property
    def has_resolvers(self) -> bool: ...
    def resolve(self, key: str, is_local: bool) -> Any: ...
    def swapkey(self, old_key: str, new_key: str, new_value: Any=...) -> Any: ...
    def add_tmp(self, value: Any) -> str: ...
    @property
    def ntemps(self) -> int: ...
    @property
    def full_scope(self) -> Any: ...
