"""
This type stub file was generated by pyright.
"""

from python_toolbox.exceptions import CuteException

'''Defines exceptions.'''
class SleekRefDied(CuteException):
    '''You tried to access a sleekref's value but it's already dead.'''
    ...


