import abc
from abc import ABC, abstractmethod

class Contract(ABC, metaclass=abc.ABCMeta):
    @abstractmethod
    def _get_schema(self): ...
    @abstractmethod
    def _parse(self): ...
    @abstractmethod
    def as_apalike(self): ...
    @abstractmethod
    def as_bibtex(self, reference: str = 'YourReferenceHere'): ...
    @abstractmethod
    def as_cff(self): ...
    @abstractmethod
    def as_codemeta(self): ...
    @abstractmethod
    def as_endnote(self): ...
    @abstractmethod
    def as_schemaorg(self): ...
    @abstractmethod
    def as_ris(self): ...
    @abstractmethod
    def as_zenodo(self): ...
    @abstractmethod
    def validate(self): ...
