"""
This type stub file was generated by pyright.
"""

from numba import guvectorize

"""Numba implementation of resampler"""
_resample_loop_p = ...
_resample_loop_s = ...
@guvectorize("(n),(m),(p),(p),(),()->(m)", nopython=True)
def resample_f_p(x, t_out, interp_win, interp_delta, num_table, scale, y): # -> None:
    ...

@guvectorize("(n),(m),(p),(p),(),()->(m)", nopython=True)
def resample_f_s(x, t_out, interp_win, interp_delta, num_table, scale, y): # -> None:
    ...

