"""
This type stub file was generated by pyright.
"""

from future.backports.urllib import response as urllib_response

"""Exception classes raised by urllib.

The base exception class is URLError, which inherits from IOError.  It
doesn't define any behavior of its own, but is the base class for all
exceptions defined in this package.

HTTPError is an exception class that is also a valid HTTP response
instance.  It behaves this way because HTTP protocol errors are valid
responses, with a status code, headers, and a body.  In some contexts,
an application may want to handle an exception like a regular
response.
"""
__all__ = ['URLError', 'HTTPError', 'ContentTooShortError']
class URLError(IOError):
    def __init__(self, reason, filename=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class HTTPError(URLError, urllib_response.addinfourl):
    """Raised when HTTP error occurs, but also acts like non-error return"""
    __super_init = ...
    def __init__(self, url, code, msg, hdrs, fp) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def reason(self): # -> Any:
        ...
    
    def info(self): # -> Any:
        ...
    


class ContentTooShortError(URLError):
    def __init__(self, message, content) -> None:
        ...
    


