from typing import Any

"""
This type stub file was generated by pyright.
"""

from python_toolbox import caching

"""Defines functions for getting generic bitmaps, sometimes from the OS."""
is_mac = ...
is_gtk = ...
is_win = ...
@caching.cache()
def get_closed_folder_bitmap(size: Any=...) -> Any:
    ...

@caching.cache()
def get_open_folder_bitmap(size: Any=...) -> Any:
    ...




