"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import List
from triton.runtime.jit import constexpr_function

class DistributedLayout:
    """
    Base class for distributed memory layouts in Gluon IR.
    """
    @property
    def type(self): # -> constexpr_type:
        ...
    
    @property
    def rank(self):
        ...
    


@dataclass(frozen=True)
class AutoLayout(DistributedLayout):
    def mangle(self): # -> Literal['AL']:
        ...
    
    @property
    def rank(self):
        ...
    


@dataclass(frozen=True)
class CoalescedLayout(DistributedLayout):
    def mangle(self): # -> Literal['CL']:
        ...
    
    @property
    def rank(self):
        ...
    


@dataclass(frozen=True)
class BlockedLayout(DistributedLayout):
    """
    Represents a blocked layout, partitioning a tensor across threads, warps, and CTAs.

    Args:
        size_per_thread (List[int]): Number of elements per thread per dimension.
        threads_per_warp (List[int]): Number of threads per warp per dimension.
        warps_per_cta (List[int]): Number of warps per CTA per dimension.
        order (List[int]): The ordering of dimensions for partitioning.
        cga_layout (Optional[List[List[int]]]): Bases describing how CTAs tile each dimension.
    """
    size_per_thread: List[int]
    threads_per_warp: List[int]
    warps_per_cta: List[int]
    order: List[int]
    cga_layout: List[List[int]] = ...
    def __post_init__(self): # -> None:
        ...
    
    def mangle(self) -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    
    @property
    def rank(self): # -> int:
        ...
    


@dataclass(frozen=True)
class SliceLayout(DistributedLayout):
    """
    Represents a layout corresponding to slicing a distributed tensor along one dimension.

    Args:
        dim (int): The dimension index to slice.
        parent (DistributedLayout): The parent layout before slicing.
    """
    dim: int
    parent: DistributedLayout
    def __post_init__(self): # -> None:
        ...
    
    def mangle(self) -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    
    @property
    def rank(self):
        ...
    
    @property
    def cga_layout(self): # -> list[Any]:
        ...
    


@dataclass(frozen=True)
class DistributedLinearLayout(DistributedLayout):
    """
    Represents a linear distributed layout with explicit bases at register, lane, warp, and block levels.
    See: https://arxiv.org/abs/2505.23819 for reference.

    Args:
        reg_bases (List[List[int]]): Bases for register-level distribution.
        lane_bases (List[List[int]]): Bases for lane-level distribution.
        warp_bases (List[List[int]]): Bases for warp-level distribution.
        block_bases (List[List[int]]): Bases for block-level distribution.
        shape (List[int]): The tensor global shape.
    """
    reg_bases: List[List[int]]
    lane_bases: List[List[int]]
    warp_bases: List[List[int]]
    block_bases: List[List[int]]
    shape: List[int]
    def __post_init__(self): # -> None:
        ...
    
    def mangle(self): # -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    
    @property
    def rank(self): # -> int:
        ...
    


@dataclass(frozen=True)
class DotOperandLayout(DistributedLayout):
    """
    Represents a layout for a dot operand.

    Args:
        operand_index (int): 0 for LHS and 1 for RHS of the dot operation.
        parent (DistributedLayout): The parent layout, representing the MMA.
        k_width (int): Number of elements per 32-bits.
    """
    operand_index: int
    parent: DistributedLayout
    k_width: int
    def __post_init__(self): # -> None:
        ...
    
    def mangle(self) -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    
    @property
    def rank(self):
        ...
    
    @property
    def cga_layout(self): # -> list[Any]:
        ...
    


@dataclass(frozen=True, eq=True)
class NVMMADistributedLayout(DistributedLayout):
    """
    Represents a layout for NVIDIA MMA (tensor core) operations.

    Args:
        version (List[int]): Version identifier for the MMA instruction.
        warps_per_cta (List[int]): Number of warps per CTA.
        instr_shape (List[int]): Instruction shape for MMA.
        cga_layout (Optional[List[List[int]]]): Bases describing CTA tiling.
    """
    version: List[int]
    warps_per_cta: List[int]
    instr_shape: List[int]
    cga_layout: List[List[int]] = ...
    def __post_init__(self): # -> None:
        ...
    
    def mangle(self) -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    
    @property
    def rank(self): # -> int:
        ...
    


class SharedLayout:
    """
    Base class for shared memory layouts in Gluon IR.
    """
    @property
    def type(self): # -> constexpr_type:
        ...
    


@dataclass(frozen=True)
class NVMMASharedLayout(SharedLayout):
    """
    Represents a layout for shared memory suitable for NVIDIA MMA operations.

    Args:
        swizzle_byte_width (int): Width in bytes for swizzling.
        element_bitwidth (int): Bitwidth of element type.
        rank (int): Rank of the tensor.
        transposed (bool): Whether the layout is transposed.
        fp4_padded (bool): Whether FP4 padding is used.
        cga_layout (Optional[List[List[int]]]): Bases describing CTA tiling.
    """
    swizzle_byte_width: int
    element_bitwidth: int
    rank: int = ...
    transposed: bool = ...
    fp4_padded: bool = ...
    cga_layout: List[List[int]] = ...
    def __post_init__(self): # -> None:
        ...
    
    @staticmethod
    @constexpr_function
    def get_default_for(block_shape, dtype, transposed=..., fp4_padded=..., cga_layout=...): # -> NVMMASharedLayout:
        """Returns an NVMMASharedLayout with default swizzling for a given shape.

        This picks the largest swizzle pattern compatible with the shape, which
        allows emitting the fewest TMA or MMA messages.
        """
        ...
    
    def mangle(self) -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    


@dataclass(frozen=True, eq=True)
class SwizzledSharedLayout(SharedLayout):
    """
    Represents a generic swizzled shared memory layout.

    Args:
        vec (int): Vector width for swizzling.
        per_phase (int): Elements per swizzle phase.
        max_phase (int): Maximum number of swizzle phases.
        order (List[int]): Dimension ordering for swizzling.
        cga_layout (Optional[List[List[int]]]): Bases describing CTA tiling.
    """
    vec: int
    per_phase: int
    max_phase: int
    order: List[int]
    cga_layout: List[List[int]] = ...
    def __post_init__(self): # -> None:
        ...
    
    def mangle(self) -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    


@dataclass(frozen=True, eq=True)
class PaddedSharedLayout(SharedLayout):
    """
    Represents a layout for the access to shared memory. Compared to SwizzledSharedLayout,
    it combined padding and element reordering via linear transformation (e.g. row permutation)
    to avoid shared memory bank conflicts. After every interval tensor elements, the
    corresponding number of padding elements are inserted. If a position corresponds to
    multiple intervals, the padding amounts are summed.

    In the following example of a tensor,
    `eM` represents original elements in the and `pN` represents padded element.

    Before padding, the shared memory looks like:
    [e0, e1,
     e2, e3,
     e4, e5,
     e6, e7,
     ...]

    After padding with interval-padding list [[2, 1], [4, 2]] with an identity remapping,
    the shared memory will be
    [e0, e1, p0,
     e2, e3, p1, p2, p3,
     e4, e5, p4,
     e6, e7, p5, p6, p7,
     ...]

    Furthermore this encoding allows for a linear remapping from the 1-D shared
    memory offset to logical n-D tensor elements. The remapping is given in the form
    of linear bases mapping from offset to [dim0, dim1...dimN-1].
    See LinearLayout.h for more details how linear layouts are applied to remap
    elements.
    Some concrete examples using `xN` and `yN` to mean the logical n-D tensor elements
    and `pN` to mean padding:

    After padding for shape = [8] with interval-padding list [[2, 2]], offset_bases = [[2], [1]] and block_bases = []:
    [x0, x2, p0 p1, x1, x3]

    After padding for shape = [8, 4] with interval_padding_pairs = [[8, 1]], offset_bases = [[0, 1], [0, 2], /*gap, stride by 2 rows*/[2, 0], [4, 0], [1, 0]]] and block_bases = []:
    [
        x0y0, x0y1, x0y2, x0y3,
        x2y0, x2y1, x2y2, x2y3,
        p0,
        x4y0, x4y1, x4y2, x4y3,
        x6y0, x6y1, x6y2, x6y3,
        p1,
        x1y0, x1y1, x1y2, x1y3,
        x3y0, x3y1, x3y2, x3y3,
        p2,
        x5y0, x5y1, x5y2, x5y3,
        x7y0, x7y1, x7y2, x7y3,
    ]

    Args:
        interval_padding_pairs (List[int]): List of [interval, padding] pair and both interval and padding must be powers of 2.
        offset_bases (List[int]): Bases for shared memory offsets
        block_bases (List[List[int]]): Bases for block-level shared memory offsets.
        shape (List[int]): n-D logical shared memory shape
    """
    interval_padding_pairs: List[List[int]]
    offset_bases: List[List[int]]
    block_bases: List[List[int]]
    shape: List[int]
    def __post_init__(self): # -> None:
        ...
    
    def mangle(self) -> str:
        ...
    
    def verify(self): # -> None:
        ...
    
    @staticmethod
    @constexpr_function
    def with_identity_for(interval_padding_pairs, shape, order): # -> PaddedSharedLayout:
        """Returns a PaddedSharedLayout with the given interval and padding pairs and an identity mapping as the linear component for the given shape and order.
        """
        ...
    
    def __hash__(self) -> int:
        ...
    


@dataclass(frozen=True)
class SharedLinearLayout(SharedLayout):
    """Represents a shared memory layout defined via an explicit LinearLayout."""
    offset_bases: List[List[int]]
    block_bases: List[List[int]] = ...
    alignment: int = ...
    def __post_init__(self): # -> None:
        ...
    
    def mangle(self) -> str:
        ...
    
    def __hash__(self) -> int:
        ...
    


def bases_per_dim(bases, rank, skip_broadcast=...):
    ...

def warps_per_cta(layout, shape): # -> list[int]:
    ...

