from .table_builder import TableUnbuilder as TableUnbuilder
from _typeshed import Incomplete
from collections.abc import Generator

def unbuildColrV1(layerList, baseGlyphList): ...
def _flatten_layers(lst) -> Generator[Incomplete, Incomplete]: ...

class LayerListUnbuilder:
    layers: Incomplete
    tableUnbuilder: Incomplete
    def __init__(self, layers) -> None: ...
    def unbuildPaint(self, paint): ...
    def _unbuildPaintColrLayers(self, source): ...
