from typing import Any

"""
This type stub file was generated by pyright.
"""

class Key:
    """A key combination."""

    def __init__(self, key_code: Any, cmd: Any=..., alt: Any=..., shift: Any=...) -> None:
        ...

    @staticmethod
    def get_from_key_event(event: Any) -> Any: # -> Key:
        """Construct a Key from a wx.EVT_KEY_DOWN event."""

    def to_accelerator_pair(self) -> Any: # -> tuple[Any, int]:
        ...

    def is_alphanumeric(self) -> Any: # -> bool:
        ...


    def __unicode__(self) -> Any:
        ...

    def __hash__(self) -> int:
        ...

    def __eq__(self, other: object) -> bool:
        ...

    def __ne__(self, other: object) -> bool:
        ...

    def __repr__(self) -> Any: # -> str:
        """
        Get a string representation of the `Key`.

        Example output:

            <Key: Alt-Shift-K>

        """






