from IPython.core import history

class ColabHistoryManager(history.HistoryManager):
    def reset(self, new_session: bool = True) -> None: ...
    def store_inputs(self, line_num, source, source_raw=None) -> None: ...
