from IPython.core import oinspect

def getdoc(obj): ...

class _SafeReprParam:
    def __init__(self, v) -> None: ...

class ColabInspector(oinspect.Inspector):
    def info(self, obj, oname: str = '', formatter=None, info=None, detail_level: int = 0): ...

def get_source_definition(obj): ...
