from ipykernel import ipkernel

class Kernel(ipkernel.IPythonKernel):
    def do_inspect(self, code, cursor_pos, detail_level: int = 0, *args, **kwargs): ...
    def complete_request(self, stream, ident, parent) -> None: ...
    async def inspect_request(self, stream, ident, parent) -> None: ...
