from google.colab import errors as errors

class MessageError(errors.Error): ...

def read_reply_from_input(message_id, timeout_sec=None): ...
def send_request(request_type, request_body, parent=None, expect_reply: bool = True): ...
def blocking_request(request_type, request: str = '', timeout_sec: int = 5, parent=None): ...
