import dataclasses
from _typeshed import Incomplete

@dataclasses.dataclass
class ChartData:
    title: str
    code: str

class MplChart:
    chart_html: Incomplete
    def __init__(self, chart_html) -> None: ...
    @classmethod
    def from_current_mpl_state(cls): ...
    def display(self) -> None: ...

class autoviz:
    MplChart = MplChart

def histogram(df_name: str, colname: str, num_bins: int = 20) -> ChartData: ...
def categorical_histogram(df_name, colname) -> ChartData: ...
def heatmap(df_name: str, x_colname: str, y_colname: str) -> ChartData: ...
def swarm_plot(df_name: str, value_colname: str, facet_colname: str, jitter_domain_width: int = 8) -> ChartData: ...
def violin_plot(df_name: str, value_colname: str, facet_colname: str, inner: str) -> ChartData: ...
def value_plot(df_name: str, y: str) -> ChartData: ...
def scatter_plot(df_name: str, x_colname: str, y_colname: str) -> ChartData: ...
def time_series_multiline(df_name: str, timelike_colname: str, value_colname: str, series_colname: str) -> ChartData: ...
