from _typeshed import Incomplete

class ChartSectionType:
    CATEGORICAL_HISTOGRAM: str
    FACETED_DISTRIBUTION: str
    HEATMAP: str
    HISTOGRAM: str
    SCATTER: str
    TIME_SERIES_LINE_PLOT: str
    VALUE_PLOT: str

class ChartSection:
    def __init__(self, section_type, charts, displayables) -> None: ...
    @property
    def section_type(self): ...
    @property
    def charts(self): ...
    def display(self) -> None: ...
    def to_json(self): ...

class SectionTitle:
    title: Incomplete
    def __init__(self, title) -> None: ...
    def display(self) -> None: ...

class DataframeRegistry:
    def __init__(self, namespace) -> None: ...
    def get_or_register_varname(self, df): ...

class ChartWithCode:
    def __init__(self, df, plot_func, args, kwargs, df_registry) -> None: ...
    @property
    def chart_id(self): ...
    def display(self) -> None: ...
    def to_json(self): ...
    def get_code_and_title(self): ...
    def get_code(self): ...

def histograms_section(df, colnames, df_registry): ...
def value_plots_section(df, colnames, df_registry): ...
def categorical_histograms_section(df, colnames, df_registry): ...
def heatmaps_section(df, colname_pairs, df_registry): ...
def scatter_section(df, colname_pairs, df_registry): ...
def faceted_distributions_section(df, colname_pairs, df_registry): ...
def time_series_line_plots_section(df, colname_pairs, df_registry): ...
