import IPython
from _typeshed import Incomplete

class _IntrinsicTypeFormatter(IPython.core.formatters.BaseFormatter):
    format_type: Incomplete
    print_method: Incomplete

def enable_string_repr() -> None: ...
def disable_string_repr() -> None: ...
def enable_df_style_formatter(): ...
def disable_df_style_formatter() -> None: ...
def enable_dataframe_metadata_repr() -> None: ...
def disable_dataframe_metadata_repr() -> None: ...
def enable_pandas_series_repr(): ...
def disable_pandas_series_repr() -> None: ...
def enable_function_repr() -> None: ...
def disable_function_repr() -> None: ...
def enable_ndarray_repr() -> None: ...
def disable_ndarray_repr() -> None: ...
