from _typeshed import Incomplete
from ipykernel import zmqshell

class Shell(zmqshell.ZMQInteractiveShell):
    events: Incomplete
    def init_events(self) -> None: ...
    inspector: Incomplete
    def init_inspector(self) -> None: ...
    history_manager: Incomplete
    def init_history(self) -> None: ...
    def getoutput(self, *args, **kwargs): ...
    def system(self, *args, **kwargs): ...
    def object_inspect(self, oname, detail_level: int = 0): ...
    def run_cell_magic(self, magic_name, line, cell): ...
