from _typeshed import Incomplete
from google.colab._import_hooks._cv2 import DisabledFunctionError as DisabledFunctionError

SNIPPET_MODULES: Incomplete

def initialize() -> None: ...

class ColabTraceback:
    stb: Incomplete
    error_details: Incomplete
    def __init__(self, stb, error_details) -> None: ...

class FormattedTracebackError(Exception):
    def __init__(self, message, stb, details) -> None: ...

class _CustomErrorHandlers:
    custom_error_handlers: Incomplete
    def __init__(self, shell) -> None: ...
    def handle_error(self, shell, etype, exception, tb, tb_offset=None): ...
    @staticmethod
    def disabled_message(error): ...
    @staticmethod
    def import_message(error): ...

def compute_completion_metadata(shell, matches, inspect_magics: bool = True): ...
