from typing import Any, Generator

__all__ = ['generate_text', 'list_models', 'ModelProxyServiceError']

class ModelProxyServiceError(Exception): ...

def generate_text(prompt: str, model_name: str = 'google/gemini-2.5-flash', stream: bool = False) -> str | Generator[str, Any, None]: ...
def list_models() -> list[str]: ...
