import socketserver as _socketserver
from _typeshed import Incomplete
from http import server as _http_server

__all__ = ['upload_file', 'upload', 'download', 'view']

def upload_file(filename) -> None: ...
def upload(target_dir: str = ''): ...

class _V6Server(_socketserver.TCPServer):
    address_family: Incomplete

class _FileHandler(_http_server.SimpleHTTPRequestHandler):
    def translate_path(self, path): ...
    def log_message(self, fmt, *args) -> None: ...
    def end_headers(self) -> None: ...

def download(filename) -> None: ...
def view(filepath) -> None: ...
