import abc
from _typeshed import Incomplete
from google.colab import auth as auth

class InteractiveSheet:
    sheet: Incomplete
    worksheet: Incomplete
    url: Incomplete
    embedded_url: Incomplete
    backend: Incomplete
    storage_strategy: Incomplete
    def __init__(self, *, title: str = '', url: str = '', sheet_id: str = '', df=None, worksheet_id=None, worksheet_name: str = '', credentials=None, include_column_headers: bool = True, display: bool = True, backend=...) -> None: ...
    @classmethod
    def generate_creds(cls, credentials=None): ...
    def as_df(self, range_name=None): ...
    def update(self, df, location: str = '', clear: bool = True, **kwargs) -> None: ...
    def display(self, height: int = 600) -> None: ...

class InteractiveSheetStorageStrategy(abc.ABC, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def read(self, worksheet): ...
    @abc.abstractmethod
    def write(self, worksheet, df, location, **kwargs): ...

class HeaderlessStorageStrategy(InteractiveSheetStorageStrategy):
    def read(self, worksheet, range_name=None): ...
    def write(self, worksheet, df, location, **kwargs) -> None: ...

class HeaderStorageStrategy(InteractiveSheetStorageStrategy):
    def read(self, worksheet, range_name=None): ...
    def write(self, worksheet, df, location, **kwargs) -> None: ...

class PolarsHeaderlessStorageStrategy(InteractiveSheetStorageStrategy):
    def __init__(self) -> None: ...
    def read(self, worksheet, range_name=None): ...
    def write(self, worksheet, df, location, **kwargs) -> None: ...

class PolarsHeaderStorageStrategy(InteractiveSheetStorageStrategy):
    def __init__(self) -> None: ...
    def read(self, worksheet, range_name=None): ...
    def write(self, worksheet, df, location, **kwargs) -> None: ...
