from google.colab import errors as errors

class NotebookAccessError(Exception):
    def __init__(self, key) -> None: ...

class SecretNotFoundError(errors.Error):
    def __init__(self, key) -> None: ...

class TimeoutException(errors.Error):
    def __init__(self, key) -> None: ...

def get(key: str) -> str: ...
