from _typeshed import Incomplete

__all__ = ['encoders', 'get_encoder', 'get_encoder_names', 'get_preprocessing_params', 'get_preprocessing_fn']

encoders: Incomplete

def get_encoder(name, in_channels: int = 3, depth: int = 5, weights=None, output_stride: int = 32, **kwargs): ...
def get_encoder_names(): ...
def get_preprocessing_params(encoder_name, pretrained: str = 'imagenet'): ...
def get_preprocessing_fn(encoder_name, pretrained: str = 'imagenet'): ...
