from ._base import EncoderMixin as EncoderMixin
from _typeshed import Incomplete
from torchvision.models.densenet import DenseNet

class DenseNetEncoder(DenseNet, EncoderMixin):
    def __init__(self, out_channels, depth: int = 5, output_stride: int = 32, **kwargs) -> None: ...
    def make_dilated(self, *args, **kwargs) -> None: ...
    def forward(self, x): ...
    def load_state_dict(self, state_dict) -> None: ...

densenet_encoders: Incomplete
