import torch
from ._base import EncoderMixin as EncoderMixin
from ._inceptionresnetv2 import InceptionResNetV2 as InceptionResNetV2
from _typeshed import Incomplete

class InceptionResNetV2Encoder(InceptionResNetV2, EncoderMixin):
    def __init__(self, out_channels: list[int], depth: int = 5, output_stride: int = 32, **kwargs) -> None: ...
    def make_dilated(self, *args, **kwargs) -> None: ...
    def forward(self, x: torch.Tensor) -> list[torch.Tensor]: ...
    def load_state_dict(self, state_dict, **kwargs) -> None: ...

inceptionresnetv2_encoders: Incomplete
