import torch
from ._base import EncoderMixin as EncoderMixin
from ._inceptionv4 import InceptionV4 as InceptionV4
from _typeshed import Incomplete

class InceptionV4Encoder(InceptionV4, EncoderMixin):
    def __init__(self, out_channels: list[int], depth: int = 5, output_stride: int = 32, **kwargs) -> None: ...
    def make_dilated(self, *args, **kwargs) -> None: ...
    def forward(self, x: torch.Tensor) -> list[torch.Tensor]: ...
    def load_state_dict(self, state_dict, **kwargs) -> None: ...

inceptionv4_encoders: Incomplete
