import torch
import torchvision
from ._base import EncoderMixin as EncoderMixin
from _typeshed import Incomplete
from typing import Sequence

class MobileNetV2Encoder(torchvision.models.MobileNetV2, EncoderMixin):
    def __init__(self, out_channels: list[int], depth: int = 5, output_stride: int = 32, **kwargs) -> None: ...
    def get_stages(self) -> dict[int, Sequence[torch.nn.Module]]: ...
    def forward(self, x: torch.Tensor) -> list[torch.Tensor]: ...
    def load_state_dict(self, state_dict, **kwargs) -> None: ...

mobilenet_encoders: Incomplete
