from ._base import EncoderMixin as EncoderMixin
from ._xception import Xception as Xception
from _typeshed import Incomplete

class XceptionEncoder(Xception, EncoderMixin):
    def __init__(self, out_channels: list[int], *args, depth: int = 5, output_stride: int = 32, **kwargs) -> None: ...
    def make_dilated(self, *args, **kwargs) -> None: ...
    def forward(self, x): ...
    def load_state_dict(self, state_dict) -> None: ...

xception_encoders: Incomplete
