from dataclasses import dataclass
from fontTools.designspaceLib import (
	AxisDescriptor as AxisDescriptor, DesignSpaceDocument as DesignSpaceDocument,
	DesignSpaceDocumentError as DesignSpaceDocumentError, RangeAxisSubsetDescriptor as RangeAxisSubsetDescriptor,
	SimpleLocationDict as SimpleLocationDict, ValueAxisSubsetDescriptor as ValueAxisSubsetDescriptor,
	VariableFontDescriptor as VariableFontDescriptor)
from typing import TypeAlias

def clamp(value, minimum, maximum): ...

@dataclass
class Range:
    minimum: float
    maximum: float
    default: float = ...
    def __post_init__(self) -> None: ...
    def __contains__(self, value: float | Range) -> bool: ...
    def intersection(self, other: Range) -> Range | None: ...
Region: TypeAlias = dict[str, Range | float]
ConditionSet: TypeAlias = dict[str, Range]
Rule: TypeAlias = list[ConditionSet]
Rules: TypeAlias = dict[str, Rule]

def locationInRegion(location: SimpleLocationDict, region: Region) -> bool: ...
def regionInRegion(region: Region, superRegion: Region) -> bool: ...
def userRegionToDesignRegion(doc: DesignSpaceDocument, userRegion: Region) -> Region: ...
def getVFUserRegion(doc: DesignSpaceDocument, vf: VariableFontDescriptor) -> Region: ...
