"""
This type stub file was generated by pyright.
"""

""" Routines for manipulating RFC2047 encoded words.

This is currently a package-private API, but will be considered for promotion
to a public API if there is demand.

"""
__all__ = ['decode_q', 'encode_q', 'decode_b', 'encode_b', 'len_q', 'len_b', 'decode', 'encode']
_q_byte_subber = ...
def decode_q(encoded): # -> tuple[bytes, list[Any]]:
    ...

class _QByteMap(dict):
    safe = ...
    def __missing__(self, key):
        ...
    


_q_byte_map = ...
def encode_q(bstring): # -> newstr:
    ...

def len_q(bstring): # -> int:
    ...

def decode_b(encoded): # -> tuple[bytes, list[Any]] | tuple[bytes, list[InvalidBase64CharactersDefect]]:
    ...

def encode_b(bstring): # -> str:
    ...

def len_b(bstring): # -> int:
    ...

_cte_decoders = ...
def decode(ew): # -> tuple[str, Any | newstr, Any | newstr, list[InvalidBase64CharactersDefect]]:
    """Decode encoded word and return (string, charset, lang, defects) tuple.

    An RFC 2047/2243 encoded word has the form:

        =?charset*lang?cte?encoded_string?=

    where '*lang' may be omitted but the other parts may not be.

    This function expects exactly such a string (that is, it does not check the
    syntax and may raise errors if the string is not well formed), and returns
    the encoded_string decoded first from its Content Transfer Encoding and
    then from the resulting bytes into unicode using the specified charset.  If
    the cte-decoded string does not successfully decode using the specified
    character set, a defect is added to the defects list and the unknown octets
    are replaced by the unicode 'unknown' character \uFDFF.

    The specified charset and language are returned.  The default for language,
    which is rarely if ever encountered, is the empty string.

    """
    ...

_cte_encoders = ...
_cte_encode_length = ...
def encode(string, charset=..., encoding=..., lang=...): # -> str:
    """Encode string using the CTE encoding that produces the shorter result.

    Produces an RFC 2047/2243 encoded word of the form:

        =?charset*lang?cte?encoded_string?=

    where '*lang' is omitted unless the 'lang' parameter is given a value.
    Optional argument charset (defaults to utf-8) specifies the charset to use
    to encode the string to binary before CTE encoding it.  Optional argument
    'encoding' is the cte specifier for the encoding that should be used ('q'
    or 'b'); if it is None (the default) the encoding which produces the
    shortest encoded sequence is used, except that 'q' is preferred if it is up
    to five characters longer.  Optional argument 'lang' (default '') gives the
    RFC 2243 language string to specify in the encoded word.

    """
    ...

