"""
This type stub file was generated by pyright.
"""

class Error(Exception):
    """Base exception class for all ufo2ft errors."""
    ...


class InvalidFontData(Error):
    """Raised when input font contains invalid data."""
    ...


class InvalidFeaturesData(Error):
    """Raised when input font contains invalid features data."""
    ...


class InvalidDesignSpaceData(Error):
    """Raised when input DesignSpace document contains invalid data."""
    ...


