"""
This type stub file was generated by pyright.
"""

"""
This file provides fallback data for info attributes
that are required for building OTFs. There are two main
functions that are important:

* :func:`~getAttrWithFallback`
* :func:`~preflightInfo`

There are a set of other functions that are used internally
for synthesizing values for specific attributes. These can be
used externally as well.
"""
logger = ...
_styleMapStyleNames = ...
def ascenderFallback(info):
    ...

def descenderFallback(info):
    ...

def capHeightFallback(info):
    ...

def xHeightFallback(info):
    ...

def styleMapFamilyNameFallback(info): # -> str | Any:
    """
    Fallback to *openTypeNamePreferredFamilyName* if
    *styleMapStyleName* or, if *styleMapStyleName* isn't defined,
    *openTypeNamePreferredSubfamilyName* is
    *regular*, *bold*, *italic* or *bold italic*, otherwise
    fallback to *openTypeNamePreferredFamilyName openTypeNamePreferredFamilyName*.
    """
    ...

def styleMapStyleNameFallback(info): # -> str | Any:
    """
    Fallback to *openTypeNamePreferredSubfamilyName* if
    it is one of *regular*, *bold*, *italic*, *bold italic*, otherwise
    fallback to *regular*.
    """
    ...

_date_format = ...
def dateStringForNow(): # -> str:
    ...

def openTypeHeadCreatedFallback(info): # -> str:
    """
    Fallback to the environment variable SOURCE_DATE_EPOCH if set, otherwise
    now.
    """
    ...

def openTypeHheaAscenderFallback(info): # -> Any | int | str | list[int]:
    """
    Fallback to *ascender + typoLineGap*.
    """
    ...

def openTypeHheaDescenderFallback(info): # -> Any | int | str | list[int] | None:
    """
    Fallback to *descender*.
    """
    ...

def openTypeHheaCaretSlopeRiseFallback(info): # -> Any | int | str | list[int] | None:
    """
    Fallback to *openTypeHheaCaretSlopeRise*. If the italicAngle is zero,
    return UPEM. If italicAngle is non-zero, compute the slope rise from the
    complementary openTypeHheaCaretSlopeRun, if the latter is defined.
    Else, default to the font's UPEM.
    """
    ...

def openTypeHheaCaretSlopeRunFallback(info): # -> Literal[0]:
    """
    Fallback to *openTypeHheaCaretSlopeRun*. If the italicAngle is zero,
    return 0. If italicAngle is non-zero, compute the slope run from the
    complementary openTypeHheaCaretSlopeRise.
    """
    ...

def openTypeNameVersionFallback(info): # -> str:
    """
    Fallback to *versionMajor.versionMinor* in the form 0.000.
    """
    ...

def openTypeNameUniqueIDFallback(info): # -> str:
    """
    Fallback to *openTypeNameVersion;openTypeOS2VendorID;postscriptFontName*.
    """
    ...

def openTypeNamePreferredFamilyNameFallback(info): # -> Any | int | str | list[int] | None:
    """
    Fallback to *familyName*.
    """
    ...

def openTypeNamePreferredSubfamilyNameFallback(info): # -> Any | int | str | list[int] | None:
    """
    Fallback to *styleName*.
    """
    ...

def openTypeNameWWSFamilyNameFallback(info): # -> None:
    ...

def openTypeNameWWSSubfamilyNameFallback(info): # -> None:
    ...

def openTypeOS2TypoAscenderFallback(info): # -> Any | int | str | list[int] | None:
    """
    Fallback to *ascender*.
    """
    ...

def openTypeOS2TypoDescenderFallback(info): # -> Any | int | str | list[int] | None:
    """
    Fallback to *descender*.
    """
    ...

def openTypeOS2TypoLineGapFallback(info): # -> Any | int:
    """
    Fallback to *UPM * 1.2 - ascender + descender*, or zero if that's negative.
    """
    ...

def openTypeOS2WinAscentFallback(info): # -> Any | int | str | list[int]:
    """
    Fallback to *ascender + typoLineGap*.
    """
    ...

def openTypeOS2WinDescentFallback(info): # -> int:
    """
    Fallback to *descender*.
    """
    ...

_postscriptFontNameExceptions = ...
_postscriptFontNameAllowed = ...
def normalizeStringForPostscript(s, allowSpaces=...): # -> LiteralString:
    ...

def normalizeNameForPostscript(name): # -> LiteralString:
    ...

def postscriptFontNameFallback(info): # -> LiteralString:
    """
    Fallback to a string containing only valid characters
    as defined in the specification. This will draw from
    *openTypeNamePreferredFamilyName* and *openTypeNamePreferredSubfamilyName*.
    """
    ...

def postscriptFullNameFallback(info): # -> str:
    """
    Fallback to *openTypeNamePreferredFamilyName openTypeNamePreferredSubfamilyName*.
    """
    ...

def postscriptSlantAngleFallback(info): # -> Any | int | str | list[int] | None:
    """
    Fallback to *italicAngle*.
    """
    ...

def postscriptUnderlineThicknessFallback(info): # -> Any | float:
    """Return UPM * 0.05 (50 for 1000 UPM) and warn."""
    ...

def postscriptUnderlinePositionFallback(info): # -> Any | float:
    """Return UPM * -0.075 (-75 for 1000 UPM) and warn."""
    ...

def postscriptBlueScaleFallback(info): # -> float:
    """
    Fallback to a calculated value: 3/(4 * *maxZoneHeight*)
    where *maxZoneHeight* is the tallest zone from *postscriptBlueValues*
    and *postscriptOtherBlues*. If zones are not set, return 0.039625.
    """
    ...

staticFallbackData = ...
specialFallbacks = ...
requiredAttributes = ...
recommendedAttributes = ...
def getAttrWithFallback(info, attr): # -> Any | float | int | str | list[int] | None:
    """
    Get the value for *attr* from the *info* object.
    If the object does not have the attribute or the value
    for the atribute is None, this will either get a
    value from a predefined set of attributes or it
    will synthesize a value from the available data.
    """
    ...

def preflightInfo(info): # -> dict[str, set[Any]]:
    """
    Returns a dict containing two items. The value for each
    item will be a list of info attribute names.

    ==================  ===
    missingRequired     Required data that is missing.
    missingRecommended  Recommended data that is missing.
    ==================  ===
    """
    ...

def intListToNum(intList, start, length):
    ...

def dateStringToTimeValue(date): # -> int:
    ...

