"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from fontTools import ttLib
from ufoLib2 import Font

if TYPE_CHECKING:
    ...
logger = ...
class InstructionCompiler:
    def __init__(self, ufo: Font, otf: ttLib.TTFont, autoUseMyMetrics: bool = ...) -> None:
        ...
    
    def compileGlyphInstructions(self, ttGlyph, name) -> None:
        """Compile the glyph instructions from the UFO glyph `name` to bytecode
        and add it to `ttGlyph`."""
        ...
    
    def autoUseMyMetrics(self, ttGlyph, glyphName): # -> None:
        """Set the "USE_MY_METRICS" flag on the first component having the
        same advance width as the composite glyph, no transform and no
        horizontal shift (but allow it to shift vertically).
        This forces the composite glyph to use the possibly hinted horizontal
        metrics of the sub-glyph, instead of those from the "hmtx" table.
        """
        ...
    
    def update_maxp(self) -> None:
        """Update the maxp table with relevant values from the UFO and compiled
        font.
        """
        ...
    
    def setupTable_cvt(self) -> None:
        """Make the cvt table."""
        ...
    
    def setupTable_fpgm(self) -> None:
        ...
    
    def setupTable_gasp(self): # -> None:
        ...
    
    def setupTable_prep(self) -> None:
        ...
    


