"""
This type stub file was generated by pyright.
"""

"""NOTE: this module was moved to fonttools, it is kept here only for backward
compatibility. Please import it from the new location.
"""
__all__ = ["maxCtxFont"]
