
__all__ = ["_expand_slot", "pre_post_context_matches", "would_apply_at_position"]
def i2s(buffer_items): # -> LiteralString:
    ...

def glyphs_match(buffer_glyphs, routine_glyphs, namedclasses=...): # -> bool:
    ...

def pre_post_context_matches(self, buf, ix, namedclasses=...): # -> bool:
    ...

def would_apply_at_position(self, buf, ix, namedclasses=...): # -> bool:
    ...
