from pandas import DataFrame as DataFrame
from pandas._typing import MutableMappingT as MutableMappingT
from pandas.core.dtypes.dtypes import BaseMaskedDtype as BaseMaskedDtype, ExtensionDtype as ExtensionDtype
from typing import Literal, overload

@overload
def to_dict(df: DataFrame, orient: Literal['dict', 'list', 'series', 'split', 'tight', 'index'] = ..., *, into: type[MutableMappingT] | MutableMappingT, index: bool = ...) -> MutableMappingT: ...
@overload
def to_dict(df: DataFrame, orient: Literal['records'], *, into: type[MutableMappingT] | MutableMappingT, index: bool = ...) -> list[MutableMappingT]: ...
@overload
def to_dict(df: DataFrame, orient: Literal['dict', 'list', 'series', 'split', 'tight', 'index'] = ..., *, into: type[dict] = ..., index: bool = ...) -> dict: ...
@overload
def to_dict(df: DataFrame, orient: Literal['records'], *, into: type[dict] = ..., index: bool = ...) -> list[dict]: ...
