"""
This type stub file was generated by pyright.
"""

import io
import re
import fontFeatures
import fontTools.feaLib.ast as ast
from fontTools.feaLib.parser import Parser
from warnings import warn

def bad_statement_to_comment(s): # -> Comment:
    ...

class FeaParser:
    """Turns a AFDKO feature file or string into a FontFeatures object.

    Args:
        featurefile: File object or string.
        font: Optionally, a TTFont object.
        glyphNames: Optionally, a list of glyph names in the font
    """
    def __init__(self, featurefile, font=..., glyphNames=..., includeDir=...) -> None:
        ...
    
    def parse(self): # -> FontFeatures:
        """Parse the feature code.

        Returns:
            A ``FontFeatures`` object containing the rules of this file.
        """
        ...
    
    def start_lookup_block(self, location, name, use_extension=...): # -> None:
        ...
    
    def start_feature(self, location, name, use_extension=...): # -> None:
        ...
    
    def set_font_revision(self, location, revision): # -> None:
        ...
    
    def add_name_record(self, *args): # -> None:
        ...
    
    def add_featureName(self, tag): # -> None:
        ...
    
    def set_script(self, location, script): # -> None:
        ...
    
    def set_language(self, location, language, include_default, required): # -> None:
        ...
    
    def add_single_subst(self, location, prefix, suffix, mapping, forceChain): # -> None:
        ...
    
    def add_reverse_chain_single_subst(self, location, prefix, suffix, mapping): # -> None:
        ...
    
    def add_multiple_subst(self, location, prefix, glyph, suffix, replacements, forceChain): # -> None:
        ...
    
    def add_alternate_subst(self, location, prefix, glyph, suffix, replacement): # -> None:
        ...
    
    def add_ligature_subst(self, location, prefix, glyphs, suffix, replacement, forceChain): # -> None:
        ...
    
    def add_chain_context_subst(self, location, prefix, glyphs, suffix, lookups): # -> None:
        ...
    
    add_chain_context_pos = ...
    def add_single_pos(self, location, prefix, suffix, pos, forceChain): # -> None:
        ...
    
    def add_specific_pair_pos(self, location, glyph1, value1, glyph2, value2): # -> None:
        ...
    
    def add_class_pair_pos(self, location, glyphclass1, value1, glyphclass2, value2): # -> None:
        ...
    
    def add_cursive_pos(self, location, glyphclass, entryAnchor, exitAnchor): # -> None:
        ...
    
    def add_mark_base_pos(self, location, bases, marks): # -> None:
        ...
    
    add_mark_mark_pos = ...
    def add_mark_lig_pos(self, location, bases, marks): # -> None:
        ...
    
    def set_lookup_flag(self, location, value, markAttach, markFilter): # -> None:
        ...
    
    def add_language_system(self, location, script, language): # -> None:
        ...
    
    def setElidedFallbackName(self, location, *args): # -> None:
        ...
    
    def addDesignAxis(self, location, *args): # -> None:
        ...
    
    def addAxisValueRecord(self, location, *args): # -> None:
        ...
    
    def add_ligatureCaretByPos_(self, location, *args): # -> None:
        ...
    
    def add_lookup_call(self, lookup_name): # -> None:
        ...
    
    def end_lookup_block(self): # -> None:
        ...
    
    def end_feature(self): # -> None:
        ...
    
    def add_feature_reference(self, location, featurename): # -> None:
        ...
    
    def add_glyphClassDef(self, location, base, ligature, mark, component): # -> None:
        ...
    


