
def glyphref(g): # -> GlyphName | GlyphClass:
    ...

def gensym(ff): # -> str:
    ...

def replaceLongWithClasses(i, ff): # -> None:
    ...

def feaPreamble(self, ff): # -> list[Any]:
    ...

def asFeaAST(self): # -> ChainContextPosStatement | ChainContextSubstStatement | IgnoreSubstStatement:
    ...
