from pandas.io.sas.sasreader import ReaderBase
import pandas as pd

class XportReader(ReaderBase):
    def close(self) -> None: ...
    def __next__(self) -> pd.DataFrame: ...
    def read(self, nrows: int | None = None) -> pd.DataFrame: ...
