"""
This type stub file was generated by pyright.
"""

from .freezer import Freezer
from .freezer_property import FreezerProperty

'''
Defines the `Freezer` and `FreezerProperty` classes.

See their documentation for more information.
'''
