"""
This type stub file was generated by pyright.
"""

from typing import Tuple
from .anchorPropagation import propagate_anchors
from .background import decompose_backgrounds, zero_background_width
from .cu2qu import cubic_to_quadratic
from .customParameters import apply_custom_parameters
from .decomposeMixed import decompose_mixed_glyphs
from .dropUnexported import drop_unexported_glyphs
from .fillOpentype import fill_opentype_values
from .glyphDataXML import bake_in_glyphdata
from .glyphs3fea import translate_glyphs3_fea
from .intermediateLayer import promote_intermediate_layers
from .marks import zero_mark_widths
from .rename import rename_glyphs

FILTERS = ...
def parse_filter(input: str) -> Tuple[str, dict]:
    ...

