from _typeshed import Incomplete
from abc import ABC

class AbstractAuthorShared(ABC):
    _author: Incomplete
    _behaviors: Incomplete
    def __init__(self, author) -> None: ...
    @staticmethod
    def _from_thin_air() -> None: ...
    def _get_full_last_name(self): ...
    def _has_affiliation(self): ...
    def _has_alias(self): ...
    def _has_given_name(self): ...
    def _has_family_name(self): ...
    def _has_name(self): ...
    def _has_orcid(self): ...
