from _typeshed import Incomplete
from abc import ABC

class AbstractUrlShared(ABC):
    _cffobj: Incomplete
    _behaviors: Incomplete
    def __init__(self, cffobj) -> None: ...
    def _get_urls_from_identifiers(self): ...
    def _has_identifiers_url(self): ...
    def _has_repository(self): ...
    def _has_repository_artifact(self): ...
    def _has_repository_code(self): ...
    def _has_url(self): ...
