import abc
from _typeshed import Incomplete
from abc import abstractmethod

class ApalikeObjectShared(metaclass=abc.ABCMeta):
    supported_apalike_props: Incomplete
    supported_cff_versions: Incomplete
    cffobj: Incomplete
    author: Incomplete
    year: Incomplete
    title: Incomplete
    version: Incomplete
    doi: Incomplete
    url: Incomplete
    def __init__(self, cffobj, initialize_empty: bool = False) -> None: ...
    def __str__(self) -> str: ...
    def add_all(self): ...
    @abstractmethod
    def add_author(self): ...
    @abstractmethod
    def add_year(self): ...
    def add_title(self): ...
    def add_version(self): ...
    @abstractmethod
    def add_doi(self): ...
    @abstractmethod
    def add_url(self): ...
    def as_string(self): ...
    def check_cffobj(self) -> None: ...
