import abc
from _typeshed import Incomplete
from abc import abstractmethod
from cffconvert.behavior_shared.abstract_url_shared import AbstractUrlShared as AbstractUrlShared

class ApalikeUrlShared(AbstractUrlShared, metaclass=abc.ABCMeta):
    _behaviors: Incomplete
    def __init__(self, cffobj) -> None: ...
    def _from_identifiers_url(self): ...
    def _from_repository(self): ...
    def _from_repository_artifact(self): ...
    def _from_repository_code(self): ...
    @staticmethod
    def _from_thin_air() -> None: ...
    def _from_url(self): ...
    @abstractmethod
    def as_string(self): ...
