import abc
from typing import Any, ClassVar
from abc import abstractmethod

class BibtexObjectShared(metaclass=abc.ABCMeta):
    supported_bibtex_props: ClassVar[list[str]]
    supported_cff_versions: ClassVar[list[str]]
    cffobj: dict[str, Any]
    author: str | None
    doi: str | None
    month: str | None
    title: str | None
    url: str | None
    year: str | None
    def __init__(self, cffobj: dict[str, Any], initialize_empty: bool = False) -> None: ...
    def __str__(self, reference: str = 'YourReferenceHere') -> str: ...
    def add_all(self) -> 'BibtexObjectShared': ...
    @abstractmethod
    def add_author(self) -> 'BibtexObjectShared': ...
    @abstractmethod
    def add_doi(self) -> 'BibtexObjectShared': ...
    @abstractmethod
    def add_month(self) -> 'BibtexObjectShared': ...
    def add_title(self) -> 'BibtexObjectShared': ...
    @abstractmethod
    def add_url(self) -> 'BibtexObjectShared': ...
    @abstractmethod
    def add_year(self) -> 'BibtexObjectShared': ...
    def as_string(self, reference: str = 'YourReferenceHere') -> str: ...
    def check_cffobj(self) -> None: ...
