import abc
from _typeshed import Incomplete
from abc import abstractmethod

class BibtexObjectShared(metaclass=abc.ABCMeta):
    supported_bibtex_props: Incomplete
    supported_cff_versions: Incomplete
    cffobj: Incomplete
    author: Incomplete
    doi: Incomplete
    month: Incomplete
    title: Incomplete
    url: Incomplete
    year: Incomplete
    def __init__(self, cffobj, initialize_empty: bool = False) -> None: ...
    def __str__(self, reference: str = 'YourReferenceHere') -> str: ...
    def add_all(self): ...
    @abstractmethod
    def add_author(self): ...
    @abstractmethod
    def add_doi(self): ...
    @abstractmethod
    def add_month(self): ...
    def add_title(self): ...
    @abstractmethod
    def add_url(self): ...
    @abstractmethod
    def add_year(self): ...
    def as_string(self, reference: str = 'YourReferenceHere'): ...
    def check_cffobj(self) -> None: ...
