import abc
from _typeshed import Incomplete
from abc import abstractmethod
from cffconvert.behavior_shared.abstract_author_shared import AbstractAuthorShared as AbstractAuthorShared

class EndnoteAuthorShared(AbstractAuthorShared, metaclass=abc.ABCMeta):
    _behaviors: Incomplete
    def __init__(self, author) -> None: ...
    def _from_alias(self): ...
    def _from_given_and_last(self): ...
    def _from_given(self): ...
    def _from_last(self): ...
    def _from_name(self): ...
    @abstractmethod
    def as_string(self): ...
