import abc
from _typeshed import Incomplete
from abc import abstractmethod

class EndnoteObjectShared(metaclass=abc.ABCMeta):
    supported_endnote_props: Incomplete
    supported_cff_versions: Incomplete
    cffobj: Incomplete
    author: Incomplete
    doi: Incomplete
    keyword: Incomplete
    name: Incomplete
    url: Incomplete
    year: Incomplete
    def __init__(self, cffobj, initialize_empty: bool = False) -> None: ...
    def __str__(self) -> str: ...
    def add_all(self): ...
    @abstractmethod
    def add_author(self): ...
    @abstractmethod
    def add_doi(self): ...
    def add_keyword(self): ...
    def add_name(self): ...
    @abstractmethod
    def add_url(self): ...
    @abstractmethod
    def add_year(self): ...
    def as_string(self): ...
    def check_cffobj(self) -> None: ...
