import abc
from _typeshed import Incomplete
from abc import abstractmethod

class RisObjectShared(metaclass=abc.ABCMeta):
    supported_ris_props: Incomplete
    supported_cff_versions: Incomplete
    cffobj: Incomplete
    abstract: Incomplete
    author: Incomplete
    date: Incomplete
    doi: Incomplete
    keywords: Incomplete
    title: Incomplete
    url: Incomplete
    year: Incomplete
    def __init__(self, cffobj, initialize_empty: bool = False) -> None: ...
    def __str__(self) -> str: ...
    def add_all(self): ...
    def add_abstract(self): ...
    @abstractmethod
    def add_author(self): ...
    @abstractmethod
    def add_date(self): ...
    @abstractmethod
    def add_doi(self): ...
    def add_keywords(self): ...
    def add_title(self): ...
    @abstractmethod
    def add_url(self): ...
    @abstractmethod
    def add_year(self): ...
    def as_string(self): ...
    def check_cffobj(self) -> None: ...
