import abc
from _typeshed import Incomplete
from abc import abstractmethod

class SchemaorgObjectShared(metaclass=abc.ABCMeta):
    supported_schemaorg_props: Incomplete
    supported_cff_versions: Incomplete
    cffobj: Incomplete
    author: Incomplete
    code_repository: Incomplete
    date_published: Incomplete
    description: Incomplete
    identifier: Incomplete
    keywords: Incomplete
    license: Incomplete
    name: Incomplete
    url: Incomplete
    version: Incomplete
    context: Incomplete
    def __init__(self, cffobj, initialize_empty: bool = False, context: str = 'https://schema.org') -> None: ...
    def __str__(self, sort_keys: bool = True, indent: int = 2) -> str: ...
    def add_all(self): ...
    @abstractmethod
    def add_author(self): ...
    @abstractmethod
    def add_date_published(self): ...
    def add_description(self): ...
    @abstractmethod
    def add_identifier(self): ...
    def add_keywords(self): ...
    def add_license(self): ...
    def add_name(self): ...
    @abstractmethod
    def add_urls(self): ...
    def add_version(self): ...
    def as_string(self): ...
    def check_cffobj(self) -> None: ...
