import abc
from _typeshed import Incomplete
from abc import abstractmethod

class ZenodoObjectShared(metaclass=abc.ABCMeta):
    supported_zenodo_props: Incomplete
    supported_cff_versions: Incomplete
    cffobj: Incomplete
    creators: Incomplete
    description: Incomplete
    keywords: Incomplete
    license: Incomplete
    publication_date: Incomplete
    title: Incomplete
    version: Incomplete
    def __init__(self, cffobj, initialize_empty: bool = False) -> None: ...
    def __str__(self, sort_keys: bool = True, indent: int = 2) -> str: ...
    def add_all(self): ...
    @abstractmethod
    def add_creators(self): ...
    def add_description(self): ...
    def add_keywords(self): ...
    def add_license(self): ...
    @abstractmethod
    def add_publication_date(self): ...
    def add_title(self): ...
    def add_version(self): ...
    def as_string(self): ...
    def check_cffobj(self) -> None: ...
