from _typeshed import Incomplete
from cffconvert.behavior_shared.bibtex_object_shared import BibtexObjectShared as Shared

class BibtexObject(Shared):
    supported_cff_versions: Incomplete
    author: Incomplete
    def add_author(self): ...
    doi: Incomplete
    def add_doi(self): ...
    month: Incomplete
    def add_month(self): ...
    url: Incomplete
    def add_url(self): ...
    year: Incomplete
    def add_year(self): ...
