from _typeshed import Incomplete
from cffconvert.contracts.citation import Contract as Contract

class Citation_1_0_x(Contract):
    supported_cff_versions: Incomplete
    cffstr: Incomplete
    cffversion: Incomplete
    cffobj: Incomplete
    schema: Incomplete
    def __init__(self, cffstr, cffversion) -> None: ...
    def _get_schema(self): ...
    def _parse(self): ...
    def as_apalike(self): ...
    def as_bibtex(self, reference: str = 'YourReferenceHere'): ...
    def as_cff(self): ...
    def as_codemeta(self): ...
    def as_endnote(self): ...
    def as_ris(self): ...
    def as_schemaorg(self): ...
    def as_zenodo(self): ...
    def validate(self) -> None: ...
