"""
This type stub file was generated by pyright.
"""

"""This module is DEPRECATED and will be removed in a future release.

For anchor propagation on GSFont objects, you can use the
`glyphsLib.builder.transformations.propagate_anchors` module.
For anchor propagation on UFO font objects, you can try the
`ufo2ft.filters.propagateAnchors` filter.
"""
def to_ufo_propagate_font_anchors(self, ufo): # -> None:
    """Copy anchors from parent glyphs' components to the parent."""
    ...

