from .constants import ANNOTATIONS_LIB_KEY as ANNOTATIONS_LIB_KEY
from glyphsLib.types import Point as Point

def to_ufo_annotations(self, ufo_glyph, layer) -> None: ...
def to_glyphs_annotations(self, ufo_glyph, layer) -> None: ...
