"""
This type stub file was generated by pyright.
"""

from glyphsLib.util import LoggerMixin

class UFOBuilder(LoggerMixin):
    """Builder for Glyphs to UFO + designspace."""
    def __init__(self, font, ufo_module=..., designspace_module=..., family_name=..., instance_dir=..., propagate_anchors=..., use_designspace=..., minimize_glyphs_diffs=..., generate_GDEF=..., store_editor_state=..., write_skipexportglyphs=..., expand_includes=..., minimal=..., glyph_data=...) -> None:
        """Create a builder that goes from Glyphs to UFO + designspace.

        Keyword arguments:
        font -- The GSFont object to transform into UFOs. We expect this GSFont
                object to have been pre-processed with
                ``glyphsLib.builder.preflight_glyphs``.
        ufo_module -- A Python module to use to build UFO objects (you can pass
                      a custom module that has the same classes as ufoLib2 or
                      defcon to get instances of your own classes). Default: ufoLib2
        designspace_module -- A Python module to use to build a Designspace
                              Document. Default is fontTools.designspaceLib.
        family_name -- if provided, the master UFOs will be given this name and
                       only instances with this name will be returned.
        instance_dir -- if provided, instance UFOs will be located in this
                        directory, according to their Designspace filenames.
        propagate_anchors -- DEPRECATED. Use preflight_glyphs to propagate anchors on
                             the GSFont before building UFOs.
        use_designspace -- set to True to make optimal use of the designspace:
                           data that is common to all ufos will go there.
        minimize_glyphs_diffs -- set to True to store extra info in UFOs
                                 in order to get smaller diffs between .glyphs
                                 .glyphs files when going glyphs->ufo->glyphs.
        generate_GDEF -- set to False to skip writing a `table GDEF {...}` in
                         the UFO features.
        store_editor_state -- If True, store editor state in the UFO like which
                              glyphs are open in which tabs ("DisplayStrings").
        write_skipexportglyphs -- If True, write the export status of a glyph
                                         into the UFOs' and Designspace's lib instead
                                         of the glyph level lib key
                                         "com.schriftgestaltung.Glyphs.Export".
        expand_includes -- If True, expand include statements in the GSFont features
                           and inline them in the UFO features.fea.
        minimal -- If True, it is assumed that the UFOs will only be used in font
                   production, and unnecessary steps will be skipped.
        glyph_data -- A list of GlyphData.
        """
        ...
    
    @property
    def masters(self): # -> Generator[Any, Any, None]:
        """Get an iterator over master UFOs that match the given family_name."""
        ...
    
    def to_ufo_layers(self): # -> None:
        ...
    
    @property
    def designspace(self): # -> Any:
        """Get a designspace Document instance that links the masters together
        and holds instance data.
        """
        ...
    
    @property
    def instance_data(self): # -> dict[str, list[Any] | Any]:
        ...
    


def filter_instances_by_family(instances, family_name=...): # -> Generator[Any, None, None]:
    """Yield instances whose 'familyName' custom parameter is
    equal to 'family_name'.
    """
    ...

class GlyphsBuilder(LoggerMixin):
    """Builder for UFO + designspace to Glyphs."""
    def __init__(self, ufos=..., designspace=..., glyphs_module=..., ufo_module=..., minimize_ufo_diffs=..., expand_includes=...) -> None:
        """Create a builder that goes from UFOs + designspace to Glyphs.

        If you provide:
            * Some UFOs, no designspace: the given UFOs will be combined.
                No instance data will be created, only the weight and width
                axes will be set up (if relevant).
            * A designspace, no UFOs: the UFOs will be loaded according to
                the designspace's sources. Instance and axis data will be
                converted to Glyphs.
            * Both a designspace and some UFOs: not supported for now.
                TODO: (jany) find out whether there is a use-case here?

        Keyword arguments:
        ufos -- The list of UFOs to combine into a GSFont
        designspace -- A MutatorMath Designspace to use for the GSFont
        glyphs_module -- The glyphsLib.classes module to use to build glyphsLib
                         classes (you can pass a custom module with the same
                         classes as the official glyphsLib.classes to get
                         instances of your own classes, or pass the Glyphs.app
                         module that holds the official classes to import UFOs
                         into Glyphs.app)
        ufo_module -- A Python module to use to load UFO objects from DS source paths.
                      You can pass a custom module that has the same classes as ufoLib2
                      or defcon to get instances of your own classes (default: ufoLib2)
        minimize_ufo_diffs -- set to True to store extra info in .glyphs files
                              in order to get smaller diffs between UFOs
                              when going UFOs->glyphs->UFOs
        expand_includes -- If True, expand include statements in the UFOs' features.fea
                           and inline them in the GSFont features.
        """
        ...
    
    @property
    def font(self): # -> Any:
        """Get the GSFont built from the UFOs + designspace."""
        ...
    


