
UFO2FT_COLOR_LAYERS_KEY: str
UFO2FT_COLOR_PALETTES_KEY: str
def _to_ufo_color_palette_layers(builder, master, layerMapping): ...
def _find_or_insert_color(color, palette): ...
def _radius(rect, point): ...
def _to_gradient_paint(gradient, layer, palette): ...
def _to_stroked_paint(attributes, layer, palette, ufo_glyph, ufo): ...
def _to_component_paint(component): ...
def _to_ufo_color_layers(builder, ufo, master, layerMapping): ...
def to_ufo_color_layers(self, ufo, master): ...
