from .common import to_ufo_color as to_ufo_color
from .constants import UFO2FT_COLOR_LAYERS_KEY as UFO2FT_COLOR_LAYERS_KEY, UFO2FT_COLOR_PALETTES_KEY as UFO2FT_COLOR_PALETTES_KEY

def _to_ufo_color_palette_layers(builder, master, layerMapping) -> None: ...
def _find_or_insert_color(color, palette): ...
def _radius(rect, point): ...
def _to_gradient_paint(gradient, layer, palette): ...
def _to_stroked_paint(attributes, layer, palette, ufo_glyph, ufo): ...
def _to_component_paint(component): ...
def _to_ufo_color_layers(builder, ufo, master, layerMapping) -> None: ...
def to_ufo_color_layers(self, ufo, master) -> None: ...
