from . import UFOBuilder as UFOBuilder
from ..classes import GSFont as GSFont, GSFontMaster as GSFontMaster
from .constants import ANONYMOUS_FEATURE_PREFIX_NAME as ANONYMOUS_FEATURE_PREFIX_NAME, GLYPHLIB_PREFIX as GLYPHLIB_PREFIX, INSERT_FEATURE_MARKER_COMMENT as INSERT_FEATURE_MARKER_COMMENT, INSERT_FEATURE_MARKER_RE as INSERT_FEATURE_MARKER_RE, LANGUAGE_MAPPING as LANGUAGE_MAPPING, ORIGINAL_CATEGORY_KEY as ORIGINAL_CATEGORY_KEY, ORIGINAL_FEATURE_CODE_KEY as ORIGINAL_FEATURE_CODE_KEY, REVERSE_LANGUAGE_MAPPING as REVERSE_LANGUAGE_MAPPING
from .tokens import PassThruExpander as PassThruExpander, TokenExpander as TokenExpander
from _typeshed import Incomplete
from glyphsLib.util import PeekableIterator as PeekableIterator
from ufoLib2 import Font as Font

def autostr(automatic): ...
def to_ufo_master_features(self, ufo, master) -> None: ...
def _to_name_langID(language): ...
def _to_glyphs_language(langID): ...
def _is_manual_kern_feature(feature):
    """Return true if the feature is a manually written 'kern' features."""
def _to_ufo_features(font: GSFont, ufo: Font | None = None, generate_GDEF: bool = False, master: GSFontMaster | None = None, expand_includes: bool = False, minimal: bool = False) -> str:
    """Convert GSFont features, including prefixes and classes, to UFO.

    Optionally, build a GDEF table definiton, excluding 'skip_export_glyphs'.
    """
def _build_public_opentype_categories(ufo: Font) -> dict[str, str]:
    '''Returns a dictionary mapping glyph names to GDEF categories.

    Does not handle ligature carets. A GDEF table with both categories and
    ligature carets is generated by ufo2ft\'s GdefFeatureWriter at compile time,
    using the categories dict and glyph data.

    Determining the categories requires anchor propagation or user care to work
    as expected, as Glyphs.app also looks at anchors for classification:

    * Base: any glyph that has an attaching anchor (such as "top"; "_top" does
      not count) and is neither classified as Ligature nor Mark using the
      definitions below;
    * Ligature: if subCategory is "Ligature" and the glyph has at least one
      attaching anchor;
    * Mark: if category is "Mark" and subCategory is either "Nonspacing" or
      "Spacing Combining";
    * Compound: never assigned by Glyphs.app.

    See:

    * https://github.com/googlefonts/glyphsLib/issues/85
    * https://github.com/googlefonts/glyphsLib/pull/100#issuecomment-275430289
    '''
def regenerate_gdef(self) -> None: ...
def regenerate_opentype_categories(font: GSFont, ufo: Font) -> None: ...
def _replace_block(kind, tag, repl, features): ...
def replace_feature(tag, repl, features): ...
def replace_table(tag, repl, features): ...
def replace_prefixes(repl_map, features_text, glyph_names=None):
    """Replace all '# Prefix: NAME' sections in features.

    Args:
        repl_map: Dict[str, str]: dictionary keyed by prefix name containing
            feature code snippets to be replaced.
        features_text: str: feature text to be parsed.
        glyph_names: Optional[Sequence[str]]: list of valid glyph names, used
            by feaLib Parser to distinguish glyph name tokens containing '-' from
            glyph ranges such as 'a-z'.

    Returns:
        str: new feature text with replaced prefix paragraphs.
    """
def to_glyphs_features(self) -> None: ...
def _to_glyphs_features(font, features_text, glyph_names=None, glyphs_module=None, include_dir=None, expand_includes: bool = False) -> None:
    """Import features text in GSFont, split into prefixes, features and classes.

    Args:
        font: GSFont
        feature_text: str
        glyph_names: Optional[Sequence[str]]
        glyphs_module: Optional[Any]
        include_dir: Optional[str]
        expand_includes: bool
    """
def _features_are_different_across_ufos(self): ...
def _normalize_whitespace(text): ...
def _to_glyphs_features_basic(self) -> None: ...

class FeaDocument:
    """Parse the string of a fea code into statements."""
    _doc: Incomplete
    statements: Incomplete
    _lines: Incomplete
    def __init__(self, text, glyph_set=None, include_dir=None, expand_includes: bool = False) -> None: ...
    def text(self, statements):
        """Recover the original fea code of the given statements from the
        given block.
        """
    def _statement_text(self, statement): ...
    def _build_end_locations(self) -> None: ...
    def _build_end_locations_rec(self, block) -> None: ...
    WHITESPACE_RE: Incomplete
    WHITESPACE_OR_NAME_RE: Incomplete
    def _previous_char(self, line, char): ...
    def _in_block_end_location(self, block): ...

class FeatureFileProcessor:
    """Put fea statements into the correct fields of a GSFont."""
    doc: Incomplete
    glyphs_module: Incomplete
    statements: Incomplete
    _font: Incomplete
    def __init__(self, doc, glyphs_module=None) -> None: ...
    def to_glyphs(self, font) -> None: ...
    PREFIX_RE: Incomplete
    AUTOMATIC_RE: Incomplete
    DISABLED_RE: Incomplete
    NOTES_RE: Incomplete
    def _process_file(self) -> None: ...
    def _process_prefix(self): ...
    def _process_glyph_class_definition(self): ...
    def _process_feature_block(self): ...
    def _process_gdef_table_block(self): ...
    def _pop_comment(self, statements, comment_re):
        """Look for the comment that matches the given regex.
        If it matches, return the regex match object and list of statements
        without the special one.
        """
    def _pop_comment_block(self, statements, header_re):
        """Look for a series of comments that start with one that matches the
        regex. If the first comment is found, all subsequent comments are
        popped from statements, concatenated and dedented and returned.
        """
    def _rstrip_newlines(self, string, number: int = 1): ...
