from .constants import BRACKET_GLYPH_RE as BRACKET_GLYPH_RE, UFO_GROUPS_NOT_IN_FEATURE_KEY as UFO_GROUPS_NOT_IN_FEATURE_KEY, UFO_KERN_GROUP_PATTERN as UFO_KERN_GROUP_PATTERN, UFO_ORIGINAL_KERNING_GROUPS_KEY as UFO_ORIGINAL_KERNING_GROUPS_KEY
from glyphsLib import classes as classes

def _get_glyphs_with_rtl_kerning(font): ...
def to_ufo_groups(self) -> None: ...
def to_glyphs_groups(self) -> None: ...
def _is_kerning_group(name): ...
def _to_glyphs_kerning_group(self, name, glyphs) -> None: ...
def _glyph_kerning_attr(side, is_rtl: bool = False):
    """Return rightKerningGroup or leftKerningGroup depending on the UFO
    group's side (1 or 2).

    Flip values for RTL kerning.
    """
def _assert_groups_are_identical(self, reference_ufo, ufo) -> None: ...
def _ufo_logging_ref(ufo):
    """Return a string that can identify this UFO in logs."""
