
UFO_ORIGINAL_KERNING_GROUPS_KEY: str
UFO_GROUPS_NOT_IN_FEATURE_KEY: str
def _get_glyphs_with_rtl_kerning(font): ...
def to_ufo_groups(self): ...
def to_glyphs_groups(self): ...
def _is_kerning_group(name): ...
def _to_glyphs_kerning_group(self, name, glyphs): ...
def _glyph_kerning_attr(side, is_rtl: bool = ...):
    """Return rightKerningGroup or leftKerningGroup depending on the UFO
    group's side (1 or 2).

    Flip values for RTL kerning.
    """
def _assert_groups_are_identical(self, reference_ufo, ufo): ...
def _ufo_logging_ref(ufo):
    """Return a string that can identify this UFO in logs."""

