from .constants import BRACKET_GLYPH_RE as BRACKET_GLYPH_RE, UFO_GROUPS_NOT_IN_FEATURE_KEY as UFO_GROUPS_NOT_IN_FEATURE_KEY, UFO_KERN_GROUP_PATTERN as UFO_KERN_GROUP_PATTERN, UFO_ORIGINAL_KERNING_GROUPS_KEY as UFO_ORIGINAL_KERNING_GROUPS_KEY
from glyphsLib import classes as classes

def to_ufo_groups(self) -> None: ...
def to_glyphs_groups(self) -> None: ...
