from .constants import HINTS_LIB_KEY as HINTS_LIB_KEY
from glyphsLib.types import IndexPath as IndexPath, Point as Point

def to_ufo_hints(self, ufo_glyph, layer) -> None: ...
def to_glyphs_hints(self, ufo_glyph, layer) -> None: ...
