"""
This type stub file was generated by pyright.
"""

def flip_class_side(s): # -> str:
    ...

def to_ufo_kerning(self): # -> None:
    ...

def to_glyphs_kerning(self): # -> None:
    """Add UFO kerning to GSFont."""
    ...

