def flip_class_side(s): ...
def to_ufo_kerning(self): ...
def _to_ufo_kerning(self, ufo, kerning_data):
    """Add .glyphs kerning to an UFO."""
def to_glyphs_kerning(self):
    """Add UFO kerning to GSFont."""
