from .constants import LAYER_ID_KEY as LAYER_ID_KEY, LAYER_ORDER_PREFIX as LAYER_ORDER_PREFIX, LAYER_ORDER_TEMP_USER_DATA_KEY as LAYER_ORDER_TEMP_USER_DATA_KEY, UFO2FT_COLOR_LAYER_MAPPING_KEY as UFO2FT_COLOR_LAYER_MAPPING_KEY

def to_ufo_color_layer_names(self, master, ufo) -> None: ...
def to_ufo_layer(self, glyph, layer): ...
def to_ufo_background_layer(self, layer): ...
def to_glyphs_layer(self, ufo_layer, glyph, master): ...
def to_glyphs_layer_order(self, glyph) -> None: ...
