UFO2FT_COLOR_LAYER_MAPPING_KEY: str
LAYER_ID_KEY: str
LAYER_ORDER_PREFIX: str
LAYER_ORDER_TEMP_USER_DATA_KEY: str
def to_ufo_color_layer_names(self, master, ufo): ...
def to_ufo_layer(self, glyph, layer): ...
def to_ufo_background_layer(self, layer): ...
def _layer_order_in_glyph(self, layer): ...
def to_glyphs_layer(self, ufo_layer, glyph, master): ...
def _get_or_make_foreground(self, glyph, master): ...
def to_glyphs_layer_order(self, glyph): ...
def _layer_order(layer): ...
