"""
This type stub file was generated by pyright.
"""

def to_ufo_paths(self, ufo_glyph, layer): # -> None:
    """Draw .glyphs paths onto a pen."""
    ...

def to_glyphs_paths(self, ufo_glyph, layer): # -> None:
    ...

