import enum
from glyphsLib.classes import GSLayer as GSLayer
from typing import ClassVar

class Pole(enum.IntEnum):
    _new_member_: ClassVar[builtin_function_or_method] = ...
    _use_args_: ClassVar[bool] = ...
    _member_names_: ClassVar[list] = ...
    _member_map_: ClassVar[dict] = ...
    _value2member_map_: ClassVar[dict] = ...
    _hashable_values_: ClassVar[list] = ...
    _unhashable_values_: ClassVar[list] = ...
    _unhashable_values_map_: ClassVar[dict] = ...
    _member_type_: ClassVar[type[int]] = ...
    _value_repr_: ClassVar[wrapper_descriptor] = ...
    MIN: ClassVar[Pole] = ...
    MAX: ClassVar[Pole] = ...
    __format__: ClassVar[method_descriptor] = ...
    @staticmethod
    def _generate_next_value_(name, start, count, last_values):
        """
        Generate the next value when not given.

        name: the name of the member
        start: the initial start value or None
        count: the number of existing members
        last_values: the list of values assigned
        """
    @classmethod
    def __init__(cls, value) -> None: ...
def normalized_location(layer, base_layer): ...
def variation_model(glyph, smart_layers, layer): ...
def get_coordinates(layer): ...
def set_coordinates(layer, coords): ...
def decompose_smart_components_in_layer(self, layer):
    """Decompose any smart components in a layer, returning a new layer with paths.

    This recursively instantiates nested smart components before extracting
    coordinates for interpolation.

    See https://github.com/googlefonts/glyphsLib/issues/1111
    """
def instantiate_smart_component(self, layer, component, pen):
    """Instantiate a smart component by interpolating and drawing to a pointPen."""
