from _typeshed import Incomplete
from typing import ClassVar

def _like(got, expected): ...

class TokenExpander:
    number_token_re: ClassVar[str] = ...
    glyph_predicate_re: ClassVar[str] = ...
    glyph_property_re: ClassVar[str] = ...
    bare_number_value_re: ClassVar[str] = ...
    gsglyph_predicate_objects: ClassVar[list] = ...
    gsglyph_predicate_object_re: ClassVar[str] = ...
    comparators_re: ClassVar[str] = ...
    apply_comparators: ClassVar[dict] = ...
    def __init__(self, font, master) -> None: ...
    def expand(self, featurecode): ...
    def _consume_match(self, m): ...
    def parse_token(self): ...
    def parse_bare_number_value(self, number): ...
    def parse_number_token(self, token, layer: Incomplete | None = ...): ...
    def parse_glyph_property(self, token): ...
    def parse_glyph_predicate(self, token): ...
    def _parse_glyph_predicate_to_array(self): ...
    def _parse_optional_not(self): ...
    def _parse_error_in_predicate(self, thing): ...
    def _parse_object(self): ...
    def _parse_comparator(self): ...
    def _parse_value(self): ...
    def _get_value_for_anchor(self, layer, value): ...
    def _get_value_for_layer(self, layer, value): ...
    def _get_value_for_glyph(self, g, value): ...
    def _compare(self, got, comparator, expected): ...
    def _parse_compound(self): ...

class PassThruExpander:
    def expand(self, token): ...
