from _typeshed import Incomplete

def _like(got, expected): ...

class TokenExpander:
    number_token_re: str
    glyph_predicate_re: str
    glyph_property_re: str
    bare_number_value_re: str
    font: Incomplete
    master: Incomplete
    def __init__(self, font, master) -> None: ...
    featurecode: Incomplete
    output: str
    position: int
    def expand(self, featurecode): ...
    def _consume_match(self, m) -> None: ...
    def parse_token(self) -> None: ...
    def parse_bare_number_value(self, number): ...
    def parse_number_token(self, token, layer=None): ...
    def parse_glyph_property(self, token): ...
    originaltoken: Incomplete
    glyph_predicate: Incomplete
    def parse_glyph_predicate(self, token): ...
    gsglyph_predicate_objects: Incomplete
    gsglyph_predicate_object_re: Incomplete
    comparators_re: str
    def _parse_glyph_predicate_to_array(self): ...
    def _parse_optional_not(self): ...
    def _parse_error_in_predicate(self, thing) -> None: ...
    def _parse_object(self): ...
    def _parse_comparator(self): ...
    def _parse_value(self): ...
    def _get_value_for_anchor(self, layer, value): ...
    def _get_value_for_layer(self, layer, value): ...
    def _get_value_for_glyph(self, g, value): ...
    apply_comparators: Incomplete
    def _compare(self, got, comparator, expected): ...
    def _parse_compound(self): ...

class PassThruExpander:
    def expand(self, token): ...
