from .constants import DEFAULT_FEATURE_WRITERS as DEFAULT_FEATURE_WRITERS, DEFAULT_LAYER_NAME as DEFAULT_LAYER_NAME, FONT_USER_DATA_KEY as FONT_USER_DATA_KEY, GLYPHS_MATH_EXTENDED_SHAPE_KEY as GLYPHS_MATH_EXTENDED_SHAPE_KEY, GLYPHS_MATH_PREFIX as GLYPHS_MATH_PREFIX, GLYPHS_MATH_VARIANTS_KEY as GLYPHS_MATH_VARIANTS_KEY, GLYPHS_PREFIX as GLYPHS_PREFIX, GLYPH_USER_DATA_KEY as GLYPH_USER_DATA_KEY, LAYER_LIB_KEY as LAYER_LIB_KEY, LAYER_NAME_KEY as LAYER_NAME_KEY, NODE_USER_DATA_KEY as NODE_USER_DATA_KEY, PUBLIC_PREFIX as PUBLIC_PREFIX, UFO2FT_FEATURE_WRITERS_KEY as UFO2FT_FEATURE_WRITERS_KEY, UFO_DATA_KEY as UFO_DATA_KEY
from _typeshed import Incomplete

logger: Incomplete

def to_designspace_family_user_data(self) -> None: ...
def to_ufo_family_user_data(self, ufo) -> None:
    """Set family-wide user data as Glyphs does."""
def to_ufo_master_user_data(self, ufo, master) -> None:
    """Set master-specific user data as Glyphs does."""
def to_ufo_glyph_user_data(self, ufo, ufo_glyph, glyph) -> None: ...
def to_ufo_layer_lib(self, master, ufo, ufo_layer) -> None: ...
def to_ufo_layer_user_data(self, ufo_glyph, layer) -> None: ...
def to_ufo_node_user_data(self, ufo_glyph, node, user_data: dict): ...
def to_glyphs_family_user_data_from_designspace(self) -> None:
    """Set the GSFont userData from the designspace family-wide lib data."""
def to_glyphs_family_user_data_from_ufo(self, ufo) -> None:
    """Set the GSFont userData from the UFO family-wide lib data."""
def to_glyphs_master_user_data(self, ufo, master) -> None:
    """Set the GSFontMaster userData from the UFO master-specific lib data."""
def to_glyphs_glyph_user_data(self, ufo, glyph) -> None: ...
def to_glyphs_layer_lib(self, ufo_layer, master) -> None: ...
def to_glyphs_layer_user_data(self, ufo_glyph, layer) -> None: ...
def to_glyphs_node_user_data(self, ufo_glyph, node, path_index, node_index) -> None: ...
