"""
This type stub file was generated by pyright.
"""

import fontFeatures
from .Routine import optimizations as routine_optimizations
from .FontFeatures import optimizations as overall_optimizations

class Optimizer:
    def __init__(self, ff) -> None:
        ...
    
    def optimize(self, level=...): # -> None:
        ...
    
    def optimize_routine(self, r, level): # -> None:
        ...
    


