"""
This type stub file was generated by pyright.
"""

from .l1snr import L1SNRDBLoss, L1SNRLoss, MultiL1SNRDBLoss, STFTL1SNRDBLoss, dbrms

__all__ = ["dbrms", "L1SNRLoss", "L1SNRDBLoss", "STFTL1SNRDBLoss", "MultiL1SNRDBLoss"]
__version__ = ...
