"""
This type stub file was generated by pyright.
"""

from . import base_profile
from .cute_profile import profile_ready

'''
Defines `profile_ready`, a decorator for flexibly profiling a function..

See its documentation for more details.
'''
