"""
This type stub file was generated by pyright.
"""

import abc

class BaseProfileHandler(metaclass=abc.ABCMeta):
    '''Profile handler which saves the profiling result in some way.'''
    def __call__(self, profile): # -> None:
        ...
    
    @abc.abstractmethod
    def handle(self): # -> None:
        ...
    
    make_file_name = ...


class AuxiliaryThreadProfileHandler(BaseProfileHandler):
    '''Profile handler that does its action on a separate thread.'''
    thread = ...
    def handle(self): # -> None:
        ...
    
    @abc.abstractmethod
    def thread_job(self): # -> None:
        ...
    


class EmailProfileHandler(AuxiliaryThreadProfileHandler):
    '''Profile handler that sends the profile via email on separate thread.'''
    def __init__(self, email_address, smtp_server, smtp_user, smtp_password, use_tls=...) -> None:
        ...
    
    def thread_job(self): # -> None:
        ...
    


class FolderProfileHandler(AuxiliaryThreadProfileHandler):
    '''Profile handler that saves the profile to disk on separate thread.'''
    def __init__(self, folder) -> None:
        ...
    
    def thread_job(self): # -> None:
        ...
    


class PrintProfileHandler(BaseProfileHandler):
    '''Profile handler that prints profile data to standard output.'''
    def __init__(self, sort_order) -> None:
        ...
    
    def handle(self): # -> None:
        ...
    


def get_profile_handler(profile_handler_string): # -> FolderProfileHandler | PrintProfileHandler | EmailProfileHandler:
    '''Parse `profile_handler_string` into a `ProfileHandler` class.'''
    ...

