"""
This type stub file was generated by pyright.
"""

from ..._core import builtin
from ..._layouts import DotOperandLayout
from .._layouts import AMDMFMALayout
from .._ops import _mma_scaled
from ..cdna3 import __all__ as __cdna3_all, _buffer_atomic_rmw_impl
from . import async_copy
from triton._C.libtriton.gluon_ir import get_amd_mfma_scale_layout as _get_mfma_scale_layout
from triton.runtime.jit import constexpr_function

__all__ = [*__cdna3_all, "async_copy", "mfma_scaled", "get_mfma_scale_layout"]
@builtin
def mfma_scaled(a, a_scale, a_format, b, b_scale, b_format, acc, _semantic=...): # -> tensor:
    """
    AMD Scaled MFMA operation.

    ```
    c = a * a_scale @ b * b_scale + acc
    ```

    `a` and `b` use microscaling formats described in
    "OCP Microscaling Formats (MX) Specification":
    https://www.opencompute.org/documents/ocp-microscaling-formats-mx-v1-0-spec-final-pdf.
    Currently supported only on CDNA4 hardware.

    Args:
        a (tensor): The operand A to be multiplied.
        a_scale (Optional[tensor]): Scale factor for operand A.
        a_format (str): Format of the operand A. Available formats: `e2m1`, `e4m3`, `e5m2`.
        b (tensor): The operand B to be multiplied.
        b_scale (Optional[tensor]): Scale factor for operand B.
        b_format (str): Format of the operand B. Available formats: `e2m1`, `e4m3`, `e5m2`.
        acc (tensor): Accumulator tensor.
    """

@constexpr_function
def get_mfma_scale_layout(dot_operand_layout, shape):
    """Get the scale layout for MFMA scaled operands.

    Args:
        dot_operand_layout (DotOperandLayout): The dot operand layout.
        shape (List[int]): The shape of the scale tensor.

    Return:
        layout (DistributedLinearLayout): The scale layout.
    """

@builtin
def buffer_atomic_max(ptr, offsets, value, mask=..., sem=..., scope=..., _semantic=...):
    ...

@builtin
def buffer_atomic_min(ptr, offsets, value, mask=..., sem=..., scope=..., _semantic=...):
    ...

@builtin
def buffer_atomic_add(ptr, offsets, value, mask=..., sem=..., scope=..., _semantic=...):
    ...

@builtin
def buffer_atomic_and(ptr, offsets, value, mask=..., sem=..., scope=..., _semantic=...):
    ...

@builtin
def buffer_atomic_or(ptr, offsets, value, mask=..., sem=..., scope=..., _semantic=...):
    ...

@builtin
def buffer_atomic_xor(ptr, offsets, value, mask=..., sem=..., scope=..., _semantic=...):
    ...

@builtin
def buffer_atomic_xchg(ptr, offsets, value, mask=..., sem=..., scope=..., _semantic=...):
    ...
