"""
This type stub file was generated by pyright.
"""

from fontParts.base.base import BaseDict
from fontParts.base.deprecated import DeprecatedGroups, RemovedGroups

class BaseGroups(BaseDict, DeprecatedGroups, RemovedGroups):
    """
    A Groups object. This object normally created as part of a
    :class:`BaseFont`. An orphan Groups object can be created like this::

        >>> groups = RGroups()

    This object behaves like a Python dictionary. Most of the dictionary
    functionality comes from :class:`BaseDict`, look at that object for the
    required environment implementation details.

    Groups uses :func:`normalizers.normalizeGroupKey` to normalize the key of
    the ``dict``, and :func:`normalizers.normalizeGroupValue` to normalize the
    value of the ``dict``.
    """
    keyNormalizer = ...
    valueNormalizer = ...
    _font = ...
    font = ...
    def findGlyph(self, glyphName): # -> list[Any]:
        """
        Returns a ``list`` of the group or groups associated with
        **glyphName**.
        **glyphName** will be an :ref:`type-string`. If no group is found
        to contain **glyphName** an empty ``list`` will be returned. ::

            >>> font.groups.findGlyph("A")
            ["A_accented"]
        """
        ...
    
    side1KerningGroups = ...
    side2KerningGroups = ...
    def remove(self, groupName): # -> None:
        """
        Removes a group from the Groups. **groupName** will be
        a :ref:`type-string` that is the group name to
        be removed.

        This is a backwards compatibility method.
        """
        ...
    
    def asDict(self): # -> dict[Any, Any]:
        """
        Return the Groups as a ``dict``.

        This is a backwards compatibility method.
        """
        ...
    
    def __contains__(self, groupName): # -> None:
        """
        Tests to see if a group name is in the Groups.
        **groupName** will be a :ref:`type-string`.
        This returns a ``bool`` indicating if the **groupName**
        is in the Groups. ::

            >>> "myGroup" in font.groups
            True
        """
        ...
    
    def __delitem__(self, groupName): # -> None:
        """
        Removes **groupName** from the Groups. **groupName** is a
        :ref:`type-string`.::

            >>> del font.groups["myGroup"]
        """
        ...
    
    def __getitem__(self, groupName): # -> None:
        """
        Returns the contents of the named group. **groupName** is a
        :ref:`type-string`. The returned value will be a
        :ref:`type-immutable-list` of the group contents.::

            >>> font.groups["myGroup"]
            ("A", "B", "C")

        It is important to understand that any changes to the returned group
        contents will not be reflected in the Groups object. If one wants to
        make a change to the group contents, one should do the following::

            >>> group = font.groups["myGroup"]
            >>> group.remove("A")
            >>> font.groups["myGroup"] = group
        """
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        """
        Iterates through the Groups, giving the key for each iteration. The
        order that the Groups will iterate though is not fixed nor is it
        ordered.::

            >>> for groupName in font.groups:
            >>>     print groupName
            "myGroup"
            "myGroup3"
            "myGroup2"
        """
        ...
    
    def __len__(self): # -> int:
        """
        Returns the number of groups in Groups as an ``int``.::

            >>> len(font.groups)
            5
        """
        ...
    
    def __setitem__(self, groupName, glyphNames): # -> None:
        """
        Sets the **groupName** to the list of **glyphNames**. **groupName**
        is the group name as a :ref:`type-string` and **glyphNames** is a
        ``list`` of glyph names as :ref:`type-string`.

            >>> font.groups["myGroup"] = ["A", "B", "C"]
        """
        ...
    
    def clear(self): # -> None:
        """
        Removes all group information from Groups,
        resetting the Groups to an empty dictionary. ::

            >>> font.groups.clear()
        """
        ...
    
    def get(self, groupName, default=...): # -> None:
        """
        Returns the contents of the named group.
        **groupName** is a :ref:`type-string`, and the returned values will
        either be :ref:`type-immutable-list` of group contents or ``None``
        if no group was found. ::

            >>> font.groups["myGroup"]
            ("A", "B", "C")

        It is important to understand that any changes to the returned group
        contents will not be reflected in the Groups object. If one wants to
        make a change to the group contents, one should do the following::

            >>> group = font.groups["myGroup"]
            >>> group.remove("A")
            >>> font.groups["myGroup"] = group
        """
        ...
    
    def items(self): # -> list[tuple[Any, Any]]:
        """
        Returns a list of ``tuple`` of each group name and group members.
        Group names are :ref:`type-string` and group members are a
        :ref:`type-immutable-list` of :ref:`type-string`. The initial
        list will be unordered.

            >>> font.groups.items()
            [("myGroup", ("A", "B", "C"), ("myGroup2", ("D", "E", "F"))]
        """
        ...
    
    def keys(self): # -> list[Any]:
        """
        Returns a ``list`` of all the group names in Groups. This list will be
        unordered.::

            >>> font.groups.keys()
            ["myGroup4", "myGroup1", "myGroup5"]
        """
        ...
    
    def pop(self, groupName, default=...): # -> None:
        """
        Removes the **groupName** from the Groups and returns the list of
        group members. If no group is found, **default** is returned.
        **groupName** is a :ref:`type-string`. This must return either
        **default** or a :ref:`type-immutable-list` of glyph names as
        :ref:`type-string`.

            >>> font.groups.pop("myGroup")
            ("A", "B", "C")
        """
        ...
    
    def update(self, otherGroups): # -> None:
        """
        Updates the Groups based on **otherGroups**. *otherGroups** is a
        ``dict`` of groups information. If a group from **otherGroups** is in
        Groups, the group members will be replaced by the group members from
        **otherGroups**. If a group from **otherGroups** is not in the Groups,
        it is added to the Groups. If Groups contain a group name that is not
        in *otherGroups**, it is not changed.

            >>> font.groups.update(newGroups)
        """
        ...
    
    def values(self): # -> list[Any]:
        """
        Returns a ``list`` of each named group's members.
        This will be a list of lists, the group members will be a
        :ref:`type-immutable-list` of :ref:`type-string`. The initial
        list will be unordered.

            >>> font.groups.items()
            [("A", "B", "C"), ("D", "E", "F")]
        """
        ...
    


