from _typeshed import Incomplete
from sympy.plotting.pygletplot.plot_mode import PlotMode as PlotMode

class PlotModeBase(PlotMode):
    """
    Intended parent class for plotting
    modes. Provides base functionality
    in conjunction with its parent,
    PlotMode.
    """
    i_vars: Incomplete
    d_vars: Incomplete
    intervals: Incomplete
    aliases: Incomplete
    is_default: bool
    styles: Incomplete
    style_override: str
    default_wireframe_color: Incomplete
    default_solid_color: Incomplete
    default_rot_preset: str
    def _get_evaluator(self): ...
    def _get_sympy_evaluator(self) -> None: ...
    def _get_lambda_evaluator(self) -> None: ...
    def _on_calculate_verts(self) -> None: ...
    def _on_calculate_cverts(self) -> None: ...
    verts: Incomplete
    cverts: Incomplete
    bounds: Incomplete
    cbounds: Incomplete
    _draw_lock: Incomplete
    _calculating_verts: Incomplete
    _calculating_cverts: Incomplete
    _calculating_verts_pos: float
    _calculating_verts_len: float
    _calculating_cverts_pos: float
    _calculating_cverts_len: float
    _max_render_stack_size: int
    _draw_wireframe: Incomplete
    _draw_solid: Incomplete
    _style: Incomplete
    _color: Incomplete
    predraw: Incomplete
    postdraw: Incomplete
    use_lambda_eval: Incomplete
    style: Incomplete
    color: Incomplete
    bounds_callback: Incomplete
    def __init__(self, *args, bounds_callback: Incomplete | None = None, **kwargs) -> None: ...
    def synchronized(f): ...
    def push_wireframe(self, function) -> None:
        """
        Push a function which performs gl commands
        used to build a display list. (The list is
        built outside of the function)
        """
    def push_solid(self, function) -> None:
        """
        Push a function which performs gl commands
        used to build a display list. (The list is
        built outside of the function)
        """
    def _create_display_list(self, function): ...
    def _render_stack_top(self, render_stack): ...
    def _draw_solid_display_list(self, dl) -> None: ...
    def _draw_wireframe_display_list(self, dl) -> None: ...
    def draw(self) -> None: ...
    def _on_change_color(self, color) -> None: ...
    def _on_calculate(self) -> None: ...
    def _calculate_all(self) -> None: ...
    def _calculate_verts(self) -> None: ...
    def _calculate_cverts(self) -> None: ...
    def _get_calculating_verts(self): ...
    def _get_calculating_verts_pos(self): ...
    def _get_calculating_verts_len(self): ...
    def _get_calculating_cverts(self): ...
    def _get_calculating_cverts_pos(self): ...
    def _get_calculating_cverts_len(self): ...
    def _get_style(self): ...
    def _set_style(self, v) -> None: ...
    def _get_color(self): ...
    def _set_color(self, v) -> None: ...
    calculating_verts: Incomplete
    calculating_verts_pos: Incomplete
    calculating_verts_len: Incomplete
    calculating_cverts: Incomplete
    calculating_cverts_pos: Incomplete
    calculating_cverts_len: Incomplete
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
