"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Callable, Optional, Type
from ufo2ft.instantiator import Instantiator
from ufo2ft.util import colrClipBoxQuantization

@dataclass
class BaseCompiler:
    postProcessorClass: Type = ...
    featureCompilerClass: Optional[Type] = ...
    featureWriters: Optional[list] = ...
    filters: Optional[list] = ...
    glyphOrder: Optional[list] = ...
    useProductionNames: Optional[bool] = ...
    removeOverlaps: bool = ...
    overlapsBackend: Optional[str] = ...
    inplace: bool = ...
    layerName: Optional[str] = ...
    skipExportGlyphs: Optional[bool] = ...
    debugFeatureFile: Optional[str] = ...
    notdefGlyph: Optional[str] = ...
    colrLayerReuse: bool = ...
    colrAutoClipBoxes: bool = ...
    colrClipBoxQuantization: Callable[[object], int] = ...
    feaIncludeDir: Optional[str] = ...
    skipFeatureCompilation: bool = ...
    ftConfig: dict = ...
    def __post_init__(self): # -> None:
        ...
    
    def compile(self, ufo): # -> Any:
        ...
    
    def preprocess(self, ufo_or_ufos):
        ...
    
    def compileOutlines(self, ufo, glyphSet):
        ...
    
    def postprocess(self, ttf, ufo, glyphSet, info=...): # -> Any:
        ...
    
    def compileFeatures(self, ufo, ttFont=..., glyphSet=...): # -> Any:
        """Compile OpenType Layout features from `ufo` into FontTools OTL tables.
        If `ttFont` is None, a new TTFont object is created containing the new
        tables, else the provided `ttFont` is updated with the new tables.

        If no explicit `featureCompilerClass` is provided, the one used will
        depend on whether the ufo contains any MTI feature files in its 'data'
        directory (thus the `MTIFeatureCompiler` is used) or not (then the
        default FeatureCompiler for Adobe FDK features is used).

        If skipExportGlyphs is provided (see description in the ``compile*``
        functions), the feature compiler will prune groups (removing them if empty)
        and kerning of the UFO of these glyphs. The feature file is left untouched.

        `debugFeatureFile` can be a file or file-like object opened in text mode,
        in which to dump the text content of the feature file, useful for debugging
        auto-generated OpenType features like kern, mark, mkmk etc.
        """
        ...
    


@dataclass
class BaseInterpolatableCompiler(BaseCompiler):
    """Create FontTools TrueType fonts from the DesignSpaceDocument UFO sources
    with interpolatable outlines. Cubic curves are converted compatibly to
    quadratic curves using the Cu2Qu conversion algorithm.

    If the Designspace contains a "public.skipExportGlyphs" lib key, these
    glyphs will not be exported to the final font. If these glyphs are used as
    components in any other glyph, those components get decomposed. If the lib
    key doesn't exist in the Designspace, all glyphs are exported (keys in
    individual UFOs are ignored). UFO groups and kerning will be pruned of
    skipped glyphs.

    The DesignSpaceDocument should contain SourceDescriptor objects with 'font'
    attribute set to an already loaded defcon.Font object (or compatible UFO
    Font class). If 'font' attribute is unset or None, an AttributeError exception
    is thrown.

    Return a copy of the DesignSpaceDocument object (or the same one if
    inplace=True) with the source's 'font' attribute set to the corresponding
    TTFont instance.

    For sources that have the 'layerName' attribute defined, the corresponding TTFont
    object will contain only a minimum set of tables ("head", "hmtx", "glyf", "loca",
    "maxp", "post" and "vmtx"), and no OpenType layout tables.
    """
    extraSubstitutions: Optional[dict] = ...
    variableFontNames: Optional[list] = ...
    instantiator: Optional[Instantiator] = ...
    compilingVFDefaultSource: bool = ...
    def compile(self, ufos): # -> Generator[Any, Any, None]:
        ...
    
    def compile_one(self, ufo, glyphSet, layerName): # -> Any:
        ...
    
    def compile_designspace(self, designSpaceDoc):
        ...
    
    def compile_variable(self, designSpaceDoc): # -> dict[Any, Any]:
        ...
    
    def compile_all_variable_features(self, designSpaceDoc, vfNameToTTFont, originalSources, originalGlyphsets, debugFeatureFile=...): # -> None:
        ...
    
    def compile_variable_features(self, designSpaceDoc, ttFont, glyphSet): # -> None:
        ...
    


