
from .baseCompiler import BaseInterpolatableCompiler
from dataclasses import dataclass
from typing import Optional, Type

@dataclass
class InterpolatableTTFCompiler(BaseInterpolatableCompiler):
    preProcessorClass: type = ...
    outlineCompilerClass: type = ...
    convertCubics: bool = ...
    cubicConversionError: float | None = ...
    reverseDirection: bool = ...
    flattenComponents: bool = ...
    layerNames: str | None = ...
    colrLayerReuse: bool = ...
    colrAutoClipBoxes: bool = ...
    autoUseMyMetrics: bool = ...
    allQuadratic: bool = ...
    skipFeatureCompilation: bool = ...
    def compileOutlines(self, ufo, glyphSet, layerName=...): # -> Any:
        ...
