
from .baseCompiler import BaseInterpolatableCompiler
from dataclasses import dataclass
from typing import Optional, Type
from ufo2ft.constants import CFFOptimization

@dataclass
class InterpolatableOTFCompiler(BaseInterpolatableCompiler):
    preProcessorClass: type = ...
    outlineCompilerClass: type = ...
    roundTolerance: float | None = ...
    optimizeCFF: CFFOptimization = ...
    colrLayerReuse: bool = ...
    colrAutoClipBoxes: bool = ...
    skipFeatureCompilation: bool = ...
    def compileOutlines(self, ufo, glyphSet, layerName=...): # -> Any:
        ...
