
from .baseCompiler import BaseCompiler
from dataclasses import dataclass
from typing import Optional, Type
from ufo2ft.constants import CFFOptimization

@dataclass
class OTFCompiler(BaseCompiler):
    preProcessorClass: type = ...
    outlineCompilerClass: type = ...
    optimizeCFF: CFFOptimization = ...
    roundTolerance: float | None = ...
    cffVersion: int = ...
    subroutinizer: str | None = ...
