
from .baseCompiler import BaseCompiler
from dataclasses import dataclass
from typing import Optional, Type

@dataclass
class TTFCompiler(BaseCompiler):
    preProcessorClass: type = ...
    outlineCompilerClass: type = ...
    convertCubics: bool = ...
    cubicConversionError: float | None = ...
    reverseDirection: bool = ...
    rememberCurveType: bool = ...
    flattenComponents: bool = ...
    autoUseMyMetrics: bool = ...
    dropImpliedOnCurves: bool = ...
    allQuadratic: bool = ...
    def compileOutlines(self, ufo, glyphSet): # -> Any:
        ...
