
from .interpolatableOTFCompiler import InterpolatableOTFCompiler
from dataclasses import dataclass
from typing import Optional, Type
from ufo2ft.constants import CFFOptimization

@dataclass
class VariableCFF2sCompiler(InterpolatableOTFCompiler):
    preProcessorClass: type = ...
    outlineCompilerClass: type = ...
    roundTolerance: float | None = ...
    colrAutoClipBoxes: bool = ...
    cffVersion: int = ...
    optimizeCFF: CFFOptimization = ...
    excludeVariationTables: tuple = ...
    variableFeatures: bool = ...
