
from .interpolatableTTFCompiler import InterpolatableTTFCompiler
from dataclasses import dataclass
from typing import Optional, Type

@dataclass
class VariableTTFsCompiler(InterpolatableTTFCompiler):
    preProcessorClass: type = ...
    outlineCompilerClass: type = ...
    convertCubics: bool = ...
    cubicConversionError: float | None = ...
    reverseDirection: bool = ...
    flattenComponents: bool = ...
    excludeVariationTables: tuple = ...
    optimizeGvar: bool = ...
    colrAutoClipBoxes: bool = ...
    autoUseMyMetrics: bool = ...
    dropImpliedOnCurves: bool = ...
    allQuadratic: bool = ...
    variableFeatures: bool = ...
