"""
This type stub file was generated by pyright.
"""

from itertools import *

if "batched" not in globals():
    def batched(iterable, n): # -> Generator[tuple[Any, ...], Any, None]:
        ...
    
