"""
This type stub file was generated by pyright.
"""

from collections import UserDict, UserList

__all__ = ["LazyDict", "LazyList"]
class LazyDict(UserDict):
    def __init__(self, data) -> None:
        ...
    
    def __getitem__(self, k): # -> object:
        ...
    


class LazyList(UserList):
    def __getitem__(self, k): # -> list[list[Any] | object | Any] | object:
        ...
    
    def __add__(self, other): # -> NotImplementedType | list[Any]:
        ...
    
    def __radd__(self, other): # -> NotImplementedType | list[Any]:
        ...
    


