from _typeshed import Incomplete
from fontTools.misc.textTools import tobytes as tobytes, tostr as tostr

__version__: str
__copyright__: str

class Error(Exception): ...

def pack(fmt, obj): ...
def unpack(fmt, data, obj=None): ...
def unpack2(fmt, data, obj=None): ...
def calcsize(fmt): ...

_elementRE: Incomplete
_extraRE: Incomplete
_emptyRE: Incomplete
_fixedpointmappings: Incomplete
_formatcache: Incomplete

def getformat(fmt, keep_pad_byte: bool = False): ...
def _test() -> None: ...
