from fontTools.misc.textTools import tobytes as tobytes, tostr as tostr

__version__: str

class Error(Exception): ...

def pack(fmt, obj): ...
def unpack(fmt, data, obj=None): ...
def unpack2(fmt, data, obj=None): ...
def calcsize(fmt): ...
def getformat(fmt, keep_pad_byte: bool = False): ...
