from _typeshed import Incomplete

__all__ = ['Vector']

class Vector(tuple):
    """A math-like vector.

    Represents an n-dimensional numeric vector. ``Vector`` objects support
    vector addition and subtraction, scalar multiplication and division,
    negation, rounding, and comparison tests.
    """
    __slots__: Incomplete
    def __new__(cls, values, keep: bool = False): ...
    def __repr__(self) -> str: ...
    def _vectorOp(self, other, op): ...
    def _scalarOp(self, other, op): ...
    def _unaryOp(self, op): ...
    def __add__(self, other): ...
    __radd__ = __add__
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __mul__(self, other): ...
    __rmul__ = __mul__
    def __truediv__(self, other): ...
    def __rtruediv__(self, other): ...
    def __pos__(self): ...
    def __neg__(self): ...
    def __round__(self, *, round=...): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __bool__(self) -> bool: ...
    __nonzero__ = __bool__
    def __abs__(self): ...
    def length(self):
        """Return the length of the vector. Equivalent to abs(vector)."""
    def normalized(self):
        """Return the normalized vector of the vector."""
    def dot(self, other):
        """Performs vector dot product, returning the sum of
        ``a[0] * b[0], a[1] * b[1], ...``"""
    def toInt(self): ...
    @property
    def values(self): ...
    @values.setter
    def values(self, values) -> None: ...
    def isclose(self, other: Vector, **kwargs) -> bool:
        """Return True if the vector is close to another Vector."""
