from _typeshed import Incomplete
from fontTools import ttLib as ttLib
from fontTools.misc.textTools import safeEval as safeEval
from fontTools.ttLib import TTFont
from fontTools.ttLib.tables.DefaultTable import DefaultTable as DefaultTable

log: Incomplete

class TTXParseError(Exception): ...

BUFSIZE: int

class XMLReader:
    file: Incomplete
    _closeStream: bool
    ttFont: Incomplete
    progress: Incomplete
    quiet: Incomplete
    root: Incomplete
    contentStack: Incomplete
    contentOnly: Incomplete
    stackSize: int
    def __init__(self, fileOrPath, ttFont: TTFont, progress=None, quiet=None, contentOnly: bool = False) -> None: ...
    def read(self, rootless: bool = False) -> None: ...
    def close(self) -> None: ...
    def _parseFile(self, file) -> None: ...
    currentTable: Incomplete
    def _startElementHandler(self, name, attrs) -> None: ...
    def _characterDataHandler(self, data) -> None: ...
    def _endElementHandler(self, name) -> None: ...

class ProgressPrinter:
    def __init__(self, title, maxval: int = 100) -> None: ...
    def set(self, val, maxval=None) -> None: ...
    def increment(self, val: int = 1) -> None: ...
    def setLabel(self, text) -> None: ...
