"""
This type stub file was generated by pyright.
"""

from typing import List, Optional, Tuple
from .BaseObject import BaseObject, I18NDictionary, Number
from dataclasses import dataclass

Tag = str
@dataclass
class _AxisFields:
    name: I18NDictionary = ...
    tag: Tag = ...
    id: str = ...
    min: int = ...
    max: int = ...
    default: int = ...
    map: List[Tuple[int, int]] = ...
    hidden: bool = ...


@dataclass
class Axis(BaseObject, _AxisFields):
    """Represents an axis in a multiple master or variable font."""
    _write_one_line = ...
    def __post_init__(self): # -> None:
        ...
    
    def normalize_value(self, value: Number) -> float:
        """Return a normalized co-ordinate (-1.0 to 1.0) for the given value.
        The value provided is expected to be in userspace coordinates."""
        ...
    
    def denormalize_value(self, value: float) -> Number:
        """Return a userspace coordinate for the given normalized value."""
        ...
    
    @property
    def maximum(self): # -> int:
        ...
    
    @property
    def minimum(self): # -> int:
        ...
    
    @property
    def maxValue(self): # -> int:
        ...
    
    @property
    def minValue(self): # -> int:
        ...
    
    @property
    def axisTag(self): # -> Tag:
        ...
    
    @property
    def defaultValue(self): # -> int:
        ...
    
    @property
    def inverted_map(self) -> Optional[Tuple[float, float]]:
        """Return the axis map as a list of tuples, where the first value is the
        designspace coordinate and the second value is the userspace coordinate."""
        ...
    
    def map_forward(self, v: Number) -> Number:
        """Map a location on this axis from userspace to designspace."""
        ...
    
    def map_backward(self, v: Number) -> Number:
        """Map a location on this axis from designspace to userspace."""
        ...
    
    def userspace_to_designspace(self, v: Number) -> Number:
        """Map a location on this axis from userspace to designspace."""
        ...
    
    def designspace_to_userspace(self, v: Number) -> Number:
        """Map a location on this axis from designspace to userspace."""
        ...
    


