
from dataclasses import dataclass
from typing import TypeAlias, Union

class IncompatibleMastersError(ValueError):
    ...


Color = ...
Position = ...
Number: TypeAlias = int | float
class I18NDictionary(dict):
    @classmethod
    def with_default(cls, s): # -> Self:
        ...

    def copy_in(self, other): # -> None:
        ...

    def default_or_dict(self): # -> Self | None:
        ...

    def get_default(self): # -> None:
        ...

    def set_default(self, value): # -> None:
        ...

    def write(self, stream, indent): # -> None:
        ...

    @property
    def as_fonttools_dict(self): # -> dict[Any, Any]:
        ...



@dataclass
class BaseObject:
    _formatspecific: dict = ...
    _: dict = ...
    def __post_init__(self): # -> None:
        ...

    _write_one_line = ...
    _separate_items = ...
    def write(self, stream, indent=...): # -> None:
        ...
