"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from .BaseObject import BaseObject

@dataclass
class Component(BaseObject):
    name: str
    position: list = ...
    transform: list = ...
    _serialize_slots = ...


