"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Tuple
from babelfont import Font
from .BaseObject import BaseObject

PREFIX_MARKER = ...
PREFIX_RE = ...
@dataclass
class Features(BaseObject):
    """A representation of the OpenType feature code."""
    classes: Dict[str, List[str]] = ...
    prefixes: Dict[str, str] = ...
    features: List[Tuple[str, str]] = ...
    @classmethod
    def from_fea(cls, fea: str, glyphNames=...) -> Features:
        """Load features from a .fea file."""
        ...
    
    def to_fea(self) -> str:
        """Dump features to a .fea file."""
        ...
    
    def as_ast(self, font: Font) -> Dict[str, Any]:
        ...
    


