
from .BaseObject import BaseObject
from .Layer import Layer
from dataclasses import dataclass
from typing import List, Optional

@dataclass
class _GlyphFields:
    name: str
    production_name: str | None = ...
    category: str = ...
    codepoints: list[int] = ...
    layers: list[Layer] = ...
    exported: bool = ...
    direction: str = ...


@dataclass
class Glyph(BaseObject, _GlyphFields):
    _write_one_line = ...
    @property
    def babelfont_filename(self): # -> str:
        ...



class GlyphList(dict):
    def append(self, thing): # -> None:
        ...

    def write(self, stream, indent): # -> None:
        ...

    def __iter__(self) -> GlyphList:
        ...

    def __next__(self) -> Glyph:
        ...
