
from .Anchor import Anchor
from .BaseObject import BaseObject, Color
from .Font import Font
from .Glyph import Glyph
from .Guide import Guide
from .Shape import Shape
from dataclasses import dataclass
from fontTools.ufoLib.pointPen import AbstractPointPen
from functools import cached_property
from typing import List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    ...
@dataclass
class _LayerFields:
    width: int = ...
    height: int = ...
    vertWidth: int | None = ...
    name: str = ...
    _master: str = ...
    id: str = ...
    guides: list[Guide] = ...
    shapes: list[Shape] = ...
    anchors: list[Anchor] = ...
    color: Color = ...
    layerIndex: int = ...
    background: str | None = ...
    isBackground: bool = ...
    location: list[float] = ...
    _font: Font | None = ...
    _glyph: Glyph | None = ...


@dataclass
class Layer(BaseObject, _LayerFields):
    @property
    def master(self): # -> Master | None:
        ...

    @property
    def paths(self) -> list[Shape]:
        ...

    @property
    def components(self) -> list[Shape]:
        ...

    def recursive_component_set(self): # -> set[str | Any]:
        ...

    @cached_property
    def bounds(self): # -> Incomplete:
        ...

    @property
    def lsb(self): # -> Incomplete | Literal[0]:
        ...

    @property
    def rsb(self): # -> Any | Literal[0]:
        ...

    @property
    def valid(self): # -> bool:
        ...

    @property
    def anchors_dict(self): # -> dict[str, Anchor]:
        ...

    def draw(self, pen): # -> None:
        ...

    def drawPoints(self, pen): # -> None:
        ...

    def clearContours(self): # -> None:
        ...

    def getPen(self): # -> SegmentToPointPen:
        ...

    def decompose(self): # -> None:
        ...



class LayerPen(AbstractPointPen):
    def __init__(self, target) -> None:
        ...

    def beginPath(self, identifier=..., **kwargs): # -> None:
        ...

    def endPath(self): # -> None:
        """End the current sub path."""

    def addPoint(self, pt, segmentType=..., smooth=..., name=..., identifier=..., **kwargs): # -> None:
        ...

    def addComponent(self, baseGlyphName, transformation, identifier=..., **kwargs): # -> None:
        ...
