
from .BaseObject import BaseObject, I18NDictionary
from .Guide import Guide
from .Layer import Layer
from dataclasses import dataclass
from typing import Optional, Union

CORE_METRICS = ...
@dataclass
class _MasterFields:
    name: I18NDictionary
    id: str = ...
    location: dict = ...
    sparse: bool = ...
    guides: [Guide] = ...
    metrics: dict = ...
    kerning: dict = ...
    font: Font = ...


@dataclass
class Master(BaseObject, _MasterFields):
    """A font master."""

    CORE_METRICS = ...
    def __post_init__(self): # -> None:
        ...

    def get_glyph_layer(self, glyphname: str) -> Layer | None:
        ...

    @property
    def normalized_location(self) -> dict[str, float]:
        ...

    @property
    def xHeight(self) -> int | float:
        ...

    @property
    def capHeight(self) -> int | float:
        ...

    @property
    def ascender(self) -> int | float:
        ...

    @property
    def descender(self) -> int | float:
        ...

    @property
    def valid(self) -> bool:
        ...
