"""
This type stub file was generated by pyright.
"""

from fontTools.pens.pointPen import AbstractPointPen

class DigestPointPen(AbstractPointPen):
    """
    This calculates a tuple representing the structure and values in a glyph:

        - including coordinates
        - including components
    """
    def __init__(self, ignoreSmoothAndName=...) -> None:
        ...
    
    def beginPath(self, identifier=...): # -> None:
        ...
    
    def endPath(self): # -> None:
        ...
    
    def addPoint(self, pt, segmentType=..., smooth=..., name=..., **kwargs): # -> None:
        ...
    
    def addComponent(self, baseGlyphName, transformation, identifier=...): # -> None:
        ...
    
    def getDigest(self): # -> tuple[Any, ...]:
        """
        Return the digest as a tuple with all coordinates of all points.
        """
        ...
    
    def getDigestPointsOnly(self, needSort=...): # -> tuple[Any, ...]:
        """
        Return the digest as a tuple with all coordinates of all points,
        - but without smooth info or drawing instructions.
        - For instance if you want to compare 2 glyphs in shape,
          but not interpolatability.
        """
        ...
    


class DigestPointStructurePen(DigestPointPen):
    """
    This calculates a tuple representing the structure and values in a glyph:

        - excluding coordinates
        - excluding components
    """
    def addPoint(self, pt, segmentType=..., smooth=..., name=..., **kwargs): # -> None:
        ...
    
    def addComponent(self, baseGlyphName, transformation, identifier=...): # -> None:
        ...
    


if __name__ == "__main__":
    ...
