"""
This type stub file was generated by pyright.
"""

from fontTools.pens.pointPen import AbstractPointPen

class GuessSmoothPointPen(AbstractPointPen):
    """
    Filtering PointPen that tries to determine whether an on-curve point
    should be "smooth", ie. that it's a "tangent" point or a "curve" point.
    """
    def __init__(self, outPen, error=...) -> None:
        ...
    
    def beginPath(self, identifier=...): # -> None:
        ...
    
    def endPath(self): # -> None:
        ...
    
    def addPoint(self, pt, segmentType=..., smooth=..., name=..., **kwargs): # -> None:
        ...
    
    def addComponent(self, glyphName, transformation, identifier=...): # -> None:
        ...
    


if __name__ == "__main__":
    ...
