from _typeshed import Incomplete
from mpmath.ctx_mp_python import PythonMPContext, _mpc, _mpf
from sympy.polys.domains.domainelement import DomainElement

__all__ = ['RealElement', 'ComplexElement', 'MPContext']

class RealElement(_mpf, DomainElement):
    """An element of a real domain. """
    __slots__: Incomplete
    __mpf__: Incomplete
    def _set_mpf(self, val) -> None: ...
    _mpf_: Incomplete
    def parent(self): ...

class ComplexElement(_mpc, DomainElement):
    """An element of a complex domain. """
    __slots__: Incomplete
    __mpc__: Incomplete
    def _set_mpc(self, val) -> None: ...
    _mpc_: Incomplete
    def parent(self): ...

class MPContext(PythonMPContext):
    def __init__(ctx, prec: int = 53, dps: Incomplete | None = None, tol: Incomplete | None = None, real: bool = False) -> None: ...
    def _make_tol(ctx): ...
    def make_tol(ctx): ...
    def _convert_tol(ctx, tol): ...
    def _convert_fallback(ctx, x, strings) -> None: ...
    @property
    def _repr_digits(ctx): ...
    @property
    def _str_digits(ctx): ...
    def to_rational(ctx, s, limit: bool = True): ...
    def almosteq(ctx, s, t, rel_eps: Incomplete | None = None, abs_eps: Incomplete | None = None): ...
