def pad_along_axis(array, target_length, axis: int = 0): ...
def hwr(x, floor: float = 1e-07): ...
def compute_nbwin(size, frame_length, hop_length): ...
def compute_length(nbwin, frame_length, hop_length): ...
def triangular_window(length, power: float = 1.0): ...
def frame_signal(x, frame_length, hop_length): ...
def unframe_signal(framed, hop_length, window_fn=...): ...
