from numpy import bool_ as bool_, floating as floating
from numpy.typing import NDArray as NDArray
from os import PathLike
from typing import Any

def load_json(path: str | PathLike[Any]) -> Any: ...
def load_audio(path: str | PathLike[Any], fsspec_kwargs: dict[Any, Any] | None = None, **kwargs: Any) -> list[NDArray[floating[Any]] | float]: ...
def save_audio(path: str | PathLike[Any], audio: NDArray[floating[Any]], **kwargs: Any) -> None: ...
def get_fs(path: str | PathLike[Any]) -> Any: ...
