from numba.core import errors as errors
from numba.core.extending import overload as overload
from numba.core.pythonapi import NativeValue as NativeValue, box as box, unbox as unbox
from numba.core.types import BaseTuple as BaseTuple, Boolean as Boolean, Number as Number, UniTuple as UniTuple
from numba.cpython.builtins import cast_int as cast_int, max_vararg as max_vararg, min_vararg as min_vararg
from numba.np.types import NPDatetime as NPDatetime, NPTimedelta as NPTimedelta

def box_npdatetime(typ, val, c): ...
def unbox_npdatetime(typ, obj, c): ...
def box_nptimedelta(typ, val, c): ...
def unbox_nptimedelta(typ, obj, c): ...
def ol_max_datetime(*x): ...
def ol_min_datetime(*x): ...
def ol_int(x): ...
