from numba.core import types as types
from numba.core.errors import TypingError as TypingError
from numba.core.extending import overload as overload, register_jitable as register_jitable

def _siftdown(heap, startpos, pos) -> None: ...
def _siftup(heap, pos) -> None: ...
def _siftdown_max(heap, startpos, pos) -> None: ...
def _siftup_max(heap, pos) -> None: ...
def reversed_range(x): ...
def _heapify_max(x) -> None: ...
def _heapreplace_max(heap, item): ...
def assert_heap_type(heap) -> None: ...
def assert_item_type_consistent_with_heap_type(heap, item) -> None: ...
def hq_heapify(x): ...
def hq_heappop(heap): ...
def heappush(heap, item): ...
def heapreplace(heap, item): ...
def heappushpop(heap, item): ...
def check_input_types(n, iterable) -> None: ...
def nsmallest(n, iterable): ...
def nlargest(n, iterable): ...
