from _typeshed import Incomplete
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from fontTools.config import OPTIONS as OPTIONS
from fontTools.misc.intTools import bit_count as bit_count, bit_indices as bit_indices
from fontTools.ttLib import TTFont as TTFont
from fontTools.ttLib.tables import otBase as otBase, otTables as otTables
from functools import cached_property as cached_property
from typing import NamedTuple, TypeAlias

log: Incomplete
COMPRESSION_LEVEL: Incomplete
GPOS_COMPACT_MODE_ENV_KEY: str
GPOS_COMPACT_MODE_DEFAULT: Incomplete

def _compression_level_from_env() -> int: ...
def compact(font: TTFont, level: int) -> TTFont: ...
def compact_lookup(font: TTFont, level: int, lookup: otTables.Lookup) -> None: ...
def compact_ext_lookup(font: TTFont, level: int, lookup: otTables.Lookup) -> None: ...
def compact_pair_pos(font: TTFont, level: int, subtables: Sequence[otTables.PairPos]) -> Sequence[otTables.PairPos]: ...
def compact_class_pairs(font: TTFont, level: int, subtable: otTables.PairPos) -> list[otTables.PairPos]: ...
def is_really_zero(class2: otTables.Class2Record) -> bool: ...
Pairs: TypeAlias = dict[tuple[tuple[str, ...], tuple[str, ...]], tuple[otBase.ValueRecord, otBase.ValueRecord]]

def _getClassRanges(glyphIDs: Iterable[int]): ...
def _classDef_bytes(class_data: list[tuple[list[tuple[int, int]], int, int]], class_ids: list[int], coverage: bool = False): ...

class ClusteringContext(NamedTuple):
    lines: Incomplete
    all_class1: Incomplete
    all_class1_data: Incomplete
    all_class2_data: Incomplete
    valueFormat1_bytes: Incomplete
    valueFormat2_bytes: Incomplete

@dataclass
class Cluster:
    ctx: ClusteringContext
    indices_bitmask: int
    @cached_property
    def indices(self): ...
    @cached_property
    def column_indices(self): ...
    @property
    def width(self): ...
    @cached_property
    def cost(self): ...
    @property
    def coverage_bytes(self): ...
    @property
    def classDef1_bytes(self): ...
    @property
    def classDef2_bytes(self): ...

def cluster_pairs_by_class2_coverage_custom_cost(font: TTFont, pairs: Pairs, compression: int = 5) -> list[Pairs]: ...
