from _typeshed import Incomplete
from torch import nn

def exists(val): ...
def default(val, d): ...
def calc_same_padding(kernel_size): ...

class Swish(nn.Module):
    def forward(self, x): ...

class GLU(nn.Module):
    dim: Incomplete
    def __init__(self, dim) -> None: ...
    def forward(self, x): ...

class DepthWiseConv1d(nn.Module):
    padding: Incomplete
    conv: Incomplete
    def __init__(self, chan_in, chan_out, kernel_size, padding) -> None: ...
    def forward(self, x): ...

class Scale(nn.Module):
    fn: Incomplete
    scale: Incomplete
    def __init__(self, scale, fn) -> None: ...
    def forward(self, x, **kwargs): ...

class PreNorm(nn.Module):
    fn: Incomplete
    norm: Incomplete
    def __init__(self, dim, fn) -> None: ...
    def forward(self, x, **kwargs): ...

class Attention(nn.Module):
    heads: Incomplete
    scale: Incomplete
    to_q: Incomplete
    to_kv: Incomplete
    to_out: Incomplete
    max_pos_emb: Incomplete
    rel_pos_emb: Incomplete
    dropout: Incomplete
    def __init__(self, dim, heads: int = 8, dim_head: int = 64, dropout: float = 0.0, max_pos_emb: int = 512) -> None: ...
    def forward(self, x, context=None, mask=None, context_mask=None): ...

class FeedForward(nn.Module):
    net: Incomplete
    def __init__(self, dim, mult: int = 4, dropout: float = 0.0) -> None: ...
    def forward(self, x): ...

class ConformerConvModule(nn.Module):
    net: Incomplete
    def __init__(self, dim, causal: bool = False, expansion_factor: int = 2, kernel_size: int = 31, dropout: float = 0.0) -> None: ...
    def forward(self, x): ...

class ConformerBlock(nn.Module):
    ff1: Incomplete
    attn: Incomplete
    conv: Incomplete
    ff2: Incomplete
    post_norm: Incomplete
    def __init__(self, *, dim, dim_head: int = 64, heads: int = 8, ff_mult: int = 4, conv_expansion_factor: int = 2, conv_kernel_size: int = 31, attn_dropout: float = 0.0, ff_dropout: float = 0.0, conv_dropout: float = 0.0, conv_causal: bool = False) -> None: ...
    def forward(self, x, mask=None): ...

class Conformer(nn.Module):
    dim: Incomplete
    layers: Incomplete
    def __init__(self, dim, *, depth, dim_head: int = 64, heads: int = 8, ff_mult: int = 4, conv_expansion_factor: int = 2, conv_kernel_size: int = 31, attn_dropout: float = 0.0, ff_dropout: float = 0.0, conv_dropout: float = 0.0, conv_causal: bool = False) -> None: ...
    def forward(self, x): ...
