
from collections.abc import Sequence
from pathlib import Path
from picosvg.svg_transform import Affine2D
from typing import NamedTuple, Optional, Tuple

FLAGS = ...
_DEFAULT_CONFIG_FILE = ...
_COLOR_FORMATS = ...
class Axis(NamedTuple):
    axisTag: str
    name: str
    default: float


class AxisPosition(NamedTuple):
    axisTag: str
    position: float


class MasterConfig(NamedTuple):
    name: str
    style_name: str
    output_ufo: str
    position: tuple[AxisPosition, ...]
    sources: tuple[Path, ...]
    def pos(self, axisTag: str) -> float:
        ...



class FontConfig(NamedTuple):
    family: str = ...
    output_file: str = ...
    color_format: str = ...
    upem: int = ...
    width: int = ...
    ascender: int = ...
    descender: int = ...
    linegap: int = ...
    transform: Affine2D = ...
    version_major: int = ...
    version_minor: int = ...
    reuse_tolerance: float = ...
    ignore_reuse_error: bool = ...
    keep_glyph_names: bool = ...
    clip_to_viewbox: bool = ...
    clipbox_quantization: int | None = ...
    fea_file: str = ...
    glyphmap_generator: str = ...
    bitmap_resolution: int = ...
    bitmap_resolutions: tuple[int, ...] = ...
    use_zopflipng: bool = ...
    use_pngquant: bool = ...
    pngquant_flags: str = ...
    pretty_print: bool = ...
    axes: tuple[Axis, ...] = ...
    masters: tuple[MasterConfig, ...] = ...
    source_names: tuple[str, ...] = ...
    @property
    def output_format(self): # -> str:
        ...

    @property
    def has_bitmaps(self) -> bool:
        ...

    @property
    def has_picosvgs(self) -> bool:
        ...

    @property
    def has_untouchedsvgs(self) -> bool:
        ...

    @property
    def has_svgs(self) -> bool:
        ...

    @property
    def is_vf(self) -> bool:
        ...

    @property
    def is_ot_svg(self) -> bool:
        ...

    def validate(self): # -> Self:
        ...

    def default(self) -> MasterConfig:
        ...



def write(dest: Path, config: FontConfig): # -> None:
    ...

_DEFAULT_CONFIG = ...
def load(config_file: Path | None = ..., additional_srcs: tuple[Path] | None = ...) -> FontConfig:
    ...

def load_configs(config_files: Sequence[Path], additional_srcs: tuple[Path] | None = ...) -> tuple[FontConfig]:
    ...
