"""
This type stub file was generated by pyright.
"""

"""Helps deal with emoji OpenType Layout features."""
DEFAULT_GSUB_FEATURE_TAG = ...
def generate_fea(rgi_sequences, feature_tag=...): # -> LiteralString:
    ...

