"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Tuple

@dataclass(frozen=True)
class GlyphMapping:
    svg_file: Optional[Path]
    bitmap_file: Optional[Path]
    codepoints: Tuple[int, ...]
    glyph_name: str
    def __post_init__(self): # -> None:
        ...
    
    def csv_line(self) -> str:
        ...
    


def load_from(file) -> Tuple[GlyphMapping]:
    ...

def parse_csv(filename) -> Tuple[GlyphMapping]:
    ...

