"""
This type stub file was generated by pyright.
"""

"""Wrapper around pngquant command.

This runs the pnquant command as a subprocess, forwarding all the unparsed options
after '--', while also handling two special error codes 98 or 99 by simply copying the
input file to the output file.
Pngquant exits with 98 when the conversion results in a larger file than the original;
and with 99 when the conversion results in quality below the requested minimum.

Usage:

    $ python -m nanoemoji.pngquant -i INPUT -o OUTPUT -- [PNGQUANTFLAGS]
"""
FLAGS = ...
def main(argv): # -> int:
    ...

if __name__ == "__main__":
    ...
