"""
This type stub file was generated by pyright.
"""

import ufoLib2
from fontTools import ttLib
from nanoemoji import codepoints
from nanoemoji.config import FontConfig
from nanoemoji.color_glyph import ColorGlyph
from nanoemoji.glyph import glyph_name
from nanoemoji.png import PNG
from pathlib import Path
from picosvg.svg import SVG
from typing import Callable, NamedTuple, Optional, Tuple

"""Writes UFO and/or font files."""
FLAGS = ...
class InputGlyph(NamedTuple):
    svg_file: Optional[Path]
    bitmap_file: Optional[Path]
    codepoints: Tuple[int, ...]
    glyph_name: str
    svg: Optional[SVG]
    bitmap: Optional[PNG]
    ...


class ColorGenerator(NamedTuple):
    apply_ufo: Callable[[FontConfig, ufoLib2.Font, Tuple[ColorGlyph, ...]], None]
    apply_ttfont: Callable[[FontConfig, ufoLib2.Font, Tuple[ColorGlyph, ...], ttLib.TTFont], None]
    font_ext: str
    ...


_COLOR_FORMAT_GENERATORS = ...
def main(argv): # -> None:
    ...

if __name__ == "__main__":
    ...
