"""
This type stub file was generated by pyright.
"""

"""Writes an html file suitable to screenshot for a single font glyph"""
FLAGS = ...
def main(argv): # -> None:
    ...

if __name__ == "__main__":
    ...
