from numba.core import cgutils as cgutils, types as types
from numba.core.extending import intrinsic as intrinsic, make_attribute_wrapper as make_attribute_wrapper, models as models, overload as overload, register_jitable as register_jitable, register_model as register_model

class NumPyRngBitGeneratorModel(models.StructModel):
    def __init__(self, dmm, fe_type) -> None: ...

class NumPyRandomGeneratorTypeModel(models.StructModel):
    def __init__(self, dmm, fe_type) -> None: ...

def next_double(bitgen): ...
def next_uint32(bitgen): ...
def next_uint64(bitgen): ...
@register_jitable
def next_float(bitgen): ...
