from ..args import In as In, InOut as InOut, Out as Out
from .cudadrv.devices import gpus as gpus, require_context as require_context, reset as reset
from .kernel import FakeCUDAKernel as FakeCUDAKernel
from collections.abc import Generator
from contextlib import contextmanager
from numba.core.sigutils import is_signature as is_signature

def select_device(dev: int = 0) -> None: ...
def is_float16_supported(): ...

class stream:
    """
    The stream API is supported in the simulator - however, all execution
    occurs synchronously, so synchronization requires no operation.
    """

    @contextmanager
    def auto_synchronize(self) -> Generator[None]: ...
    def synchronize(self) -> None: ...

def synchronize() -> None: ...
def close() -> None: ...
def declare_device(*args, **kwargs) -> None: ...
def detect() -> None: ...
def list_devices(): ...

class Event:
    """
    The simulator supports the event API, but they do not record timing info,
    and all simulation is synchronous. Execution time is not recorded.
    """

    def record(self, stream: int = 0) -> None: ...
    def wait(self, stream: int = 0) -> None: ...
    def synchronize(self) -> None: ...
    def elapsed_time(self, event): ...
event = Event

def jit(func_or_sig=None, device: bool = False, debug: bool = False, argtypes=None, inline: bool = False, restype=None, fastmath: bool = False, link=None, boundscheck=None, opt: bool = True, cache=None): ...
@contextmanager
def defer_cleanup() -> Generator[None]: ...
