"""
This type stub file was generated by pyright.
"""

log = ...
class ACOptions:
    def __init__(self) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    def justReporting(self): # -> bool:
        ...
    


def getGlyphNames(glyphSpec, fontGlyphList, fDesc): # -> list[Any] | None:
    ...

def filterGlyphList(options, fontGlyphList, fDesc): # -> list[Any]:
    """
    Returns the list of glyphs which are in the intersection of the argument
    list and the glyphs in the font.
    """
    ...

def get_glyph(options, font, name): # -> None:
    ...

FontInstance = ...
def setUniqueDescs(fontInstances): # -> None:
    ...

class fontWrapper:
    """
    Stores references to one or more related instance font objects.
    Extracts glyphs from those objects by name, hints them, and
    stores the result back those objects. Optionally saves the
    modified glyphs in corresponding output font files.
    """
    def __init__(self, options, fil) -> None:
        ...
    
    def numGlyphs(self): # -> int:
        ...
    
    def hintStatus(self, name, hintedGlyphTuple): # -> bool:
        ...
    
    class glyphiter:
        def __init__(self, parent) -> None:
            ...
        
        def __next__(self): # -> tuple[Any | Literal['.notdef'], Any | tuple[Any | None, ...], Any]:
            ...
        
    
    
    def __iter__(self): # -> glyphiter:
        ...
    
    def hint(self): # -> bool:
        ...
    
    def save(self): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    


def openFont(path, options): # -> UFOFontData | CFFFontData:
    ...

def get_outpath(options, font_path, i):
    ...

def hintFiles(options): # -> None:
    ...

