from fontTools.ttLib import TTFont
from . import fdTools as fdTools, FontParseError as FontParseError
from .glyphData import glyphData as glyphData
from _typeshed import Incomplete
from fontTools.misc.psCharStrings import T2OutlineExtractor

log: Incomplete
kStackLimit: int
kStemLimit: int

class SEACError(Exception):
    """Raised when a charString has an obsolete 'seac' operator"""

def hintOn(i, hintMaskBytes):
    """Used to help convert T2 hintmask bytes to a boolean array"""
def denormalizeValue(nv, a): ...
def denormalizeLocation(loc, axes): ...

class T2ToGlyphDataExtractor(T2OutlineExtractor):
    '''
    Inherits from the fontTools Outline Extractor and adapts some of the
    operator methods to match the "hint pen" interface of the glyphData class
    '''
    glyph: Incomplete
    readStems: Incomplete
    readFlex: Incomplete
    hintMaskBytes: Incomplete
    vhintCount: int
    hhintCount: int
    def __init__(self, gd, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, readStems: bool = True, readFlex: bool = True) -> None: ...
    def op_endchar(self, index) -> None: ...
    def op_hflex(self, index) -> None: ...
    def op_flex(self, index) -> None: ...
    def op_hflex1(self, index) -> None: ...
    def op_flex1(self, index) -> None: ...
    def op_hstem(self, index) -> None: ...
    def op_vstem(self, index) -> None: ...
    def op_hstemhm(self, index) -> None: ...
    def op_vstemhm(self, index) -> None: ...
    def countHints(self, args, horiz) -> None: ...
    def doMask(self, index, cntr: bool = False): ...
    def op_hintmask(self, index): ...
    def op_cntrmask(self, index): ...

def convertT2ToGlyphData(t2CharString, readStems: bool = True, readFlex: bool = True, roundCoords: bool = True, name=None):
    """Wrapper method for T2ToGlyphDataExtractor execution"""

class CFFFontData:
    inputPath: Incomplete
    font_format: Incomplete
    is_cff2: bool
    is_vf: bool
    vs_data_models: Incomplete
    desc: Incomplete
    ttFont: TTFont
    cffTable: Incomplete
    topDict: Incomplete
    charStrings: Incomplete
    glyph_programs: Incomplete
    vsIndexMap: Incomplete
    axes: Incomplete
    temp_cs_extract: Incomplete
    temp_cs_merge: Incomplete
    def __init__(self, path, font_format) -> None: ...
    def getGlyphList(self): ...
    def getPSName(self): ...
    def get_min_max(self, upm): ...
    def convertToGlyphData(self, glyphName, readStems, readFlex, roundCoords, doAll: bool = False): ...
    def updateFromGlyph(self, gl, glyphName) -> None: ...
    def save(self, path) -> None: ...
    def close(self) -> None: ...
    def isCID(self): ...
    def getPrivateDictVal(self, pDict, attr, default, vsindex, vsi): ...
    def getPrivateFDDict(self, allowNoBlues, noFlex, vCounterGlyphs, hCounterGlyphs, desc, fdIndex: int = 0, gl_vsindex=None): ...
    def getfdIndex(self, name): ...
    def isVF(self): ...
    def getInputPath(self): ...
    def getPrivateDict(self, fdIndex): ...
    def mergePrivateMap(self, privateMap) -> None: ...
    @staticmethod
    def getInstanceName(vn, vsi, axes): ...
    def get_vf_glyphs(self, glyph_name): ...
    @staticmethod
    def get_vs_data_models(topDict, axes): ...
    def merge_hinted_glyphs(self, name) -> None: ...

def interpolate_cff2_charstring(charstring, gname, interpolateFromDeltas, vsindex): ...
def merge_hinted_programs(charstring, t2_programs, gname, vs_data_model): ...
def get_scalars(self, vsindex, region_idx): ...

class VarDataModel:
    var_data: Incomplete
    master_vsi_list: Incomplete
    delta_weights: Incomplete
    def __init__(self, var_data, vsindex, master_vsi_list) -> None: ...
    @property
    def num_masters(self): ...
    def getDeltas(self, master_values, *, round=...): ...
