"""
This type stub file was generated by pyright.
"""

from fontTools.misc.psCharStrings import T2OutlineExtractor
from fontTools.varLib.varStore import VarStoreInstancer

"""
Utilities for converting between T2 charstrings and glyphData objects.
"""
log = ...
kStackLimit = ...
kStemLimit = ...
class SEACError(Exception):
    """Raised when a charString has an obsolete 'seac' operator"""
    ...


def hintOn(i, hintMaskBytes):
    """Used to help convert T2 hintmask bytes to a boolean array"""
    ...

def denormalizeValue(nv, a):
    ...

def denormalizeLocation(loc, axes): # -> dict[Any, Any]:
    ...

class T2ToGlyphDataExtractor(T2OutlineExtractor):
    """
    Inherits from the fontTools Outline Extractor and adapts some of the
    operator methods to match the "hint pen" interface of the glyphData class
    """
    def __init__(self, gd, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, readStems=..., readFlex=...) -> None:
        ...
    
    def op_endchar(self, index): # -> None:
        ...
    
    def op_hflex(self, index): # -> None:
        ...
    
    def op_flex(self, index): # -> None:
        ...
    
    def op_hflex1(self, index): # -> None:
        ...
    
    def op_flex1(self, index): # -> None:
        ...
    
    def op_hstem(self, index): # -> None:
        ...
    
    def op_vstem(self, index): # -> None:
        ...
    
    def op_hstemhm(self, index): # -> None:
        ...
    
    def op_vstemhm(self, index): # -> None:
        ...
    
    def countHints(self, args, horiz): # -> None:
        ...
    
    def doMask(self, index, cntr=...): # -> tuple[Incomplete, list[Any], list[Any], Incomplete]:
        ...
    
    def op_hintmask(self, index): # -> tuple[Incomplete, Incomplete]:
        ...
    
    def op_cntrmask(self, index): # -> tuple[Incomplete, Incomplete]:
        ...
    


def convertT2ToGlyphData(t2CharString, readStems=..., readFlex=..., roundCoords=..., name=...): # -> glyphData:
    """Wrapper method for T2ToGlyphDataExtractor execution"""
    ...

class CFFFontData:
    def __init__(self, path, font_format) -> None:
        ...
    
    def getGlyphList(self): # -> list[str]:
        ...
    
    def getPSName(self): # -> Incomplete:
        ...
    
    def get_min_max(self, upm): # -> tuple[Incomplete | Any, Incomplete | Any]:
        ...
    
    def convertToGlyphData(self, glyphName, readStems, readFlex, roundCoords, doAll=...): # -> glyphData | None:
        ...
    
    def updateFromGlyph(self, gl, glyphName): # -> None:
        ...
    
    def save(self, path): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def isCID(self): # -> bool:
        ...
    
    def getPrivateDictVal(self, pDict, attr, default, vsindex, vsi): # -> Any | list[Any]:
        ...
    
    def getPrivateFDDict(self, allowNoBlues, noFlex, vCounterGlyphs, hCounterGlyphs, desc, fdIndex=..., gl_vsindex=...): # -> FDDict | tuple[list[Any], Any | int | None]:
        ...
    
    def getfdIndex(self, name): # -> Literal[0] | None:
        ...
    
    def isVF(self): # -> bool:
        ...
    
    def getInputPath(self): # -> Any:
        ...
    
    def getPrivateDict(self, fdIndex):
        ...
    
    def mergePrivateMap(self, privateMap): # -> None:
        ...
    
    @staticmethod
    def getInstanceName(vn, vsi, axes): # -> str:
        ...
    
    def get_vf_glyphs(self, glyph_name): # -> tuple[list[Any], Any | int]:
        ...
    
    @staticmethod
    def get_vs_data_models(topDict, axes): # -> list[Any]:
        ...
    
    def merge_hinted_glyphs(self, name): # -> None:
        ...
    


def interpolate_cff2_charstring(charstring, gname, interpolateFromDeltas, vsindex): # -> list[Any]:
    ...

def merge_hinted_programs(charstring, t2_programs, gname, vs_data_model):
    ...

@_add_method(VarStoreInstancer)
def get_scalars(self, vsindex, region_idx): # -> dict[int, float]:
    ...

class VarDataModel:
    def __init__(self, var_data, vsindex, master_vsi_list) -> None:
        ...
    
    @property
    def num_masters(self): # -> int:
        ...
    
    def getDeltas(self, master_values, *, round=...): # -> list[Any]:
        ...
    


