from _typeshed import Incomplete

class GlyphReport:
    """Class to store stem and zone data from a particular glyph"""
    name: Incomplete
    hstems: Incomplete
    vstems: Incomplete
    hstems_pos: Incomplete
    vstems_pos: Incomplete
    char_zones: Incomplete
    stem_zone_stems: Incomplete
    all_stems: Incomplete
    def __init__(self, name=None, all_stems: bool = False) -> None: ...
    def clear(self) -> None: ...
    def charZone(self, l, u) -> None: ...
    def stemZone(self, l, u) -> None: ...
    def stem(self, l, u, isLine, isV: bool = False) -> None: ...

class Report:
    glyphs: Incomplete
    def __init__(self) -> None: ...
    @staticmethod
    def round_value(val): ...
    def parse_stem_dict(self, stem_dict):
        """
        stem_dict: {45.5: 1, 47.0: 2}
        """
    def parse_zone_dicts(self, char_dict, stem_dict): ...
    def assemble_rep_list(self, items_dict, count_dict): ...
    def save(self, path, options) -> None: ...
