from _typeshed import Incomplete
from afdko.fdkutils import get_temp_file_path as get_temp_file_path, run_shell_command as run_shell_command, validate_path as validate_path

logger: Incomplete

class ShellCommandError(Exception): ...

def replaceCFF(otfPath, tempFilePath) -> None: ...
def get_options(args): ...

class dictspec: ...

def getDictmap(options): ...
def remapDicts(fpath, dictmap) -> None: ...
def main(args=None): ...
