from . import FontParseError as FontParseError, fdTools as fdTools
from .glyphData import glyphData as glyphData, norm_float as norm_float
from _typeshed import Incomplete
from fontTools.pens.pointPen import AbstractPointPen

log: Incomplete
PUBLIC_GLYPH_ORDER: str
ADOBE_DOMAIN_PREFIX: str
PROCESSED_LAYER_NAME: Incomplete
PROCESSED_GLYPHS_DIRNAME: Incomplete
HASHMAP_NAME: Incomplete
HASHMAP_VERSION_NAME: str
HASHMAP_VERSION: Incomplete
AUTOHINT_NAME: str
CHECKOUTLINE_NAME: str
POINT_NAME_PATTERN: str
HINT_DOMAIN_NAME1: str
HINT_DOMAIN_NAME2: str
FLEX_INDEX_LIST_NAME: str
HINT_SET_LIST_NAME: str
HSTEM3_NAME: str
HSTEM_NAME: str
POINT_NAME: str
POINT_TAG: str
STEMS_NAME: str
VSTEM3_NAME: str
VSTEM_NAME: str
STACK_LIMIT: int

class UFOFontData:
    path: Incomplete
    newGlyphMap: Incomplete
    log_only: Incomplete
    fontDict: Incomplete
    hashMapChanged: bool
    writeToDefaultLayer: Incomplete
    desc: Incomplete
    def __init__(self, path, log_only, write_to_default_layer) -> None: ...
    def getUnitsPerEm(self): ...
    def getPSName(self): ...
    def getInputPath(self): ...
    @staticmethod
    def isCID(): ...
    def convertToGlyphData(self, name, readStems, readFlex, roundCoords, doAll: bool = False): ...
    def updateFromGlyph(self, glyph, name) -> None: ...
    def save(self, path) -> None: ...
    @property
    def hashMap(self): ...
    def writeHashMap(self, writer) -> None: ...
    def updateHashEntry(self, glyphName) -> None: ...
    def removeHashEntry(self, glyphName) -> None: ...
    def recalcHashEntry(self, glyphName, glyph) -> None: ...
    def checkSkipGlyph(self, glyphName, newSrcHash, doAll): ...
    @staticmethod
    def get_glyph_data(glyph, name, readStems, readFlex, roundCoords, glyphset): ...
    def getGlyphList(self): ...
    @property
    def glyphMap(self): ...
    @property
    def processedLayerGlyphMap(self): ...
    @property
    def fontInfo(self): ...
    def getPrivateFDDict(self, allowNoBlues, noFlex, vCounterGlyphs, hCounterGlyphs, desc, fdIndex=None): ...
    def getfdIndex(self, name): ...
    def isVF(self): ...
    def get_min_max(self, upm): ...
    def mergePrivateMap(self, privateMap) -> None: ...
    @staticmethod
    def close() -> None: ...

class HashPointPen(AbstractPointPen):
    glyphset: Incomplete
    width: Incomplete
    data: Incomplete
    def __init__(self, glyph, glyphset=None) -> None: ...
    def getHash(self): ...
    def beginPath(self, identifier=None, **kwargs) -> None: ...
    def endPath(self) -> None: ...
    def addPoint(self, pt, segmentType=None, smooth: bool = False, name=None, identifier=None, **kwargs) -> None: ...
    def addComponent(self, baseGlyphName, transformation, identifier=None, **kwargs) -> None: ...

class GlyphDataWrapper:
    '''
    Wraps a glyphData object while storing the properties set by readGlyph
    to aid output of hint data in Adobe\'s "hint format 2" for UFO.
    '''
    lib: Incomplete
    width: Incomplete
    def __init__(self, glyph) -> None: ...
    def addUfoFlex(self, uhl, pointname) -> None:
        """Mark the named point as starting a flex hint"""
    def addUfoMask(self, uhl, masks, pointname) -> None:
        """Associates the hint set represented by masks with the named point"""
    def addUfoHints(self, uhl, pe, labelnum, startSubpath: bool = False):
        """Adds hints to the pathElement, naming points as necessary"""
    def drawPoints(self, pen, ufoHintLib: bool = True):
        """
        Calls pointPen commands on pen to draw the glyph, optionally naming
        some points and building a library of hint annotations
        """
