from _typeshed import Incomplete
from torch import Tensor as Tensor
from torch.nn import Module, ModuleList as ModuleList
from typing import Literal

def exists(val): ...
def default(val, d): ...
def broadcat(tensors, dim: int = -1): ...
def slice_at_dim(t, dim_slice: slice, *, dim): ...
def rotate_half(x): ...
def apply_rotary_emb(freqs, t, start_index: int = 0, scale: float = 1.0, seq_dim: int = -2, freqs_seq_dim=None): ...
def apply_learned_rotations(rotations, t, start_index: int = 0, freq_ranges=None): ...

class RotaryEmbedding(Module):
    freqs_for: Incomplete
    cache_if_possible: Incomplete
    cache_max_seq_len: Incomplete
    cached_freqs_seq_len: int
    freqs: Incomplete
    learned_freq: Incomplete
    seq_before_head_dim: Incomplete
    default_seq_dim: Incomplete
    interpolate_factor: Incomplete
    use_xpos: Incomplete
    scale_base: Incomplete
    cached_scales_seq_len: int
    apply_rotary_emb: Incomplete
    def __init__(self, dim, custom_freqs: Tensor | None = None, freqs_for: Literal['lang', 'pixel', 'constant'] = 'lang', theta: int = 10000, max_freq: int = 10, num_freqs: int = 1, learned_freq: bool = False, use_xpos: bool = False, xpos_scale_base: int = 512, interpolate_factor: float = 1.0, theta_rescale_factor: float = 1.0, seq_before_head_dim: bool = False, cache_if_possible: bool = True, cache_max_seq_len: int = 8192) -> None: ...
    @property
    def device(self): ...
    def get_seq_pos(self, seq_len, device=None, dtype=None, offset: int = 0): ...
    def rotate_queries_or_keys(self, t, seq_dim=None, offset: int = 0, scale=None): ...
    def rotate_queries_with_cached_keys(self, q, k, seq_dim=None, offset: int = 0): ...
    def rotate_queries_and_keys(self, q, k, seq_dim=None): ...
    def get_scale(self, t: Tensor, seq_len: int | None = None, offset: int = 0): ...
    def get_axial_freqs(self, *dims, offsets: tuple[int | float, ...] | Tensor | None = None): ...
    def forward(self, t: Tensor, seq_len: int | None = None, offset: int = 0): ...
