from _typeshed import Incomplete

log: Incomplete

def _featureVariationRecordIsUnique(rec, seen): ...
def _limitFeatureVariationConditionRange(condition, axisLimit): ...
def _instantiateFeatureVariationRecord(record, recIdx, axisLimits, fvarAxes, axisIndexMap): ...
def _instantiateFeatureVariations(table, fvarAxes, axisLimits) -> None: ...
def instantiateFeatureVariations(varfont, axisLimits) -> None: ...
