"""
This type stub file was generated by pyright.
"""

from fontTools.misc import psCharStrings
from fontTools import ttLib
from fontTools.misc.loggingTools import deprecateFunction
from fontTools.subset.util import _add_method

class _ClosureGlyphsT2Decompiler(psCharStrings.SimpleT2Decompiler):
    def __init__(self, components, localSubrs, globalSubrs) -> None:
        ...
    
    def op_endchar(self, index): # -> None:
        ...
    


@_add_method(ttLib.getTableClass("CFF "))
def closure_glyphs(self, s): # -> None:
    ...

@_add_method(ttLib.getTableClass("CFF "))
def prune_pre_subset(self, font, options): # -> Literal[True]:
    ...

@_add_method(ttLib.getTableClass("CFF "))
def subset_glyphs(self, s): # -> Literal[True]:
    ...

@_add_method(ttLib.getTableClass("CFF "))
def prune_post_subset(self, ttfFont, options): # -> Literal[True]:
    ...

@deprecateFunction("use 'CFFFontSet.desubroutinize()' instead", category=DeprecationWarning)
@_add_method(ttLib.getTableClass("CFF "))
def desubroutinize(self): # -> None:
    ...

@deprecateFunction("use 'CFFFontSet.remove_hints()' instead", category=DeprecationWarning)
@_add_method(ttLib.getTableClass("CFF "))
def remove_hints(self): # -> None:
    ...

@deprecateFunction("use 'CFFFontSet.remove_unused_subroutines' instead", category=DeprecationWarning)
@_add_method(ttLib.getTableClass("CFF "))
def remove_unused_subroutines(self): # -> None:
    ...

