"""
This type stub file was generated by pyright.
"""

from functools import cache
from typing import Dict, Iterable, Iterator, Optional, Set, Tuple
from lxml import etree
from fontTools import ttLib
from fontTools.subset.util import _add_method

__all__ = ["subset_glyphs"]
GID_RE = ...
NAMESPACES = ...
XLINK_HREF = ...
@cache
def xpath(path):
    ...

def group_elements_by_id(tree: etree.Element) -> Dict[str, etree.Element]:
    ...

def parse_css_declarations(style_attr: str) -> Dict[str, str]:
    ...

def iter_referenced_ids(tree: etree.Element) -> Iterator[str]:
    ...

def closure_element_ids(elements: Dict[str, etree.Element], element_ids: Set[str]) -> None:
    ...

def subset_elements(el: etree.Element, retained_ids: Set[str]) -> bool:
    ...

def remap_glyph_ids(svg: etree.Element, glyph_index_map: Dict[int, int]) -> Dict[str, str]:
    ...

def href_local_target(el: etree.Element) -> Optional[str]:
    ...

def update_glyph_href_links(svg: etree.Element, id_map: Dict[str, str]) -> None:
    ...

def ranges(ints: Iterable[int]) -> Iterator[Tuple[int, int]]:
    ...

@_add_method(ttLib.getTableClass("SVG "))
def subset_glyphs(self, s) -> bool:
    ...

