c_helpers: dict

def meminfo_alloc(*args, **kwargs): ...
def meminfo_alloc_safe(*args, **kwargs): ...
def meminfo_new(*args, **kwargs): ...
def memsys_disable_stats(*args, **kwargs): ...
def memsys_enable_stats(*args, **kwargs): ...
def memsys_get_stats_alloc(*args, **kwargs): ...
def memsys_get_stats_free(*args, **kwargs): ...
def memsys_get_stats_mi_alloc(*args, **kwargs): ...
def memsys_get_stats_mi_free(*args, **kwargs): ...
def memsys_shutdown(*args, **kwargs): ...
def memsys_stats_enabled(*args, **kwargs): ...
def memsys_use_cpython_allocator(*args, **kwargs): ...
