"""
This type stub file was generated by pyright.
"""

from ..._core import _unwrap_if_constexpr, builtin
from . import async_copy, mbarrier
from triton import knobs
from triton.experimental.gluon.language import _core as ttgl
from triton.experimental.gluon.language._layouts import DotOperandLayout, NVMMADistributedLayout

__all__ = ["async_copy", "mbarrier", "mma_v2"]
@builtin
def mma_v2(a, b, acc, input_precision=..., _semantic=...): # -> tensor:
    ...
