import types
from _typeshed import Incomplete

logger: Incomplete

class Context:
    checker: Incomplete
    newcontext: Incomplete
    def __init__(self, checker, newcontext) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...

class CompatibilityChecker:
    errors: Incomplete
    context: Incomplete
    okay: bool
    fonts: Incomplete
    default_source_idx: Incomplete
    def __init__(self, fonts, default_source_idx: int = 0) -> None: ...
    @staticmethod
    def glyph_is_empty(glyph): ...
    current_fonts: Incomplete
    def check(self): ...
    def check_glyph(self, glyphs, default_is_empty: bool = False): ...
    def check_contours(self, contours): ...
    def ensure_all_same(self, func, objs, what): ...
    def _name_for(self, font): ...
