c_helpers: dict
long_max: int
long_min: int
py_buffer_size: int
py_gil_state_size: int
py_unicode_1byte_kind: int
py_unicode_2byte_kind: int
py_unicode_4byte_kind: int

def _import_cython_function(*args, **kwargs): ...
def rnd_get_np_state_ptr(*args, **kwargs): ...
def rnd_get_py_state_ptr(*args, **kwargs): ...
def rnd_get_state(*args, **kwargs): ...
def rnd_seed(*args, **kwargs): ...
def rnd_set_state(*args, **kwargs): ...
def rnd_shuffle(*args, **kwargs): ...
