from pandas import Series
from pandas.core.accessor import PandasDelegate
from typing import Any

class BaseAccessor:
    def __init__(self, data: Any=...) -> None: ...

class SparseAccessor(BaseAccessor, PandasDelegate):
    @classmethod
    def from_coo(cls, A: Any, dense_index: bool = False) -> Series: ...
    def to_coo(self, row_levels: Any=..., column_levels: Any=..., sort_labels: bool = False) -> Any: ...
    def to_dense(self) -> Any: ...

class SparseFrameAccessor(BaseAccessor, PandasDelegate):
    @classmethod
    def from_spmatrix(cls, data: Any, index: Any=..., columns: Any=...) -> Any: ...
    def to_dense(self) -> Any: ...
    def to_coo(self) -> Any: ...
    @property
    def density(self) -> float: ...
