import torch.nn as nn
from _typeshed import Incomplete

class BaseObject(nn.Module):
    def __init__(self, name=None) -> None: ...

class Metric(BaseObject): ...

class Loss(BaseObject):
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __mul__(self, value): ...
    def __rmul__(self, other): ...

class SumOfLosses(Loss):
    l1: Incomplete
    l2: Incomplete
    def __init__(self, l1, l2) -> None: ...
    def __call__(self, *inputs): ...

class MultipliedLoss(Loss):
    loss: Incomplete
    multiplier: Incomplete
    def __init__(self, loss, multiplier) -> None: ...
    def __call__(self, *inputs): ...
