import torch.nn as nn
from . import base as base
from ..base.modules import Activation as Activation
from _typeshed import Incomplete

class JaccardLoss(base.Loss):
    eps: Incomplete
    activation: Incomplete
    ignore_channels: Incomplete
    def __init__(self, eps: float = 1.0, activation=None, ignore_channels=None, **kwargs) -> None: ...
    def forward(self, y_pr, y_gt): ...

class DiceLoss(base.Loss):
    eps: Incomplete
    beta: Incomplete
    activation: Incomplete
    ignore_channels: Incomplete
    def __init__(self, eps: float = 1.0, beta: float = 1.0, activation=None, ignore_channels=None, **kwargs) -> None: ...
    def forward(self, y_pr, y_gt): ...

class L1Loss(nn.L1Loss, base.Loss): ...
class MSELoss(nn.MSELoss, base.Loss): ...
class CrossEntropyLoss(nn.CrossEntropyLoss, base.Loss): ...
class NLLLoss(nn.NLLLoss, base.Loss): ...
class BCELoss(nn.BCELoss, base.Loss): ...
class BCEWithLogitsLoss(nn.BCEWithLogitsLoss, base.Loss): ...
