from .meter import AverageValueMeter as AverageValueMeter
from _typeshed import Incomplete

class Epoch:
    model: Incomplete
    loss: Incomplete
    metrics: Incomplete
    stage_name: Incomplete
    verbose: Incomplete
    device: Incomplete
    def __init__(self, model, loss, metrics, stage_name, device: str = 'cpu', verbose: bool = True) -> None: ...
    def batch_update(self, x, y) -> None: ...
    def on_epoch_start(self) -> None: ...
    def run(self, dataloader): ...

class TrainEpoch(Epoch):
    optimizer: Incomplete
    def __init__(self, model, loss, metrics, optimizer, device: str = 'cpu', verbose: bool = True) -> None: ...
    def on_epoch_start(self) -> None: ...
    def batch_update(self, x, y): ...

class ValidEpoch(Epoch):
    def __init__(self, model, loss, metrics, device: str = 'cpu', verbose: bool = True) -> None: ...
    def on_epoch_start(self) -> None: ...
    def batch_update(self, x, y): ...
